### ISSUE TITLE
Regression bounded for negative values but not positive values

### ISSUE THREAD

**Issue by arniwesth** [JohnLangford/vowpal_wabbit#1002]
I am using the vw c# interface v. 8.0.0.52 (obtained via nuget).

I am testing vw for online regression on data streams (so true online train-predict-loop). The parameters are straightforward: --adaptive --normalized --invariant (aka default).

Below is an example graph of the regression problem. Orange data points are the observed stream of regression targets and red data points are predictions by vw.

I infer from the graph that predictions with negative values are bounded by the currently largest observed negative target value while predictions with positive values do not seem to be bounded at all. 

This seems odd. I would either expect the predictions not to be bounded this way or to be bounded uniformly for both positive and negative values. Before I dig further into this I would like to know if people here believes this is expected behavior.

![vw_stream_prediction_v1](https://cloud.githubusercontent.com/assets/409051/15621929/c64a4764-2464-11e6-900f-42f0c3fceaed.jpg)

**Comment by JohnLangford** [comment]
You are running into some strange defaulting.  Basically, the default range
for regression is [0,1] and when the label exceeds this range, that becomes
the new range.

What is a better approach?  Should we default to no range and then limit to
the range of observations?

-John

**Comment by arielf** [comment]
@arniwesth  This is a beautiful graph, thanks.  Can you share the code generating it?

Many of the high vw-predictions on the positive side (especially in the 1st half and 1st quarter of the data-set) seem to be much more extreme than anything in the orange (actual target) set. Also the range expansions in the orange-set are smaller and much less jittery, so it seems there's more to that than just range expansion to [min, max].

Can you also share the data-set itself?
Is this only affecting the C# interface or vw (C++ compiled binary) as well?

**Comment by JohnLangford** [comment]
I've changed the defaults to make things work more cleanly in the master branch now.
