### ISSUE TITLE
make test 4 failed error

### ISSUE THREAD

**Issue by lstavr** [JohnLangford/vowpal_wabbit#1008]
Hi,
While trying to run make test (Ubuntu 14.04 LTS, 64bit) after successfully running:
sudo apt-get install libboost-program-options-dev libboost-python-dev
sudo apt-get install zlib1g-dev
sudo apt-get install libtool
sudo apt-get install libboost-all-dev

./autogen.sh
./configure --with-boost-libdir=/usr/lib/x86_64-linux-gnu
make

 I get the following error in make test:

Making all in vowpalwabbit
make[1]: Entering directory `/home/username/ThirdParty/vowpal_wabbit/vowpalwabbit'
make  all-am
make[2]: Entering directory `/home/username/ThirdParty/vowpal_wabbit/vowpalwabbit'
make[2]: Leaving directory `/home/username/ThirdParty/vowpal_wabbit/vowpalwabbit'
make[1]: Leaving directory `/home/username/ThirdParty/vowpal_wabbit/vowpalwabbit'
Making all in cluster
make[1]: Entering directory `/home/username/ThirdParty/vowpal_wabbit/cluster'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/home/username/ThirdParty/vowpal_wabbit/cluster'
Making all in library
make[1]: Entering directory `/home/username/ThirdParty/vowpal_wabbit/library'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/home/username/ThirdParty/vowpal_wabbit/library'
make[1]: Entering directory `/home/username/ThirdParty/vowpal_wabbit'
make[1]: Nothing to be done for `all-am'.
make[1]: Leaving directory `/home/username/ThirdParty/vowpal_wabbit'
cd test && ./RunTests -f -E 0.001 ../vowpalwabbit/vw ../vowpalwabbit/vw
Testing on: hostname=hostname OS=linux
Testing vw: ../vowpalwabbit/vw
RunTests: '-D' to see any diff output
RunTests: '-d' to see only significant diff output
RunTests: '-o' to force overwrite references
RunTests: '-e' to abort/exit on first failure
RunTests: test 1: stderr OK
RunTests: test 2: stderr OK
RunTests: test 2: minor (<0.001) precision differences ignored
RunTests: test 2: 0001.predict OK
RunTests: test 3: stderr OK
RunTests: test 4: stdout OK
RunTests: test 4: FAILED: ref(train-sets/ref/0002.stderr) != stderr(0002.stderr)
	cmd: /usr/bin/timeout 30 ../vowpalwabbit/vw -k -d train-sets/0002.dat -f models/0002.model --invariant
RunTests: test 5: stderr OK
RunTests: test 6: stderr OK
RunTests: test 6: minor (<0.001) precision differences ignored
RunTests: test 6: 0002b.predict OK
RunTests: test 7: stderr OK
RunTests: test 8: stderr OK
RunTests: test 8: minor (<0.001) precision differences ignored
RunTests: test 8: 0002c.predict OK
RunTests: test 9: stderr OK
RunTests: test 9: minor (<0.001) precision differences ignored
RunTests: test 9: cs_test.ldf.csoaa.predict OK
RunTests: test 10: stderr OK
RunTests: test 10: minor (<0.001) precision differences ignored
RunTests: test 10: cs_test.ldf.wap.predict OK
RunTests: test 11: stderr OK
RunTests: test 12: stderr OK
RunTests: test 13: stderr OK
RunTests: test 14: stdout OK
RunTests: test 14: stderr OK
RunTests: test 15: stdout OK
RunTests: test 15: stderr OK
RunTests: test 16: stdout OK
RunTests: test 16: stderr OK
RunTests: test 17: minor (<0.001) precision differences ignored
RunTests: test 17: stderr OK
RunTests: test 18: stderr OK
RunTests: test 19: stderr OK
RunTests: test 20: stderr OK
RunTests: test 20: 0022.predict OK
RunTests: test 21: stderr OK
RunTests: test 22: stdout OK
RunTests: test 22: minor (<0.001) precision differences ignored
RunTests: test 22: stderr OK
RunTests: test 23: stdout OK
RunTests: test 23: minor (<0.001) precision differences ignored
RunTests: test 23: stderr OK
RunTests: test 24: minor (<0.001) precision differences ignored
RunTests: test 24: stderr OK
RunTests: test 25: stderr OK
RunTests: test 25: minor (<0.001) precision differences ignored
RunTests: test 25: bs.reg.predict OK
RunTests: test 26: stderr OK
RunTests: test 26: minor (<0.001) precision differences ignored
RunTests: test 26: bs.prreg.predict OK
RunTests: test 27: stderr OK
RunTests: test 27: minor (<0.001) precision differences ignored
RunTests: test 27: bs.vote.predict OK
RunTests: test 28: stderr OK
RunTests: test 28: minor (<0.001) precision differences ignored
RunTests: test 28: bs.prvote.predict OK
RunTests: test 29: stderr OK
RunTests: test 30: stderr OK
RunTests: test 31: stderr OK
RunTests: test 32: stderr OK
RunTests: test 33: stderr OK
RunTests: test 34: stderr OK
RunTests: test 34: topk-rec.predict OK
RunTests: test 35: stderr OK
RunTests: test 36: stderr OK
RunTests: test 37: stderr OK
RunTests: test 38: minor (<0.001) precision differences ignored
RunTests: test 38: stderr OK
RunTests: test 39: stderr OK
RunTests: test 40: stderr OK
RunTests: test 41: stderr OK
RunTests: test 42: minor (<0.001) precision differences ignored
RunTests: test 42: stderr OK
RunTests: test 43: stderr OK
RunTests: test 44: stderr OK
RunTests: test 44: sequence_data.nonldf.test.predict OK
RunTests: test 45: stderr OK
RunTests: test 46: stderr OK
RunTests: test 47: stderr OK
RunTests: test 47: sequence_data.ldf.test.predict OK
RunTests: test 48: stderr OK
RunTests: test 49: stderr OK
RunTests: test 49: sequencespan_data.nonldf.test.predict OK
RunTests: test 50: stderr OK
RunTests: test 51: stderr OK
RunTests: test 51: sequencespan_data.nonldf-bilou.test.predict OK
RunTests: test 52: stderr OK
RunTests: test 53: stderr OK
RunTests: test 54: stderr OK
RunTests: test 54: minor (<0.001) precision differences ignored
RunTests: test 54: stage_poly.s025.predict OK
RunTests: test 55: stderr OK
RunTests: test 56: stderr OK
RunTests: test 56: minor (<0.001) precision differences ignored
RunTests: test 56: stage_poly.s025.doubling.predict OK
RunTests: test 57: stderr OK
RunTests: test 57: minor (<0.001) precision differences ignored
RunTests: test 57: stage_poly.s100.doubling.predict OK
RunTests: test 58: stdout OK
RunTests: test 58: stderr OK
RunTests: test 59: stdout OK
RunTests: test 59: stderr OK
RunTests: test 60: stderr OK
RunTests: test 61: stdout OK
RunTests: test 61: stderr OK
RunTests: test 62: minor (<0.001) precision differences ignored
RunTests: test 62: stderr OK
RunTests: test 62: minor (<0.001) precision differences ignored
RunTests: test 62: ksvm_train.linear.predict OK
RunTests: test 63: minor (<0.001) precision differences ignored
RunTests: test 63: stderr OK
RunTests: test 63: minor (<0.001) precision differences ignored
RunTests: test 63: ksvm_train.poly.predict OK
RunTests: test 64: minor (<0.001) precision differences ignored
RunTests: test 64: stderr OK
RunTests: test 64: minor (<0.001) precision differences ignored
RunTests: test 64: ksvm_train.rbf.predict OK
RunTests: test 65: stderr OK
RunTests: test 66: stderr OK
RunTests: test 67: stderr OK
RunTests: test 68: stderr OK
RunTests: test 69: stderr OK
RunTests: test 69: sequence_data.nonldf.beam.test.predict OK
RunTests: test 70: stderr OK
RunTests: test 70: sequence_data.ldf.beam.test.predict OK
RunTests: test 71: stderr OK
RunTests: test 71: minor (<0.001) precision differences ignored
RunTests: test 71: 0002.autolink.predict OK
RunTests: test 72: stderr OK
RunTests: test 73: minor (<0.001) precision differences ignored
RunTests: test 73: stderr OK
RunTests: test 73: minor (<0.001) precision differences ignored
RunTests: test 73: 0001_ftrl.predict OK
RunTests: test 74: stderr OK
RunTests: test 75: stderr OK
RunTests: test 76: stderr OK
RunTests: test 77: stderr OK
RunTests: test 78: stderr OK
RunTests: test 79: stderr OK
RunTests: test 80: stderr OK
RunTests: test 81: stderr OK
RunTests: test 82: stderr OK
RunTests: test 82: minor (<0.001) precision differences ignored
RunTests: test 82: ftrl_pistol.predict OK
RunTests: test 83: stderr OK
RunTests: test 84: stderr OK
RunTests: test 85: stderr OK
RunTests: test 85: multilabel.predict OK
RunTests: test 86: stderr OK
RunTests: test 86: multilabel_ldf.predict OK
RunTests: test 87: stderr OK
RunTests: test 87: cb_adf_rank.predict OK
RunTests: test 88: stderr OK
RunTests: test 89: stderr OK
RunTests: test 89: test_named.predict OK
RunTests: test 90: stderr OK
RunTests: test 91: stderr OK
RunTests: test 91: test_named_csoaa.predict OK
RunTests: test 92: stderr OK
RunTests: test 92: minor (<0.001) precision differences ignored
RunTests: test 92: inv_hash.cmp OK
RunTests: test 93: stderr OK
RunTests: test 93: cb_adf_dr.predict OK
RunTests: test 94: stderr OK
RunTests: test 95: stderr OK
RunTests: test 96: minor (<0.001) precision differences ignored
RunTests: test 96: stdout OK
RunTests: test 96: stderr OK
RunTests: test 97: stderr OK
RunTests: test 98: stderr OK
RunTests: test 98: minor (<0.001) precision differences ignored
RunTests: test 98: 0098.predict OK
RunTests: test 99: stderr OK
RunTests: test 99: minor (<0.001) precision differences ignored
RunTests: test 99: 0099.predict OK
RunTests: test 100: stderr OK
RunTests: test 101: stderr OK
RunTests: test 102: stderr OK
RunTests: test 102: active_cover.predict OK
RunTests: test 103: stderr OK
RunTests: test 104: stderr OK
RunTests: test 105: stderr OK
RunTests: test 106: stderr OK
RunTests: test 106: minor (<0.001) precision differences ignored
RunTests: test 106: 0001_ftrl_holdout.predict OK
RunTests: test 107: minor (<0.001) precision differences ignored
RunTests: test 107: stderr OK
RunTests: test 108: minor (<0.001) precision differences ignored
RunTests: test 108: stderr OK
RunTests: test 108: minor (<0.001) precision differences ignored
RunTests: test 108: 0001_ftrl_holdout_off.predict OK
RunTests: test 109: stderr OK
RunTests: test 109: minor (<0.001) precision differences ignored
RunTests: test 109: oaa_probabilities.predict OK
RunTests: test 110: stderr OK
RunTests: test 110: csoaa_ldf_probabilities.predict OK
RunTests: test 111: stderr OK
RunTests: test 112: stderr OK
RunTests: test 113: stderr OK
RunTests: test 113: confidence.preds OK
RunTests: test 114: stderr OK
RunTests: test 115: stderr OK
RunTests: test 116: stderr OK
RunTests: test 116: cb_eval.preds OK
RunTests: test 117: stderr OK
RunTests: test 117: minor (<0.001) precision differences ignored
RunTests: test 117: ftrl.audit_regr OK
RunTests: test 118: stderr OK
RunTests: test 118: csoaa.audit_regr OK
RunTests: test 119: stderr OK
RunTests: test 119: mwt_learn.preds OK
RunTests: test 120: stderr OK
RunTests: test 120: mwt_learn_exclude.preds OK
RunTests: test 121: stderr OK
RunTests: test 121: rcv1_raw_cb_explore.preds OK
RunTests: test 122: minor (<0.001) precision differences ignored
RunTests: test 122: stderr OK
RunTests: test 122: minor (<0.001) precision differences ignored
RunTests: test 122: confidence_after_training.preds OK
RunTests: test 123: stderr OK
RunTests: test 123: cb_eval1.preds OK
RunTests: test 124: stderr OK
RunTests: test 124: cb_eval2.preds OK
RunTests: test 125: stderr OK
RunTests: test 126: stderr OK
RunTests: test 127: stdout OK
RunTests: test 127: stderr OK
make: *** [test] Error 1

**Comment by arielf** [comment]
Thanks for the report.
I can't reproduce this on my (~3 years old) hardware with latest.

On Ubuntu/Debian there's no need to run `autogen.sh`
Could you please try `make` without `autogen.sh`?
Note that you will have to start clean, because autogen overwrites the original `Makefile`.  It is possible that `git checkout Makefile */Makefile` would bring you close to clean.

If you still get the test 4 failure, please rerun test 4 only, and take a look at the actual diff by adding `-d` to the RunTests flags.
```
   cd test
   ./RunTests -d -fe -E 0.001  4
```
Would be cool if you could post the diff here.

It is possible that this is just a precision issue.
If so, you may try to increase the tolerance of RunTests ten-fold by using:  `-E 0.01`
and if it passes, there's not too much to worry: different hardwares (especially when old) have subtle bugs in their floating-point implementations.

**Comment by lstavr** [comment]
It worked great without the ./autogen.sh command, thank you!
