### ISSUE TITLE
Error Correcting Tournament default to Filter Tree

### ISSUE THREAD

**Issue by MrMathias** [JohnLangford/vowpal_wabbit#1020]
Am I understanding the code correctly, when I say that "--error" is a non-documented parameter to ECT which defaults to 0+1, i.e., a filter tree?

If so, either the documentation should cover this parameter, or the code should default to something that is not a filter tree. Maybe 4log(k) as per the article.

**Comment by JohnLangford** [comment]
I could see either enabling an explicit --filter_tree or doing better 
documentation.   Do you want to tweak either?

-John

**Comment by MrMathias** [comment]
I would like to give it a go.

If you see fit, I will change `--error` with `--m_tournaments` and add that to the documentation. It is a missed opportunity to not simply use the formulation of the ECT article.

Further, I believe the default parameter should be changed from `1` to `4 ln k`, such that ECT achieve its novelty performance by default, i.e., O(1) regret with O(log k) complexity.

**Comment by JohnLangford** [comment]
We should have an explicit --filter_tree option as well which defaults as the present.

Changing the default of --ect to 4 ln k seems fine, but I'm less clear on --m_tournaments.  Maybe just --tournaments?  I don't see the point of m_.

**Comment by JohnLangford** [comment]
Closing this for now.   A patch to tweak the defaults is welcome.
