### ISSUE TITLE
RuntimeError: the argument ('--lambda') for option '--softmax' is invalid

### ISSUE THREAD

**Issue by Feynman27** [JohnLangford/vowpal_wabbit#1026]
I'm trying to run a simple contextual bandit using the python wrapper pyvw. My training data is taken from the wiki and looks like
| a:1 b:0.5
0:0.1:0.75 | a:0.5 b:1 c:2

shared | s_1 s_2
0:1.0:0.5 | a:1 b:1 c:1
| a:0.5 b:2 c:1

I'm running the command from a python script using

`pyvw.vw(-d train_adf.dat --cb_explore_adf --softmax --lambda 10)` 

but get the error:

RuntimeError                              Traceback (most recent call last)
<ipython-input-14-3e99716baef0> in <module>()
----> 1 pyvw.vw('-d train_adf.dat --cb_explore_adf --softmax --lambda 10')

/home/thomas/Sandbox/VowpalWabbit/vowpal_wabbit/python/vowpalwabbit/pyvw.pyc in __init__(self, argString, **kw)
     65         if argString is not None: l = [argString] + l
     66         print ' '.join(l)
---> 67         pylibvw.vw.__init__(self,' '.join(l))
     68         self.finished = False
     69 

RuntimeError: the argument ('--lambda') for option '--softmax' is invalid

All other exploration strategies (e.g. epsilon-greedy) work fine.

**Comment by Feynman27** [comment]
Remove --lambda and just using --softmax 10 removes the error. Though I'm not sure this is setting the lambda value at the moment.

**Comment by JohnLangford** [comment]
I'm confused about why that worked. Alekh, can you comment?

-John

**Comment by JohnLangford** [comment]
Ah yes, I incorrectly remembered how I have done this. I pass the lambda
parameter as an argument to softmax it seems, which is not being read
correctly in the setup. I will send a PR with update.

Alekh

**Comment by JohnLangford** [comment]
This should be fixed now.
