### ISSUE TITLE
[Feature Request] Rectified linear unit option for the neural net

### ISSUE THREAD

**Issue by zachmayer** [JohnLangford/vowpal_wabbit#1028]
The neural net model in VW currently uses sigmoid units.  I was thinking it might be useful to have some other activation functions, most notably rectified linear units.

Thanks!

**Comment by ekg** [comment]
I am also interested in this. Would it be a straightforward change?

**Comment by zachmayer** [comment]
I think the activation happens here: https://github.com/JohnLangford/vowpal_wabbit/blob/4faae05eddce3bcde15e0626d52b04b19c8bc24c/vowpalwabbit/nn.cc#L212

It looks like you could replace `fasttanh` with a function for calculating the rectified linear activation, but I'm not sure.

**Comment by JohnLangford** [comment]
Let me 'cc Paul Mineiro.  You need to get the gradient right also.

-John

**Comment by JohnLangford** [comment]
Yes I think letting the user select the activation function would be easy, you just need two functions which do the forward and backward, and then make (fast)tanh the default.


If you send John a pull request cc-me on it and I'll take a look.


p


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by joshloyal** [comment]
I'd be happy to submit a pull request for this. Since we're only changing the activation, it should be as simple as abstracting away the activation to a general nonlinearity that has a basic call and a `first_derivative` and plugging them in were necessary as Paul said.

**Comment by JohnLangford** [comment]
Go ahead.

-John

**Comment by JohnLangford** [comment]
Closing, as we can discuss in the pull request.
