### ISSUE TITLE
C# Contextual Bandit Prediction Exception

### ISSUE THREAD

**Issue by ErikOmberg** [JohnLangford/vowpal_wabbit#1034]
I setup a simple application using the C# VW wrapper in CB mode like this:

 

          VW.VowpalWabbit<VWRecord> vw = new VW.VowpalWabbit<VWRecord>(new VowpalWabbitSettings
            {
                EnableStringExampleGeneration = true,
                Verbose = true,
                Arguments = "--cb 20 --cb_type dr"
            });

When I call Predict, it causes a System.Overflow exception:

![image](https://cloud.githubusercontent.com/assets/8632110/16752131/9b084098-47a4-11e6-819b-fa3fed2f3fd3.png)

I took a look at the mwt-ds project, which uses CB VW.Predict in a very similar way. Please let me know if you have suggestions or think I might be missing some steps. Thank you.

**Comment by JohnLangford** [comment]
Not sure what's up.  @eisber do you know?

**Comment by eisber** [comment]
Your VW arguments must match the prediction type. There is no check if the memory layout of the return prediction matches – thus you’ll get some weird exceptions.
If you use –cb you’ll have to use cost sensitive prediction from what I remember correctly. @John Langford<mailto:jcl@microsoft.com>: what part of ex->pred union is populated by --cb?

In general I’d follow https://github.com/GitTools/GitLink (Enable Source Server) and you’ll be able to step into the VW calls.

Markus

**Comment by JohnLangford** [comment]
multiclass as per: https://github.com/JohnLangford/vowpal_wabbit/blob/master/vowpalwabbit/csoaa.cc#L95

**Comment by ErikOmberg** [comment]
Wonderful! I changed my predict call to use PredictionType CostSensitive, and that appears to be working. Thank you.

`var vwPrediction = vw.Predict(record, VowpalWabbitPredictionType.CostSensitive);`
