### ISSUE TITLE
Any way to get_tag() in VW Java ?

### ISSUE THREAD

**Issue by zihaolucky** [JohnLangford/vowpal_wabbit#1035]
In java version, learner provides `learn` and `predict`, I'm wondering whether we have any options to get these info. Thanks~

**Comment by JohnLangford** [comment]
You want the tag for an example?

-John

**Comment by zihaolucky** [comment]
Yes. The `Tag` in training/test data. 
` [Label] [Importance] [Base] [Tag]|Namespace Features |Namespace Features ... |Namespace Features`

**Comment by zihaolucky** [comment]
Here's my code:

```java
VWIntLearner m1 = VWLearners.create("--oaa 3 -f model.vw --nn 128 --passes 10 -c --ngram t2");

for (String d : features) {
    m1.learn(d);
}
m1.close();

VWIntLearner predict = VWLearners.create("-t -i model.vw");
for (String feature : features) {
    int pred = predict.predict(feature);  // predict.predict return int. Any way to get Tag?
    System.out.println(" pred: " + pred);
}
predict.close();
```

**Comment by JohnLangford** [comment]
@jmorra @deaktator 

It's easy to add an interface to get the tag of an example, but I'm sketchy on the value from a library interface perspective.  If you are predicting in the library, you are creating an example---in particular you are creating an example with a known tag.  Why not just record the tag separately on the java side and feed no tag into the example?

**Comment by zihaolucky** [comment]
Aha I see. Thanks for your help.

**Comment by JohnLangford** [comment]
There was a similar issue on the python interface that was solved there, so this is in general possible.  Closing this for now.
