### ISSUE TITLE
No apparent way to pickle a model from vowpalwabbit.sklearn_vw.VWClassifier

### ISSUE THREAD

**Issue by dakami** [JohnLangford/vowpal_wabbit#1040]
Pickling a fitted classifier gives you:

RuntimeError: Pickling of "vowpalwabbit.pyvw.vw" instances is not enabled (http://www.boost.org/libs/python/doc/v2/pickle.html)

Means I basically need to build the classifier at runtime every time to do actual prediction (or, I suppose, use CRIU).

**Comment by pommedeterresautee** [comment]
I am not using the Scikit wrapper but just the Python one. 
I made the same mistake than you.
You need to provide the model path as an option (-f) like you would do with the C++ client.
You make your learning, when it is finished, you call the finish() method.
At that moment your model is written on disk.

Hope it helps.

**Comment by gramhagen** [comment]
#1052 adds save and load methods for the sklearn interface as an alternative to the f option.

I was thinking it might be helpful to use sphinx to autogenerate api docs for the python build.  Is that the kind of documentation that would be helpful?

**Comment by JohnLangford** [comment]
1052 is in, so closing for now.  Better documentation is very welcome form anyone who can contribute.

**Comment by lfleck** [comment]
Is there any update on using pickle? 
I'm defining multiple contextual bandits and try to train them in multiple python processes like this: 

```
from vowpalwabbit import pyvw
from concurrent.futures import ProcessPoolExecutor

def dummy_train(model):
    pass

vw1 = pyvw.vw(f"--cb_explore 5 --interactions UUA --quiet --cover 4 -f test4.model")
vw2 = pyvw.vw(f"--cb_explore 5 --interactions UUA --quiet --cover 5 -f test5.model")
models = [vw1, vw2]

with ProcessPoolExecutor(max_workers=2) as executor:
    executor.map(dummy_train, models)
```


However, even with the "-f" option stated above, the originally mentioned 'Pickling of "vowpalwabbit.pyvw.vw" instances is not enabled' error appears. Same holds for [cloudpickle](https://github.com/cloudpipe/cloudpickle) which e.g. [joblib](https://joblib.readthedocs.io/en/latest/) uses for serialization. 

Are there any suggested ways to run VowpalWabbit models in multiple python processes?

**Comment by jackgerrits** [comment]
@gramhagen did you enable pickling in the PR you just submitted? (https://github.com/VowpalWabbit/vowpal_wabbit/pull/2368)

**Comment by gramhagen** [comment]
yes, you can pickle the sklearn model, under the hood this is accomplished using 
```
pyvw.vw.save(file)
pyvw.vw(initial_regressor=file)
```

but the problem will persist here since this is passing the pyvw.vw object itself (which is not picklable) to each new process. So you need to encapsulate model creation in your dummy_train function and only pass the parameters you want to vary.

example:
```
from vowpalwabbit.pyvw import vw
from multiprocessing import Pool

def dummy_train(params):
    model = vw(**params)
    ec = model.example("1 | a b c")
    model.learn(ec)
    model.finish()


if __name__ == "__main__":
    pool = Pool(processes=2)
    variants = (
        {"f": "model_0.vw", "quiet": True},
        {"f": "model_1.vw", "quiet": True},
    )
    pool.map(dummy_train, variants)
```
