### ISSUE TITLE
[Python] Decreases of L2S perf when oracle=0 (needs PR)

### ISSUE THREAD

**Issue by pommedeterresautee** [JohnLangford/vowpal_wabbit#1042]
I try to build a POS tagger for French with L2S based on French UD dataset.
I use the Python wrapper.

When I don't use `allowed=` parameter in `predict()` function I get a 0.08 hamming loss (state of the art is 0.03).

When I used `allowed=` to inform VW that I know deterministically some POS tag (for punctuation and det) and I provided it to VW through `allowed=` the hamming loss goes up to 0.11/0.12 (whatever the policies I tried for roll_in/roll_out).

It doesn't make sense to me as I am reducing the search space.
I have checked that the POS tag I deterministically guess are 100% matching the real POS tag.

I have also noticed that VW needs more call to `_run()` function to finish, with less info to guess...

Can someone help to understand why the perf are decreasing and may be what I can change to improve perf?

**Comment by KaiWeiChang** [comment]
Could you provide the _run function?

**Comment by pommedeterresautee** [comment]
Thank you @KaiWeiChang for your anwer.

Please find below my whole class:
To make the code more clear (and not make ref outside of the class), I just forced the correct answer for pos tag == 4 which is punctuation.
Results are of course the same than the one described in my previous message.

```python
class SequenceLabelerNoLDF(pyvw.SearchTask):
    def __init__(self, vw, sch, num_actions):
        pyvw.SearchTask.__init__(self, vw, sch, num_actions)
        self.counter = 0
        self.cache_ex = {}
        sch.set_options(sch.AUTO_HAMMING_LOSS | sch.AUTO_CONDITION_FEATURES)

    def _run(self, sentence):
        output = []
        for n, item in enumerate(sentence):
            pos, word, word_lower, word_description = item
            if word in self.cache_ex:
                ex = self.cache_ex[word]
            else:
                ex = self.vw.example({'w': ["w_" + word, "wl_" + word_lower],
                                      'p': ["p3_" + word_lower[:3], "s3_" + word_lower[-3:],
                                            "p1_" + word_lower[:1], "s1_" + word_lower[-1:]],
                                      't': ["upper_" + str(word[0].isupper()), "digit_" + str(word[0].isdigit())]})

                self.cache_ex[word] = ex

            pos_possible = [4] if pos == 4 else None

            pred = self.sch.predict(examples=ex, my_tag=n + 1, oracle=pos,
                                    condition=[(n, 3, 'x')], allowed=pos_possible)
            output.append(pred)
        self.counter += 1
        if self.counter % 100 == 0:
            print ("\r" + str(self.counter)),
        return output
```

BTW caching examples in a dict increase the rapidity of the model learning and should be included in the examples... It is even more important for cost sensitive learning where generating all examples takes a lots of times.

**Comment by KaiWeiChang** [comment]
Could you try one thing for me. 
When pos != 4 set possible to all the possible labels explicitly. 

That is change:

    possible = [4] if pos == 4 else None

to

    possible = [4] if pos == 4 else [1,2,3,4,...] 

It looks that there might be a bug in initializing the predictor when allowed=None.

**Comment by pommedeterresautee** [comment]
Crazy results!

If I use `allowed=None` (always None), I get 0.89
if I use `possible = [4] if pos == 4 else None` I get 0.85 on the sample
if I use `possible = [4] if pos == 4 else [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17]` I get 0.91
if I use `possible = [4] if pos == 4 else [0, 1, 2, 3, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17]` I get 0.92

Results are `1-hamming`
FYI I tried on a 30% of the whole dataset to get results more rapidly (usually do my test on 30%, always correlated with results for full dataset).

I will try tomorrow on the whole dataset but clearly there is something interesting here!

**Comment by KaiWeiChang** [comment]
Wait? you mean 0.92 in hamming loss comparing with 0.08 you used to have? Or this is accuracy?

**Comment by pommedeterresautee** [comment]
No as Said I now report 1 minus Hamming. 
Sorry to not be clear.

**Comment by pommedeterresautee** [comment]
Both messages are reporting hamming. 

0.08 on the whole dataset reported in the first message - > 0.92 as reported in the Last message

**Comment by KaiWeiChang** [comment]
I see. So, it seems that the last one gave you similar results as without using allowed.

**Comment by pommedeterresautee** [comment]
Last give same results on the sample. I usually gain up to two points on the full dataset. 
So it's very encouraging.
But it's 2Am here, will try tomorrow.

**Comment by KaiWeiChang** [comment]
Thanks! I'll take a look at the potential bug on the initialization...

**Comment by pommedeterresautee** [comment]
FYI, I got the results for the full dataset re run this morning:
- `allowed=None` (always None) -> **0.920** (like in my first message)
- `possible = [4] if pos == 4 else [0, 1, 2, 3, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17]` -> **0.949**

I will complete my tests tonight with `possible = [4] if pos == 4 else None` on the full dataset (should get the same results as my first message but want to check in case of...).

**Comment by pommedeterresautee** [comment]
Something else I forgot to report is time taken by the model.
When allowed is used the learning takes 53mn instead of 40mn when allowed is always set to None!

**Comment by pommedeterresautee** [comment]
@KaiWeiChang I updated my message with all perf and all times for each configuration of allowed (other parameters and features are the same for all tests).

Obviously there is an issue when comparing `allowed=None` and `allowed=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17]`.
Time to process the dataset is another indicator that the work done is not the same.

Have you find a fix for the bug?

**Comment by KaiWeiChang** [comment]
Thanks. Apparently, there are some problems in the initiation. I haven't figured out it. 

For the time difference, I think the reason is transforming an array from python to C++ is slow, and the predictor function is somehow in an inner loop. There may be a way to reuse the predictor instead of  repeatedly creating a new instance of it. 

You may want to use allowed=range(len(tags)) for now (it does the things you want), I'll try to figure out the bugs later...

**Comment by pommedeterresautee** [comment]
@KaiWeiChang may be I don't get how VW but I noticed that setting `search_rollout` and `search_rollin` to different values (`mix`, `mix_per_roll`, `mix_per_state`,  etc.) has no effect on the result (exception: oracle makes my results different).
When setting `search_rollout` to `none` make the whole process crash with a 139 error code.

I am thinking that may be there is another issue in reading parameters from Python package.

Is my understanding of these parameters correct?

**Comment by pommedeterresautee** [comment]
@KaiWeiChang needs more check but seems the bug is related to the fact that the prediction ID starts with 0 instead of 1. On C++ client starting with 0 is forbidden. 

Will test more tonight. If this is the case, the easy fix is to throw an exception if allowed is used for a tag with 0 (and some documentation in the Python package).

**Comment by pommedeterresautee** [comment]
@KaiWeiChang 
Going deeper in my test, behaviour when a tag is 0 changes according to the roll out policy (not tested roll in):
* `search_rollout='none'`: crash after some examples if tags include 0 until I set `allowed=range(0,17)`
* `search_rollout='mix'`: perf decreases severely if tags include 0 until I set `allowed=range(0,17)`

When I send tags from `range(1,18)` -> no more issue, no need to set allowed (same results when set or  not set to `range(1,18)`).

Therefore, my opinion is to throw an exception when `oracle=0` in `predict()` function.

**Comment by pommedeterresautee** [comment]
@KaiWeiChang do you want me to make a PR for that or you plan to work on it?
(just checking if oracle==0 and throw an exception on Python part + unit test)

**Comment by JohnLangford** [comment]
@hal3 for reference.  I'm interested in a pull request from anyone.

**Comment by hal3** [comment]
I'm trying to catch up here. The use of 0 as a label is definitely an issue and shouldn't be done. I agree a warning/error should be emitted rather that "weird behavior." That's an easy fix.

Beyond that fix, are there remaining issues?

My experience is that sometimes allowing all actions even when you know the right answer can be a win. This is somewhat counter-intuitive, but what's going on is that you're giving more training data from which to learn, and this turns out to be useful.

**Comment by JohnLangford** [comment]
Should be fixed now.
