### ISSUE TITLE
Share POS tag / NER source code referenced in papers / slides

### ISSUE THREAD

**Issue by pommedeterresautee** [JohnLangford/vowpal_wabbit#1043]
Would it be possible to get the source code in this repository of the examples used in the papers/presentation related to the POS tagger and NER tagger?

It doesn't seem to be in https://github.com/JohnLangford/vowpal_wabbit/blob/master/test/RunTests

The examples in Python folder are slow and obviously under-optimised (no cache, not best options, etc.) and the code in tests is applied to super small dataset.

Best would be to published the code in Python example so other user can reuse it (instead of C++ which may be more difficult to manipulate).

**Comment by JohnLangford** [comment]
I believe the code you want is here: https://github.com/JohnLangford/vowpal_wabbit/blob/master/vowpalwabbit/search_sequencetask.cc

**Comment by pommedeterresautee** [comment]
Thanks.
