### ISSUE TITLE
Documentation missing on how to get LOLS / SEARN / DAGGER / Aggra predictions

### ISSUE THREAD

**Issue by pommedeterresautee** [JohnLangford/vowpal_wabbit#1044]
It took me time to understand that I should play with roll in / roll out policies to make VW applying LOLS or Dagger L2S strategies.

So far I have no idea on how to get Aggra.

As there is several papers using these approach, it would be great to see this information in the Wiki part of this repository (even just a few lines to get a start for a new user).

**Comment by JohnLangford** [comment]
@KaiWeiChang do you think you can add some wiki documentation?

**Comment by pommedeterresautee** [comment]
Wiki page with explanation would be awesome. 

The minimum and would not take time would be to add commands in test run file. For instance the same operation like POS tagging on WSJ dataset using SEARN, Dagger, LOLS and Aggrevate (may be there are others...). Therefore the user would see the variation of the parameters for the same use case to get each of these L2S algo.

If you can do a wiki page, then a short description of the different algo with when to use them (like LOLS when the labels are not perfect,...), the parameters to use and a link to a paper would be awesome. 

Took me quite some time to understand what does what. 

Moreover, so far, I have still not found how to perform Aggrevate algo (I understand that it's like LOLS with Beta=1, but I get exact same results than LOLS...). Seems the search_beta parameter doesn't produce any effect with the roll in and roll out parameters for LOLS
