### ISSUE TITLE
ipynb files are broken

### ISSUE THREAD

**Issue by pommedeterresautee** [JohnLangford/vowpal_wabbit#1045]
The following files can't be viewed in Github following a commit dated as of June 14th, 2016 (da2b54468344d75dbd0e54c6a832005f89aaaecc)

![image](https://cloud.githubusercontent.com/assets/1029874/16981127/78f70586-4e69-11e6-950e-60c6f6d0be3c.png)

![image](https://cloud.githubusercontent.com/assets/1029874/16981190/b36ff3a8-4e69-11e6-9fa6-d871cca8d6e2.png)

Moreover, file https://github.com/JohnLangford/vowpal_wabbit/blob/master/python/poisson_regression.ipynb should be in vowpal_wabbit/python/examples/ folder (but this file can be viewed on Github).

**Comment by gramhagen** [comment]
yeah, there are some invalid headers on some of the cells, I can fix that and move the poisson notebook over

**Comment by gramhagen** [comment]
PR #1047

**Comment by JohnLangford** [comment]
Closing in favor of pull request.
