### ISSUE TITLE
Is it possible to provide a tool that can convert binary model to readable model and vice versa

### ISSUE THREAD

**Issue by robbine** [JohnLangford/vowpal_wabbit#1046]
I check the command lines, It seems there is no such tool

**Comment by eisber** [comment]
Create an empty text file: empty.txt

vw -i <model filename> --readable_model <text file name> -d empty.txt

**Comment by gramhagen** [comment]
That will give you the weights corresponding to the feature hashes, but you will need to use the original training data set instead of an empty file to get the raw feature names (unless you converted them all to numeric features).

**Comment by robbine** [comment]
Thanks! it's very convenient.
And is there a way to convert readable model back to binary model ?
Is it possible ?

**Comment by JohnLangford** [comment]
Not right now.

-John
