### ISSUE TITLE
Is it possible to run Learning to Search in Active Learning setup?

### ISSUE THREAD

**Issue by usptact** [JohnLangford/vowpal_wabbit#1049]
I am successfully training a model for sequence tagging using the "--search_task sequence" option. My question is how to do, if possible, such learning in active learning setup.

What I have:

- seed training file with sequences tagged
- large dataset with no sequence tags

What I would like:

- Learn the model from labeled training data
- Learn from the large unlabeled dataset while asking the labels for unsure/difficult cases

**Comment by JohnLangford** [comment]
This is not possible at present.  It is something that we are 
considering, but setting this up to work well is to some extent a 
research problem.

-John

**Comment by usptact** [comment]
Thanks, @JohnLangford ! I was playing with different argument combinations and going back and forth to vw --help and examples to no avail. I will close the issue then.
