### ISSUE TITLE
import pyvw Kills ipython/jupyter kernel

### ISSUE THREAD

**Issue by JoshuaC3** [JohnLangford/vowpal_wabbit#1051]
When in my jupyter notebook, if I do `import pyvw` and then run cell this kills my ipython kernel.

I have vowpal wabbit installed successfully (`autogen`, `config`, `make `and `make install`, then ran `make test`) and have brew installed python 2.7.x, boost and python-boost. I have Anaconda on my system so I removed this from $PATH and added the brew installed python path. Then I did` pip install pyvw` and ` pip install notebook`.

I then run the `jupyter notebook` in terminal, open it up in chrome and run `import pyvw`. This then kills the kernel.

Any suggestions to resolve this issue. Is there any more information that I can give you?

**Comment by gramhagen** [comment]
Can you  try:
pip install vowpalwabbit

Then in the notebook
from vowpalwabbit import pyvw

**Comment by pommedeterresautee** [comment]
`pyvw ` is the old package.
`vowpalwabbit` is the new one.

**Comment by JoshuaC3** [comment]
I have already installed this:

```
Joshs-MBP:Python Dev Josh$ pip install vowpalwabbit
Requirement already satisfied (use --upgrade to upgrade): vowpalwabbit in /usr/local/lib/python2.7/site-packages
```

Now I start up the juptyer notebook and run import pyvw

```
from vowpalwabbit import pyvw

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-76d9c58cae1b> in <module>()
----> 1 from vowpalwabbit import pyvw

ImportError: No module named vowpalwabbit
```

`usr/local/lib` is in my environment path variable.

**Comment by gramhagen** [comment]
It sounds like you may be running the jupyter notebook in the anaconda
environment instead of your base /usr/local/lib/python2.7 env.
what do you get back from ‘which jupyter’ ?

**Comment by JoshuaC3** [comment]
`Joshs-MBP:Python Dev Josh$ which jupyter
/usr/local/bin/jupyter`

**Comment by gramhagen** [comment]
peculiar (unless that's a softlink to something else), I find using virtualenvs can help avoid some difficulties when working with new packages.
Kenneth Reitz has a good tutorial here: http://docs.python-guide.org/en/latest/dev/virtualenvs/

you could also try to install it directly in a notebook, once you've started jupyter and opened a notebook you can run
```!pip install vowpalwabbit```
might be interesting to see what this returns too
```!which pip```

**Comment by JoshuaC3** [comment]
Pip install first.
```
In [3]:
!pip install vowpalwabbit

Requirement already satisfied (use --upgrade to upgrade): vowpalwabbit in /usr/local/lib/python2.7/site-packages
```

Then which pip.

```
In [4]:
!which pip

/usr/local/bin/pip
```

Haven't done virtualenvs yet but will read link and have a try later.

**Comment by gramhagen** [comment]
this is pretty wild to me, are you still having trouble? I can't understand how you can get a message saying vowpalwabbit is installed in the notebook and also can't import it?  the only thing I can think is that you might make sure you're starting your notebook somewhere like /tmp so it won't try to find packages based on the local path.

**Comment by JoshuaC3** [comment]
Yes still it will not load. If I use pyvw directly it kills the ipython kernel and if I import vowpalwabbit it has no module still.

How do I check the `/tmp` issue?

**Comment by gramhagen** [comment]
From the command line just change directory to /tmp then try 'jupyter
notebook'
That way it won't have any build artifacts from the vw repo on the path to
confuse things.

**Comment by JohnLangford** [comment]
Closing this---I'm presuming it's addressed?

**Comment by JoshuaC3** [comment]
It is still not working. I haven't tried @gramhagen's last suggestion. I will look at this as soon as possible and update.

**Comment by Saxamos** [comment]
Hi same problem here

**Comment by gramhagen** [comment]
@Saxamos can you describe what is happening for you?
How did you install vowpalwabbit? What system are you running? What version of jupyter notebook?
Can you import pyvw when using ipython console?

**Comment by Saxamos** [comment]
Hi @gramhagen thanks for the answer.
First I installed VW using pip and then directly from the repo. I had in both case the same error : 
- on jupyter either I import vowpalwabbit and there is no module or I do "from vowpalwabbit import pyvw" and it kills the kernel
- on the terminal, I enter python and then the import make a segmentation error, leaving python.

**Comment by gramhagen** [comment]
It sounds like the libraries being accessed at runtime differ from what was
built at installation. Is this python 2.7?

**Comment by Saxamos** [comment]
Yes, python 2.7 on mac. Ok I'm gonna try to check the paths

**Comment by lhwilke** [comment]
The most often reason why this happens is that another python version is in the path at compile time. 
Try these commands inside the notebook:

!which python
and
!python2.7-config --ldflags

There should be exact the same output as you have on the shell. E.g. something like this:

$ which python
/usr/local/bin/python
$ python2.7-config --ldflags
-L/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/config -lpython2.7 -ldl -framework CoreFoundation

If this is not the case, set path path at compile time appropriately: export PATH=....

**Comment by Saxamos** [comment]
Thx for answering.
I ran the commands and got in both case (notebook and shell):
/Users/samuelrochette/anaconda/bin/python
-lpython2.7 -ldl -framework CoreFoundation -u _PyMac_Error

Is the PyMac_Error normal (I'm currently trying to find out what it means)?

**Comment by gramhagen** [comment]
Ah. There is an issue with installing under anaconda. The boost libraries
it uses often are not the same ones found during installation. We need to
work out a better library path resolution for anaconda in setup.py. I know
it's not ideal but you could try using the system level python by removing
anaconda from your path. I will post here if I'm able to find a better
resolution.

**Comment by Saxamos** [comment]
Ah, I'd like to use it in a jupyter notebook though, do you think it's possible?

**Comment by gramhagen** [comment]
Yes. It's definitely possible and there are example notebooks in the repo.
But it's not supported under anaconda.
