### ISSUE TITLE
Trouble importing vowpal wabbit sklearn

### ISSUE THREAD

**Issue by dhruvghulati** [JohnLangford/vowpal_wabbit#1058]
I read the docs and it says to set up the `sklearn` version of Vowpal Wabbit, I need to install via pip. However, since I was having exit code 193 errors when running `from vowpalwabbit.sklearn_vw import VWClassifier` I followed the instructions to remove any conda bin directory from my path and then install vowpal wabbit via pip. However, if I do so, I lose any `pip` installation I have.

Essentially all I am looking for is to be able to run the https://github.com/JohnLangford/vowpal_wabbit/wiki/Cost-Sensitive-One-Against-All-%28csoaa%29-multi-class-example as a cost-sensitive multinomial logistic regression in python, where I have a bag of words 2D numpy array as the features:

```
[[ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 ..., 
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]] 
```
Class labels for each instance:
`
u'A', u'B', u'C',..., u'B', u'A', u'C'] `

And costs for each instance:

```
[[ 0.36303512 ],
[ 0.24472353 ],
[ 0.36303512 ],
....
[ 0.00650667 ],
[ 0.06445714 ],
[ 0.05]]
```

What can I do to get myself up and running instead of spending all my time configuring/searching for a python wrapper?

**Comment by gramhagen** [comment]
once you have removed conda from your path you should reinstall the python
wrapper. from the vowpal_wabbit/python directory, under whichever
virtualenv you want to use (or none if that’s what you want).
```
python setup.py clean
python setup.py install
```

**Comment by dhruvghulati** [comment]
OK thank you, this answered my question. Can I after installing this then amend my `$PATH` again to include the conda bin so that I don't lose my whole conda features (pip etc)?

**Comment by gramhagen** [comment]
unfortunately no, if you do that importing anything in vowpalwabbit will
seg fault because it is built using your system’s boost-python library and
not conda’s.  there’s nothing stopping you from pip installing the other
packages necessary without conda, most of the modern packages (numpy,
scipy, sklearn, etc.) are pretty easy to just pip install nowadays.

ideally, we can get vw to either build under conda, or setup vw under conda
forge, it’s just not something I’ve had the time to tackle

**Comment by JohnLangford** [comment]
Closing for now.  @gramhagen it would probably need to be you, so if you can find the time that would be great.
