### ISSUE TITLE
Purpose of  IEnumerable predict method in vowpalwabbit.cpp

### ISSUE THREAD

**Issue by Wirack** [JohnLangford/vowpal_wabbit#1062]
As I was investigating the c# wrapper I stumbled upon the following code fragment in the vowpalwabbit.cpp file in the vw_clr project:

```
generic<typename T> T VowpalWabbit::Predict(IEnumerable<String^>^ lines, IVowpalWabbitPredictionFactory<T>^ predictionFactory)
  {
#if _DEBUG
    if (lines == nullptr)
      throw gcnew ArgumentNullException("lines");
#endif

    auto examples = gcnew List<VowpalWabbitExample^>;

    try
    {
      for each (auto line in lines)
      {
        auto ex = ParseLine(line);
        examples->Add(ex);

        Predict(ex);
      }

      auto empty = GetOrCreateNativeExample();
      examples->Add(empty);
      empty->MakeEmpty(this);
      Predict(empty);

      return examples[0]->GetPrediction(this, predictionFactory);
    }
    finally
    { for each (auto ex in examples)
    {
      delete ex;
    }
    }
  }

```
[Link to code in question](https://github.com/eisber/vowpal_wabbit/blob/master/cs/cli/vowpalwabbit.cpp#L477-L509)

I was wondering why the method only returns the first prediction.
I thought the purpose of the method was to return all the predictions, e.g. as an IEnumerable<T>. 
If this is not the case, what purpose does the method in question serve?

**Comment by eisber** [comment]
Certain reductions have the concept of multi-line examples (cb_adf, csoaa_ldf,…). As the particular task requires more structure than is expressable on a single line using namespaces, data is spread over multiple lines. Thus really you can see these multiple lines as a single “example” and the interface returns a single prediction for it (e.g. a ranking over those lines).
This is *not* optimization to feed a batch of examples.

Are you looking for something specific in the wrapper?

Markus

**Comment by Wirack** [comment]
Thanks for responding, then the method makes sense for me aswell :)

In relation to looking for something specific in the wrapper:
I do a batch of predictions, so was looking for something to speedup that prediction process.

I will use the predict method with a single example at a time for now :)

Maybe it is worthwhile to add functionality to the wrapper for a batch of predictions?
I am thinking in the nature of multithreading?

**Comment by eisber** [comment]
We support multithreaded already. There is VowpalWabbitThreadedPrediction. It will maintain a pool of VW instances sharing the memory intensive weights between, so it won’t eat up all your memory. Have a look for the test cases to show it works, should be pretty straight forward. The pool allows for model upgrade as well.

Markus

**Comment by Wirack** [comment]
Thanks! will definitely take a look.
