### ISSUE TITLE
Sequence tagging Hogwild mode

### ISSUE THREAD

**Issue by usptact** [JohnLangford/vowpal_wabbit#1063]
I have a large dataset with sequences that have tags in them. I am using the `--search` and `--search_task sequence` options to learn from this data.

The learning from such data is fine but uses only one core. I tried to use Hogwild mode to learn from the dataset while leveraging all cores of my machine.

While learning terminates successfully, I have a question about the quality of the learned model. Are there any hidden underwater stones?

The learning to search approach basically breaks the complex sequence tagging problem to smaller binary classifier training. That is my understanding how it works behind the scenes. I don't know whether Hogwild mode is appropriate for sequence tagging task.

**Comment by JohnLangford** [comment]
It's hard to answer this in any authoritative fashion.  The core issue is that hogwild is a race condition.  Is your problem such that one subset of features can be used and updated while the other subset is doing something else?  That's often true with text features.   It's often not true with dense features.  Whether or not this is beneficial seems strongly problem dependent.

**Comment by usptact** [comment]
@JohnLangford Thanks for mentioning the race condition issue. Yes, the features are lexical features extracted from text (unigrams, bigrams, suffixes/prefixes, capitalization patterns etc, basically Stanford NER features).

My toy dataset is comprised of ~5K sequences. The feature extractor generates about ~150K unique features in total.

**Comment by JohnLangford** [comment]
Just try it and see.

-John
