### ISSUE TITLE
Ultimately running model on test data

### ISSUE THREAD

**Issue by dhruvghulati** [JohnLangford/vowpal_wabbit#1065]
I was unsure from your tutorial on cost sensitive classification how I run my model on my test data:

https://github.com/JohnLangford/vowpal_wabbit/wiki/One-Against-All-%28oaa%29-multi-class-example

Should I create a new dat file called `csoaa_test.dat` which contains only the test features and their tags:
```
0| 0 1 0
1| 1 0 0
2| 1 1 0
3| 1 1 1
```
And then run: `vw -t -i csoaa.model csoaa_test.dat -p csoaa.predict`? In the current tutorial you run this model directly on the same data you trained your model on.

**Comment by JohnLangford** [comment]
Are you using oaa or csoaa (multiclass labels or cost sensitive 
multiclass labels?)

Anyways, the below looks correct, except that your features are odd.  
The feature specification is sparse so you want something like:


0| 2
1| 1
2| 1 2
3| 1 2 3

(where each feature index implicitly has a feature value of 1)

-John

**Comment by dhruvghulati** [comment]
I am using cost sensitive multiclass labels, and those are sparse features because they are a simplified version of a bag of words vector which is 5000 words long for each test instance. So a value is 1 if that word in the vectorizer appears. Is this why I am getting very low recall thus far?

**Comment by arielf** [comment]
Yes,

vw input is not positional (where column defines feature id).

Your input features (not their values) are just 0 and 1.
This doesn't look like it represents distinct words (there are only 2 distinct values which doesn't make sense).

So you should use the words themselves directly, not 0, 1 as the features following the pipe.

**Comment by dhruvghulati** [comment]
@arielf thanks for this. I gave the above as an example but are you saying my features should be:

```
0| cat
1| the
2|the cat
3|the cat mat
```

Not sure if this is what you were referring to, but I thought the value just to the left of the `|` is just a tag so you can call it anything (I just give it the index number of my total samples). I guess that doesn't matter from what @JohnLangford wrote.

**Comment by JohnLangford** [comment]
You need to have a space between the '|' and the first feature.  Otherwise, it treats this is a namespace declaration.

**Comment by dhruvghulati** [comment]
Running into a separate issue more related to cost formation, but the crux of this issue has been solved in my mind now, thanks.
