### ISSUE TITLE
csoaa predicting an invalid class

### ISSUE THREAD

**Issue by dhruvghulati** [JohnLangford/vowpal_wabbit#1067]
I am guessing this may be because I have examples of the exact same features which have different costs for different labels? Or because my training features are very different to my test features?

My model is predicting the label "16" even though I only have training labels from 0 to 15.

```
warning: csoaa predicted an invalid class
NAN prediction in example 14545, forcing 0.000000
```
This happens across all my files, but I have attached a sample pipeline of training to test for one of my pipelines.

Commands run were:

```
vw --csoaa 16 closed_cost_1.dat -f closed_cost_1.model
vw -t -i closed_cost_1.model test.dat -p closed_cost_1.predict
```

[closed_cost_1.dat.txt](https://github.com/JohnLangford/vowpal_wabbit/files/410720/closed_cost_1.dat.txt)
[closed_cost_1.model.txt](https://github.com/JohnLangford/vowpal_wabbit/files/410721/closed_cost_1.model.txt)
[closed_cost_1.predict.txt](https://github.com/JohnLangford/vowpal_wabbit/files/410722/closed_cost_1.predict.txt)
[test.dat.txt](https://github.com/JohnLangford/vowpal_wabbit/files/410723/test.dat.txt)

No idea why this is the case - note that it does predict some values that are within my allowed values but overall most of my predictions have been defaulted to being this invalid class.

**Comment by arielf** [comment]
Not sure if his is the reason but all documentation and examples use 1..N rather than 0..(N-1)

**Comment by JohnLangford** [comment]
That's likely it.

**Comment by dhruvghulati** [comment]
Yes this solved the issue!

**Comment by arielf** [comment]
Thanks.
Please don't close this yet.  I feel there's a need for improving the error message here.  I'll take a stab at it hopefully this week.
