### ISSUE TITLE
Error building python extension

### ISSUE THREAD

**Issue by bobpoekert** [JohnLangford/vowpal_wabbit#1074]
Running `pip install -e .` in the python directory of the current master of vw I get the following error:

```
configure.ac:2: error: required file 'vowpalwabbit/config.h.in' not found
    configure.ac:76: error: required file 'vowpalwabbit/Makefile.in' not found
    configure.ac:76: error: required file 'cluster/Makefile.in' not found
    Makefile.am:1: error: required directory ./vowpalwabbit does not exist
    Makefile.am:1: error: required directory ./cluster does not exist
```

This is on Ubuntu 14.04

**Comment by gramhagen** [comment]
when installing from the local source it will copy over what is in your vowpal_wabbit directory to build the files necessary to make the vw libraries.  do those files not exist in your checkout?  you may want to use python setup to clean the installation and retry:
```
python setup.py clean
python setup.py install
```

**Comment by JohnLangford** [comment]
I'm assuming this is solved and closing.  Thanks @gramhagen
