### ISSUE TITLE
unresolved externals on Windows

### ISSUE THREAD

**Issue by danmelamed** [JohnLangford/vowpal_wabbit#1080]
Linking breaks on Windows.  Looks like the new externals are in the recent code for marginal features.

Error	7	error LNK2019: unresolved external symbol "struct LEARNER::learner<char> * __cdecl marginal_setup(struct vw &)" (?marginal_setup@@YAPEAU?$learner@D@LEARNER@@AEAUvw@@@Z) referenced in function "void __cdecl parse_reductions(struct vw &)" (?parse_reductions@@YAXAEAUvw@@@Z)	C:\dev\Repos\VS2013\vwJLMaster\vowpalwabbit\vw_static.lib(parse_args.obj)	libvw
Error	8	error LNK1120: 1 unresolved externals	C:\dev\Repos\VS2013\vwJLMaster\vowpalwabbit\dll\x64\Debug\libvw.dll	1	1	libvw
Error	9	error LNK2019: unresolved external symbol "struct LEARNER::learner<char> * __cdecl marginal_setup(struct vw &)" (?marginal_setup@@YAPEAU?$learner@D@LEARNER@@AEAUvw@@@Z) referenced in function "void __cdecl parse_reductions(struct vw &)" (?parse_reductions@@YAXAEAUvw@@@Z)	C:\dev\Repos\VS2013\vwJLMaster\cs\cli\vw_dynamic.lib(parse_args.obj)	vw_clr
Error	10	error LNK1120: 1 unresolved externals	C:\dev\Repos\VS2013\vwJLMaster\vowpalwabbit\x64\Debug\VowpalWabbit.Core.dll	1	1	vw_clr
Error	11	error LNK2019: unresolved external symbol "struct LEARNER::learner<char> * __cdecl marginal_setup(struct vw &)" (?marginal_setup@@YAPEAU?$learner@D@LEARNER@@AEAUvw@@@Z) referenced in function "void __cdecl parse_reductions(struct vw &)" (?parse_reductions@@YAXAEAUvw@@@Z)	C:\dev\Repos\VS2013\vwJLMaster\vowpalwabbit\vw_static.lib(parse_args.obj)	vw
Error	12	error LNK1120: 1 unresolved externals	C:\dev\Repos\VS2013\vwJLMaster\vowpalwabbit\x64\Debug\vw.exe	1	1	vw

**Comment by JohnLangford** [comment]
Thanks, this should be fixed in the current master.
