### ISSUE TITLE
Interactions: redundancy and arbitrary choice 

### ISSUE THREAD

**Issue by leonid-ubimo** [JohnLangford/vowpal_wabbit#1081]
Consider the following training (toy_train_data.vw) and test (toy_train_data.vw) sets:

toy_train_data.vw:
1 |app app_cat=1 app_cat=2
-1 |app app_cat=1 app_cat=0
-1 |app app_cat=0 app_cat=0
1 |app app_cat=2 app_cat=1
-1 |app app_cat=2 app_cat=0

toy_test_data.vw:
1 |app app_cat=1 app_cat=2

When applying
vw -d toy_train_data.vw --loss_function logistic -f toy.model -q ::
vw -t -d toy_train_data.vw -i toy.model --invert_hash toy_readable.model -k
I get the model below:

Version 8.2.1
Id
Min label:-50
Max label:50
bits:18
lda:0
0 ngram:
0 skip:
options: --quadratic ::
Checksum: 2790829087
:0
Constant:116060:-0.0389918
app^app_cat=0:151922:-0.39858
app^app_cat=0*app^app_cat=0:26372:-0.449031
app^app_cat=1:123454:0.104361
app^app_cat=1*app^app_cat=0:95976:-0.165491
app^app_cat=1*app^app_cat=1:181668:0.104361
app^app_cat=1*app^app_cat=2:111133:0.154262
app^app_cat=2:169351:0.162436
app^app_cat=2*app^app_cat=0:209655:-0.169681
app^app_cat=2*app^app_cat=1:33211:0.167245
app^app_cat=2*app^app_cat=2:259586:0.162436

The interaction app^app_cat=1*app^app_cat=2 has been duplicated with different coefficients:
app^app_cat=1*app^app_cat=2:111133:0.154262
app^app_cat=2*app^app_cat=1:33211:0.167245

When predicting with --audit option
vw -t -d toy_test_data.vw -i toy.model -p toy_prediction.txt --loss_function logistic --link logistic --audit
I obtain the following output:
app^app_cat=2:169351:1:0.162436@0   app^app_cat=2*app^app_cat=2:259586:1:0.162436@0    app^app_cat=1*app^app_cat=2:111133:1:0.154262@0    app^app_cat=1:123454:1:0.104361@0   app^app_cat=1*app^app_cat=1:181668:1:0.104361@0    Constant:116060:1:-0.0389918@0

One of the coefficients (0.154262) has been chosen arbitrary.

**Comment by leonid-ubimo** [comment]
Have you reproduced this bug? Waiting for a response.

**Comment by JohnLangford** [comment]
I'm not following the issue.  In particular I do not see a duplicate index in the above.  Closing for now, but reopen if you can describe the issue better.

**Comment by leonid-ubimo** [comment]
Actually, app^app_cat=1app^app_cat=2 and app^app_cat=2*app^app_cat=1 is the same interaction. However, it has two different coefficients: 0.154262 and 0.167245.
