### ISSUE TITLE
Option cannot be specified more than once

### ISSUE THREAD

**Issue by martinpopel** [JohnLangford/vowpal_wabbit#1084]
In https://github.com/JohnLangford/vowpal_wabbit/issues/1082#issuecomment-241135130 @arielf wrote

> Seeing how many users get hit by the "cannot be specified more than once" error.
> I'm thinking maybe we should rethink it.

I think this should be discussed in a separate issue (here).
I like @arielf 's suggestion
- Check and if the two 'specified' values for the option are the same, don't abort

**Comment by martinpopel** [comment]
One special example to consider: option `--probabilities` does not change the way a model is trained, but it could be useful in training because it reports multi-class logistic loss (in addition to zero-one loss). The main purpose of `--probabilities` is for testing to convert the predicted values (`-p`) to probabilities.

There may be several models, some trained with  `--probabilities`, some without and I may want to test all of them and predict probabilities. Currently, it is not possible (I need to provide the `--probabilities` option *only* for those models which were trained without it).

For me this is a low-priority issue - I have not encountered the problem above yet. But for newcomers, the error may be counter-intuitive (it says "more than once", but they see the option just once on the command line, they are not aware that it is saved in the model).

**Comment by JohnLangford** [comment]
This is fixed in the master now.
