### ISSUE TITLE
--invert_hash with LDA?

### ISSUE THREAD

**Issue by MaJaHa95** [JohnLangford/vowpal_wabbit#1085]
Hey everyone,

Is it possible to use the `--invert_hash` option with LDA? I've been having trouble getting it to work, and looking at [the code](https://github.com/JohnLangford/vowpal_wabbit/blob/3ab6f489c59cf3825db448f5d287eeb74fb27940/vowpalwabbit/gd.cc#L252), it seems like it might be explicitly ruled out (or I could be totally misinterpreting that).

I'm using the C# wrapper for VW, if that matters (although I assume it shouldn't), and I put together this minimal example.

```
var predictionsFile = Path.GetTempFileName();
var invertedHash = Path.GetTempFileName();

// Examples from https://msdn.microsoft.com/en-us/library/mt762914.aspx
// Yes, my real data gets cleaned before this point.
var lines = new[]
{
    "| This book has its good points. If anything, it helps you put into words what you want from a supervisor",
    "| I admit, I haven't finished this book. A friend recommended it to me as I have been having problems with insomnia",
    "| Poorly written I tried reading this book but found it so turgid and poorly written that I put it down in frustration.",
    "| Since borrowing a dog-eared copy from friends who were passing it around a number of years ago, I have not been able to get my hands on this book which became a short-lived cult favorite",
    "| The plot of this book was interesting, and it could have been a good book. Unfortunately, it wasn't. The main problem for me was that"
};

using (var learner = new VowpalWabbit($"--lda 10 --invert_hash { invertedHash } -p { predictionsFile }"))
{
    learner.Learn(lines);
}

foreach (var line in File.ReadLines(invertedHash).Skip(10))
{
    Console.WriteLine(line);
}
```

However, the lines printed to the console continue to use the keyword indexes (presumably hashed values). It's actually identical output format to `--readable_model`.

It's possible (likely, even) that I'm just misunderstanding something fundamental here; I'm very new to VW, and LDA, and in over my head.

Thanks,
Matthew

**Comment by arielf** [comment]
You can't do that directly.  LDA is not very friendly as default `vw` where you can use features directly and its implementation is often not fully orthogonal to various standard `vw` options. You need to build a dictionary to convert document words and topics to indexes and back.

But no worries, all the heavy lifting and translation back-and-forth has been implemented in a python script in the utl directory:

- `vw-lda`

It was designed tp help you interact with `vw --lda` in a much more friendly/easy way: you give it a collection of docs (directories and/or files) and it does all the LDA topic analysis work for you.

Note that it calls another tiny perl script `vw-doc2lda` to convert documents into vectors for you, so please make sure it is also in your PATH.

Credit: Chetan Ganjihal for most of this contribution.

**Comment by MaJaHa95** [comment]
@arielf Thanks for the response!

And yeah, that's convenient, thanks.

The part I was really looking for (initially removed for brevity) was n-gram support, which doesn't look like it's built into either of those scripts. It's not really an issue for me to implement that myself, but I was hoping to benefit from the work that's already been completed.

But I'll look some more through those scripts and see if I can benefit from them. I already do have a tokenization pipeline (built on Elasticsearch, so no real complaints there), it's just not as fast as I'd like, but that becomes a problem for *their* Issues list :).

Anyway, thank you for your help!

**Comment by arielf** [comment]
I realize this is not always an option for all `vw` users, but if you feel a feature is missing and could add what's missing to the scripts to make them more general, that would be really cool. Thanks!

**Comment by MaJaHa95** [comment]
Unfortunately, my Python skills are...lacking. Not like it's a tough language, but I'd hate to force others to read that :). I'll take a look at it, though.

I would, however, love to build a plugin for VW to work in Elasticsearch. That'd be super handy for my work, and I suspect others' as well. I don't know Java well either (which is required for doing that), but that's something I've thought about doing for a little while. Especially if I can justify it to my manager.

It'd be *super cool* if I could write a query in Elasticsearch, then automatically perform LDA against resultant documents. And not for my use-case, but on the supervised side, it'd be super cool if an Elasticsearch index (or a query from it) could be used to train a model, based again on documents, with a single field indicating the label feature.

I don't know if you know of anything like that already, but if not, I've been thinking about writing that for a little while. There'll be a bit of a learning curve, but I'm thinking about it.
