### ISSUE TITLE
Bug in sort_features?

### ISSUE THREAD

**Issue by KristianHolsheimer** [JohnLangford/vowpal_wabbit#1088]
Hi again,

I just noticed that there might be a bug in the `--sort_features` option. Namely, I noticed that it runs fine on:
```
echo "| foo bar" | vw --sort_features
```
but throws an error on
```
echo "| bar foo" | vw --sort_features
```
Then I looked at integer features, where
```
echo "| 1 2" | vw --sort_features --hash strings
```
runs fine, but
```
echo "| 2 1" | vw --sort_features --hash strings
```
throws an error. Here's the stacktrace: http://pastebin.com/WGiMXpte

Are you able to see what's happening here?

**Comment by arielf** [comment]
@KristianHolsheimer  thanks for the report.

I can't reproduce the error with latest (8.2.1) on Ubuntu 16.04.1 LTS.
All 4 commands seem to work fine, even though I have exactly the same version of libc:  `/lib/x86_64-linux-gnu/libc-2.23.so` as in the pastebin log.

```
$ echo "| foo bar" | vw --sort_features
Num weight bits = 18
learning rate = 0.5
initial_t = 0
power_t = 0.5
using no cache
Reading datafile = 
num sources = 1
average  since         example        example  current  current  current
loss     last          counter         weight    label  predict features
0.000000 0.000000            1            1.0  unknown   0.0000        3

finished run
number of examples per pass = 1
passes used = 1
weighted example sum = 1.000000
weighted label sum = 0.000000
average loss = 0.000000
total feature number = 3
 
 
$ echo "| bar foo" | vw --sort_features
Num weight bits = 18
learning rate = 0.5
initial_t = 0
power_t = 0.5
using no cache
Reading datafile = 
num sources = 1
average  since         example        example  current  current  current
loss     last          counter         weight    label  predict features
0.000000 0.000000            1            1.0  unknown   0.0000        3

finished run
number of examples per pass = 1
passes used = 1
weighted example sum = 1.000000
weighted label sum = 0.000000
average loss = 0.000000
total feature number = 3


$ echo "| 1 2" | vw --sort_features --hash strings
Num weight bits = 18
learning rate = 0.5
initial_t = 0
power_t = 0.5
using no cache
Reading datafile =
num sources = 1
average  since         example        example  current  current  current
loss     last          counter         weight    label  predict features
0.000000 0.000000            1            1.0  unknown   0.0000        3

finished run
number of examples per pass = 1
passes used = 1
weighted example sum = 1.000000
weighted label sum = 0.000000
average loss = 0.000000
total feature number = 3


$ echo "| 2 1" | vw --sort_features --hash strings
Num weight bits = 18
learning rate = 0.5
initial_t = 0
power_t = 0.5
using no cache
Reading datafile =
num sources = 1
average  since         example        example  current  current  current
loss     last          counter         weight    label  predict features
0.000000 0.000000            1            1.0  unknown   0.0000        3

finished run
number of examples per pass = 1
passes used = 1
weighted example sum = 1.000000
weighted label sum = 0.000000
average loss = 0.000000
total feature number = 3


$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.1 LTS"
```

I see this is on some Linux, which exactly, and with what `vw` version do you see this?

Have you built `vw` with `autogen.sh` (known to have issues) or with the default `Makefile`?

Thanks

**Comment by KristianHolsheimer** [comment]
Hmm, that's odd.

I used a fresh clone (and I just did a git pull and make to be sure I have the latest version.. error's still there).
```
$ git rev-parse HEAD
bd68e805b9a21f4e5a27327123f450606981c011
```
Our distributions are the same as well..
```
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.1 LTS"
```

I build by running `make`.

**Comment by arielf** [comment]
Thanks and sorry!

I can reproduce now.

Apparently I wasn't on latest "latest." Only a day old or so.

This is a very recent regression.

make test also fails in test 62 with:
*** Error in `../vowpalwabbit/vw': free(): invalid pointer: 0x0000000000c2acf0 ***

Need to run a `git bisect` to figure out the commit that caused this.

**Comment by arielf** [comment]
Ran git bisect,

Looks like this commit caused the regression:
```
db1b15cbb6b74cf18e45a81902086ebecc100f80 is the first bad commit
commit db1b15cbb6b74cf18e45a81902086ebecc100f80
Date:   Wed Aug 17 21:21:42 2016 -0400

    updated v_array::erase() and delete_v to properly destroy contained elements; removed redundant invocations of same in feature_group.h
```

To verify:
```

$ git checkout db1b15cbb6b74cf18e45a81902086ebecc100f80
$ make vw test

# test 62 fails with:
Aborted
RunTests: test 62: '/usr/bin/timeout 30 ../vowpalwabbit/vw --ksvm --l2 1 --reprocess 5 -b 18 -p ksvm_train.linear.predict -d train-sets/rcv1_smaller.dat' failed (exitcode=134)
```


And also this fails:
```
echo "| bar foo" | vowpalwabbit/vw --sort_features
```

If I go back to one earlier commit:  `commit 77cb357 fixed invalid copying of shared_ptr`
everything runs fine (all tests pass)

```
$ git checkout 77cb357
$ make vw test
# all good

$ echo "| bar foo" | vowpalwabbit/vw --sort_features
# all good
```

@danmelamed can you take a look?

Thanks!

**Comment by arielf** [comment]
@danmelamed 
Looks like the additional object destroy calls caused a double free in one (and potentially more) particular code-path.  This is based on the error message in test 62:
     Error in `../vowpalwabbit/vw': free(): invalid pointer: 0x0000000000c2acf0

**Comment by JohnLangford** [comment]
I can't seem to reproduce?  Neither test 62 nor echo "| 2 1" | vw
--sort_features --hash strings cause an error and everything runs clean
under valgrind.

-John

**Comment by arielf** [comment]
Are you on Ubuntu 16.04?

**Comment by JohnLangford** [comment]
No, 14.04.4.

-John

**Comment by arielf** [comment]
Just tried on 14.04 as well - can't reproduce there.
On 16.04 it reliably reproduces.
16.04 has a much newer compiler (g++ 5.4.0) among many other upgrades.

**Comment by JohnLangford** [comment]
I'll need to upgrade as well.

The change that Dan introduced seems correct, so there may be some places in the code which were papering over an incorrectness here.

**Comment by JohnLangford** [comment]
I checked in a fix for this here: https://github.com/JohnLangford/vowpal_wabbit/commit/30d383e7a7cf4dd244a244f54d4110a882941cd5  Basically, there was something sketchy with sort related to audit features when you don't have a audit features.  Anyways, it should be fixed now.

**Comment by JohnLangford** [comment]
(Thanks for the report.)

**Comment by KristianHolsheimer** [comment]
Thanks so much for fixing this so quickly, much appreciated!!

**Comment by arielf** [comment]
Thanks John.
Confirming that this issue is gone in commit 30d383e7a7cf4dd244a244f54d4110a882941cd5
