### ISSUE TITLE
Python sklearn - error in pip version

### ISSUE THREAD

**Issue by tomkee** [JohnLangford/vowpal_wabbit#1089]
While training data with sklearn.VWClassifier I got error in self.fit():

> KeyError 0: In function fit(), line 277:
>     X = tovw(x=X, y=y, sample_weight=sample_weight)[0]
> This problem occurs only in version from pip, the one from repo works great.

**Comment by gramhagen** [comment]
Ah.  Ok I will update the version in PyPI shortly. On vacation right now.
Thanks!

**Comment by gramhagen** [comment]
@tomkee - I just released 8.2.1 to PyPI.  Let me know if that works for you.

**Comment by tomkee** [comment]
Yes, it works!

**Comment by gramhagen** [comment]
Great!
