### ISSUE TITLE
What does vowpal assign as the costs of undefined label:cost pairs for a training instance in csoaa

### ISSUE THREAD

**Issue by dhruvghulati** [JohnLangford/vowpal_wabbit#1091]
I am curious what the underlying algorithm assigns as the cost for undefined label-cost pairs for a training instance (for example if I have 4 potential labels, but on each row I only put the cost for 1 label instead of all 4). i.e.:

```
3:0.04 instance1| the cat sat on mat
2:0.01 instance2| location_slot united states
```

Instead of:

```
1:0.23 2:0.56 3:0.04 4:0.78 instance1| the cat sat on mat
1:0.61 2:0.01 3:0.08 4:0.03 instance2| location_slot united states
```

Are the costs for every other label assigned as 1? infinity? `None`?

**Comment by JohnLangford** [comment]
None is more accurate.  Each entry corresponds to an update, and no update occurs if you do not specify an entry.
