### ISSUE TITLE
vowpal wabbit with Python - Anaconda: Fatal Python error

### ISSUE THREAD

**Issue by lmsanch** [JohnLangford/vowpal_wabbit#1095]
I am installing Vowpal Wabbit VW (including dependencies) following the steps below :

```
$ brew install libtool autoconf automake
$ brew install boost
$ brew install boost-python
pip install vowpalwabbit
```

Everything installs fine w/o errors, however, when I try to import VW from python, I get the following:

```
Python 2.7.11 |Anaconda custom (x86_64)| (default, Dec  6 2015, 18:57:58) 
[GCC 4.2.1 (Apple Inc. build 5577)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> from vowpalwabbit import pyvw
Fatal Python error: PyThreadState_Get: no current thread
Abort trap: 6

```
Does anybody know how to fix this issue?

**Comment by arielf** [comment]
Does this error occur if you use the system python, or only when you use anaconda's?
Generally speaking: you cannot mix C++/boost libraries compiled with different compilers/ABIs etc.

**Comment by lmsanch** [comment]
I only use anaconda's python..my development environment is all there.

**Comment by arielf** [comment]
Obviously you use Anaconda's python but your system has multiple pythons installed. `brew install` is probably not using "your" (preferred) python. Along similar lines: can you run `pip install` again with `--verbose` in effect, and look at what it does. Mainly at the paths it prints.  Does it install into the Anaconda env?

I'm by no means a Mac OS-X env expert, and I don't use a Mac (or conda) but I know mixing-up python virtual-envs and binary incompatible C++ modules is always a recipe for trouble.

The below threads may provide you with some hints on possible fixes:

- [https://stackoverflow.com/questions/15678153/homebrew-python-on-mac-os-x-10-8-fatal-python-error-pythreadstate-get-no-cu](https://stackoverflow.com/questions/15678153/homebrew-python-on-mac-os-x-10-8-fatal-python-error-pythreadstate-get-no-cu)
- [https://stackoverflow.com/questions/22244642/macports-python-on-mac-os-x-mavericks-fatal-python-error-pythreadstate-get](https://stackoverflow.com/questions/22244642/macports-python-on-mac-os-x-mavericks-fatal-python-error-pythreadstate-get)

HTH

**Comment by lmsanch** [comment]
Thank you. It is very difficult to make VW work with Anaconda. Nevertheless, I found a temp solution: I created a Ubuntu VM and installed everything there. Works fine.

**Comment by arielf** [comment]
Igualmente, Hermano.  Glad you found a solution.  The problem is that `vw` uses `boost` and `boost` tends to change ABI (binary interface) very frequently, so if anaconda was built with one tool-set and/or boost-library version and `vw` with a different one, the two can't inter-operate.

**Comment by marsal64** [comment]
Hi, below is my fix for Centos 7

# Anaconda 3 installed in /opt/anaconda3
# clone vowpal wabbit
cd /opt
git clone  https://github.com/JohnLangford/vowpal_wabbit.git
# install boost into Anaconda
conda install -c anaconda boost
# amend boost library path for vowpal wabbit
export LD_LIBRARY_PATH="/opt/anaconda3/lib"
export LIBRARY_PATH="/opt/anaconda3/lib"
export CPLUS_INCLUDE_PATH="/opt/anaconda3/include"
# compile and install vowpal wabbit
cd /opt/vowpal_wabbit/python
python setup.py install
# test
python -c "from vowpalwabbit import pyvw; vw = pyvw.vw(quiet=True); ex = vw.example('1 | a b c'); vw.learn(ex); print(vw.predict(ex))"

**Comment by franz101** [comment]
@marsal64 wow, this made installation possible... but still getting:
ModuleNotFoundError: No module named 'pylibvw'
