### ISSUE TITLE
VW C# bindings under Mono?

### ISSUE THREAD

**Issue by emrobi** [JohnLangford/vowpal_wabbit#1099]
Is it possible to get the C# binding/nuget package to run under Mono on a Linux box?

**Comment by eisber** [comment]
Unlikely as the binding used C++/CLI that’s not supported under Mono. We’d have to change quite a bit to make use of PInvoke.

**Comment by JohnLangford** [comment]
There is an old PInvoke interface available. My understanding is that PInvoke is also not such a great interface because you have much less type safety.
