### ISSUE TITLE
run vw under cluster env with --bfgs option has multiple different output model

### ISSUE THREAD

**Issue by lcytzk** [JohnLangford/vowpal_wabbit#1100]
Before I use --bfgs option, I modify the single_machine by adding --readable_model in order to save my model than run the script, and I got two same model files.

After this, I add --bfgs option, and rerun the script, but I got two different model files.

Maybe I do it in a wrong way, but I can not find other specific infos about cluster with bfgs, so PLEASE help me.
1. Did I do something wrong or miss something?
2. Or maybe the phenomenon I discribe above is expected? If so, how to get the final model?

Thanks for your helping. 

PLUS:
1. I cat two file as one file then run vw command locally without cluster options, but got a model file different from two model files before. No matter I add --bfgs option or not. Why the results are differen from each other?

PLUSS:
2. I read the runvw.sh and notice that it do gd first then bfgs, so I do the same way, and got two same models, but why? Why only bfgs broken? The question above remains, the model generated by cluster is different from the local version.

**Comment by JohnLangford** [comment]
There isn't enough information here to debug.  I suspect your script is somehow not symmetric across the machines leading to badness.
