### ISSUE TITLE
vw --loss_function logistic --oaa 5 -i model -t -d test.vw -r raw_predictions.txt .. results in empty raw_predictions.txt file

### ISSUE THREAD

**Issue by ankit20395** [JohnLangford/vowpal_wabbit#1103]
vw --loss_function logistic -i model -t -d test.vw -r raw_predictions.txt  only testing
raw predictions = raw_predictions.txt
Num weight bits = 18
learning rate = 0.5
initial_t = 0
power_t = 0.5
using no cache
Reading datafile = test.vw
num sources = 1
average  since         example        example  current  current  current
loss     last          counter         weight    label  predict features

if I remove --oaa then it generate a empty raw_prediction file...

**Comment by JohnLangford** [comment]
This seems to be fixed in the current master.
