### ISSUE TITLE
Convergence for active learner

### ISSUE THREAD

**Issue by fgregg** [JohnLangford/vowpal_wabbit#1109]
Thanks for the great package!

With VW's active learning, is there any a way to evaluate convergence or other principled rules to stop asking for examples?

Best,

Forest

**Comment by JohnLangford** [comment]
If you use --confidence, it outputs an estimate of the importance of an 
example with the opposite label required to cause the prediction to 
change.  This could be leveraged into a stopping rule, if desired.

-John

**Comment by fgregg** [comment]
Does this change expected input for the active learning. 

I'm using the current version from github

With this this command to start the server:

```bash
vw --active --loss_function logistic --port 26542 --mellowness 0.01 --confidence
```
I can send two labeled examples over the socket

1. `-1 1 | 0:2.598557710647583 1:3.6677632331848145 2:0.0 3:4.785714149475098 4:1.0 5:1.0`
2. `'-1 1 | 0:4.596938610076904 1:4.121527671813965 2:0.0 3:4.785714149475098 4:1.0 5:1.0`

But when I try to send a third example the socket is closed

`-1 1 | 0:1.6666666269302368 1:3.9962120056152344 2:0.0 3:1.9285714626312256 4:0.0 5:1.0`

Everything works fine if I omit the `--confidence` flag.

**Comment by JohnLangford** [comment]
Yes.... 

You probably want to periodically save the model and then evaluate with --confidence.
