### ISSUE TITLE
problem of running on hadoop clusters

### ISSUE THREAD

**Issue by ll3021359** [JohnLangford/vowpal_wabbit#1110]
when run the runvw-yarn.sh code on hadoop clusters, the job stop at the following status and didn't progress, what the problems is ? (I tested the code on non-hadoop clusters and worked)

16/09/27 01:09:50 INFO mapreduce.Job: Running job: job_1471428592509_1165868
16/09/27 01:10:03 INFO mapreduce.Job: Job job_1471428592509_1165868 running in uber mode : false
16/09/27 01:10:03 INFO mapreduce.Job:  map 0% reduce 0%
16/09/27 01:10:19 INFO mapreduce.Job:  map 20% reduce 0%
16/09/27 01:10:21 INFO mapreduce.Job:  map 37% reduce 0%
16/09/27 01:10:22 INFO mapreduce.Job:  map 42% reduce 0%
16/09/27 01:10:24 INFO mapreduce.Job:  map 48% reduce 0%
16/09/27 01:10:25 INFO mapreduce.Job:  map 75% reduce 0%
16/09/27 01:10:27 INFO mapreduce.Job:  map 77% reduce 0%
16/09/27 01:10:28 INFO mapreduce.Job:  map 88% reduce 0%
16/09/27 01:10:34 INFO mapreduce.Job:  map 94% reduce 0%
16/09/27 01:10:37 INFO mapreduce.Job:  map 100% reduce 0%

**Comment by JohnLangford** [comment]
VW typically runs in a map only mode where communication is direct between VW instances.  You'll need to examine the error output of individual mappers to diagnose further.
