### ISSUE TITLE
Sklearn interface is not providing parameter for low rank quadratic features ( --lrq )

### ISSUE THREAD

**Issue by felixmaximilian** [JohnLangford/vowpal_wabbit#1116]
Regarding the python interface, it seems that the sklearn wrapper does not provide the "--lrq" parameter in vowpalwabbit.sklearn_vw.VWClassifier.
This makes it impossible to enable the factorization machine style classification.

**Comment by JohnLangford** [comment]
@gramhagen is this an easy fix?

**Comment by gramhagen** [comment]
should be, let me test it out now

**Comment by gramhagen** [comment]
this is all set, thanks for pointing it out @felixmaximilian
