### ISSUE TITLE
How to create multiline examples for predictions in Python?

### ISSUE THREAD

**Issue by usptact** [JohnLangford/vowpal_wabbit#1121]
Hi,

I've trained a --csoaa_ldf model which makes use of multiline examples. Each example is a block of lines: each line tells what loss is incurred.

Here is one example:

```
1:0 |f <features> |g <features>
2:1 |f <features> |g <features>
...
50:0 |f <features> |g <features>
\n
```

I would like to use Python interface for making predictions. I installed the vowpalwabbit package for Python and managed to load the model.

It is unclear to me how to build an example for prediction task. I tried to pass a string with all block lines separated with a newline symbol but that does not appear to work. I get a single digit as prediction. The prediction is expected to be a series of numbers, one for each possible class (as many as lines in the block).

I looked in the python directory for examples but failed to find on what to do with multiline examples.

**Comment by JohnLangford** [comment]
@gramhagen @hal3 csoaa_ldf is possible via the python interface, right?

**Comment by gramhagen** [comment]
Yes, I believe so.  I haven’t tested it through the scikit learn interface,
but you can import pyvw from vowpalwabbit and call pyvw.vw() with csoaa ldf
params.

**Comment by JohnLangford** [comment]
It's more complicated than just the parameters because multiline examples
are not (yet) first class primitives in VW.  Essentially, you need to input
a stream of examples corresponding to individual lines and ending in an
empty example (equivalent to a newline), then read out the predictions from
the input examples.

Again, I believe this should be working, but I don't have a quick test case
to confirm.

**Comment by gramhagen** [comment]
There is some code in the python binding to accept examples for ldf.  If
you can point me to a script exercising that functionality from the command
line I can create a python test.

**Comment by JohnLangford** [comment]
Functionality is exercised here:
https://github.com/JohnLangford/vowpal_wabbit/blob/master/test/RunTests#L875

-John

**Comment by gramhagen** [comment]
ok, digging in more, couple problems, the current python wrapper is only providing the partial prediction for context sensitive and cbandits label types. There are some bugs there I can fix. Should we also support --probabilities here to provide all probabilities for each label?

as for the multiline support, learning string inputs gets routed to this function in pylibvw.cc
```
float my_learn_string(vw_ptr all, char*str)
{ example*ec = VW::read_example(*all, str);
  all->learn(ec);
  float pp = ec->partial_prediction;
  VW::finish_example(*all, ec);
  return pp;
}
```
should we expect read_example() and learn() to manage the multiline input?

**Comment by JohnLangford** [comment]
The VW core does not support multline examples as a first class object yet,
so "no" unfortunately.   It's on the todo list.

-John

**Comment by gramhagen** [comment]
ok, I'll work on getting the correct prediction out.

@usptact, until we can support multiline you'll have to convert your blocks to single examples externally with something like this:

```
def convert_multiline_examples(multiline):
    examples = []
    labels = []
    features = []
    for line in multiline.split('\n'):
        if not line:
            examples.append('{l} | {f}'.format(l=' '.join(labels), f=' '.join(features)))
            labels = []
            features = []
        else:
            label_cost, feature_str = line.split('|')
            label, cost = label_cost.strip().split(':')
            feature_str = ' '.join(['{l}_{f}'.format(l=label, f=f) for f in feature_str.strip().split()])
            labels.append(label_cost)
            features.append(feature_str)
    if labels:
        examples.append('{l} | {f}'.format(l=' '.join(labels), f=' '.join(features)))
    
    return examples
```

**Comment by usptact** [comment]
@gramhagen Thanks a lot for your time looking into the issue! Should I close this ticket then?

**Comment by gramhagen** [comment]
yeah, I plan to roll the fixes to the csoo and context bandits estimates
from python into the rework of PR #1139

On Tue, Nov 29, 2016 at 2:10 PM usptact <notifications@github.com> wrote:

@gramhagen <https://github.com/gramhagen> Thanks a lot for your time
looking into the issue! Should I close this ticket then?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/JohnLangford/vowpal_wabbit/issues/1121#issuecomment-263667339>,
or mute the thread
