### ISSUE TITLE
Add rapidjson to dependency list

### ISSUE THREAD

**Issue by omtcyfz** [JohnLangford/vowpal_wabbit#1123]
I've tried to install `vowpal_wabbit` on my Ubuntu 16.10 and I get this kind of error:

``` c++
./parse_example_json.h:16:10: fatal error: 'rapidjson/reader.h' file not found
#include <rapidjson/reader.h>
         ^
```

Basically, this means that `rapidjson` is missing. However, I have installed all dependencies from README.

Thus, please add

``` bash
sudo apt-get install rapidjson-dev
```

To the Ubuntu installation instructions.

**Comment by eisber** [comment]
Rapidjson is actually a subtree of VW github source. Did you sync to from github?

**Comment by omtcyfz** [comment]
Aw, yes, sorry. Didn't notice that.

Hm... That's really weird. I just cloned the repo few hours ago and during build stage I got these messages every time.

Actually, what I did was basically

```bash
apt-get install libboost-program-options-dev zlib1g-dev
git clone git://github.com/JohnLangford/vowpal_wabbit.git
cd vowpal_wabbit
make CXX=clang++
```

**Comment by arielf** [comment]
I just verified (on vanilla Ubuntu 16.04.1) that no additional package install is needed.  `vw` clones and builds (with either clang++, or g++) , and passes `make test` on a system without `rapidjson` (or `rapidjson-dev`) installed.

Could this be 16.10 specific?  I haven't yet moved to 16.10.

**Comment by omtcyfz** [comment]
@arielf I don't know whether that is Ubuntu 16.10 issue, but building with `make` instead of `make CXX=clang++` does help to get rid of this error.

```bash
$ clang++ --version
clang version 3.8.1-12ubuntu1 (tags/RELEASE_381/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

**Comment by arielf** [comment]
Interesting, on 16.04.1 it builds fine but the version is slightly older:
```
$ clang++ --version
clang --version
clang version 3.8.0-2ubuntu4 (tags/RELEASE_380/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

This may be a clang bug. There was another fixed pretty recently which prevented clang++ from linking `vw` (ABI incompatibility with Ubuntu precompiled libs).

Anyway, it doesn't look like a `vw` issue since it builds with gcc, so closing this for now.

**Comment by aszalucha** [comment]
@arielf I had the problem on 16.04.1 when I used ./autogen.sh
However on the other 16.04.1 when I didn't use ./autogen.sh everything work
