### ISSUE TITLE
same training configuration, different data format, inconsistent results 

### ISSUE THREAD

**Issue by ghost** [JohnLangford/vowpal_wabbit#1125]
I'm new to `vw`, doing some experiments with it, and I observed some really really weird issue which confuses me badly.

I have a very simple dataset, see below (let's call it `a.vw`):

```
-1 |a 1 |b c57
1 |a 2 |b c3
```

yes, 2 namespaces (`a` and `b`), and after reading wiki, I know that `vw` will automatically make the real features like `a^1` or `b^c57`.
However, before I knew it, I actually made a `vw` file like this (call it `b.vw`):

```
-1 |a a_1 |b b_c57
1 |a a_2 |b b_c3
```

As you can see, I just add prefix for each feature manually.

Now I train models on both files with same configuration, like this:

```
cat a.vw | vw --loss_function logistic --passes 1 --hash all -f a.model --invert_hash a.readable  --random_seed 1
cat b.vw | vw --loss_function logistic --passes 1 --hash all -f b.model --invert_hash b.readable --random_seed 1
```

then I checked the readable model files, they're the same, see below:

```
$ cat a.readable
Version 8.2.1
Id
Min label:-50
Max label:50
bits:18
lda:0
0 ngram:
0 skip:
options:
Checksum: 295637807
:0
Constant:116060:-0.0539969
a^1:112195:-0.235305
a^2:1080:0.243315
b^c3:46188:0.243315
b^c57:166454:-0.235305
```

```
$ cat b.readable
Version 8.2.1
Id
Min label:-50
Max label:50
bits:18
lda:0
0 ngram:
0 skip:
options:
Checksum: 295637807
:0
Constant:116060:-0.0539969
a^a_1:252326:-0.235305
a^a_2:85600:0.243315
b^b_c3:166594:0.243315
b^b_c57:227001:-0.235305
```

Finally, I did prediction using both models on both datasets respectively, like this:

```
$ cat a.vw | vw -t -i a.model -p a.pred --link logistic --quiet
$ cat b.vw | vw -t -i b.model -p b.pred --link logistic --quiet
```

Now, here comes the problem, `a.pred` holds very different results from `b.pred`, see below:

```
$ cat a.pred
0.428175
0.547189

$ cat b.pred
0.371776
0.606502
```

WHY? Does it mean we have to manually add prefix for features?

**Comment by MLWave** [comment]
Can reproduce when leaving in `--hash all`.

> By default VW hashes string features and does not hash integer features. --hash all hashes all feature identifiers. This is useful if your features are integers and you want to use parallelization as it will spread the features almost equally among the threads or cluster nodes, having a load balancing effect.

`cat a.vw`

`-1 |a a_1 |b b_c57
1 |a a_2 |b b_c3`

`cat b.vw`

`-1 |a 1 |b c57
1 |a 2 |b c3`

`vw --loss_function logistic -d b.vw -f b.model --hash all`

`vw --loss_function logistic -d a.vw -f a.model --hash all`

`vw -d b.vw -t -i b.model -p b.preds --link logistic`

`vw -d a.vw -t -i a.model -p a.preds --link logistic`

`cat a.preds`

`0.428175
0.547189`

`cat b.preds`

`0.371776
0.606502`

Can not reproduce when leaving out `--hash all`.

`cat a.vw`

`-1 |a a_1 |b b_c57
1 |a a_2 |b b_c3`

`cat b.vw`

`-1 |a 1 |b c57
1 |a 2 |b c3`

`vw --loss_function logistic -d b.vw -f b.model`

`vw --loss_function logistic -d a.vw -f a.model`

`vw -d b.vw -t -i b.model -p b.preds --link logistic`

`vw -d a.vw -t -i a.model -p a.preds --link logistic`

`cat a.preds`

`0.371776
0.606502`

`cat b.preds`

`0.371776
0.606502`

I think this is intended behavior, given the "By default VW hashes string features and does not hash integer features.".

**Comment by JohnLangford** [comment]
The problem with this seems to be an inconsistent application of --hash all.  I've modified VW to keep --hash all in the file arguments if it is ever used.

**Comment by JohnLangford** [comment]
Oh, and thanks :-)
