### ISSUE TITLE
Segmentation fault when use JSON

### ISSUE THREAD

**Issue by sh1ng** [JohnLangford/vowpal_wabbit#1128]
vw -d train_0.json --json --compressed --rank 5  --cache_file vw.cache
Num weight bits = 18
learning rate = 10
initial_t = 1
power_t = 0.5
creating cache_file = vw.cache
Reading datafile = train_0.json
num sources = 1
average  since         example        example  current  current  current
loss     last          counter         weight    label  predict features
Segmentation fault (core dumped)

[train_0.json.zip](https://github.com/JohnLangford/vowpal_wabbit/files/579384/train_0.json.zip)

**Comment by eisber** [comment]
The format is not supported, have a look here: https://github.com/JohnLangford/vowpal_wabbit/wiki/JSON
Individual examples must be on separate lines, not elements of an array.
I’ll look into making the error messaging more graceful.

**Comment by sh1ng** [comment]
Thanks you for the clarification.

By the way, that could be a great feature, it's easier(and probably faster) to generate valid json than process it line by line.

**Comment by eisber** [comment]
It very much depends on the JSON generating system. If you use something like Azure Stream Analytics, it creates line separated JSON by default.

The C# JSON parser supports arrays, I might add it to the C++ part too.

**Comment by sh1ng** [comment]
I'm using python pandas to produce json chunks(just dataframe.to_json).

I don't really know internal implementation and why do you need per line json, but in my opinion if you support json as input format it should be just a valid json. JSON Array sounds logical for me.

**Comment by sh1ng** [comment]
On the other hand if you consider input stream of data as json objects separated by \n it's better to distinguish --JSON and --JSON_STREAM and support both of them.
