### ISSUE TITLE
Predictions for Learning 2 Search with PyVW degrade after ~200 examples

### ISSUE THREAD

**Issue by samuelbroscheit** [JohnLangford/vowpal_wabbit#1129]
I have implemented a joint tokenizer and sentence boundary detector to play around with learning 2 search and pyvw a little bit. I extended the BIO sequence tagging scheme with an additional state for the sentence boundary. 

During training I supply sequences consisting of multiple continuous sentences.

During testing I supply the whole document for prediction. After (in average) ~200 examples (characters) the predictions degrade and randomly create sequences that have no apparent connection to the current input. 

Am I missing something here? I've changed everything that I could think of: example ring size, number of epochs, number and size of training sequences, different feature sets but nothing changed.

**Comment by JohnLangford** [comment]
It's hard to comment without having something reproducible.  Can you make a reproducible test case?

**Comment by samuelbroscheit** [comment]
Hi John,


yeah sure, I'll try to create an example. I just wanted to make sure that I
didn't miss something obvious. Thank you for creating such an amazing piece
of software, btw.

Best,

Samuel

**Comment by JohnLangford** [comment]
Closing this for now.  Reopen if/when you get a test case we can use.
