### ISSUE TITLE
Mac build?

### ISSUE THREAD

**Issue by allonbendavid** [JohnLangford/vowpal_wabbit#1131]
I can't build _any_ version of the JNI for Darwin with MacOS Sierra and any variant of libboost (1.5.5, 1.5.9, 1.6.0, 1.6.2).  I've gone back to tags of released binaries that include the Darwin lib in the jar and I cannot build them successfully either.  I think they might have been built on a previous OS and/or previous versions of boost.

If anyone can build the Darwin lib (java/src/main/bin/build.sh), please let me know what version of boost and build tools/OS you are using.

Thanks!

**Comment by JohnLangford** [comment]
@jmorra @deaktator any idea what's going wrong?

**Comment by deaktator** [comment]
I don't have MacOS Sierra on any computer. Maybe I can upgrade one of my personal computers and take a look.  I'll get back.

**Comment by allonbendavid** [comment]
I'm also trying another technique on the tagged 8.2.0 to see if I can get
it built again,  I'll update everyone but I'm not optimistic.  If anyone
else is successful that would be a milestone.

Thx.

**Comment by allonbendavid** [comment]
The other anomaly is if you download/clone tag 8.2.0, the POM in the java
project is versioned at 8.1.2-SNAPSHOT, so I'm not sure what version you're
getting when you add 8.2.0 as a maven dependency.

**Comment by allonbendavid** [comment]
Yeah, just double-checked, there is no git history in master of the POM
ever being at 8.2.0.  Jumps from 8.1.2-SNAPSHOT to 8.2.1-SNAPSHOT

**Comment by deaktator** [comment]
Hey Allon,

I'm pretty positive the tagging process and maven release are independent. It would be nice to unify this somehow but I'm not really sure how.

**Comment by allonbendavid** [comment]
I'm not quite sure how the overall build is being done and tagged, but what
is strange is that there is a Maven release of 8.2.0 but there is no Git
history of the POM ever being at that version, so you really don't know
what revision of the code you're getting when you pull that.  Seems like
someone may have updated the POM to that version locally, did a release
build and deploy from their desktop, but never checked in the version, so
the master has no record of it.

**Comment by jon-morra-zefr** [comment]
Unfortunately I am very familiar with how the release process is done and it's very messy.  The pom versioning is controlled by `configure.ac`.  The file you mainly want to look at is `java/src/main/bin/build.sh`.  One of our medium term goals is to rewrite the entire release process to make it more streamlined.  Until that is done, however, we're left in a less than idea situation.

As for your specific question, I don't have Seirra installed so I can't look myself.  I'm guessing that it was 1.59, but I'm not positive.

**Comment by allonbendavid** [comment]
I looked at the date of the Darwin lib in the JNI jar and it was dated
7/11/16.  In git there was a merge of master on that date, so I checked out
that revision and was able to build a lib for Alpine (not macOS still) that
seems to operate the same as the pre-built mac binary.  So I'm guessing the
java lib version 8.2.0 is likely a build of the 7/11 merge of master.

At least I have that going now. VW Java on Docker Alpine container; not bad!

**Comment by JohnLangford** [comment]
I'm going to leave this open for now, so we have a todo to improve the Java build.

**Comment by raoufaghrout** [comment]
Is there any update on this? 

It would be great to get a vw-jni jar released for version 8.3.0 / 8.3.1.

**Comment by cpdomina** [comment]
I was also unable to run the JNI build with MacOs Sierra. The only way it worked for me was using the compiled library from [Maven](https://mvnrepository.com/artifact/com.github.johnlangford/vw-jni) (version 8.2.0) and following  [this instructions](https://github.com/eHarmony/aloha/tree/master/aloha-vw-jni).
It seems that the latest version of `boost` that you get with `brew install` works for compiling `vw` but not the JNI.

**Comment by allonbendavid** [comment]
Yeah, I think that was my experience too.  Had to get the lib from 8.2.0,
which also maybe mis-versioned because if you checkout that tag, it is not
the same.

**Comment by jon-morra-zefr** [comment]
There is an open PR to improve the whole build system.  I would love to get some feedback on that.

**Comment by JohnLangford** [comment]
@jon-morra-zefr PR has been merged, so I'm closing this for now.
