### ISSUE TITLE
vw-varinfo: command not found

### ISSUE THREAD

**Issue by tonygrey** [JohnLangford/vowpal_wabbit#1144]
I installed vowpal wabbit 7.3.0 in linux-mint. I am able to use vw for training and predicting. But, I am not able to execute the command vw-varinfo. It is giving an error 'command not found'.

**Comment by arielf** [comment]
vw-varinfo isn't included in the package.
You can get it from the git repository `utl` subdirectory:
[https://github.com/JohnLangford/vowpal_wabbit/tree/master/utl](https://github.com/JohnLangford/vowpal_wabbit/tree/master/utl)

**Comment by tonygrey** [comment]
I downloaded utl subdirectory. what should I do to get it running?

**Comment by arielf** [comment]
Just call it by name.

Make sure the directory is in your `PATH` and files in it are executable, and call it from any shell.
Alternatively copy the `vw-varinfo` script (it is a perl script) to any directory that is already in your `PATH`.

Use:   `echo $PATH` in a shell to see your current `PATH` setting.

Change `PATH` in your `~/.profile` or `~/.bashrc` to make it take effect after each login. 

See, e.g:  [https://askubuntu.com/questions/60218/how-to-add-a-directory-to-the-path](https://askubuntu.com/questions/60218/how-to-add-a-directory-to-the-path)

**Comment by JohnLangford** [comment]
Looks resolved, closing.  Thanks @arielf
