### ISSUE TITLE
how to prevent vw from hashing on cluster training

### ISSUE THREAD

**Issue by robbine** [JohnLangford/vowpal_wabbit#1145]
hi, I tried to run logistic regression on cluster, however I cannot prevent vw from hashing
my training sample looks like this "-1 | 0:1.0 2:1.0 10:1.0 16:1.0 180:1.0 6485:1.0 6624:1.0 13351:1.0 18135:1.0 23042:1.0 30743:1.0 30970:1.0 37886:1.0 51155:1.0"
my script looks like this
gdcmd="./vw 
        --noconstant
        --total $nmappers
        --node $mapper
        --unique_id $mapred_job_id
        --passes 20
        --readable_model sgd.rmodel
        -d /dev/stdin
        -f sgd.vwmodel
        --cache_file temp.cache
        --span_server $submit_host
        --loss_function=logistic"

mapred_job_id=`expr $mapred_job_id \* 2` #create new nonce
bfgscmd="./vw
        --noconstant
        --total $nmappers
        --node $mapper
        --unique_id $mapred_job_id
        --cache_file temp.cache
        --bfgs
        --mem 5
        --passes 2
        --save_per_pass
        --readable_model bfgs.rmodel
        --span_server $submit_host
        -f bfgs.vwmodel
        -i sgd.vwmodel
        --loss_function=logistic"

**Comment by robbine** [comment]
I tried to add --invert_hash so that I can get a mapping between orignal index and hash index
but it confilcts with both multiple pass and cache file

**Comment by robbine** [comment]
I tried to use these two cmds in map script, it seems working.
gdcmdfirst="./vw 
        -b 30
        --total $nmappers
        --node $mapper
        --unique_id $mapred_job_id
        -d train.data
        -c
        --passes 4
        -f sgd0.vwmodel
        --span_server $submit_host
        --loss_function=logistic"

gdcmdlast="./vw 
        -t
        -p prediction
        --invert_hash my.invert_hash
        --total $nmappers
        --node $mapper
        --unique_id $mapred_job_id
        -d train.data
        -i sgd$pass.vwmodel
        -f sgd.vwmodel
        --span_server $submit_host
        --loss_function=logistic"

**Comment by JohnLangford** [comment]
VW always hashes, but in the case where an index is used as a feature, the index is the hash (by default).  Hence, you need do nothing.  If you want to look at what the parameters are use --readable_model <filename>
