### ISSUE TITLE
rapidjson/reader.h: No such file or directory

### ISSUE THREAD

**Issue by dselivanov** [JohnLangford/vowpal_wabbit#1157]
Reporting to just let you know, on 14.04.4 LTS I got following:
```sh
make
```
> fatal error: rapidjson/reader.h: No such file or directory’

Solved as suggested here: http://stackoverflow.com/questions/40253440/vowpal-wabbit-installation-encounters-error-of-rapidjson-reader-h

**Comment by JohnLangford** [comment]
Thanks, I fixed this.  The problem was that the automake build wasn't updated when rapidjson was added for json parsing.
