### ISSUE TITLE
[HELP]vowpal wabbit c api is stable? predict the same query ,cost different time

### ISSUE THREAD

**Issue by xjj210130** [JohnLangford/vowpal_wabbit#1158]
hi all:
  i use vowpal wabbit c api  to predict score. When i test the same query more than 10000 times,  the vw cost different time . Most of time is less than 2ms, but some of time cost 50ms. It cost too much.
Is there some one meet this questions.
The following is my code:
 example *item;
 vw *tmp_model=VW::initialize((char *)"-t -i " + path)

item = VW::read_example(*tmp_model, cstrFeature);
tmp_model->learn(item);
 VW::finish_example(*tmp_model, item);

Thanks very much.

**Comment by xjj210130** [comment]
There are 24 threads  to accept reqs, one request use one thread .
I use the following code:
item = VW::read_example(*tmp_model, cstrFeature);
tmp_model->learn(item);
VW::finish_example(*tmp_model, item);

in the same thead.

**Comment by eisber** [comment]
I don’t think the learn function is thread safe…

**Comment by xjj210130** [comment]
I use the code like the following:
 void predict()
{
item = VW::read_example(*tmp_model, cstrFeature);
tmp_model->learn(item);
VW::finish_example(*tmp_model, item);
}

each thread use the function independently.  

The above question , maybe  is my fault, I should  add para: ring_size.

**Comment by eisber** [comment]
Do you lock(*tmp_model) or have separate *tmp_model instances?

Markus

**Comment by xjj210130** [comment]
Do you meaning, each thread use separate  vw pointer?or, the vw should be locked?
In fact ,i use only one vw instances. i init it once:   vw*pVw = VW::initialize();
all thread use the pVw.

I use it like the above method, is it wrong?
Thank you very much.

**Comment by JohnLangford** [comment]
Are you trying to predict or learn?

**Comment by xjj210130** [comment]
i use vw to predict ,It's online service.

**Comment by JohnLangford** [comment]
This is tardy (sorry).   For fully safety, I would suggest having multiple VW instances which have a shared model.  

W.r.t. the occasional 50ms latencies you are hitting, I suspect(?) an OS thread is stepping on a process thread creating the latency.
