### ISSUE TITLE
[Input] Repeating features in a feature space yield bag of words ?

### ISSUE THREAD

**Issue by knarf-hackatal2016** [JohnLangford/vowpal_wabbit#1162]
I'm using Vowpal Wabbit for the first time with text input and I have a doubt for the input format.

If an input line is

`1 | the cat play with the other cat`

would it be similar to

`1 | the:2 cat:2 play:1 with:1 other:1`

or

`1 | the cat play with other`

Differently put, what happens when you repeat a feature several times in the same feature space ? I guess it should be the first one but I haven't found it explicitly written in the input doc.

EDIT: corrected  `the`

**Comment by arielf** [comment]
It would be closer to the 1st (unclear why you split feature `the` and not `cat` into two separate instances, but `cat cat`, `cat:1 cat:1`, and `cat:2` are all equivalent).

tip: running with `--audit` (or `-a` for short) can help debug/understand cases like this.

**Comment by knarf-hackatal2016** [comment]
Thank you very much. `the` is my mistake, I was focusing too much on `cat` in my example.
Thank you for the tip. In the end it behaves as it should and as I expected. Maybe it could be explicitly written in the Input format section, otherwise the issue can be closed.

**Comment by arielf** [comment]
Thanks, I added the clarification to the [Input format wiki paget](https://github.com/JohnLangford/vowpal_wabbit/wiki/Input-format)
Look under **Notes / feature repetitions**
