### ISSUE TITLE
Did prediction file format change?

### ISSUE THREAD

**Issue by ApproximateIdentity** [JohnLangford/vowpal_wabbit#1170]
I'm referring to running vw with the following command:

```
vw \
    --quiet \
    --kill_cache \
    --lda 10 \
    --passes 10 \
    --bit_precision 17 \
    --lda_D 121913 \
    --lda_rho 0.1 \
    --lda_alpha 1.0 \
    --predictions prediction.dat \
    --readable_model topics.dat \
    --cache_file vw.cache \
    vw_filt.out
```

On the tags 8.1.1 and 8.2.1 I will get a `prediction.dat` file whose first few lines look something like this (the numbers at the end are filenames):

```
2.709291 3.748886 2.635445 2.966908 2.750491 2.527958 22.724691 2.379436 4.636326 2.920568  0
4.014686 18.711739 4.910296 3.394306 3.817025 5.269470 2.039592 14.775342 11.527375 14.540164  1
30.611147 59.884499 5.447314 10.420916 66.731827 6.932438 16.839697 17.592268 10.607274 14.932616  2
```

On the master branch as well as tag 8.3.1 this is the example output for the predictions file (note the missing filenames on the right):

```
2.85257 18.6931 7.96367 3.09938 3.41683 3.95295 2.23623 2.506 3.1368 2.14248
7.64389 1.81842 3.30513 4.90719 2.72247 4.37669 3.19765 3.43439 4.47375 47.1204
5.98134 31.5858 9.26367 44.4078 5.77528 13.172 55.3435 33.3292 6.92226 34.2192
```

On another note, is it the case that the different version tags don't correspond to any actual branches? I was trying look at the history of the different versions, but couldn't find the commits corresponding to the tags on any of the branches. How do these tags come into being?

(If I'm entirely wrong here and instead just ignorant of the necessary git commands feel free to yell, but I've been searching and am at a loss.)

**Comment by JohnLangford** [comment]
There was a change in the way that lda predictions were being printed related to unifying prediction types.  This looks like a bug where tags might be getting suppressed.  Can you create a simple complete example exhibiting it?

**Comment by ApproximateIdentity** [comment]
Sorry I should have provided more details. Use this input file:

`input`
```
 1 doc_1| token_1:1
 1 doc_2| token_2:1
```

Next use this command:

```
vw \
    --quiet \
    --kill_cache \
    --lda 2 \
    --passes 3 \
    --bit_precision 17 \
    --lda_D 2 \
    --lda_rho 0.1 \
    --lda_alpha 1.0 \
    --predictions prediction.dat \
    --readable_model topics.dat \
    --cache_file vw.cache \
    input
```

If you run this on tag `8.2.1`, you get the following output:

`prediction.dat`
```
1.421533 1.578467  doc_1
1.524285 1.475715  doc_2
1.234987 1.765013  doc_1
1.602497 1.397503  doc_2
1.085111 1.914889  doc_1
1.736417 1.263583  doc_2
```

After recompiling on the current master branch and running again, I get the following output:

`prediction.dat`
```
1.51467 1.48533
1.35468 1.64532
1.5571 1.4429
1.10205 1.89795
1.63649 1.36351
1.02021 1.97979
```

**Comment by arielf** [comment]
Thanks!
We can now reproduce.
Once fixed, we should also add little test in `test/RunTests` to ensure this `--lda` regression doesn't happen in the future.

**Comment by udibr** [comment]
any progress?
