### ISSUE TITLE
Error: daemonerrno = unknown vw (parser.cc:439): daemonerrno = unknown

### ISSUE THREAD

**Issue by ankitarya10** [JohnLangford/vowpal_wabbit#1173]
I am using vowpal wabbit in a docker container. Using the following docker image:

https://github.com/shabbychef/docker-vw/blob/master/Dockerfile

I get the error
Error: daemonerrno = unknown vw (parser.cc:439): daemonerrno = unknown

running the following command:
vw -i <model_name> -t --daemon --quiet --loss_function logistic --link logistic --port 26542 --probabilities

I am not sure what the error is about, any insight would be super helpful !

**Comment by arielf** [comment]
Not sure what it is either, but lines 437-439 in parser.cc are:
```
    // background process
    if (!all.active && daemon(1,1))
      THROWERRNO("daemon");
```

So it seems like the `daemon(1,1)` called failed in this particular docker env.

And why would `daemon()` fail?  `man daemon` says:
```
RETURN VALUE
       (This function forks, and if the fork(2)  succeeds,  the  parent  calls
       _exit(2),  so that further errors are seen by the child only.)  On suc-
       cess daemon() returns zero.  If an error occurs,  daemon()  returns  -1
       and  sets errno to any of the errors specified for the fork(2) and set-
       sid(2).

```
Something in that env is too restrictive? What happens if you simplify?  run `vw` not as a daemon (drop some of the options) does it work?  Try to run same under sudo, does it work? etc.

**Comment by ankitarya10** [comment]
without --daemon
```

vw -i  <model_name> -t --loss_function logistic --link logistic --port 26542 --probabilities

Generating 2-grams for all namespaces.
creating quadratic features for pairs: lc lu cu
only testing
Num weight bits = 28
learning rate = 0.5
initial_t = 0
power_t = 0.5
using no cache
Error: daemonerrno = unknown

finished run
number of examples = 0
weighted example sum = 0
weighted label sum = 0
average loss = -nan
average multiclass log loss = -nan
total feature number = 0
vw (parser.cc:439): daemonerrno = unknown
```

Same result as above with sudo.

Do you think it could be something to do with the port ?

**Comment by arielf** [comment]
Possibly.  Did you try to drop the `--port` ?

**Comment by ankitarya10** [comment]
yep same error.

**Comment by ankitarya10** [comment]
@arielf I was able to run through https://github.com/JohnLangford/vowpal_wabbit/wiki/Daemon-example. So i don't think port is an issue. 

At this point my guess is that it has something to do with the model file, but it runs fine on my local Mac, on a separate ubuntu system i tested.

**Comment by ankitarya10** [comment]
Closing the issue.  It turns out the system was running out of memory, probably causing the above mentioned issue. A bigger aws instance solved the problem. 

A better error would have been nice. Not sure if that could be done though, given daemon could fail for a number of reasons.

**Comment by arielf** [comment]
@ankitarya10 
Since you are in the best position to reproduce this.
Any patch / pull-request would be greatly appreciated.
Thank you!
