### ISSUE TITLE
How do I build and install libvw_c_wrapper?

### ISSUE THREAD

**Issue by jrmarkle** [JohnLangford/vowpal_wabbit#1175]
I'm trying to test some changes to the C wrapper but I can't seem to find any `make` targets that actually build `vwdll.cpp` or `libvw_c_wrapper` for Linux. Can anyone point me in the right direction?

**Comment by jrmarkle** [comment]
I found that the debian maintainer's fork github.com/yarikoptic/vowpal_wabbit has a branch `debian` which does build and install the C wrapper, but perhaps there is another way to get this working.

**Comment by arielf** [comment]
Is merging this fork by submitting a PR a good idea?

**Comment by jrmarkle** [comment]
I'm not sure. It's a bit out of date (version 8.1.1).

**Comment by jrmarkle** [comment]
I've found that if I run
```
./autogen.sh
make
sudo make install
```
then the library is built and installed but if I skip the `./autogen.sh` step and just run
```
make
sudo make install
```
then `make` succeeds but the libraries are not built or installed.

**Comment by arielf** [comment]
Sounds like this needs fixing in the original `Makefile`.  `autogen.sh` overrides the original.

To get all original `Makefile`s back:  `git checkout Makefile */Makefile`

**Comment by arielf** [comment]
But I would be careful to not pollute/infect the default `Makefile`s with all of GNU `libtool` complexities (linking with temporary `.lt` files etc.) which `autogen.sh` adds.
