### ISSUE TITLE
Python wrapper with Windows Binaries

### ISSUE THREAD

**Issue by klvbdmh** [JohnLangford/vowpal_wabbit#1176]
I've downloaded precompiled Windows binaries from the [releases page](https://github.com/eisber/vowpal_wabbit/releases). Is there any way I can use those binaries with the Python wrapper? I tried to follow the instructions, but I'm missing `pyvw35.dll'` file. It's not available in the Windows binaries from the .msi installer.

Alternatively, is it possible to make Python Wheels for Vowpal Wabbit?

**Comment by eisber** [comment]
@gramhagen can you release a new version for the pip repository?

**Comment by gramhagen** [comment]
Sure. I'll setup a new account on PyPI and try to automate the steps so we
can add it to the build box.

**Comment by gramhagen** [comment]
@eisber released 8.3.2
I also set up a new owner for pypi and testpypi, I can give you the credential info and steps to try and upload new versions. Let me know if that build works for what you need, there are a few changes to the docs and manifest that need to be made, so I'll submit a PR.

**Comment by gramhagen** [comment]
#1186 is the PR referenced above

**Comment by majube** [comment]
@gramhagen is version 8.3.2 supposed to work on Python 3.6? pip install vowpalwabbit fails for me with 
`Exception: Pre-built vw/python library for Windows is not supported` at line 108 of setup.py - though interestingly line 108 of setup.py in the master repository contains a different error message ("Pre-built vw/python library for Windows is not supported for this python version").

**Comment by eisber** [comment]
I only prebuilt for python 2.7 and python 3.5

Markus

**Comment by eisber** [comment]
I just added python 3.6 to the Windows build… though we’re still missing the pip release.

**Comment by bratao** [comment]
@eisber Do you have any w32 binary for Python 3.6 ?

**Comment by eisber** [comment]
I do, am just don’t find the time to publish them to pip…  It’s public  on my fork (https://github.com/eisber/vowpal_wabbit/tree/master/python/windows36)

Are you able to build yourself? https://github.com/JohnLangford/vowpal_wabbit/wiki/Windows-Build

-Markus

**Comment by funkindy** [comment]
Hello!
I also have a question on how to use precompiled binaries for python wrapper. Is it possible?

**Comment by gramhagen** [comment]
yes, it is possible to upload binaries with pip for targeted machines, i’d
like to do it, but need to learn more about it

**Comment by funkindy** [comment]
I mean ive downloaded binaries (.msi), extracted them. I now have an ability to use VW with command line interface. Is there any way i can use them to maintain python wrapper?

Thanks.

**Comment by Scott-Graham-Bose** [comment]
Oh i see. Well, the python package needs to connect to dll’s which are consistent with the commands it uses. It seems like if you have those dlls you could overwrite the ones used by the python package installation, but it might not be that straightforwad. I’m not as familiar with the windows side of the python packaging @eisber might be able to help.

**Comment by ODemidenko** [comment]
@eisber I am stuck with the same problem that was mentioned before:
> pip install vowpalwabbit fails for me with
> Exception: Pre-built vw/python library for Windows is not supported
I have python 3.6 and already install vw from .msi package. But I want to get the python wrapper.

What is the way to do this?
You have previously provided a link to your [fork](https://github.com/eisber/vowpal_wabbit/tree/master/python/windows36), but I can't get what could be done with it.
I either don't have an opportunity and understanding how to build it myself, as you suggested:
> Are you able to build yourself? https://github.com/JohnLangford/vowpal_wabbit/wiki/Windows-Build
It's just tricky to install both VisualStudio versions mentioned there. Besides, it is still unclear how these instructions will help to solve the problem.

I believe, many people are already either facing the problem or will face it soon, upgrading to python 3.6. Probably, this problem deserves a clear solution, available for everybody

**Comment by JohnLangford** [comment]
@eisber what's that status of python-on-windows?

**Comment by eisber** [comment]
For python 3.6 we're dependent on https://github.com/sergey-shandar/getboost/issues/33 & 
https://svn.boost.org/trac10/ticket/13023

**Comment by JohnLangford** [comment]
I think we're stuck, so closing this for now.

**Comment by sergey-shandar** [comment]
Switch to Boost 1.65 should solve the problem

**Comment by arekrob** [comment]
Is there any progress on this issue? I would also like to use vowpalwabbit with Python 3.6.
