### ISSUE TITLE
Making documentation not working

### ISSUE THREAD

**Issue by AbdealiJK** [JohnLangford/vowpal_wabbit#1177]
The readme says to do `make doc` in the root directory but that just gives:
```
$ make doc
make: Nothing to be done for `doc'.
```

Even if I cd into the doc directory and do a `make` it does the same and gives the same error:
```
$ cd doc/
$ make doc
cd ..; make doc ; cd doc
make[1]: Nothing to be done for `doc'.
```
How do we make the documentation for local usage ?

I did a `./configure` and am now trying to `make` and `make doc`
`make` is running but `make doc` is not

**Comment by arielf** [comment]
`make doc` at the top level dir works fine for me.

Perhaps it says 'nothing to be done ...' because it is already made?

Try:
```
    # -- Make sure we have the source tree original Makefiles
    git checkout Makefile */Makefile
    make doc
```
When I try this, it creates a ton of of files under `doc/html`
Note, you need to have `doxygen` installed.

**Comment by AbdealiJK** [comment]
It seems like if I do a reset to master and then do `make doc` - it works.
But if I run `./autogen.sh` and then run `make doc` it does not work because the Makefile has been overwritten by the `./autogen.sh`

Possibly this should be mentioned in the documentation ?

**Comment by arielf** [comment]
[Documentation extended/fixed in this PR](https://github.com/JohnLangford/vowpal_wabbit/pull/1180)
Awaiting merge.

**Comment by JohnLangford** [comment]
Thanks @arielf and @AbdealiJK .
