### ISSUE TITLE
Cubic features and self interactions

### ISSUE THREAD

**Issue by seriouscoder123** [JohnLangford/vowpal_wabbit#1182]
It looks like if `cubic` option is used, each namespace can appear multiple times in the interactions. For example:

`echo` '1 |t a b |q x y |d r:2' | vw --cubic tqd --invert_hash test.model`

Produces:

```
Version 8.3.2
Id
Min label:0
Max label:1
bits:18
lda:0
0 ngram:
0 skip:
options: --cubic tqd
Checksum: 3708859066
:0
Constant:116060:0.079418
d^r:59721:0.039709
q^x:157849:0.079418
q^y:137910:0.079418
t^a:63913:0.079418
t^a*q^x*d^r:103839:0.039709
t^a*q^x*q^y*d^r:139214:0.039709
t^a*q^x*t^b*q^x*d^r:37523:0.039709
t^a*q^x*t^b*q^x*q^y*d^r:98890:0.039709
t^b:155229:0.079418
```

As you can see, namespace `t` and `q` can appear multiple times. I was expecting to see the following combinations:
```
t^a*q^x*d^r
t^a*q^y*r^r
t^b*q^x*d^r
t^b*q^y*r^r
```

Additionally `quadratic` option doesn't include the same namespace multiple time:

`echo '1 |t a b |q x y |d r:2' | vw -q tq --invert_hash test.model`

produces:

```
Version 8.3.2
Id
Min label:0
Max label:1
bits:18
lda:0
0 ngram:
0 skip:
options: --quadratic tq
Checksum: 485986055
:0
Constant:116060:0.079418
d^r:59721:0.039709
q^x:157849:0.079418
q^y:137910:0.079418
t^a:63913:0.079418
t^a*q^x:224658:0.079418
t^a*q^y:204733:0.079418
t^b:155229:0.079418
t^b*q^x:58622:0.079418
t^b*q^y:38609:0.079418
```

Can anyone please clarify the behaviour of VW in this case?

Thanks.

**Comment by JohnLangford** [comment]
I believe there is a bug in the string creation process for audited cubic features (but not the cubic feature values themselves).  Consider this:

 4:17PM work-11: echo '1 |t s:.1 |q p:.2 o:.3 |d c:.4' | vw --cubic tqd --audit --quiet                                                                         0
	t^s:65894:0.1:0@0	q^p:83875:0.2:0@0	q^o:30074:0.3:0@0	d^c:124965:0.4:0@0	Constant:116060:1:0@0	t^s*q^p*d^c:196870:0.008:0@0	t^s*q^p*q^o*d^c:227101:0.012:0@0


Where the last feature has have 0.1*0.3*0.4 not 0.1*0.2*0.3*0.4.

@trufanov-nok is this a quicky for you?

**Comment by cvhoang** [comment]
I think you're right @JohnLangford. Cubic features work fine but they're not being audited correctly.  I think the problem is on this line:

https://github.com/JohnLangford/vowpal_wabbit/blob/master/vowpalwabbit/gd.cc#L181

`dat.ns_pre` doesn't seem to receive enough `pop_back()` calls to correctly audit subsequent cubic features.

**Comment by seriouscoder123** [comment]
I think you're right @JohnLangford. Cubic features work fine but they're not being audited correctly. I think the problem is on this line:

https://github.com/JohnLangford/vowpal_wabbit/blob/master/vowpalwabbit/gd.cc#L181

`dat.ns_pre` doesn't seem to receive enough `pop_back()` calls to correctly audit subsequent cubic features.
