### ISSUE TITLE
parse_regressor.cc can't be compiled with g++

### ISSUE THREAD

**Issue by trufanov-nok** [JohnLangford/vowpal_wabbit#1183]
It's been at least 6 month I haven't look into VW code and it changed a lot since when. I was working with my old fork, but today decided to compare it with master branch. And faced with the fact that I can't build master branch with g++ which is default. With libtool or without it.
I'm getting following errors:
```
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I/usr/include -I/include -Wall -Wno-unused-local-typedefs -pedantic -I ../rapidjson/include -O3 -fomit-frame-pointer -DNDEBUG -MT parse_regressor.lo -MD -MP -MF .deps/parse_regressor.Tpo -c parse_regressor.cc  -fPIC -DPIC -o .libs/parse_regressor.o
parse_regressor.cc: In function ‘void initialize_regressor(vw&, T&)’:
parse_regressor.cc:55:22: error: parse error in template argument list
     weights.template set_default<float,set_initial<T> >(all.initial_weight);
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
parse_regressor.cc:55:22: error: expected identifier
parse_regressor.cc:57:22: error: parse error in template argument list
     weights.template set_default<random_positive<T> >();
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
parse_regressor.cc:57:22: error: expected identifier
parse_regressor.cc:59:22: error: parse error in template argument list
     weights.template set_default<random_weights<T> >();
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
parse_regressor.cc:59:22: error: expected identifier
```
It seems the code is too complicated for g++. My knowledge of templates was far not enough to bypass this. So I switched to clang++ and successfully build the project and passed `make test`.

My compilers are:

```
gcc version 6.2.0 20161005 (Ubuntu 6.2.0-5ubuntu12)
clang version 3.8.1-12ubuntu1 (tags/RELEASE_381/final)
```
Kubuntu 16.10 , 4.8.0-37-generic GNU/Linux
Could someone reproduce this problem? It's most probably g++ version dependent .

**Comment by arielf** [comment]
Hi Alex,

I can build with gcc (and clang) without issues on Ubuntu 16.04.1 LTS 
The differences between us are:

- I use the default compiler: gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4)
- I build directly using the original `Makefile` (not using `autogen.sh`, nor libtool)

**Comment by JohnLangford** [comment]
I'm using the same g++ compiler as @arielf and seeing things working fine.  

The code above is related to the work @aartibagul did to interface the model datastructure and support sparse models.  In order to support sparse models, you need to explicitly set an initializer for otherwise-uninitialized parameters.  This requires a template because a function is involved in general.  Hence, you see the template member function.  The template keyword there is just saying to parse what follows as a template instantiation rather than otherwise barfing on syntax.  See here: http://en.cppreference.com/w/cpp/language/dependent_name searching for "The template disambiguator for dependent names".  

There's probably (?) something fiddly to make it work with the new compiler.  If you can figure it out, that's great.

**Comment by trufanov-nok** [comment]
Definitely some gcc problem. Have sent them a bug report with oversimplified code sample to reproduce: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=79508

**Comment by usptact** [comment]
I am using fresh Ubuntu 16.10 install with necessary tools installed and getting the same error. My GCC is:
`gcc (Ubuntu 6.2.0-5ubuntu12) 6.2.0 20161005`

**Comment by usptact** [comment]
@trufanov-nok How did you make the clang compiler hooked up by the "make"? Did you pass some specific arguments to autogen.sh?

**Comment by josephwinston** [comment]
I'm having the same issue on Ubuntu 16.10. Using make with CXX unset, that is using gcc version 6.2.0 20161005 (Ubuntu 6.2.0-5ubuntu12), I have the regression error.  Compiling the clang (clang version 3.8.1-12ubuntu1 (tags/RELEASE_381/final)) and CXXFLAGS=" -std=c++11" gives the link error:

```
/bin/bash ../libtool  --tag=CXX   --mode=link clang -I/usr/include -I/include  -Wall -Wno-unused-local-typedefs    -pedantic  -I ../rapidjson/include   -O3 -fomit-frame-pointer -DNDEBUG -std=c++11   -o vw vw-main.o libvw.la liballreduce.la -L/usr/lib/x86_64-linux-gnu -lboost_program_options -L/lib -lz -lpthread
libtool: link: clang -I/usr/include -I/include -Wall -Wno-unused-local-typedefs -pedantic -I ../rapidjson/include -O3 -fomit-frame-pointer -DNDEBUG -std=c++11 -o .libs/vw vw-main.o  ./.libs/libvw.so ./.libs/liballreduce.so -L/usr/lib/x86_64-linux-gnu -lboost_program_options -L/lib -lz -lpthread
/usr/bin/ld: vw-main.o: undefined reference to symbol '_ZNSo9_M_insertIdEERSoT_@@GLIBCXX_3.4.9'
//usr/lib/x86_64-linux-gnu/libstdc++.so.6: error adding symbols: DSO missing from command line
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Makefile:579: recipe for target 'vw' failed
make[2]: *** [vw] Error 1
```

Leaving the CXXFLAG unset produces the following:

```
libtool: compile:  clang -DHAVE_CONFIG_H -I. -I/usr/include -I/include -Wall -Wno-unused-local-typedefs -pedantic -I ../rapidjson/include -O3 -fomit-frame-pointer -DNDEBUG -MT allreduce_sockets.lo -MD -MP -MF .deps/allreduce_sockets.Tpo -c allreduce_sockets.cc  -fPIC -DPIC -o .libs/allreduce_sockets.o
In file included from allreduce_sockets.cc:28:
In file included from ./allreduce.h:40:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/6.2.0/../../../../include/c++/6.2.0/future:35:
/usr/bin/../lib/gcc/x86_64-linux-gnu/6.2.0/../../../../include/c++/6.2.0/bits/c++0x_warning.h:32:2: error: This file requires
      compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11
      compiler options.
#error This file requires compiler and library support \
 ^
In file included from allreduce_sockets.cc:28:
./allreduce.h:95:8: error: no type named 'mutex' in namespace 'std'
  std::mutex* m_mutex;
  ~~~~~^
./allreduce.h:96:8: error: no type named 'condition_variable' in namespace 'std'
  std::condition_variable* m_cv;
  ~~~~~^
./allreduce.h:225:53: error: use of undeclared identifier 'nullptr'
      { if (max_fd > 0 && select((int)max_fd, &fds, nullptr, nullptr, nullptr) == -1)
                                                    ^
./allreduce.h:225:62: error: use of undeclared identifier 'nullptr'
      { if (max_fd > 0 && select((int)max_fd, &fds, nullptr, nullptr, nullptr) == -1)
                                                             ^
./allreduce.h:225:71: error: use of undeclared identifier 'nullptr'
      { if (max_fd > 0 && select((int)max_fd, &fds, nullptr, nullptr, nullptr) == -1)
                                                                      ^
allreduce_sockets.cc:49:9: error: use of undeclared identifier 'nullptr'
    if (nullptr == inet_ntop(AF_INET, &(far_end.sin_addr), dotted_quad, INET_ADDRSTRLEN))
        ^
allreduce_sockets.cc:111:17: error: use of undeclared identifier 'nullptr'
  if (master == nullptr)
                ^
allreduce_sockets.cc:188:9: error: use of undeclared identifier 'nullptr'
    if (nullptr == inet_ntop(AF_INET, (char*)&parent_ip, dotted_quad, INET_ADDRSTRLEN))
        ^
9 errors generated.
Makefile:690: recipe for target 'allreduce_sockets.lo' failed
make[2]: *** [allreduce_sockets.lo] Error 1
make[2]: Leaving directory '/home/hb55683/work/DecisionService/GIT/vowpal_wabbit/vowpalwabbit'
Makefile:432: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/hb55683/work/DecisionService/GIT/vowpal_wabbit/vowpalwabbit'
Makefile:570: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
```

Should I open a new issue for Ubuntu 16.10?

**Comment by trufanov-nok** [comment]
@josephwinston yes, please.
I'll try to workaround the initial issue in this thread. It seems wrapping initialization template functions into template classes shall be enough.

**Comment by usptact** [comment]
@josephwinston What I did, is to first install clang++-3.9 and then modify the Makefile. In the first few lines, I removed all "if" logic by keeping only this:
`CXX = clang++-3.9`

The original code checked whether there is GCC installed and if it is, populated the CXX variable. Else it tried to look for clang.

**Comment by rdslater** [comment]
For Ubuntu 16.10 users who arrive here, previous versions will compile.
Specifically I checked out version 8.2.1 and compiled with no issues. (gcc compile)

```
sudo git clone git://github.com/JohnLangford/vowpal_wabbit.git
cd vowpal_wabbit/
sudo ./autogen.sh
git checkout tags/8.2.1 #have not tried 8.3.0
sudo make
sudo make install
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib #add to your .bashrc
```

**Comment by trufanov-nok** [comment]
I've made a patch to bypass this problem and it's in related PR. Still I should notice that the GCC team has fixed this bug shortly after report. Fix is on trunk (don't wanna check it) and planned to be in GCC 6.4. If workaround is unwanted there is a chance that 6.4 will be available for all affected platforms and at some point  of time we can just recommend users to just update GCC or switch to a Clang for a while.
