### ISSUE TITLE
Broken link on the page: https://github.com/JohnLangford/vowpal_wabbit/wiki/Command-line-arguments

### ISSUE THREAD

**Issue by 5kyn37** [JohnLangford/vowpal_wabbit#1184]
Hello.
Current "Agnostic Active Learning without Constraints" points to http://books.nips.cc/papers/files/nips23/NIPS2010_0363.pdf, but there is a redirect to http://papers.nips.cc/book/advances-in-neural-information-processing-systems-23-2010 . I found this publication in the [archive](https://web.archive.org/web/20120525164352/http://books.nips.cc/papers/files/nips23/NIPS2010_0363.pdf).

**Comment by MLWave** [comment]
Thanks for reporting!

I fixed the broken link to the full paper (including proofs) at http://www.cs.columbia.edu/~djhsu/papers/iwal-cal.pdf
