### ISSUE TITLE
broken link on page https://github.com/JohnLangford/vowpal_wabbit/wiki/Learning-to-Search-Sub-System

### ISSUE THREAD

**Issue by 5kyn37** [JohnLangford/vowpal_wabbit#1191]
Hello. The "Learning to Search" leads to a non-existent page. Thanks.

**Comment by MLWave** [comment]
Thanks again for reporting! 

I fixed the link to http://hunch.net/~l2s/

Please feel free to edit / fix any broken links you find the future.

**Comment by JohnLangford** [comment]
Thanks @MLWave @5kyn37
