### ISSUE TITLE
JSON support for python interface

### ISSUE THREAD

**Issue by travisbrady** [JohnLangford/vowpal_wabbit#1194]
Currently `--json` does not appear to work within pyvw, I'd like to submit a PR to add support if possible.  Any pointers on where to start?

Example pasted from https://github.com/JohnLangford/vowpal_wabbit/wiki/JSON

```python
In [6]: from vowpalwabbit import pyvw

In [7]: vw = pyvw.vw('--json')
Num weight bits = 18
learning rate = 0.5
initial_t = 0
power_t = 0.5
using no cache
Reading datafile =
num sources = 1

In [10]: ex = '''{
    ...:  "f1":25,"f2":true,
    ...:  "_aux":"some ignored info"
    ...: }'''.replace('\n', '')

In [12]: e = vw.example(ex)
Error: 4 is too many tokens for a simple label: {"f1":25,"f2":true,"_aux":"someignired

## VW format of same example works as intended
In [13]: vw.example('| f1:25 f2')
Out[13]: <vowpalwabbit.pyvw.example at 0x7fd326754998>
```

**Comment by eisber** [comment]
You’ll have to mimic https://github.com/JohnLangford/vowpal_wabbit/blob/master/cs/cli/vowpalwabbit.cpp#L276

Should be straight forward. You’ll still have to provide –json even if you call the other function.

Markus

**Comment by JohnLangford** [comment]
This seems pretty doable.  Please go ahead if interested.
