### ISSUE TITLE
HiddenBias being calculated without --inpass

### ISSUE THREAD

**Issue by apoorvreddy** [JohnLangford/vowpal_wabbit#1196]
In [nn.cc](https://github.com/JohnLangford/vowpal_wabbit/blob/6d0e1e144154317c0a26f180dcf4c8141b3210f5/vowpalwabbit/nn.cc) there is a variable `hiddenbias` which seems to be used when`--inpass` is given in [line 179](https://github.com/JohnLangford/vowpal_wabbit/blob/6d0e1e144154317c0a26f180dcf4c8141b3210f5/vowpalwabbit/nn.cc#L179).
But `hiddenbias` is being calculated even when `--inpass` is not given in [Line 164](https://github.com/JohnLangford/vowpal_wabbit/blob/6d0e1e144154317c0a26f180dcf4c8141b3210f5/vowpalwabbit/nn.cc#L164)
We should not be calculating this as it's not being used when `--inpass` is not given.

**Comment by JohnLangford** [comment]
@pmineiro can you take a look at this?

**Comment by pmineiro** [comment]
ec.passthrough on line 179 is not related to --inpass argument.  The conditional on line 244 using n.inpass is an example of something driven by the --inpass argument.

Having said that, I'm not familiar with the block at line 179, it looks like it was added by somebody else.

**Comment by JohnLangford** [comment]
The code on line 179 adds the hidden layer as features.
