### ISSUE TITLE
Online learning and prediction

### ISSUE THREAD

**Issue by usptact** [JohnLangford/vowpal_wabbit#1205]
In my setting, the data points with labels arrive at some rate for training. At the same time, the current model has to be queried to do predictions. The two - learning and predictions, come in moments that are randomly interleaved. In other words, at some moments model is learning, at others - it is doing predictions.

There are two types of the models that I develop:

- classic multi-class `--ooa N` classifier;
- learning to search `--search sequence` model;

It would be great if the model resided it memory and only get stored to disk occasionally (for backup/restore purposes mainly).

Is this possible with Vowpal Wabbit? I would like to avoid re-training the model over and over again, and loading the model for predictions.

**Comment by usptact** [comment]
I think I managed to get VW running in this mode although I am highly suspicious in quality of the learned model.

First, launch the VW in daemon mode (binary classifier in my case with default options):
`vw --daemon`
Add any other options such as number classes, bits for hashing etc. By default, VW will listen on port 26542.

Second, start feeding in your training examples using Linux `netcat `utility::
```
echo "1 |f bananas apples" | nc localhost 26542
echo "0 |f grenades missiles tanks" | nc localhost 26542
echo "1 |f strawberry kale" | nc localhost 26542
echo "0 |f shotgun rifle" | nc localhost 26542
...
```
Notice the value that is printed after each example, we will use it later.
It is super important that training examples from different classes come in shuffled form!

Third, after some number of training examples, you can start doing predictions:
echo "|f flamethrower sword" | nc localhost 26542 | tee output
Notice the lack of the label, this tells VW not to train. The file output will contain the predicted label, a continuous label.

**Comment by arielf** [comment]
Yes, and you can also save/checkpoint the model periodically to disk by sending the magic `save_<filename>` (pseudo) example.

Another thing you may want to know is that you can add weights to the examples.  Examples with a weight of 0 will not update the model but if they have a label, they can still be used for both prediction and error estimate.

And lastly, tagged examples will echo their tags so you can know which prediction belongs to which example e.g. when you sent many of them at a time, asynchronously etc.

More details in [the Input format wiki](https://github.com/JohnLangford/vowpal_wabbit/wiki/Input-format)

**Comment by usptact** [comment]
@arielf Thanks for the great tips! Particularly on saving the model at arbitrary instants. Is there a way to load the previously saved model (effectively overwriting what is currently in memory?). Might be useful if last training examples screwed up the model and a complete re-train is too costly -- just load previous checkpoint model.

**Comment by arielf** [comment]
@usptact - sorry I don't think there's such an option currently.
This is a great idea, though, so it would be a nice enhancement to have (someone would need to send a PR to make it happen).

**Comment by pferrel** [comment]
What is the use of saving if a restore cannot be done? Can it be done when creating an instance of VW, like at startup?

So the workflow would be

 - create VW from existing checkpoint file or with a new empty filename.
 - get inputs and train several times, 
 - checkpoint by saving, 
 - continue until shutdown or crash. 

Then restart would create a new instance or VW with the last checkpoint as the starting model. 

Also if we are creating several models with several filenames, should we have a cache file for each? I assume getting a new VW instance would erase this cache but it should be separate if the model are during runtime. 

Do I have this right? I've tried creating a new instance of VW with a saved model file and it seems to always be blank always. Can you help a little with the CLI? I know how to create a new instance and configure it giving it a model file name, works fine, what I'm missing is how to get an instance of VW with a pre-existing checkpointed model file.

**Comment by arielf** [comment]
Sorry I don't know about the java interface but saving models and resuming has been working for me well since many years ago.   Perhaps the following little shell script example can provide some hints?

```
$ cat ./save-resume
#!/bin/bash

TrainSet=/tmp/example.vw
Model=/tmp/example.model

for i in $(seq 1 3); do
    echo "Starting iteration #$i ..."

    if [[ -e "$TrainSet" ]]; then
        : cool we already have a training set
    else
        echo "1st time, creating training set..."
        echo "1 | a b c" > $TrainSet
    fi

    VWOPTS="-d $TrainSet -P 1 -f $Model --save_resume"

    if [[ -e "$Model" ]]; then
        echo "Model already exists - using it to initialize/resume state"
        VWOPTS="$VWOPTS -i $Model"
    fi

    vw $VWOPTS
    case $? in
        (0) : cool vw succeeded ;;
        (*) echo "vw error found; aborting"; exit 1 ;;
    esac

done
```

Works fine in my env.  Resuming from previous model and continuing where it left off in each iteration.

The model replacement is atomic (using a rename at the end) so crashes or premature exits of `vw` on bad data were never an issue for me either.

You can even use the same model name in -i (model filename to load initially) and -f (model filename to write to at the end), it just works.

**Comment by pferrel** [comment]
`-f $Model --save_resume` seems to be the trick

For the checkpoint It sounds like instead of an example @usptact means you send `"save_" + $Model` to vw periodically.

**Comment by arielf** [comment]
FWIW: even without `--save-resume` the above script/example works but somewhat less smoothly because the learning rate jumps back up a bit with every restart.

In the past @JohnLangford was considering making `--save-resume` the default in every save, but that is costly.

The models saved with full `--save-resume` info (e.g. per feature learning rates) are much bigger on disk, so this extra-cost trade-off makes it desirable to have 1) both options supported 2) have the more efficient method be the default.
