### ISSUE TITLE
Boosting model loading inconsistency

### ISSUE THREAD

**Issue by trufanov-nok** [JohnLangford/vowpal_wabbit#1210]
Hi,
Let's save the model:
`vowpalwabbit/vw -d test/train-sets/0001.dat -f /tmp/m --boosting 2 --alg logistic`
And load it back:
`vowpalwabbit/vw -d test/train-sets/0001.dat -i /tmp/m --boosting 2 --alg logistic`

I'm getting a warning:
`ignoring duplicate option: '--boosting 2'`

Ok, then I deleted --boosting and -alg params and got:
`vowpalwabbit/vw -d test/train-sets/0001.dat -i /tmp/m`
result:
`vw (gd.cc:686): Model content is corrupted, weight vector index 1031742008 must be less than total vector length 262144`

That's because --alg value is either not stored in model or overwritten by default value "BBM".
To bypass this just leave --alg in command line:
`vowpalwabbit/vw -d test/train-sets/0001.dat -i /tmp/m --alg logistic`

The inconsistency here is that --alg is never used without --boosting, that's why I've tried to remove both of them. As I can't overwrite model's --boosting N value at load time (you'll get `Error: Disagreeing option values for '--boosting': 'N' vs '2'`) I don't see any sense in letting user to overwrite --alg value. Especially with default value. And keeping in mind logistic->BBM crashes app and logistic->adaptive at least gives me wrong numbers of passes: `passes used = 13691116083237382913` I conclude models are binary incompatible for different --alg values

My suggestion is to make sure --alg value is stored in model, restored correctly and can't be overwritten as it's done for --boosting now.

**Comment by arielf** [comment]
Thanks Alex.  In addition (and ideally) we should also stop considering it an error if an option specified on the command line is identical in value to the one read from a model (instead of getting the "option can be specified only once" exception/error)

I once looked at the code and found that due to the way things are implemented in `boost/program_options` this is not a trivial change, but if you can figure out how to do this correctly it would make vw much more friendly to novices.

**Comment by JohnLangford** [comment]
@arielf it's not considered an error the repeat specification has been downgraded from error to warning.  @eisber fixed this.

@trufanov-nok thanks---this issue is fixed in the master.

**Comment by arielf** [comment]
John, great to hear about repeat options changing from error to warning. Thanks.

**Comment by arielf** [comment]
And thanks to @eisber of course!

**Comment by trufanov-nok** [comment]
Thanks!
