### ISSUE TITLE
unable to keep spanning_tree running

### ISSUE THREAD

**Issue by dbhenry** [JohnLangford/vowpal_wabbit#1216]
Hi, we started having issue with spanning_tree crashing (?) but unable to find useful msg in /tmp/spanning_tree.log; last few lines look like this,

nonce 1478897002704296219 still waiting for 204 nodes out of 333 for example node 0
inbound connection from 10.80.1.40(node1:44903) serv=54733
10.80.1.40(node1:44903): nonce=1478897002704296219
10.80.1.40(node1:44903): total=333
10.80.1.40(node1:44903): node id=216
nonce 1478897002704296219 still waiting for 203 nodes out of 333 for example node 0
inbound connection from 127.0.0.1(localhost:44903) serv=33186
127.0.0.1(localhost:44903): nonce read failed, exiting
inbound connection from 127.0.0.1(localhost:44903) serv=34223
127.0.0.1(localhost:44903): nonce read failed, exiting
inbound connection from 127.0.0.1(localhost:44903) serv=35118
127.0.0.1(localhost:44903): nonce read failed, exiting

we did verify no other process is conflicting with TCP 26543 usage. any pointers or debug option we can use?

**Comment by arielf** [comment]
If this is on Linux,  dying of a process from a signal should be logged by the kernel.
Do you see anything in /var/log/syslog ?

**Comment by dbhenry** [comment]
nothing particular about this process in OS log

ran couple strace while process restarted and seems to stop after reading /etc/services, not sure what to make of this

20308 read(20, "Multiplexing\ntvpm\t\t21800/udp\t\t\t#"..., 4096) = 4096
20308 read(20, "ager\nsiemensgsm\t28240/tcp\t\t\t# Si"..., 4096) = 4096
20308 read(20, "p\t\t\t# IP-PROVISION\nciscocsdb\t434"..., 4096) = 1690
20308 read(20, "", 4096)                = 0
20308 close(20)                         = 0
20308 munmap(0x7fe558713000, 4096)      = 0
20308 write(2, "inbound connection from ", 24) = 24
20308 write(2, "127.0.0.1", 9)          = 9
20308 write(2, "(", 1)                  = 1
20308 write(2, "localhost", 9)          = 9
20308 write(2, ":", 1)                  = 1
20308 write(2, "44903", 5)              = 5
20308 write(2, ") serv=", 7)            = 7
20308 write(2, "49085", 5)              = 5
20308 write(2, "\n", 1)                 = 1
20308 recvfrom(19, "", 8, 0, NULL, NULL) = 0
20308 write(2, "127.0.0.1", 9)          = 9
20308 write(2, "(", 1)                  = 1
20308 write(2, "localhost", 9)          = 9
20308 write(2, ":", 1)                  = 1
20308 write(2, "44903", 5)              = 5
20308 write(2, "): nonce read failed, exiting", 29) = 29
20308 write(2, "\n", 1)                 = 1
20308 exit_group(1)                     = ?
20308 +++ exited with 1 +++

**Comment by arielf** [comment]
Thanks so much for the `strace`.

So this is not a crash.
It is spanning tree code deciding to exit after failing to read data from socket.

Looking at `man recvfrom` it might be an issue in the code, possibly not accounting for an edge case:

If there's no data to return (`errno` is set to `EAGAIN` or `EWOULDBLOCK`) perhaps the code shouldn't exit?

The source code is  `vowpalwabbit/spanning_tree.cc` function `SpanningTree::Run` starting line 160:
```
    size_t nonce = 0;
    if (recv(f, (char*)&nonce, sizeof(nonce), 0) != sizeof(nonce))
    { cerr << dotted_quad << "(" << hostname << ':' << ntohs(port)
           << "): nonce read failed, exiting" << endl;
      exit(1);
    }
```
where `recv` in the code becomes `recvfrom` system call:
```
      recvfrom(19, "", 8, 0, NULL, NULL) = 0   # It is returning zero just before the exit
```

And the fully reconstructed error message (from the less readable `strace` output) is:
```
    127.0.0.1(localhost:44903): nonce read failed, exiting
```

@JohnLangford  could this be an issue in the code?

**Comment by dbhenry** [comment]
indeed we were able to reproduce this by simply issuing

[root@node1~]# nc -vz -p 44903 localhost 26543

which is a simple port connect with no data and we see this message and the process exits. in our case, a new monitoring agent was introduced to check for all listening ports on the host. we were able to identify this using a combination of tcpdump and iptables to block the traffic

subsequent tests showed even with traffic initiated locally using source port not equal to 44903, somehow the ntohs(port) function still resulted in printing localhost:44903, no sure why

**Comment by JohnLangford** [comment]
If there is an extra bit of robustness that can be added to the spanning_tree that would be welcome.

**Comment by arielf** [comment]
Perhaps the fix is if the network read (recvfrom) returns a size of zero (no data) just ignore it rather than failing/exiting.  It would make the code more robust against this trivial DoS (by monitors, port scanners, or otherwise).

@dbhenry since you're in the best position of testing this and approving, would you mind sending a PR? Would be great if you could. Thanks!

**Comment by JohnLangford** [comment]
A pull request would be welcome.

-John
