### ISSUE TITLE
Use of ngrams in selected Namespace 

### ISSUE THREAD

**Issue by grigoriysol** [JohnLangford/vowpal_wabbit#1222]
Hi
I have a sample.
text_Namespace1: text of an object
feaures_Namespace2:  float/int/category/bin features object

I want to make a new feature from the Namespace1 text using the n-gram
Can the VW selectively generate ngrams for certain Namespace1?

Or do I use attributes: -q tt or interactions ttt

**Comment by Wirack** [comment]
Out of curiosity I examined the [code](https://github.com/JohnLangford/vowpal_wabbit/blob/master/vowpalwabbit/global_data.cc#L129-L148)

I found that you can create ngrams for specific namespaces.
If you want ngrams for two different namespaces  'a' and 'c' with 2-grams and 3-grams respectively you can use the following:
`--ngram a2 --ngram c3`

**Comment by arielf** [comment]
Thanks @Wirack 
I think I have never seen it documented before and that's very helpful to know.

**Comment by grigoriysol** [comment]
Thanks for the help. 
I also helped on the [http://stackoverflow.com/questions/vowpal-wabbit-ngrams-in-selected-namespace](http://stackoverflow.com/questions/43304738/vowpal-wabbit-ngrams-in-selected-namespace/43362317#43362317)
A similar functional --skips.

Works! Even here such a design:
vw -d test.data --skips b2 --ngram b2 --ngram g2 --skips g1
