### ISSUE TITLE
Add interaction terms & save model through pyvw.vw()

### ISSUE THREAD

**Issue by wenduowang** [JohnLangford/vowpal_wabbit#1224]
Hi, I have been looking for an effecient way to add interaction terms through the pyvw.vw() interface (not the sklearn interface).
I would like to specify the interaction terms and interaction depth. Currently I rely on recursive construction in Python, and then pass the interactions to the model as separate features. This of course fails to take advantage of the underlying feature hashing in vw, so I want to see if it's possible to do this in another way. Maybe similar to the command line approach?
Also, how to save the trained model in pyvw? The model cannot be serialized in Python, so pickle doesn't work.

Thanks!
Wenduo

**Comment by JohnLangford** [comment]
For adding interaction terms, the easiest thing is probably creating a new
model at present.   There is no technical reason why you could not modify
an existing model, but the interface does not presently exist.

For saving a model, you should send an example with only a tag of
save_<filename>.

-John
