### ISSUE TITLE
Problem installing VW on CentOS 7

### ISSUE THREAD

**Issue by annirvine** [JohnLangford/vowpal_wabbit#1225]
The configure script seems to run without issue, but running make gives:

`libtool: link: g++  -fPIC -DPIC -shared -nostdlib /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64/crti.o /usr/lib/gcc/x86_64-redhat-linux/4.8.5/crtbeginS.o  .libs/allreduce_sockets.o .libs/allreduce_threads.o .libs/vw_exception.o   -L/usr/lib64 -lboost_program_options-mt -L/lib -lz -lpthread -L/usr/lib/gcc/x86_64-redhat-linux/4.8.5 -L/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64 -L/lib/../lib64 -L/usr/lib/../lib64 -L/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../.. -lstdc++ -lm -lc -lgcc_s /usr/lib/gcc/x86_64-redhat-linux/4.8.5/crtendS.o /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64/crtn.o  -O3   -Wl,-soname -Wl,liballreduce.so.0 -o .libs/liballreduce.so.0.0.0
/bin/ld: cannot find -lz
collect2: error: ld returned 1 exit status
make[2]: *** [liballreduce.la] Error 1
make[2]: Leaving directory `/home/airvine/vowpal_wabbit-8.2.0/vowpalwabbit'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/home/airvine/vowpal_wabbit-8.2.0/vowpalwabbit'
make: *** [all-recursive] Error 1`

Any suggestions?

**Comment by annirvine** [comment]
The trick was installing zlib-devel!

**Comment by arielf** [comment]
https://github.com/JohnLangford/vowpal_wabbit/wiki/Tutorial

**Comment by annirvine** [comment]
Those pages are plenty visible, I'd read them all. The library names are slightly different for Red Hat. Once I realized the connection to the Ubuntu pointers it was easy to debug, but an analogous Red Hat section would be handy.

**Comment by arielf** [comment]
Small suggested improvement:
https://github.com/JohnLangford/vowpal_wabbit/pull/1226

**Comment by matanster** [comment]
Just for the record, on CentOS 6.9 and possibly all CentOs 6, you currently also have to upgrade g++ to a version supporting c++ 11, as the default g++ there does not support c++ 11. I could perform the upgrade by following here: https://hiltmon.com/blog/2015/08/09/c-plus-plus-11-on-centos-6-dot-6/.
