### ISSUE TITLE
Unable to extract latent factors of low-rank approx: `gd_mf_weights` doesn't compile

### ISSUE THREAD

**Issue by KristianHolsheimer** [JohnLangford/vowpal_wabbit#1229]
Hi there,

I'm trying to train word embeddings using vw's low-rank approximation feature. I noticed the nice [wiki page](https://github.com/JohnLangford/vowpal_wabbit/wiki/Matrix-factorization-example) that describes how to extract the latent factors.. exactly what I need.. Awesome!

I tried to compile the `gd_mf_weights` tool,
```
$ cd library
$ make gd_mf_weights
```
but I got the [this stack trace](https://pastebin.com/cZtmjvX5).

*Note* I also noticed that there was another issue with `gd_mf_weights` some time ago [#933]. I opened a new issue, because the only overlap I could see is that the `gd_mf_weights` doesn't seem to be maintained at the moment. 

Thanks!

**Comment by JohnLangford** [comment]
Lack of maintenance is definitely the issue here.  I'm 'ccing Jake who may
have time to look into.   I'm superoverloaded for the next several weeks.

-John

**Comment by KristianHolsheimer** [comment]
Okay, no worries, it would've been really nice. For the time being, I'll just use my own little hack parsing the `--audit` output.

Thanks John!

**Comment by JohnLangford** [comment]
Huh, it actually does compile, at least on my machine and travis.  Just type 'make all' in the root directory.

**Comment by KristianHolsheimer** [comment]
Okay, I'll give it another try. Thanks for looking into it
