### ISSUE TITLE
managing models

### ISSUE THREAD

**Issue by pferrel** [JohnLangford/vowpal_wabbit#1231]
I seem to be unable to post to the yahoo group so pardon the question here.

I need to use a contextual bandit with csoaa and do it using online learning. I also need potentially many models. I don't see how to deal with many independent models in the docs.

 - how do I create, send input to, and query multiple in-memory models? Do I have to launch multiple instances of vw on different ports?
 - for online learning what should be my model persistence strategy, save after every input? Also how do I save multiple models?
 - given online learning is there any reason to store input events, is there any possibility of getting online updates out of sync with input?
 - I will be adding and removing models while VW is running, is this possible? 

Any guidance with how to use the daemon commands to do the above would be helpful

**Comment by arielf** [comment]
Answers in order:

- Running multiple instances of `vw` each on a separate port is one option. Another is to generate multiple submodels within one physical model by separating examples using different name-spaces (each sub-model is assigned a different name-space). Be aware that the latter option may involve some cross-talk between channels (e.g. hash collisions, global intercept, etc.)
- You can save the present (in memory) model by sending the string `save_<filename>` to `vw` (a bogus "example").  Saving after each example may be very slow. Multiple models: use different filenames (or see alternative trick above.)
- No reason to store inputs, you can _tag_ every example with some unique ID (optional).  Details on tags: see the wiki page on `vw` input format in this github repo.  Response/prediction order is guaranteed to be the same as example input order (per `vw` main process). I've never seen an issue with out of order responses, but tags should make this moot.
- No problem, Unix/Linux makes sure renames/unlinks are atomic. `vw` doesn't touch the underlying files except at loading/saving time. A new runtime `save` creates `<filename>.writing` which is atomically renames to `<filename>` upon save completion. If `<filename>` already exists, it is replaced atomically per unix `rename(2)` semantics.

**Comment by pferrel** [comment]
Thanks for the quick responce. We have this working in the single model case and since I'm new to VW I sometimes miss the meaning of the nomenclature:

 1. What would the overhead of running vw one instance per model, in rough terms? For the namespace submodel solution I assume hash collisions are no different than adding more things to any hashmap, the more you add the more collisions occur? But these are automatically resolved at runtime--at least in Java. Not sure what a "global intercept" is.
 2. How can submodels be saved independently? I guess the namespace must be a parameter to the save? I don't understand how to do that with the commands.
 3. I asked because if I can't save with each input, the in-memory model will be out of sync with the persisted "watermark" model. In other words I will train and store on micro-batches of examples. Therefor between saves, if there is a stoppage or crash, I need to reproduce the examples that came in since the last watermark model was saved. Not a query/response question, it's about a guarantee of accurate watermark persistence. BTW can I persist to a db by "getting" the model and doing my own blob persistence?
 4. I was asking a different question, which is answered above about adding in-memory models and the answer as I understood it is--no problem, it's another vw instance or a submodel with a new namespace. 

Thanks again this is very helpful. Since my submodels are very small and may be quite numerous I hope the namespace will fit as a solution.

**Comment by arielf** [comment]
I just added a new page to the documentation:

[VW Name Spaces](https://github.com/JohnLangford/vowpal_wabbit/wiki/Name-Spaces)

Saving is only for a full model (can't separate name-spaces on saving). But you can query/predict each name space separately by adding it to the input example.

Incremental saving (delta between models) isn't supported. You may save into N separate files (log rotation style).

**Comment by pferrel** [comment]
That page is very helpful, many thanks.

I guess I could deal with saving the whole 1000 namespaces model if it could be in parallel with online learning, non-blocking. I'm trying to make VW resilient to restarts while keeping examples buffered and synced with saving watermark models.

Are saves non-blocking?

**Comment by arielf** [comment]
Saves are blocking, but unless you have huge models they are pretty fast (`vw` stores sparse models, i.e. only features with non-zero weight are saved w/ order descending by weight). 

Unless you're saving over a network (NFS or similar) which might definitely be an issue when network connectivity to SAN is lost.

**Comment by pferrel** [comment]
ok, thanks. 

But this brings up another question. My train and queries are done through akka Actors and so there may be multiple connection attempts in parallel. Are input and queries blocking also?

If all these block, it might be required to use multiple instances of vw for multiple models.

**Comment by JohnLangford** [comment]
Different processes are nonblocking in daemon mode.

-John

**Comment by JohnLangford** [comment]
I'm closing this for now in the hope(?) that it's addressed.

W.r.t. the mailing list, it's probably blocking you because you aren't signed up?  Then someone has to bless your email as not-spam.
