### ISSUE TITLE
Extracting scores in ECT

### ISSUE THREAD

**Issue by Wirack** [JohnLangford/vowpal_wabbit#1248]
I would like to extract scores for e.g. the top 10 classes in ECT, similar to the `--scores` flag usable with oaa.

I will need this functionality in order to rank the predictions for my data points to e.g. give predictions for the top 20% data points that i feel (approximately) most certain about.

Is it possible to implement such functionality in ECT?
If so, can you give me some pointers and I would gladly try to implement it.

-Søren

**Comment by JohnLangford** [comment]
This is algorithmically nontrivial since ECT does not operate in the
"compute many scores and choose the max" approach.   Instead, it functions
by traversing a DAG.  You might find --recall_tree somewhat more amenable
as the data structure is simpler.

-John

**Comment by Wirack** [comment]
Thank you, I will examine recall_tree further :)
