### ISSUE TITLE
Get wrong class

### ISSUE THREAD

**Issue by pferrel** [JohnLangford/vowpal_wabbit#1250]
I'm starting from some inherited code that used the VW class from com.github.johnlangford:vw-jni:8.1.0, which had methods `.learn`, `.close`, and `.predict` and for just a flash when I told Intellij to look at the declaration I saw that but now it shows the API in the java directory of the project and has no such methods. In fact I can't find anywhere in this GitHub repo that has this interface.

I clearly have some build setting wrong.

code:

```
import vw.VW

...

  private def createVW() : VW = {
    val reg = "--l2 " + ap.regParam
    val iters = "-c -k --passes " + ap.maxIter
    val lrate = "-l " + ap.stepSize

    val vw = new VW("--csoaa 10 " + "-b " + ap.bitPrecision + " " + "-f " + ap.modelName + " " + reg + " " + lrate + " " + iters)
    return vw
  }
...

vw.close
```

I'm using SBT to get the maven artifact mentioned above with:

```
"com.github.johnlangford" % vw-jni % "8.0.0"
```

At one point I could run and debug the code but now it won't compile. It may be an IntelliJ problem but I'd still love to know where this code is and how the vw-jni artifact is being built, the one with .lean etc.

**Comment by JohnLangford** [comment]
If you look at the .travis.yml in the master branch, the build script describes how things are made and tested.  In particular:
make all
mvn test -f java/pom.xml

Does that help?

**Comment by JohnLangford** [comment]
In addition, a significant cleanup of the java library interface has gone into the master from @jon-morra-zefr now.
