### ISSUE TITLE
Inverted Hashing failing

### ISSUE THREAD

**Issue by amit024003** [JohnLangford/vowpal_wabbit#1251]
Hi,

I want actual feature name so, I trained the model first and then run the test on same data set with model file generated in previous step. But after sometime job just get killed.

vw version: 7

Training Command:
vw -d data_shopping_train.txt --passes 50 -k --cache_file tmp/train2.txt.cache --loss_function logistic -f model.ngram_kb_v7 -b 24 --readable_model model.ngram_kb_v7.readable --ignore w --ignore c --ignore t

Test Command:
vw -d data_shopping_train.txt --loss_function logistic -t -i model.ngram_kb_v7 -b 24 --ignore w --ignore c --ignore t --invert_hash model.ngram_kb_v7.inverted --compressed -p eval.ngram_kb_v7 --link=logistic

Failure Message:
ignoring namespaces beginning with: w c t 
only testing
Num weight bits = 24
learning rate = 10
initial_t = 1
power_t = 0.5
using no cache
Reading datafile = data_shopping_train.txt
num sources = 1
average    since         example     example  current  current  current
loss       last          counter      weight    label  predict features
0.122361   0.122361            1         1.0  -1.0000  -2.0390        2
0.061924   0.001486            2         2.0  -1.0000  -6.5109        7
0.032168   0.002412            4         4.0  -1.0000  -6.4616        7
0.049435   0.066702            8         8.0  -1.0000  -1.9699        2
0.072880   0.096326           16        16.0  -1.0000  -1.3002       42
0.093551   0.114222           32        32.0  -1.0000  -1.6506       63
0.094063   0.094574           64        64.0   1.0000   4.0056       77
0.105551   0.117039          128       128.0   1.0000   4.2565       68
0.122166   0.138780          256       256.0   1.0000   2.2295       16
0.129184   0.136203          512       512.0  -1.0000  -6.5024       71
0.114704   0.100223         1024      1024.0   1.0000   3.5227       81
0.114698   0.114691         2048      2048.0   1.0000   4.7232       26
0.117855   0.121012         4096      4096.0  -1.0000  -2.6661        4
0.116570   0.115286         8192      8192.0   1.0000   1.7321       73
0.113874   0.111177        16384     16384.0   1.0000   1.2032        7
0.113817   0.113761        32768     32768.0  -1.0000  -1.9779        2
0.112881   0.111945        65536     65536.0   1.0000   5.2109       47
0.113766   0.114652       131072    131072.0  -1.0000  -5.9832       44
0.113870   0.113974       262144    262144.0   1.0000   3.2807       79
0.113569   0.113269       524288    524288.0  -1.0000  -5.1692       79
0.113436   0.113302      1048576   1048576.0  -1.0000  -3.8728       45
0.113902   0.114369      2097152   2097152.0  -1.0000  -3.8074       62
0.114289   0.114675      4194304   4194304.0  -1.0000  -2.4594       78
0.114981   0.115674      8388608   8388608.0  -1.0000  -1.1416       56
**Killed**

**Comment by arielf** [comment]
Please check your system logs (`/var/log/syslog`, ` /var/log/messages` etc. depeding on system, YMMV)
Looks like your process is being (SIG)KILL-ed by something outside it.
My best guess is that the sender of the `KILL` signal is the kernel (lookup: OOM Killer).
[https://www.google.com/search?q=oom+killer](https://www.google.com/search?q=oom+killer)

**Comment by JohnLangford** [comment]
Inverting the hash function does tend to be very memory intensive.

-John

**Comment by amit024003** [comment]
I see. I figure out a way to get the invert hash. Thanks.
