### ISSUE TITLE
OjaNewton

### ISSUE THREAD

**Issue by haozhaopop** [JohnLangford/vowpal_wabbit#1252]
Hi, I am a beginner of vowpal wabbit, and I want to implement OjaNewton to train neural network, considering the instruction on this page https://github.com/JohnLangford/vowpal_wabbit/wiki/Efficient-Second-Order-Online-Learning,
I am confused about splice.vw, is it a training data file?

**Comment by arielf** [comment]
Yes.
I made the page clearer by renaming the file in the example and moving it to the end.

**Comment by lizhangzhan** [comment]
Hi, according to the description in the OjaNewton wiki, I have successfully trained a model with criteo ad dataset. But, I do not find how to test the model. Can you please give some tip on it ?

**Comment by arielf** [comment]
Hi, I just updated the instruction page (added how to save model and how to predict)

**Comment by lizhangzhan** [comment]
Hi, all, in vw 8.6.1 version, I have still encountered a similar issue [#795](https://github.com/JohnLangford/vowpal_wabbit/issues/795)  when run the below command:

vw --OjaNewton --sketch_size=10 --alpha_inverse=0.8 -nn 32 criteo.kaggle2014.train.vw

to train a neural network with OjaNewton algorithm, a single layer with 32 neurons. Can you please give some suggestion that can work around it ?
