### ISSUE TITLE
character-level ngram

### ISSUE THREAD

**Issue by funkindy** [JohnLangford/vowpal_wabbit#1253]
Hello!
Is there an opportunity to use character-level (instead of word-level) ngrams?

eg. for the text 'the text' i want these features: 'the', 'he ', 'e t', ' te', 'tex', 'ext' (character-level 3-grams)
The Python's sklearn analog is CountVectorizer(ngram_range=(3,3), analyzer='char')

They works way better than word-level for short text classification.

Thank you.

**Comment by JohnLangford** [comment]
It's not in VW at present.

**Comment by JohnLangford** [comment]
(Patches are welcome of course.)

**Comment by funkindy** [comment]
I see, thank you very much for quick response!

**Comment by JohnLangford** [comment]
(Note that character level ngrams can be created from word level ngrams by
simply putting a s p a c e between characters.)
