### ISSUE TITLE
Error when import pyvw in Python 3.6

### ISSUE THREAD

**Issue by osm3** [JohnLangford/vowpal_wabbit#1254]
Hi!
command:
from vowpalwabbit import pyvw
returns:
ImportError: dynamic module does not define module export function (PyInit_pylibvw)
PS. python 3.6

**Comment by osm3** [comment]
Problem was solved. I reinstall anaconda with python version 3.5.

**Comment by hsm207** [comment]
Are there any plans to support vw on Python 3.6+ on Ubuntu? Python 2.7 is approaching [end-of-life ](https://pythonclock.org/) soon.

**Comment by jackgerrits** [comment]
Yes, it is currently supported. Are you seeing issues?

**Comment by hsm207** [comment]
@jackgerrits 

I am running `Ubuntu 18.04.3 LTS` and am having the following issue:

I execute the following shell commands (the installation commands is based on the [README ](https://github.com/VowpalWabbit/vowpal_wabbit/tree/master/python) in the python folder for Anaconda):

```
git clone https://github.com/VowpalWabbit/vowpal_wabbit.git
conda create -y -n vowpalwabbit python=3.7
source activate vowpalwabbit
conda install -y -c anaconda boost
pip install -e vowpal_wabbit
python -c "from vowpalwabbit import pyvw"
```

The last command gives the following traceback:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/vowpal_wabbit/python/vowpalwabbit/pyvw.py", line 5, in <module>
    import pylibvw
ImportError: dynamic module does not define module export function (PyInit_pylibvw)
```

Am I missing some commands for installation in an Anaconda environment? My conda version is 4.5.12

**Comment by jackgerrits** [comment]
@peterychang is this the known conda issue?

**Comment by peterychang** [comment]
I dont think thats a conda issue; I recall seeing it when I first started working on the python build stuff.

One thing I noticed was that the clone command is actually wrong though, we need to do a recursive clone to get all the submodules. I wonder if thats the problem?

@hsm207 Can you try this?
```
cd vowpal_wabbit
git submodule update --init
pip install -e .
```

**Comment by hsm207** [comment]
@peterychang 

I did the following:

```
git clone https://github.com/VowpalWabbit/vowpal_wabbit.git
conda create -y -n vowpalwabbit python=3.7 # same problem with python 3.6 and 3.5
source activate vowpalwabbit
conda install -y -c anaconda boost

cd vowpal_wabbit
git submodule update --init
pip install -e .

python -c "from vowpalwabbit import pyvw"
```

It still throws the same exception.

This is the output from pulling the submodules:

![image](https://user-images.githubusercontent.com/2398765/69631302-b5ce1500-1088-11ea-9353-ec18dec472b6.png)

Looks like there is only one submodule

**Comment by peterychang** [comment]
@hsm207 sorry for the build issues you're seeing, our README is pretty out of date. I've created a task to update and consolidate them.

Could you make sure the following conda packages are currently installed?
`boost py-boost zlib`
if you intend to run the vowpalwabbit tests or use the sklearn wrapper, you'll also need
` pandas numpy scipy scikit-learn six joblib`

If `pip install -e` still fails in this case, you can try running `python setup.py install -f` from the repository's root directory.

**Comment by hsm207** [comment]
@peterychang thanks for your help. This is what worked for me:

```
git clone https://github.com/VowpalWabbit/vowpal_wabbit.git
conda create -y -n vowpalwabbit python=3.7
source activate vowpalwabbit
conda install -y -c anaconda boost py-boost zlib pandas numpy scipy scikit-learn six joblib

cd vowpal_wabbit
git submodule update --init
python setup.py install -f
```

what does the `-f` option in `python setup.py install -f` do?

**Comment by peterychang** [comment]
the `-f` option is a forced install which willl overwrite any existing files
