### ISSUE TITLE
Validate the training and test data format in automated system.

### ISSUE THREAD

**Issue by amit024003** [JohnLangford/vowpal_wabbit#1256]
Hi,

I have an automated system that collect data, convert into vw format and then run the vw.  I want to include a test case to validate the each line of training/test data before passing to vw.  

Is there any binary option which can help me apart from web based solution?

Regards,

**Comment by JohnLangford** [comment]
You could run vw --noop.

-John

On Mon, Jun 12, 2017 at 10:40 PM, Amit Kumar Gupta <notifications@github.com
