### ISSUE TITLE
parser.cc:293:5: warning: cannot delete expression with pointer-to-'void' type

### ISSUE THREAD

**Issue by arielf** [JohnLangford/vowpal_wabbit#1257]
When building `vw` I get this warning which may actually mean the delete is not being done:
```
parser.cc:293:5: warning: cannot delete expression with pointer-to-'void' type
      'void *' [-Wdelete-incomplete]
    delete p->jsonp;
    ^      ~~~~~~~~
```
Could this lead to a memory-leak too?

**Comment by JohnLangford** [comment]
Markus, can you remind me why we are deleting a void*?  Perhaps we should
just create an explicit deleter function pointer and use it instead?

-John

**Comment by JohnLangford** [comment]
I wanted to avoid explicit dependencies (and possible cycles). I think the *right* think to do is introduce an interface (e.g. class with pure virtual methods).

Markus

**Comment by JohnLangford** [comment]
Is there only one function required in that interface or multiple such?
(If multiple, what are the others?)

-John

**Comment by JohnLangford** [comment]
It’s less about the other functions, it’s about the associated state.

Markus

**Comment by JohnLangford** [comment]
This is fixed in the master now.

**Comment by JohnLangford** [comment]
(And, btw, fixing it fixed a memory leak.)
