### ISSUE TITLE
Can't build jni/java library

### ISSUE THREAD

**Issue by mpashka** [JohnLangford/vowpal_wabbit#1258]
I have ubuntu 17.04 / Amd 64. And I'm trying to create suitable vw_jni.lib
I used the following instructions to build vowpal_wabbit [https://github.com/JohnLangford/vowpal_wabbit] for ubuntu.
Build finished succesfully but vw-jni.jar was absent there. And I didn't find any instructions about building it separately.
I tried vowpal_wabbit/java/Makefile
`make target/vw_jni.lib`
but it failed with errors:
```
make: include: Command not found
Makefile:49: error executing recipe for target «../vowpalwabbit/main.o»
make: [../vowpalwabbit/main.o] Error 127 (ignore)
make: *** no rules for target «../vowpalwabbit/libvw.a», required for «target/vw_jni.lib».  Stop.
```

I also checked vowpal_wabbit/java/src/main/bin/build.sh but it seems it can work only on mac os.

And inside build.sh I see that `make vw java` is called but I don't see java target in Makefiles, so I also failed to use this to create vw_jni.

**Comment by mpashka** [comment]
Just started `vowpal_wabbit/java/src/main/bin/build.sh` on mac os and got:
`...
make: *** No rule to make target `clean'.  Stop.
make: *** No rule to make target `vw'.  Stop.
mv: cannot stat `java/target/vw_jni.lib': No such file or directory`

**Comment by JohnLangford** [comment]
What happens when you download from master and say:

make all
mvn test -f java/pom.xml

**Comment by mpashka** [comment]
The problem is I don't know how autogen / autoconf / configure / make determines if java is present. I had oracle JDK 1.8 installed and had JAVA_HOME present and had java bin present also. But seems build didn't recognize that java is present.
So I clean up files, installed maven with all dependencies (open jdk, gcj I suppose) and that fixed the problem - so now I have compiled vw_jni.lib.
So it is good to mention in docs system requirements to build native java wrapper lib - vw_jni.lib.

**Comment by JohnLangford** [comment]
Cool.  If you want to tweak the wiki, please do so.  (I'm not sure where you are referring to.)
