### ISSUE TITLE
Parameter --threads has no affect

### ISSUE THREAD

**Issue by osm3** [JohnLangford/vowpal_wabbit#1259]
Hi!
Why, when i use parameter --threads with vw, only one processor kernel is used?

**Comment by JohnLangford** [comment]
Yeah, that's confusing.  I believe this was meant to enable the
thread-based allreduce functionality but it does not seem to be hooked up.
@eisber can you comment?

-John

**Comment by eisber** [comment]
This is just an option for allreduce. Did you pass the allreduce options?

**Comment by osm3** [comment]
Sorry, but what is "allreduce options"?

**Comment by osm3** [comment]
here is my command line:
vw --oaa 3750 train_data.vw -f model.vw --loss_function=hinge --passes 2 --ngram 1 --cache_file cache.vw --bit_precision 28 --threads -l 0.8 --power_t 0.8

**Comment by JohnLangford** [comment]
@eisber where is the option parsed?

-John

**Comment by funkindy** [comment]
Hi all!
Iam also interested of how to run _multicore_ VW on _single_ machine.

**Comment by eisber** [comment]
Have a look here: https://github.com/JohnLangford/vowpal_wabbit/blob/master/cs/unittest/TestAllReduce.cs#L67

**Comment by JohnLangford** [comment]
Is this only exercisable via the C# interface?

The thing I find confusing is that grep "threads" reveals nowhere that the option is actually parsed.

**Comment by eisber** [comment]
I believe it only works via C# interface as the C++ parser isn't setup to feed the individual threads or run in parallel (also relates to the example ring)

**Comment by JohnLangford** [comment]
Ok.  

Options on the C++ side are running lock-free via --daemon or running with separate processes that you sync via the network allreduce.

**Comment by osm3** [comment]
I don not understand. Could i start vw on multiple processors simultaneusly in windows?

**Comment by osm3** [comment]
if i use parameter --daemon, vw is terminated without any messages

**Comment by JohnLangford** [comment]
Daemon does not work in windows as it relies on 'fork'.   You could use
allreduce as per this script:
https://github.com/JohnLangford/vowpal_wabbit/blob/master/cluster/single_machine
but that will require some setup to partition the data.

-John

**Comment by osm3** [comment]
How can i use this sicript? There is no spanning_tree in windows.

**Comment by arielf** [comment]
@osm3 

Sorry but AFAIK, the network/daemon related features have never been ported to windows.

We always welcome users to contribute PRs making `vw` work better on WIndows.

**Comment by JohnLangford** [comment]
spanning_tree does exist in windows in general... not sure what the issue there is.
