### ISSUE TITLE
How can i use vw in non hadoop cluster

### ISSUE THREAD

**Issue by osm3** [JohnLangford/vowpal_wabbit#1260]
Hi!
Ive found this recommendation to start vw on cluster(non-hadoop):
./vw --span_server <location> --total <t> --node <n> --unique_id <u> -d <file>
My configuration: spanning tree on ubuntu, and nodes on windows.

The problem is when i start above line in windows i get no differences with vw start on standalone machine. Also there is no differences if i set incorrect location of span server (no error messages etc).

Does anybody familiar with such behaviour? Or maybe nodes cant work on windows?

Thank you.

**Comment by JohnLangford** [comment]
It should be possible to work on windows---I have used it there.

In your command line, I don't see a value for total, node, or unique_id.

-John

**Comment by osm3** [comment]
this is my command line:
vw --span_server 192.168.54.85 --total 2 --node 0 --oaa 3750 train_data.vw -f model.vw --loss_function=hinge --passes 1 --ngram 1 --cache_file cache.vw --bit_precision 28 --threads -l 0.8 --power_t 0.8

**Comment by JohnLangford** [comment]
You have no unique_id and you want to get rid of --threads.  What are the
commandlines for _each_ of your processes?

**Comment by osm3** [comment]
ok,
here is command line on server 192.168.54.84:
./spanning_tree
here is command line on first node:
vw --unique_id 5 --span_server 192.168.54.85 --total 2 --node 0 --oaa 3750 train_data.vw -f model.vw --loss_function=hinge --passes 1 --ngram 1 --cache_file cache.vw --bit_precision 28 -l 0.8 --power_t 0.8
here is command line on second node:
vw --unique_id 5 --span_server 192.168.54.85 --total 2 --node 1 --oaa 3750 train_data.vw -f model.vw --loss_function=hinge --passes 1 --ngram 1 --cache_file cache.vw --bit_precision 28 -l 0.8 --power_t 0.8

vw on nodes works separately, there is no any messages about server unavailability (84 <> 85)

**Comment by JohnLangford** [comment]
It looks like you are training precisely the same predictor on each node?  Because the input dataset to each node is identical?

**Comment by osm3** [comment]
Yes, probably. I assume, that vw must divide data automatically. But i do not know how to start vw on cluster correctly. Please, give me correct command line.
PS. Anyway, it seems like vw clients does not try to connect to vw server

**Comment by JohnLangford** [comment]
VW does not divide the data automatically.  You must do this yourself.  That works well in a Hadoop environment, but in others it requires some work.

There is no client/server architecture for VW---all running instances are symmetric.

**Comment by osm3** [comment]
Please, give me correct command line to start vw in cluster (non hadoop). What means span_server parameter?

**Comment by JohnLangford** [comment]
The question does not make sense because you need multiple commandlines,
one for each VW instance.  Have you looked at the single machine script?
https://github.com/JohnLangford/vowpal_wabbit/blob/master/cluster/single_machine


That is where you might start adapting things from.

-John

**Comment by osm3** [comment]
thanks, but where is model saved?
I do not see model parameter.
I start this command lines on linux machine, it is working, but what it is doing?

**Comment by osm3** [comment]
parameter -f model.vw does not give any effect.
Where is resulting regressor saved?
if i use parameter --readble_model, then i get two files (r0 and r1):
command line:
vw --oaa 3750 --total 2 --node 0 --unique_id 0 -d head_data --cache_file c0 -k --passes 5 --span_server localhost --holdout_off -f model.vw --readable_model r0.vw &
vw --oaa 3750 --total 2 --node 1 --unique_id 0 -d tail_data --cache_file c1 -k --passes 5 --span_server localhost --holdout_off -f model.vw --readable_model r1.vw

**Comment by JohnLangford** [comment]
Only one VW instance should save the model, but -f does do it.

-John

**Comment by osm3** [comment]
there is no model.vw file after execution of this commands:
spanning_tree
vw --oaa 3750 --total 2 --node 0 --unique_id 0 -d head_data --cache_file c0 -k --passes 5 --span_server localhost --holdout_off -f model.vw &
vw --oaa 3750 --total 2 --node 1 --unique_id 0 -d tail_data --cache_file c1 -k --passes 5 --span_server localhost --holdout_off
killall spanning_tree
where is my mistake?

**Comment by JohnLangford** [comment]
It works for me so no idea.

-John

**Comment by osm3** [comment]
exactly this lines?

**Comment by osm3** [comment]
your model.vw is concatenation of results from node 0 and node 1?

**Comment by osm3** [comment]
it is working!
thanks
