### ISSUE TITLE
Can't install in Ubuntu

### ISSUE THREAD

**Issue by parulsethi** [JohnLangford/vowpal_wabbit#1269]
I'm trying to install vowpal_wabbit and getting this error on master branch
```
make[1]: Entering directory '/gensim/gensim_dependencies/vowpal_wabbit/java'
/usr/bin/g++ -std=c++0x   -D__extern_always_inline=inline -Wall -pedantic -DNDEBUG -O3 -fomit-frame-pointer -fno-strict-aliasing  -D_FILE_OFFSET_BITS=64 -I /usr/include -I ../rapidjson/include -fPIC  -I ../rapidjson/include -c src/main/c++/vowpalWabbit_learner_VWScalarsLearner.cc -o src/main/c++/vowpalWabbit_learner_VWScalarsLearner.o -I /include -I /include/linux
In file included from src/main/c++/vowpalWabbit_learner_VWScalarsLearner.cc:1:0:
src/main/c++/vowpalWabbit_learner_VWScalarsLearner.h:2:17: fatal error: jni.h: No such file or directory
compilation terminated.
make[1]: *** [src/main/c++/vowpalWabbit_learner_VWScalarsLearner.o] Error 1
Makefile:49: recipe for target 'src/main/c++/vowpalWabbit_learner_VWScalarsLearner.o' failed
make[1]: Leaving directory '/gensim/gensim_dependencies/vowpal_wabbit/java'
make: *** [install] Error 2
Makefile:138: recipe for target 'install' failed
```
It seems to be related to this recently merged [PR](https://github.com/JohnLangford/vowpal_wabbit/commit/1e6b3849bd44de3e227e21668fb211e99a0d2be9) or maybe ones after that, as I don't get the error on using a [version](https://github.com/JohnLangford/vowpal_wabbit/commit/69ecc2847fa0c876c6e0557af409f386f0ced59a) before that merge.

OS: ubuntu:16.04

**Comment by JohnLangford** [comment]
Do you want/need java?

-John

**Comment by grafael** [comment]
Have you configured the JAVA_HOME properly? I had this problem in the past, and that solved for me.

**Comment by JohnLangford** [comment]
Closing this for now.  Probably (?) solved.

**Comment by usptact** [comment]
I get this error on Ubuntu 16.10 as well.

My $JAVA_HOME is set to "/usr/lib/jvm/java-8-oracle"

I used this guide to install Oracle's JAVA on my system:
http://tipsonubuntu.com/2016/07/31/install-oracle-java-8-9-ubuntu-16-04-linux-mint-18/

**Comment by usptact** [comment]
Is it possible to disable JAVA?

**Comment by grafael** [comment]
Install only the JRE is not enough you need to install JDK (that have the jni.h)

**Comment by arielf** [comment]
Curious: any particular reason you're preferring Oracle java and non-standard installation methods over the standard and better supported OpenJDK ?  You can run them side by side on the same box too.
```
$ dpkg -l | grep -E 'jdk|oracle'
ii  openjdk-8-jre:amd64                                         8u131-b11-0ubuntu1.16.04.2                 amd64        OpenJDK Java runtime, using Hotspot JIT
ii  openjdk-8-jre-headless:amd64                                8u131-b11-0ubuntu1.16.04.2                 amd64        OpenJDK Java runtime, using Hotspot JIT (headless)
ii  openjdk-9-jre:amd64                                         9~b114-0ubuntu1                            amd64        OpenJDK Java runtime, using Hotspot JIT
ii  openjdk-9-jre-headless:amd64                                9~b114-0ubuntu1                            amd64        OpenJDK Java runtime, using Hotspot JIT (headless)
ii  oracle-java8-installer                                      8u131-1~webupd8~2
```

**Comment by usptact** [comment]
@arielf I actually assumed that Oracle's JAVA is better / well-rounded than open source one. :) I can of course go with OpenJDK version, no problem.

**Comment by usptact** [comment]
@arielf I got rid of Oracle's Java and install openjdk-8. I had to meddle with /etc/environment to set JAVA_HOME and eventually got it working.
For posterity: you need to set and export variable JAVA_HOME, for example JAVA_HOME=/usr/lib/jvm/default-java
If you don't see it, put "source /etc/environment" in your .bashrc or .bash_profile
Btw, Ubuntu 16.10 EoL is July 21, 2017!

**Comment by arielf** [comment]
@usptact  If you care about long term support, you should be using Ubuntu 16.04 LTS (EOL in April 2021).
See [https://wiki.ubuntu.com/Releases]
