### ISSUE TITLE
./daemon-test.sh w/ foreground (test 152) fails in the travis env

### ISSUE THREAD

**Issue by arielf** [JohnLangford/vowpal_wabbit#1271]
https://travis-ci.org/JohnLangford/vowpal_wabbit#L3089

Exit status 124 from 'timeout' means one thing only:

    This test is timing out (waiting for some input?)
    in the travis (non interactive) env.

'man timeout' says:
    If  the  command times out, and --preserve-status is not set,
    then exit with status 124.  Otherwise, exit with the status of
    COMMAND.   If no signal is specified, send the TERM signal upon
    timeout.  The TERM signal kills any process that does not block
    or catch that signal.  It may be necessary to use the KILL (9)
    signal, since this signal cannot be caught, in which case the exit
    status is 128+9 rather than 124.

The ../vowpalwabbit/vw: free(): invalid pointer: 0x00002ae11a9dd000 ***
error seems to be side-effect of killing the deamon by the 'timeout'
wrapper.

@seifert could you take a look?

BTW (but seems unrelated to problem): it is cleaner to pass `--` to end `grep` options rather than try to escape the searched pattern: `\-\-foreground`

**Comment by seifert** [comment]
I will see to it.

**Comment by JohnLangford** [comment]
This one seems pretty mysterious to me as the code change is pretty simple.  I haven't been able to reproduce on my local box.  Hopefully you can?  Without it, we'll need to disable things, as a failing test is to disruptive.

**Comment by seifert** [comment]
Unfortunately, I haven't been able to reproduce problem on my environment. How often has the test been failing? Or it was first and only one fail?

I have theory why daemon-test.sh can block itself:

* on line 117 daemon starts
* then, on lines 119 - 139, PID is tested. The test was successful on these lines, so the daemon probably started successfully.
* then, on line 148, prediction request is sent
* finally, on line 150, there is waiting for response

I think that the daemon hadn't been ready when the prediction request was sent. Maybe vw process had been started, but didn't listen on port yet. So netcat had stopped immediately with exit status 1 (without any stdout) and infinite loop on line 150 was aborted by timeout.

I tried refactor daemon-test.sh, see https://github.com/seifert/vowpal_wabbit/commit/f601857581f9886cfcb4d9d508c43f2770ce608a. Is it ok and shall I create merge request?

**Comment by JohnLangford** [comment]
It's failing >50% of the time on Travis.

Go ahead and send a pull request---let's see what Travis says.

-John
