### ISSUE TITLE
Prediction confidence

### ISSUE THREAD

**Issue by grafael** [JohnLangford/vowpal_wabbit#1273]
There is a way to get the confidence prediction using learn2search? 

For example in the pos-tag example: [https://github.com/JohnLangford/vowpal_wabbit/blob/master/python/examples/Learning_to_Search.ipynb](url)

I would like to get the confidence for each tag predicted. **Is that possible**?

**Comment by JohnLangford** [comment]
It's not possible at present, but it's not far away from possible as there is an internal confidence measure that is usable.  @hal3 @KaiWeiChang have you thought about this sort of thing?

**Comment by JohnLangford** [comment]
I'm closing this for now. It's a 'patches welcome' kind of thing.
