### ISSUE TITLE
Question about the installation in windows

### ISSUE THREAD

**Issue by vatn** [JohnLangford/vowpal_wabbit#1274]
Hello,
I'm trying to follow the steps of https://github.com/JohnLangford/vowpal_wabbit/blob/master/README.windows.txt.

And I used visual studio 2013 update 5. The system is windows 10.
However, we I execute (5) (b) Using command line (available configurations are "Release" and "Debug". Available platforms are "x64" and "Win32")
	run>msbuild /p:Configuration="Release" /p:Platform="x64" vw.sln

I have always met the errors as following:

`"C:\Users\vatn\TestOnlineVOW\vowpal_wabbit\vowpalwabbit\vw.sln" (default target) (1) ->
"C:\Users\vatn\TestOnlineVOW\vowpal_wabbit\vowpalwabbit\..\cs\test\cs_test.csproj.metaproj" (default target) (6) ->
"C:\Users\vatn\TestOnlineVOW\vowpal_wabbit\cs\test\cs_test.csproj" (default target) (7) ->
"C:\Users\vatn\TestOnlineVOW\vowpal_wabbit\cs\cs\cs.csproj" (default target) (8) ->
(PreBuildEvent target) ->
  C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1250,5): error MSB3073: The command "
C:\Users\vatn\TestOnlineVOW\vowpal_wabbit\vowpalwabbit\..\cs\transform_all.bat C:\vatn\TestOnlineVOW\vowpal_wabbit\cs\cs\\r [C:\Users\vatn\TestOnlineVOW\vowpal_wabbit\cs\cs\cs.csproj]
C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1250,5): error MSB3073: " exited with c
ode 9009. [C:\Users\vatn\TestOnlineVOW\vowpal_wabbit\cs\cs\cs.csproj]

"C:\Users\vatn\TestOnlineVOW\vowpal_wabbit\vowpalwabbit\vw.sln" (default target) (1) ->
"C:\Users\vatn\TestOnlineVOW\vowpal_wabbit\vowpalwabbit\..\cs\test\cs_test.csproj.metaproj" (default target) (
6) ->
"C:\Users\vatn\TestOnlineVOW\vowpal_wabbit\cs\test\cs_test.csproj" (default target) (7) ->
"C:\Users\vatn\TestOnlineVOW\vowpal_wabbit\cs\unittest\cs_unittest.csproj" (default target) (14) ->
  C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1250,5): error MSB3073: The command "
C:\Users\vatn\TestOnlineVOW\vowpal_wabbit\vowpalwabbit\..\cs\transform_all.bat C:\Users\vatn\TestOnlineVOW\vowpal_wabbit\cs\unittest\" exited with code 9009. [C:\Users\vatn\TestOnlineVOW\vowpal_wabbit\cs\unittes
t\cs_unittest.csproj]

"C:\Users\vatn\TestOnlineVOW\vowpal_wabbit\vowpalwabbit\vw.sln" (default target) (1) ->
"C:\Users\vatn\TestOnlineVOW\vowpal_wabbit\vowpalwabbit\..\c_test\c_test.vcxproj.metaproj" (default target) (1
7) ->
"C:\Users\vatn\TestOnlineVOW\vowpal_wabbit\c_test\c_test.vcxproj" (default target) (18) ->
(PostBuildEvent target) ->
  C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(132,5): error MSB3073: The command
 "xcopy /y/d C:\Users\vatn\TestOnlineVOW\vowpal_wabbit\vowpalwabbit\dll\x64\Release\libvw.* C:\Users\vatn\TestOnlineVOW\vowpal_wabbit\c_test\Bin\x64\Release\\r [C:\Users\vatn\TestOnlineVOW\vowpal_wabbit\c_test\c_test.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(132,5): error MSB3073: :VCEnd" exite
d with code 4. [C:\Users\vatn\TestOnlineVOW\vowpal_wabbit\c_test\c_test.vcxproj]`

Can you please help me to solve this problem?
Thank you so much!

**Comment by JohnLangford** [comment]
Not sure.  @eisber any ideas?

**Comment by eisber** [comment]
a) do you have VS2015 installed as well?
b) cd C:\Users\vatn\TestOnlineVOW\vowpal_wabbit
     msbuild /p:Configuration="Release" /p:Platform="x64" vowpalwabbit\vw.sln

**Comment by vatn** [comment]
Hello, thanks for your solution, But i still failed to install.
I install VS2015. and I execute the msbuild /p:Configuration="Release" /p:Platform="x64" vowpalwabbit\vw.sln  from the command shell of both VS2015 and VS 2013, there are always three errors as following:

`"C:\Users\tianjinzi gao\TestOnlineVOW\vowpal_wabbit\vowpalwabbit\vw.sln" (default target) (1) ->
"C:\Users\tianjinzi gao\TestOnlineVOW\vowpal_wabbit\vowpalwabbit\..\cs\test\cs_test.csproj.metaproj" (default target) (
6) ->
"C:\Users\tianjinzi gao\TestOnlineVOW\vowpal_wabbit\cs\test\cs_test.csproj" (default target) (7) ->
"C:\Users\tianjinzi gao\TestOnlineVOW\vowpal_wabbit\cs\cs\cs.csproj" (default target) (8) ->
(PreBuildEvent target) ->
  C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1250,5): error MSB3073: The command "
C:\Users\tianjinzi gao\TestOnlineVOW\vowpal_wabbit\vowpalwabbit\..\cs\transform_all.bat C:\Users\tianjinzi gao\TestOnli
neVOW\vowpal_wabbit\cs\cs\\r [C:\Users\tianjinzi gao\TestOnlineVOW\vowpal_wabbit\cs\cs\cs.csproj]
C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1250,5): error MSB3073: " exited with c
ode 9009. [C:\Users\tianjinzi gao\TestOnlineVOW\vowpal_wabbit\cs\cs\cs.csproj]


"C:\Users\tianjinzi gao\TestOnlineVOW\vowpal_wabbit\vowpalwabbit\vw.sln" (default target) (1) ->
"C:\Users\tianjinzi gao\TestOnlineVOW\vowpal_wabbit\vowpalwabbit\..\cs\test\cs_test.csproj.metaproj" (default target) (
6) ->
"C:\Users\tianjinzi gao\TestOnlineVOW\vowpal_wabbit\cs\test\cs_test.csproj" (default target) (7) ->
"C:\Users\tianjinzi gao\TestOnlineVOW\vowpal_wabbit\cs\unittest\cs_unittest.csproj" (default target) (14) ->
  C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1250,5): error MSB3073: The command "
C:\Users\tianjinzi gao\TestOnlineVOW\vowpal_wabbit\vowpalwabbit\..\cs\transform_all.bat C:\Users\tianjinzi gao\TestOnli
neVOW\vowpal_wabbit\cs\unittest\" exited with code 9009. [C:\Users\tianjinzi gao\TestOnlineVOW\vowpal_wabbit\cs\unittes
t\cs_unittest.csproj]


"C:\Users\tianjinzi gao\TestOnlineVOW\vowpal_wabbit\vowpalwabbit\vw.sln" (default target) (1) ->
"C:\Users\tianjinzi gao\TestOnlineVOW\vowpal_wabbit\vowpalwabbit\..\c_test\c_test.vcxproj.metaproj" (default target) (1
7) ->
"C:\Users\tianjinzi gao\TestOnlineVOW\vowpal_wabbit\c_test\c_test.vcxproj" (default target) (18) ->
(PostBuildEvent target) ->
  C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(132,5): error MSB3073: The command
 "xcopy /y/d C:\Users\tianjinzi gao\TestOnlineVOW\vowpal_wabbit\vowpalwabbit\dll\x64\Release\libvw.* C:\Users\tianjinzi
 gao\TestOnlineVOW\vowpal_wabbit\c_test\Bin\x64\Release\\r [C:\Users\tianjinzi gao\TestOnlineVOW\vowpal_wabbit\c_test\c
_test.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(132,5): error MSB3073: :VCEnd" exite
d with code 4. [C:\Users\tianjinzi gao\TestOnlineVOW\vowpal_wabbit\c_test\c_test.vcxproj]`


Thank you

**Comment by eisber** [comment]
I guess this is due to spaces in your username (see https://stackoverflow.com/questions/1351830/what-does-exited-with-code-9009-mean-during-this-build)
Move the checkout to c:\work or so.

-Markus

**Comment by JohnLangford** [comment]
Thanks @eisber closing for now.
