### ISSUE TITLE
mapper already connected vw: std::exception

### ISSUE THREAD

**Issue by amit024003** [JohnLangford/vowpal_wabbit#1281]
Earlier I faced this problem.
https://github.com/JohnLangford/vowpal_wabbit/issues/1280
Then I tried with multiple time in iteration.

Now I am getting this error. What could be reason for this?
```

connecting to 10.213.40.217 = <hostname>
wrote unique_id=103336
wrote total=1500
wrote node=2
read ok=0
mapper already connected
vw: std::exception
```

**Comment by JohnLangford** [comment]
It means to many hosts have attempted to connect to the spanning tree server for the computation which is now trying to shutdown the extra hosts.  See here:
https://github.com/JohnLangford/vowpal_wabbit/blob/master/vowpalwabbit/spanning_tree.cc#L189

**Comment by amit024003** [comment]
what is fall back option for this? Is there any config parameter to increase this limit?

**Comment by JohnLangford** [comment]
There isn't a config parameter.  Possibly (?) the same process is trying to connect twice.  Or, maybe you have two distinct nodes with the same nodeid.  In either case the code will try to shut down one of them because only one node of a given nodeid is valid in a computation.
