### ISSUE TITLE
details on learning to search command line args

### ISSUE THREAD

**Issue by ecolss** [JohnLangford/vowpal_wabbit#1285]
Hey, `vw` guys, big fan of `vw` here :-)
I really wanted to try the `learning-to-search` functionalities to do some seq labeling tasks (such as pos tagging, ner etc.), and I've gone through some of the `vw` tutorial on the web, however only very limited info I could grasp about `l2s`, even the command line args couldn't be found on this page: [command line args](https://github.com/JohnLangford/vowpal_wabbit/wiki/Command-line-arguments), (precisely, only found `--search` option).

Please point me in the right direction on how to get more info on this `l2s` related functionalities in `vw`, thanks 1m

**Comment by JohnLangford** [comment]
One good source is the demo directory: https://github.com/JohnLangford/vowpal_wabbit/tree/master/demo 

Another is the tests: https://github.com/JohnLangford/vowpal_wabbit/blob/master/test/RunTests#L908

A third is the credit assignment compiler paper: https://arxiv.org/abs/1406.1837 .

A fourth is the source code which is in the search_XXX files.  Learning to search is made to work with your code.
