### ISSUE TITLE
Topic Modelling with c# Binding

### ISSUE THREAD

**Issue by HarryMcCarney** [JohnLangford/vowpal_wabbit#1286]
Is there an example or some documentation on this?

Many thanks

**Comment by JohnLangford** [comment]
I don't believe so, but it should be straightforward.  @eisber any comment?

**Comment by HarryMcCarney** [comment]
@eisber would really appreciate some pointers.

**Comment by JohnLangford** [comment]
Markus, can you comment on LDA-through-C#?

-John

**Comment by JohnLangford** [comment]
I looked through my code again. I actually didn’t train VW LDA models, but I rather used an existing one and then scored using C#/VW. You can get the prediction using the code below

  var topics = vw.Predict(featurizer, VowpalWabbitPredictionType.Topic);

We used bag-of-words and so regular VW examples will do, but the complete end-to-end pipeline was a lot more complex (tokenization, stemming, word-counts) and we used another internal tool to create this and then run VW at the bottom.

-Markus

**Comment by HarryMcCarney** [comment]
Thanks John. I am struggling to find documentation to create the inputs to this function. 

I am mainly interested in how to instantiate the right featurizer and what to pass with the VowpalWabbitSettings. An absolute bare bones, but runnable, hello world example would be massively helpful. Perha;ps just creating a very small, and probably useless, topic model with some text from a wikipaedia article.

Also do you know where I could find the existing model that you used. code samples most appreciated.

Thanks again.

**Comment by HarryMcCarney** [comment]
Heres a code sample (obviously this wont produce anything useful, just want to get the main blocks in place first. )
What I need to understand is what model I can pass into new VW.VowpalWabbit<Row>("-f rcv1.model")
@JohnLangford did you pass a different model in here?
Also does anyone ( @eisber ) have an example of the creation of a topic model in c#?

 ```
public class Program
    {
        static void Main(string[] args)
        {


            using (var vw = new VW.VowpalWabbit<Row>("-f rcv1.model"))
            {
                var featuriser = new Row()
                {
                    Constant = 0.5f,
                    Line = "First",
                    Label = new StringLabel("SomeLabel"),
                    Features = new List<KeyValuePair<string, float>>()
                    {
                        new KeyValuePair<string, float>("Somefeature", 0.5f)
                    }
                };
                
                var topics = vw.Predict(featuriser, VowpalWabbitPredictionType.Topic);
            }

        }

        public class Row  
        {
            [Feature(FeatureGroup = 'f', Namespace = "eatures", Name = "const", Order = 2)]
            public float Constant { get; set; }

            [Feature(FeatureGroup = 'f', Namespace = "eatures", Order = 1)]
            public IList<KeyValuePair<string, float>> Features { get; set; }

            public string Line { get; set; }

            public ILabel Label { get; set; }
        }
    }

```

Will share results of example topic model creation and prediction once i have a simple example working end to end.

Thanks again,
Harry

**Comment by JohnLangford** [comment]
Any model formed via -f can be loaded in via -i.

-John

**Comment by eisber** [comment]
Do you have a sample input line in VW format for LDA that you’d want to feed in?

Markus

**Comment by HarryMcCarney** [comment]
Thanks @eisber. I need a very simple example of topic model creation. Any input line would be fine.
