### ISSUE TITLE
Current stable release version?

### ISSUE THREAD

**Issue by ilovezfs** [JohnLangford/vowpal_wabbit#1293]
Based on https://github.com/JohnLangford/vowpal_wabbit/releases/latest it's not clear to me whether 8.2.0 or 8.4.0 is the current stable release version. Could you clarify which should be in Homebrew now? Thanks!

**Comment by JohnLangford** [comment]
Updated.

**Comment by ilovezfs** [comment]
Thanks! Next up: https://github.com/JohnLangford/vowpal_wabbit/issues/1294.
