### ISSUE TITLE
contextual bandit example

### ISSUE THREAD

**Issue by arugola** [JohnLangford/vowpal_wabbit#1302]
Hi,
do you have a working example (notebook or .py) of the Contextual Bandit Optimization using the Python API mentioned [here](https://github.com/JohnLangford/vowpal_wabbit/blob/master/python/vowpalwabbit/sklearn_vw.py)?

I could not find anything in the [examples](https://github.com/JohnLangford/vowpal_wabbit/tree/master/python/examples) folder

Thank you,

**Comment by JohnLangford** [comment]
There's nothing that I'm aware of.

-John
