### ISSUE TITLE
commit 541bad7b1eeb347747ea30ed9b7229b9ecc97986 causes test failures

### ISSUE THREAD

**Issue by ryan-deak-zefr** [JohnLangford/vowpal_wabbit#1304]
User `U-NORTHAMERICA\jcl` committed *fix some warnings in VS* hash `541bad7b1eeb347747ea30ed9b7229b9ecc97986`.  This causes some tests to fail (test 15) due to precision changes and the output of `bfgs.cc` line 975 seems to have mangled a new line.

**Comment by ryan-deak-zefr** [comment]
@JohnLangford have you seen this latest commit to master?  Looks like it's breaking the build and it doesn't look like this went through a PR.

**Comment by JohnLangford** [comment]
Yep, my bad.  Fixed.

-John
