### ISSUE TITLE
Is it possible run muliple spanning tree on hadoop cluster?

### ISSUE THREAD

**Issue by amit024003** [JohnLangford/vowpal_wabbit#1308]
Hi, 

I have a hadoop cluster on which I would like to setup multiple classification training flow. Is it possible to run separate spanning tree for each classifier?

**Comment by JohnLangford** [comment]
It's certainly possible---you just need to specify the port.  However a single spanning tree can handle multiple classification training flows as well.

**Comment by amit024003** [comment]
How to specify port in spanning tree? Is there command line option for that?

I also want to understand that how can I run multiple classification with single spanning tree. 

Thank you in advance for helping me.

**Comment by amit024003** [comment]
Please can you help me on this. That will be great.

**Comment by JohnLangford** [comment]
It looks like you can't do this in the present code, because the port is hardwired to 26543 here: https://github.com/JohnLangford/vowpal_wabbit/blob/master/vowpalwabbit/allreduce_sockets.cc#L117

This seems like a "patches welcome" kind of issue if you want to tweak the code.

**Comment by JohnLangford** [comment]
(As an alternative, you can use a span_server for multiple compute jobs).
