### ISSUE TITLE
Can't build jni/java library

### ISSUE THREAD

**Issue by mpashka** [JohnLangford/vowpal_wabbit#1310]
I have ubuntu 16.04 xenial (the same thing on ubuntu 17.04 zesty)
I need vowpal_wabbit jni library v 8.1 to run my project.
To build jni v 8.1 on ubuntu I did the following steps:
did git checkout && git update 8.1
installed autoconfigure, automake, appropriate libboost dependencies and all other dependencies that where specified in readme, ubuntu section
ran ./automake.sh
ran make
After that checked java directory. There where no target directory. So after running mvn test I got error because there where no jni lib file there.
Previously I did the trick by installing maven (which also requires openjdk). But that helped me for 8.3 version, not for 8.1.
So I'm pretty sure that to make java jni I need to install something else, but I don't know what. May be someone can tell me what else can be installed. Or may be can tell me how did you create jar file that is present in maven repository - it contains several jnis for different OSes.

**Comment by arielf** [comment]
See:

https://github.com/JohnLangford/vowpal_wabbit/issues/1305#issuecomment-320479104

You don't need `automake/autogen.sh` on Ubuntu.

**Comment by mpashka** [comment]
Please note I'm building v 8.1.
$ echo $JAVA_HOME 
/opt/java/jdk/jdk1.8
(This is Oracle JDK)
Open JDK is also installed.

$ make java (in root project dir)
 cd . && /bin/bash /opt/projects/github/JohnLangford/.versions/vowpal_wabbit/missing automake-1.15 --gnu
configure.ac:4: error: version mismatch.  This is Automake 1.15,
configure.ac:4: but the definition used by this AM_INIT_AUTOMAKE
configure.ac:4: comes from Automake 1.14.1.  You should recreate
configure.ac:4: aclocal.m4 with aclocal and run automake again.
WARNING: 'automake-1.15' is probably too old.
         You should only need it if you modified 'Makefile.am' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'automake' program is part of the GNU Automake package:
         <http://www.gnu.org/software/automake>
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         <http://www.gnu.org/software/autoconf>
         <http://www.gnu.org/software/m4/>
         <http://www.perl.org/>
Makefile:448: recipe for target 'Makefile.in' failed
make: *** [Makefile.in] Error 1

$ ./autogen.sh 
...
$ make java (in root project dir)
make: Nothing to be done for 'java'.
$ cd java && make
...
At the end of the build process I see no target dir in java - jni lib was not built (.

**Comment by mpashka** [comment]
Actually `make java` works by default only on v 8.4.
But I see there are builds in maven for v 8.1. So I assume it is possible to build vw 8.1. Event with several different jni libs. Does smbd know how to do that?

**Comment by arielf** [comment]
Hi @mpashka 

I can't answer java Qs.   @jmorra can you help?

A few points:

- 8.1 is almost 2 years old.
- autogen/automake/configure was never needed on Ubuntu. It was added as a last resort to try and help other new/unsupported environments to get going.
- `autogen.sh` overwrites all `Makefile`s, which on Ubuntu, makes things worse.

If during any (Ubuntu) build you see any mention of: `autogen.sh`, `automake`, `configure`, `libtool`, or `.libs` it means that perfectly fine Makefiles have already been overwritten/corrupted.  Please `git checkout Makefile */Makefile` to undo this destruction, and try a simple `make` instead.

Sorry, I'm not sure if this would help vs 8.1.  In particular if 8.1 was built with an older version of `libboost-dev` (C++/templates are notoriously non binary backward compatible) or used an older compiler or using older ABI flags, all bets are off.

Anyway, I would try without the `autogen.sh` (and a fresh checkout).  Does that work for you?

**Comment by JohnLangford** [comment]
I'm closing this for now.  8.1 is a dead branch---we won't be making changes there.  If anyone knows precisely how to build the old java interface feel free to comment.
