### ISSUE TITLE
Ruby bindings

### ISSUE THREAD

**Issue by arjunmenon** [JohnLangford/vowpal_wabbit#1324]
Hey
Some support for Ruby would be very good.

**Comment by JohnLangford** [comment]
I agree.   Want to make a pull request?

-John

**Comment by JohnLangford** [comment]
(closing for now, patch is welcome)

**Comment by arjunmenon** [comment]
Hey 
Could you point me to the main header files? I would like to try. 
Would try to generate FFI bindings. Want this library for Ruby.

**Comment by JohnLangford** [comment]
See here:
https://github.com/JohnLangford/vowpal_wabbit/blob/master/vowpalwabbit/vw.h

Also, you can look into the individual language directories to find
examples of usage.

-John

**Comment by ankane** [comment]
Hey @arjunmenon, if you're still interested, I created [Ruby bindings here](https://github.com/ankane/vowpalwabbit).

**Comment by JohnLangford** [comment]
Do you want to send a pull request?

-John

**Comment by ankane** [comment]
Hey @JohnLangford, I think it'll be easier to manage as a separate project. Thanks for creating Vowpal Wabbit btw 😃

**Comment by JohnLangford** [comment]
Cool.  If you are going to NeurIPS, we may do a workshop related to VW....

**Comment by ankane** [comment]
Nice - not going to that one, but if you're ever in San Francisco, let's grab coffee. My email is on my GitHub profile.
