### ISSUE TITLE
Can't build on windows

### ISSUE THREAD

**Issue by hadaev8** [JohnLangford/vowpal_wabbit#1326]
Installed all tools, open on studio 2015 and get error:
[Failure] Could not find file 'C:\Users\Andrey\Downloads\vowpal_wabbit-master\vowpal_wabbit\cs\cs\Serializer\VowpalWabbitDefaultMarshallerExt.cs'.
[Failure] Could not find file 'C:\Users\Andrey\Downloads\vowpal_wabbit-master\vowpal_wabbit\cs\unittest\RunTests.cs'.

http://puu.sh/xydp0/56d4a660ca.png

**Comment by MLWave** [comment]
@eisber has created easy .msi installers for windows. Can you try installing from that?

https://github.com/eisber/vowpal_wabbit/releases goes up to VW version 8.4.

**Comment by hadaev8** [comment]
Nothing happens after execution.

**Comment by MLWave** [comment]
You probably have vw.exe somewhere on your HD now. I don't have access to a Windows machine to create a step-by-step.

https://github.com/gatapia/py_ml_utils/blob/master/lib/vw.exe is ready made executable for Windows. Version 7.7.

**Comment by hadaev8** [comment]
Maybe I misunderstood, need I to use the studio, if I want vowpal wabbit for 
Python?

**Comment by JohnLangford** [comment]
@eisber can you comment?

**Comment by eisber** [comment]
I’m a bit confused of what should be achieved here.


  1.  for building make sure you follow: https://github.com/JohnLangford/vowpal_wabbit/wiki/Windows-Build
I believe we migrated to VS 2015… so we need to update the wiki. Anyway VS 2015 should be good.
  2.  the msi only installs the binaries on your machine – not need for build. You can use them through the “Vowpal Wabbit Command Prompt” link created in your start menu

Markus

**Comment by JohnLangford** [comment]
Thanks.  I'll close for now.
