### ISSUE TITLE
VW_InitializeA

### ISSUE THREAD

**Issue by haimnkfans** [JohnLangford/vowpal_wabbit#1331]
Hi,

I am already having the model in memory. Do I need to go through VW_InitializeA function always? or I can directly load the model into memory and go for prediction skipping VW_InitializeA function. If I can directly access it from memory, please suggest the steps. Thanks.

**Comment by mauryaakhilesh** [comment]
you should call VW_InitializeA function only when you are updating your model otherwise you always load in memory and call for prediction only . For more detail you can check sample example here [https://github.com/mauryaakhilesh/vw_issue_1245/blob/master/predict/src/vw_predict_model.cpp](url)
