### ISSUE TITLE
Disposed PooledObject may be disposed again, causing exception (depending on object type)

### ISSUE THREAD

**Issue by sidsen** [JohnLangford/vowpal_wabbit#1338]
When using the MultiworldTesting.ClientLibrary (https://github.com/Microsoft/mwt-ds) with multiple threads, the Dispose() method of a pooled VowpalWabbit object may be called concurrently by multiple threads. Currently the object is returned to the object pool and either accepted back into the pool (if the version matches) or disposed (if the version is outdated); in the latter case the dispose is done without protection of a lock:

https://github.com/JohnLangford/vowpal_wabbit/blob/17b4c66acbeb1ae241c1975ac9ee0e2ee251c899/cs/cs/ObjectPool.cs#L199

Moreover, this happens inside the object pool, whereas the right place to handle this is arguably here:

https://github.com/JohnLangford/vowpal_wabbit/blob/17b4c66acbeb1ae241c1975ac9ee0e2ee251c899/cs/cs/PooledObject.cs#L57

In particular, that Dispose method should check if the pool accepted the object back in (perhaps modify the ReturnObject method to indicate whether the object was accepted or not), and dispose it if not, all under the protection of a lock to guarantee subsequent attempts won't try to dispose the object again.

**Comment by JohnLangford** [comment]
Sid, can you fix?

**Comment by sidsen** [comment]
Yes, I stopped debugging this to work on other things, but I will get back
to it. Is there a way to "assign" it to me?

Sid

**Comment by JohnLangford** [comment]
ETA?  I'd like to do a release shortly.

**Comment by sidsen** [comment]
This was a heisenbug triggered by the localmode test cases, which spin up
hundreds of threads for prediction while model updates occur. I will try to
work on it today.

If I don't get it done by tom you might want to go ahead with your release,
I wouldn't consider this a sev1 bug based on current manifestation.

Sid

**Comment by JohnLangford** [comment]
Could #1300 be related?  (Read to the bottom)

**Comment by eisber** [comment]
After reading the thread twice, I agree that this might be related. 
When discussing this with @sidsen originally my impression was that this can be attributed the C# ObjectPool assumption that the caller needs to make sure Dispose is only called once. This originates from the use case in-mind when implementing the class (basically an single thread requests an object from the pool, makes a rank request, returns the object)

**Comment by JohnLangford** [comment]
@sidsen can you create a method to reproduce?  That will allow other people to potentially debug.

**Comment by sidsen** [comment]
Sorry for dropping the ball on this. I previously had an idea for a fix but didn't have a contiguous block of time to fully test it. At this point, others will have as much context as I do, so good idea to make it reproducible. There is a test I added called "TestDSLocalConcurrent" (in LocalModeTests.cs) that tests multithreaded access to ChooseActionAsync and ReportRewardAndComplete (the latter being a local mode-only api). If you run this test, it should reproduce the exception; if not, increase the number of threads in the function (variable NumThreads) to something higher and it should reproduce.

**Comment by JohnLangford** [comment]
I'm closing this in light of the new C++ client library that @rajan-chari has created.
