### ISSUE TITLE
Python API does not build for Python 3.6 in Ubuntu 16.04

### ISSUE THREAD

**Issue by charlescearl** [JohnLangford/vowpal_wabbit#1339]
Installing the Python API from source fails for me in Python 3.6 in Ubuntu 16.04. Is this a known problem?

I run

```
> pip install -e .
```
in the `python` subdirectory.

I get the following output, 

```
    /usr/bin/g++ -std=c++0x   -D__extern_always_inline=inline -Wall -pedantic -DNDEBUG -O3 -fomit-frame-pointer -fno-strict-aliasing  -D_FILE_OFFSET_BITS=64 -I /usr/include -I ../rapidjson/include -fPIC  -I ../rapidjson/include -o vw main.o -L. -l vw -l allreduce -L /usr/local/lib -L /usr/lib -L /usr/lib/x86_64-linux-gnu -l boost_program_options -l pthread -l z
    ./libvw.a(parse_args.o): In function `new_options(vw&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) [clone .isra.38] [clone .constprop.369]':
    parse_args.cc:(.text+0x31b): undefined reference to `boost::program_options::options_description::options_description(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int, unsigned int)'
    ./libvw.a(parse_args.o): In function `parse_diagnostics(vw&, int)':
    parse_args.cc:(.text+0x585d): undefined reference to `boost::program_options::abstract_variables_map::operator[](std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
    parse_args.cc:(.text+0x59ba): undefined reference to `boost::program_options::abstract_variables_map::operator[](std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
    ./libvw.a(parse_args.o): In function `parse_output_preds(vw&)':
    parse_args.cc:(.text+0x5c9c): undefined reference to `boost::program_options::abstract_variables_map::operator[](std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
```
and eventually 

```
   scorer.cc:(.text+0x2bf): undefined reference to `boost::program_options::options_description::options_description(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int, unsigned int)'
    scorer.cc:(.text+0x381): undefined reference to `boost::program_options::abstract_variables_map::operator[](std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
    collect2: error: ld returned 1 exit status
    Makefile:46: recipe for target 'vw' failed
    make[1]: *** [vw] Error 1
    make[1]: Leaving directory 'install_dir/vowpal_wabbit/python/src/vowpalwabbit'
    Makefile:97: recipe for target 'vw' failed
    make: *** [vw] Error 2
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "install_dir/vowpal_wabbit/python/setup.py", line 211, in <module>
        tests_require=['tox']
      File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
```

**Comment by arielf** [comment]
Looks like you're missing the boost program-options developer prereq

As the [Tutorial](https://github.com/JohnLangford/vowpal_wabbit/wiki/Tutorial) suggests:

     sudo apt install libboost-program-options-dev libboost-python-dev

or more generally all of boost dev (just in case):

    sudo apt install libboost-all-dev

**Comment by charlescearl** [comment]
I have done this install and get the same result.

**Comment by arielf** [comment]
Did you rebuild everything from scratch after installing libboost? You must rebuild from scratch since the `Makefile`s don't include dependencies on the system.  This means you must `make clean` and rebuild everything Including the library `libvw.a` after installing the boost dev prereqs.

The undefined symbols errors clearly point at the appropriate `libboost` headers missing in the environment you're building.

It is possible that you are missing them in your python3 env. Are you using some non standard setting (virtualenv etc) or the default system python3?

Also, you're running `pip` and it isn't clear if this is the python3 `pip` or the python2 one?

These can help:

    head -1 `which pip`
    which python
    $(head -1 $(which pip) | sed 's/#!//') --version

This critical point (from the errors) is that your build of the library didn't include the required `libboost` parts to get a functioning `vw` runtime.

Before going to `pip`.  Have you tried the standard vanilla builds like:
    make all
    make python
    make test
?

**Comment by charlescearl** [comment]
Ariel,
I ended up starting over  from scratch by cloning the repo into a different directory.

I ran `./autogen.sh` in the repo top level directory.

Then

```
make all
```

works. Further,

 ```
make test
```

succeeds:

```
RunTests runtime: user 12.28, system 1.17, total 13.45 sec (+0.00% vs. last)
```

My computer's  default python is `python Python 2.7.6rc1`.


You are right that my initial error report was based on doing the install inside of a virtual environment created by running:

```
virtualenv --python=/usr/bin/python3.6 vw_venv
```

When I compile within this virtualenv

```
make all
```

succeeds: 

```
make[1]: Leaving directory '/media/Hadoop2/vowpal_wabbit/library'
make[1]: Entering directory '/media/Hadoop2/vowpal_wabbit'
make[1]: Nothing to be done for 'all-am'.
make[1]: Leaving directory '/media/Hadoop2/vowpal_wabbit'
(vw_venv)charles@azad:/media/Hadoop2/vowpal_wabbit$ head -1 `which pip`
#!/media/Hadoop2/vw_venv/bin/python3.6
(vw_venv)charles@azad:/media/Hadoop2/vowpal_wabbit$ which python
/media/Hadoop2/vw_venv/bin/python
(vw_venv)charles@azad:/media/Hadoop2/vowpal_wabbit$ python
Python 3.6.2 (default, Jul 20 2017, 08:43:29) 
[GCC 5.4.1 20170519] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
(vw_venv)charles@azad:/media/Hadoop2/vowpal_wabbit$ $(head -1 $(which pip) | sed 's/#!//') --version
Python 3.6.2
```

I noticed in the Makefile in `vowpal_wabbit/python/` the paths to the libraries are different from
the ones in my directory structure post-compile. My libraries are located in the `vowpalwabbit/.libs` directory after running `make all` from `vowpal_wabbit`.

However, in the `vowpal_wabbit/python/Makefile`, the libraries are assumed to be in `vowpalwabbit` (e.g. `vowpalwabbit/libvw.a`).

If I change the paths manually in the `vowpal_wabbit/python/Makefile` and attempt to make the `pylibvw` inside of the python directory,

```
(vw_venv)charles@azad:/media/Hadoop2/vowpal_wabbit/python$ make clean
rm -f *.o pylibvw.so
(vw_venv)charles@azad:/media/Hadoop2/vowpal_wabbit/python$ PYTHON_VERSION=3.6 PYTHON_LIBS="-l boost_python-py36" make things
Using Python 3.6
g++ -std=c++0x -I/usr/include/python3.6m -I/usr/include/python3.6m  -I ../rapidjson/include -fPIC -c pylibvw.cc -o pylibvw.o
g++ -shared -Wl,--export-dynamic pylibvw.o  -L/usr/lib/python3.6/config-3.6m-x86_64-linux-gnu -L/usr/lib -lpython3.6m -lpthread -ldl  -lutil -lm  -Xlinker -export-dynamic -Wl,-O1 -Wl,-Bsymbolic-functions ../vowpalwabbit/.libs/libvw.a ../vowpalwabbit/.libs/liballreduce.a   -l boost_python-py36 -o pylibvw.so
/usr/bin/ld: ../vowpalwabbit/.libs/libvw.a(global_data.o): relocation R_X86_64_32 against `_ZSt4cerr' can not be used when making a shared object; recompile with -fPIC
../vowpalwabbit/.libs/libvw.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
Makefile:55: recipe for target 'pylibvw.so' failed
make: *** [pylibvw.so] Error 1

```

Hopefully this gives a hint to where I've gone wrong.

Thanks again!

**Comment by arielf** [comment]
I you see a mention of `.libs` anywhere, it means you're using `libtool` and your Ubuntu/Debian build is already broken.

Please don't use `autogen.sh` on Ubuntu. It is not needed and it is actually destructive.
(overwrites all original Makefiles with a lot of unneeded and brittle, extra-complexity).

Since your `Makefile`s are now broken, try:

    git checkout Makefile */Makefile

to restore your original `Makefile`s, then follow with a simple `make` (and `make test` etc.) instead.
HTH.

**Comment by arielf** [comment]
Also note that your default python is old.

If you do a simple auto upgrade to Ubuntu (apt update && apt upgrade, possibly with apt dist-upgrade), you should end up with the current stable long-term-support versions:

    Ubuntu 16.04.3 LTS
    Python 2.7.12

**Comment by charlescearl** [comment]
I really do appreciate your help and time Ariel!

The versions of Ubuntu and Python are now all updated, the latest versions of boost and boot-program options are installed but the compile fails at the same step. I'll continue searching for what might be the issue.

```
charles@azad:/media/Hadoop2/vowpal_wabbit$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
charles@azad:/media/Hadoop2/vowpal_wabbit$ head -1 `which pip`
#!/usr/bin/python
charles@azad:/media/Hadoop2/vowpal_wabbit$  $(head -1 $(which pip) | sed 's/#!//') --version
Python 2.7.12
charles@azad:/media/Hadoop2/vowpal_wabbit$ sudo apt install libboost-program-options-dev libboost-python-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libboost-program-options-dev is already the newest version (1.58.0.1ubuntu1).
libboost-python-dev is already the newest version (1.58.0.1ubuntu1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
charles@azad:/media/Hadoop2/vowpal_wabbit$ sudo apt install libboost-all-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libboost-all-dev is already the newest version (1.58.0.1ubuntu1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

```

But same compilation errors from clean repo:
```
./libvw.a(search_graph.o): In function `GraphTask::initialize(Search::search&, unsigned long&, boost::program_options::variables_map&)':
search_graph.cc:(.text+0x18c0): undefined reference to `boost::program_options::options_description::options_description(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int, unsigned int)'
search_graph.cc:(.text+0x1b73): undefined reference to `boost::program_options::abstract_variables_map::operator[](std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
./libvw.a(scorer.o): In function `scorer_setup(vw&)':
scorer.cc:(.text+0x2bf): undefined reference to `boost::program_options::options_description::options_description(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int, unsigned int)'
scorer.cc:(.text+0x381): undefined reference to `boost::program_options::abstract_variables_map::operator[](std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
collect2: error: ld returned 1 exit status
Makefile:46: recipe for target 'vw' failed
make[1]: *** [vw] Error 1
make[1]: Leaving directory '/media/Hadoop2/vowpal_wabbit/vowpalwabbit'
Makefile:97: recipe for target 'vw' failed
make: *** [vw] Error 2
```

Maybe there is a path or environment variable that I need to set before make?

**Comment by charlescearl** [comment]
Here is another thought. I am attempting to run from a dockerfile specification.
Here are the installs added to a 16.04.3 container.
Are there packages listed that strike you as problematic or incomplete?

```
RUN apt-get -y update
RUN apt-get -y install software-properties-common
RUN add-apt-repository -y ppa:jonathonf/python-3.6
RUN apt-get -y update
RUN apt-get -y install wget git python make build-essential
RUN apt-get -y install python3.6 python3.6-venv python3.6-dev
RUN apt-get -y install python-dev python-pip virtualenv
RUN apt-get -y install libpython3-all-dev libpython3.6
RUN apt-get -y install gfortran libatlas-base-dev
RUN apt-get -y install liblapacke-dev libboost-program-options-dev libboost-python-dev
RUN apt-get -y install zlib1g-dev libffi-dev
RUN apt-get -y install libncurses5-dev
```

**Comment by charlescearl** [comment]
When I installed the latest boost 1.64 from source, the compilation succeeds. The boost library that installs with ubuntu is 1.58, so I am assuming this is out of date.

**Comment by arielf** [comment]
You may use any version of libboost_program_options you want as long as:
- You build everything (library, vw, python extensions) with exactly the same version (you need to start from scratch, i.e. `make clean` every time you want to upgrade)
- Your virtualenv/docker-container/whatever uses the same runtime version as the one you built with

The last error means you're not running the same version as when you build. There's a program called `ldd` (list dynamic dependencies) which can be helpful here. e.g.:

    ldd /vowpalwabbit/vw | grep program_options

The fundamental issue is inconsistency between environments.

Although not a recommended practice, sometimes symlinking of what library is being looked for and the actual version that's installed in the runtime-env can help resolve such issues.

HTH.

**Comment by charlescearl** [comment]
Ok, something seems off with my paths, `LD_LIBRARY_PATH=/usr/local/lib make test` works. The python library works for 3.6 as well.
Thanks again.

**Comment by arielf** [comment]
Thanks for figuring this out.  I had a feeling it is a localized issue.

Setting `LD_LIBRARY_PATH` to anything (let alone something non-standard) can definitely mess-up things.  In the name of simplicity and consistency, I always recommend against it.
