### ISSUE TITLE
Python: get action and probabilities for cb_explore_adf

### ISSUE THREAD

**Issue by dahernan** [JohnLangford/vowpal_wabbit#1346]
Hi, I'm experimenting with the python wrapper and vw daemon for action dependent contextual bandits.

Given this example on daemon mode `$ vw --cb_explore_adf --daemon`
```
shared | u1
| a
1:-1:0.5 | b
```
I get action and probabilities from the socket
```
$ cat example.txt  | netcat localhost 26542
0:0.975,1:0.025
```
When I send a prediction like:
```
shared | u1
| a
| b
```
```
$ cat p.txt | netcat localhost 26542
1:0.975,0:0.025
```
So far so good, I get the action and the probabilities :)

If I translate that toy example to Python (examples are the same), I have this code:
```
from vowpalwabbit.pyvw import vw

model = vw(cb_explore_adf=True, quiet=True)
model.learn("shared | u1\r\n| a\r\n1:-1:0.5 | b\r\n\r\n")

pred = model.predict("shared | u1\r\n| a\r\n| b\r\n\r\n")

In [28]: pred
Out[28]: []
```
Notice that the predictions are empty, so I tried to use the `example` class with all of the types (`pMULTILABELS` seems the one that it should work to me) but none of types (vw.pACTION_PROBS     vw.pMULTICLASS, vw.pMULTILABELS, ...) return the actions and probabilities:
```
ex = model.example("shared | u1\r\n| a\r\n| b\r\n\r\n")
model.predict(ex, prediction_type=vw.pMULTILABELS)
Out[41]: []
```

Is it a bug? is this feature not yet supported? or a I doing something wrong?
Thanks a lot

**Comment by JohnLangford** [comment]
This is an unexpected behavior more than a bug.   

In essence, there is a bit of a hack in VW for action dependent features: each action comes in as a different example and then the internal reduction assembles a collection of examples and operates on that.  So, call learn() multiple times once with each line and then examine the output.

**Comment by JohnLangford** [comment]
(closing for now)

**Comment by MelanieFreed** [comment]
Just saw this post and I'm trying to do this exact thing now.  I tried to call learn multiple times on each line of the example and then predict, but I'm still not seeing anything in the output.  Am I doing something wrong still?

```
from vowpalwabbit import pyvw

model = pyvw.vw("--cb_explore_adf --epsilon 0.05 -q sd --quiet")

event_line1 = 'shared |s a b c'
event_line2 = ' |d dummy1'
event_line3 = '0:1.0:0.5 |d dummy2'
model.learn(event_line1)
model.learn(event_line2)
model.learn(event_line3)

event_line1 = 'shared |s a b c'
event_line2 = ' |d dummy1'
event_line3 = ' |d dummy2'
print('Predict Line 1: ', model.predict(event_line1))
print('Predict Line 2: ', model.predict(event_line2))
print('Predict Line 3: ', model.predict(event_line3))

event = 'shared |s a b c\r\n |d dummy1\r\n |d dummy2'
print('Predict All Lines: ', model.predict(event))

model.finish()
```

produces the following output:
```
Predict Line 1:  []
Predict Line 2:  []
Predict Line 3:  []
Predict All Lines:  []
```

**Comment by matanster** [comment]
@MelanieFreed did you ultimately spot the issue?

**Comment by MelanieFreed** [comment]
Hi @matanster !  I wasn't able to get that working, but from what I understand this pull request was supposed to allow for multiline examples natively: https://github.com/JohnLangford/vowpal_wabbit/pull/1467
That pull request has already been merged, so it's probably already working, but I haven't had a chance to test it out myself yet...

**Comment by jackgerrits** [comment]
Currently, in order to predict/learn using a multiline example in Python a list of examples needs to be passed to the appropriate call. I have a PR out right now that fixes this limitation and the entire example in string form can be passed to the call (#1809).

Current usage:
```
from vowpalwabbit import pyvw

model = pyvw.vw("--cb_explore_adf --epsilon 0.05 -q sd --quiet")

examples = [example('shared |s a b c'), example('|d dummy1'), example('0:1.0:0.5 |d dummy2')]
model.learn(examples)
print(model.predict(examples))

model.finish()
```

After #1809 merged:
```
from vowpalwabbit import pyvw

model = pyvw.vw("--cb_explore_adf --epsilon 0.05 -q sd --quiet")

event = 'shared |s a b c\r\n |d dummy1\r\n |d dummy2'
model.learn(event)
print('Predict All Lines: ', model.predict(event))

model.finish()
```
