### ISSUE TITLE
Is VW Thread Safe ?

### ISSUE THREAD

**Issue by apoorvreddy** [JohnLangford/vowpal_wabbit#1350]
Hi @JohnLangford,

I am using the VW apis in a C++ code, and was wondering about the current status of thread safety in VW.

This is what I'm doing now.

``` c++
  std::string vw_arg = "-t -i vw.model";
  VW_HANDLE vw = VW_InitializeA(vw_arg.c_str());
````

And then passing the vw handle to different threads which do a read_example, predict and finish_example.

I believe read_example is currently not thread safe . Specifically, lines [790, 791, and 792](https://github.com/JohnLangford/vowpal_wabbit/blob/master/vowpalwabbit/parser.cc#L790) in parser.cc .

I see that these 3 lines are being called after a get_unused_example call, which returns the pointer to a pre-allocated example struct. And get_unused_example seems to be thread safe. 

Is moving these 3 lines from read_example to get_unused_example a viable solution to this ?

Highly appreciate your recommendation/input here John !

**Comment by JohnLangford** [comment]
It's definitely not a solution.

In essence, the reduction stack in VW was not designed to be thread safe
and there are numerous operations in the stack which will barf badly in a
multithreaded environment.

What you _can_ do is have multiple VW objects which share the same
underlying model then impose whatever locking is desired on updates to that
model.  Is that adequate for what you need?

-John

**Comment by apoorvreddy** [comment]
I only need to serve predictions in a multi-threaded setup. Training of the neural net happens offline. 

So even prediction may not be thread safe, is that right ?

What you've suggested is something we've considered. We have about 200 threads, and that would mean, instantiating 200 models then, which we were trying to avoid.

**Comment by JohnLangford** [comment]
If they are the _same_ model, then the model can be fully shared.
Essentially, instead of initializing a VW object with a commandline you can
initialize with a different VW object.  If each thread has one of these VW
objects, then each thread can make predictions independently and without
interference.   The memory footprint is model size + 200 * reduction stack
size.

In linux (only) there is also a different way to achieve the same effect.
In essence, you can instantiate the model in a named piece of memory and
create the VW objects independently.

-John

**Comment by apoorvreddy** [comment]
They're indeed the same model.

This is what I'm doing now.

Each thread in the threadpool will have a getOrCreateVWModel() method, which will essentially instantiate a VW model using VW_InitializeA().

Is there a better way (fully shared) that you're pointing to ? Which API function in vwdll.h should I use for the same ? Is it VW_CopyModelData or VW_InitializeWithModel ?

**Comment by JohnLangford** [comment]
You want VW_InitializeWithModel.

-John

**Comment by apoorvreddy** [comment]
Thanks John ! This is very helpful :)

**Comment by sb2324** [comment]
Hi @JohnLangford,
we are creating VW object for each through using below code and store in shared memory along with thread number. Using thread number, corresponding thread will get the VW object for processing.

for(i =0; i <(int32_t) <number of thread>;i++)   --> currently we are using number of thread as 80
{
std::string vw_arg = "-t";
VW_HANDLE handle = VW_InitializeWithModel(vw_arg.c_str(),fileDataPtr->neural_network_model,size_of_model);
memDataPtr->handle = handle;
memDataPtr->thread_id = i;
}

During next model load, we are releasing the memory which we have taken earlier using below code:

for(i =0; i <(int32_t) <number of thread>;i++) 
{
   VW_Finish(memDataPtr->handle); 
   memDataPtr->handle = NULL;
  increate pointer memDataPtr to point on next one
}

it is working fine but after 3 -4 model load, we are getting out of memory error. I am suspecting that VW_Finish() is not releasing the memory properly.

Could you please have a look and suggest?

Thank You.
Saurabh

**Comment by apoorvreddy** [comment]
Hi @JohnLangford 

I'm unable to figure out how the model can be fully shared. Below are three snippets of code that I've tried.

```
    std::string vw_arg = "-t -i model_02-10-2017_08-10-2017";
    int num_models = 400;
    std::vector<VW_HANDLE> handle_vec;
    for (int i=0; i<num_models; i++) {
      handle_vec.push_back(VW_InitializeA(vw_arg.c_str()));
   }
```
AND

```  std::ifstream is("model_02-10-2017_08-10-2017", std::ifstream::binary);
   char *buffer; int bufferLength;

  if (is) {
    is.seekg(0, is.end);
    int bufferLength = is.tellg(); // length of file
    is.seekg(0, is.beg);
    buffer = new char[bufferLength];
    is.read(buffer, bufferLength);

    // initialize VW model from buffer
    std::string vw_arg = "-t";

    int num_models = 400;
    std::vector<VW_HANDLE> handle_vec;

    for (int i=0; i<num_models; i++) {
      handle_vec.push_back(VW_InitializeWithModel(vw_arg.c_str(), buffer, bufferLength));
    }
```

AND

```  std::string vw_arg = "-t -i model_02-10-2017_08-10-2017";

  VW_HANDLE common_model = VW_InitializeA(vw_arg.c_str());
  VW_IOBUF outputBufferHandle;

  char* outputData;
  size_t outputSize;
  VW_CopyModelData(common_model, &outputBufferHandle, &outputData, &outputSize);
  
  int num_models = 399;
  std::vector<VW_HANDLE> handle_vec;

  for (int i=0; i<num_models; i++) {
    handle_vec.push_back(VW_InitializeWithModel("-t", (char*)outputData, outputSize));
  }
```


All 3 of the above snippets take around the same memory. ~793MB. What am I doing wrong ? Could you provide an example snippet which demonstrates model sharing ?
