### ISSUE TITLE
Contextual bandit probabilities

### ISSUE THREAD

**Issue by kovacspeter** [JohnLangford/vowpal_wabbit#1352]
Hello,
I am trying to train and deploy contextual bandit. However I am struggling with getting probability from bandit. Can you point me in the right direction? I need probability in order to log it and let the model improve over time.

From what I have read through multiple threads I found out that deployed model does not explore by default. Does that mean I need to do exploration and log probability of exploration strategy? How does that play with --bag option when model is deployed? 

I am bit confused with this - I am using standard cb, not cb_adf. 

To make the question clear, can you please explain how is the probability handled and how should I log it correctly?

Thanks for help.

**Comment by JohnLangford** [comment]
You want to use --cb_explore (which explores and learns from exploration) not --cb (which just learns from exploration).   And, you'll probably want to manipulate the choice of exploration algorithms.  Use --help to see them.

You may also want to consider playing with the decision service (http://ds.microsoft.com or http://aka.ms/mwt )  See also the real world interactive learning tutorial (http://hunch.net/~rwil ).
