### ISSUE TITLE
Dead links in wiki

### ISSUE THREAD

**Issue by FintanH** [JohnLangford/vowpal_wabbit#1358]
I was reading through the [wiki on JSON](https://github.com/JohnLangford/vowpal_wabbit/wiki/JSON) and saw that the following two links were dead:

- [SimpleLabel](https://github.com/JohnLangford/vowpal_wabbit/blob/master/cs/cs/Labels/SimpleLabel.cs)

- [ContextualBanditLabel](https://github.com/JohnLangford/vowpal_wabbit/blob/master/cs/cs/Labels/ContextualBanditLabel.cs)

**Comment by JohnLangford** [comment]
@eisber fixable?

**Comment by eisber** [comment]
fixed it. got moved to C++/CLI

**Comment by FintanH** [comment]
Thanks, much appreciated :)

**Comment by JohnLangford** [comment]
Thanks Markus!
