### ISSUE TITLE
Multiline example information

### ISSUE THREAD

**Issue by FintanH** [JohnLangford/vowpal_wabbit#1359]
I was trying to find more information on the multiline examples mentioned in the [JSON wiki](https://github.com/JohnLangford/vowpal_wabbit/wiki/JSON) and briefly [here](https://github.com/JohnLangford/vowpal_wabbit/wiki/Contextual-Bandit-algorithms) but I'm not sure what the example is saying. Is there somewhere else where there's more information? Or should a more detail explanation be added somewhere?

Thanks!

**Comment by JohnLangford** [comment]
There are examples in the test cases here:
https://github.com/JohnLangford/vowpal_wabbit/blob/master/test/RunTests
(search for ldf).   You might also look into the NAACL-HTL tutorial here:
http://hunch.net/~l2s

-John

**Comment by FintanH** [comment]
Thanks John, appreciate the pointers! If I glean some more understanding I'll be sure to add it to the wiki :)
