### ISSUE TITLE
VW crashes with cb_adf data if --cb_adf is missing

### ISSUE THREAD

**Issue by eisber** [JohnLangford/vowpal_wabbit#1363]
Run vw --dsjon <filename>

Data file contents

{"_label_cost":0,"_label_probability":0.8166667,"_label_Action":3,"_labelIndex":2,"Timestamp":"2017-09-26T00:00:01.0450000Z","Version":"1","EventId":"fb4403347be44015bdbac712af614c04","a":[3,7,6,10,12,2,9,4,11,1,5,8],"c":{"_synthetic":false,"User":{"_age":0},"Geo":{"country":"United States","_countrycf":"8","state":"Illinois","city":"Chicago","_citycf":"8","dma":"602"},"MRefer":{"referer":"http://www.complex.com/"},"OUserAgent":{"_ua":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36","_DeviceBrand":"","_DeviceFamily":"Other","_DeviceIsSpider":false,"_DeviceModel":"","_OSFamily":"Mac OS X","_OSMajor":"10","_OSPatch":"5","DeviceType":"Desktop"},"_multi":[{"_tag":"cmplx$http://www.complex.com/music/2017/09/cardi-b-bodak-yellow-number-1-billboard-hot-100","i":{"constant":1,"id":"cmplx$http://www.complex.com/music/2017/09/cardi-b-bodak-yellow-number-1-billboard-hot-100"},"j":[{"_title":"Cardi B's \"Bodak Yellow\" Is Now the No. 1 Song in the Country"},{"RVisionTags":{"person":0.984984756,"dress":0.5922509},"SVisionAdult":{"isAdultContent":false,"isRacyContent":false,"adultScore":0.0346108824,"racyScore":0.273494631},"_expires":"2017-09-28T16:28:28.7213717Z"},{"Emotion0":{"anger":0.0172427054,"contempt":0.0003847821,"disgust":0.0230322219,"fear":0.000110577595,"happiness":0.000635253266,"neutral":0.05454834,"sadness":0.00132795714,"surprise":0.9027182},"_expires":"2017-09-28T16:28:28.1378308Z"},{"Tags":{"Record chart":0.19,"United States":0.245,"Twitter Inc.":0.99,"Billboard Hot 100":0.132,"Taylor Swift":0.052,"MTV":1,"MTV Video Music Award":1,"Colin Kaepernick":0.975,"Atlantic Records":0.897,"Latin music (genre)":0.012,"The New York Times":0.987,"Don't (Ed Sheeran song)":0.102,"Doo Wop (That Thing)":0.004,"J. Cole":0.786,"In America":0.009},"_expires":"2017-09-28T16:28:28.0440616Z"},{"XSentiment":1,"_expires":"2017-09-28T16:28:28.0440616Z"},null,null]},{"_tag":"cmplx$http://www.complex.com/life/2017/09/these-protests-are-about-the-repeated-murders-of-black-people","i":{"constant":1,"id":"cmplx$http://www.complex.com/life/2017/09/these-protests-are-about-the-repeated-murders-of-black-people"},"j":[{"_title":"The NFL Protests Are About Police Murdering Black People, Not Donald F*cking Trump"},{"RVisionTags":{"person":0.995686531},"SVisionAdult":{"isAdultContent":false,"isRacyContent":false,"adultScore":0.0127855418,"racyScore":0.0224091616},"_expires":"2017-09-28T19:41:11.4522562Z"},{"Emotion0":{"anger":0.0005015747,"contempt":0.00188910356,"disgust":8.319106E-05,"fear":0.0008591237,"happiness":0.65593195,"neutral":0.329581171,"sadness":0.0104280505,"surprise":0.0007258306},"_expires":"2017-09-28T19:41:10.7283092Z"},{"Tags":{"National Football League":1,"The Police":0.067,"Black":0.458,"Donald Trump":0.999,"Twitter Inc.":1,"Colin Kaepernick":0.983,"The Star-Spangled Banner":0.152,"September 1":0.004,"To Me":0.003,"African American":0.577,"United States presidential election, 2016":0.878,"The Guardian":0.78,"Jessica Williams":0.013,"United States":1,"J. Cole":0.129,"Stephen Curry":0.006,"Marshawn Lynch":0.43,"Kid Rock":0.28,"Ray Lewis":0.43,"American Civil Liberties Union":0.882,"First Amendment to the United States Constitution":0.971,"Ku Klux Klan":1,"President of the United States":1,"Nazi Germany":0.176,"Charlottesville":0.06,"Russell Simmons":0.909,"Google":0.679,"Call Me":0.005,"Shooting of Trayvon Martin":0.004,"James Brown":0.015,"Death of Sandra Bland":0.031,"Sean Bell shooting incident":0.028,"Death of Eric Garner":0.718,"Shooting of Tamir Rice":0.538,"Death of Freddie Gray":0.603,"Bill Nunn":0.998,"Do the Right Thing":0.042,"Spike Lee":0.236,"Black Lives Matter":1,"White American":0.019,"New Jersey":1},"_expires":"2017-09-28T19:41:11.5147501Z"},{"XSentiment":0,"_expires":"2017-09-28T19:41:10.9158017Z"},null,null]},{"_tag":"cmplx$http://www.complex.com/music/2017/09/kodak-black-wild-n-out-performance-explanation","i":{"constant":1,"id":"cmplx$http://www.complex.com/music/2017/09/kodak-black-wild-n-out-performance-explanation"},"j":[{"_title":"Kodak Black Reveals Why He Walked Out on 'Wild 'N Out Live' Performance"},{"RVisionTags":{"person":0.999836564,"crowd":0.0119169811},"SVisionAdult":{"isAdultContent":false,"isRacyContent":false,"adultScore":0.0463238433,"racyScore":0.0896813},"_expires":"2017-09-28T22:44:26.4211944Z"},{"Emotion0":{"anger":0.00349947438,"contempt":0.0155803207,"disgust":0.0008975146,"fear":0.000109224275,"happiness":0.150062934,"neutral":0.8235158,"sadness":0.005673473,"surprise":0.0006612703},"Emotion1":{"anger":0.00384218222,"contempt":0.006824347,"disgust":0.00495244749,"fear":0.000425022561,"happiness":0.78920114,"neutral":0.1836214,"sadness":0.009840846,"surprise":0.0012926145},"_expires":"2017-09-28T22:44:25.607835Z"},{"Tags":{"Kodak Black":0.041,"Wild 'n Out":0.964,"Concert":0.674,"Twitter Inc.":0.999,"Gerardo MejÃ­a":0.02,"Mora":0.005,"Nick Cannon":0.939,"Demetri Martin":0.01,"MTV":0.931,"Hitman":0.005,"Holla":0.014,"Orlando":0.998,"Tropical cyclone":0.961,"Florida":0.989,"Disc jockey":0.943,"Eastman Kodak":0.463,"Extra":0.022,"Pacific Time Zone":0.625,"Lyricist":0.149,"Hip hop music":0.999,"Unincorporated area":0.071,"Bigotry":0.003},"_expires":"2017-09-28T22:44:26.0774251Z"},{"XSentiment":0,"_expires":"2017-09-28T22:44:25.607835Z"},null,null]},{"_tag":"cmplx$http://www.complex.com/life/2017/09/these-protests-are-about-the-repeated-murders-of-black-people","i":{"constant":1,"id":"cmplx$http://www.complex.com/life/2017/09/these-protests-are-about-the-repeated-murders-of-black-people"},"j":[{"_title":"The NFL Protests Are About Police Murdering Black People, Not Donald F*cking Trump"}]},{"_tag":"cmplx$http://www.complex.com/sports/2017/09/drake-lebron-james-on-vince-carter-influence","i":{"constant":1,"id":"cmplx$http://www.complex.com/sports/2017/09/drake-lebron-james-on-vince-carter-influence"},"j":[{"_title":"Drake and LeBron James Break Down Vince Carter's Influence"},{"RVisionTags":{"person":0.9970636,"man":0.9959488,"wall":0.9846848,"indoor":0.9207894,"standing":0.9146376,"posing":0.4865047},"SVisionAdult":{"isAdultContent":false,"isRacyContent":false,"adultScore":0.009159397,"racyScore":0.013163521},"_expires":"2017-09-28T21:59:21.5357923Z"},{"Emotion0":{"anger":1.11920253E-05,"contempt":0.008565833,"disgust":0.000125469422,"fear":8.95339E-06,"happiness":0.924238265,"neutral":0.06555684,"sadness":0.0009425647,"surprise":0.00055085955},"Emotion1":{"anger":2.61620953E-05,"contempt":2.631442E-06,"disgust":6.10639763E-05,"fear":7.792836E-09,"happiness":0.9999085,"neutral":9.847357E-07,"sadness":7.949086E-08,"surprise":5.835768E-07},"_expires":"2017-09-28T21:59:20.8795431Z"},{"Tags":{"Drake":0.991,"LeBron James":1,"Vince Carter":1,"Complex":0.531,"Twitter Inc.":1,"Cleveland Cavaliers":1,"Chris Bosh":1,"Toronto International Film Festival":0.613,"Toronto Raptors":1,"UNK NBA":1,"Ohio":1,"Akron":0.999,"New York Knicks":0.992},"_expires":"2017-09-28T21:59:20.863867Z"},{"XSentiment":1,"_expires":"2017-09-28T21:59:20.9107387Z"},null,null]},{"_tag":"cmplx$http://www.complex.com/music/2017/09/travis-scott-astroworld-tour-amusement-park-rides","i":{"constant":1,"id":"cmplx$http://www.complex.com/music/2017/09/travis-scott-astroworld-tour-amusement-park-rides"},"j":[{"_title":"Travis Scott's 'AstroWorld' Tour Will Feature Amusement Park Rides"},{"RVisionTags":{"person":0.999199569},"SVisionAdult":{"isAdultContent":false,"isRacyContent":true,"adultScore":0.07320101,"racyScore":0.333475918},"_expires":"2017-09-28T21:28:05.4787622Z"},{"_expires":"2017-09-28T21:28:05.0100028Z"},{"Tags":{"Travis Scott":0.959,"Six Flags AstroWorld":0.855,"Amusement park":0.958,"Twitter Inc.":0.999,"Rolling Stone":1,"Kendrick Lamar":0.034,"Texas":0.999,"Shuttle Loop":0.007,"Superman":0.038,"Migos":0.424,"Metro Boomin":0.315,"Miguel":0.098},"_expires":"2017-09-28T21:28:04.9631056Z"},{"XSentiment":1,"_expires":"2017-09-28T21:28:04.9787518Z"},null,null]},{"_tag":"cmplx$http://www.complex.com/life/2017/09/donald-trump-only-supports-free-speech-when-its-white-people-speaking","i":{"constant":1,"id":"cmplx$http://www.complex.com/life/2017/09/donald-trump-only-supports-free-speech-when-its-white-people-speaking"},"j":[{"_title":"Donald Trump Only Supports Free Speech When It's White People Speaking"},{"RVisionTags":{"person":0.9994431,"man":0.987674057,"suit":0.888780653,"wearing":0.84287,"necktie":0.224700227,"older":0.210475653},"SVisionAdult":{"isAdultContent":false,"isRacyContent":false,"adultScore":0.008164651,"racyScore":0.008781098},"TVisionCelebrities":{"Donald J. Trump":0.999974966},"_expires":"2017-09-28T20:38:29.9472676Z"},{"Emotion0":{"anger":0.08966372,"contempt":0.008177046,"disgust":0.012194341,"fear":0.002226274,"happiness":4.87845E-05,"neutral":0.802652359,"sadness":0.08251124,"surprise":0.00252623577},"_expires":"2017-09-28T20:38:27.6927453Z"},{"Tags":{"Donald Trump":0.998,"White people":0.28,"Twitter Inc.":1,"President of the United States":1,"National Football League":1,"September 23":0.096,"Flag of the United States":0.525,"United States":1,"The Star-Spangled Banner":0.058,"Colin Kaepernick":0.699,"First Amendment to the United States Constitution":0.377,"National flag":0.029,"Stephen Curry":0.992,"Golden State Warriors":1,"Puerto Rico":0.403,"ESPN":1,"Jemele Hill":0.281,"September 11 attacks":1,"White House Press Secretary":0.094,"Quit Digging Your Grave with a Knife and Fork":0.005,"NASCAR":1,"Google":0.573,"Berkley":0.004,"Breitbart News Network":0.013,"Milo Yiannopoulos":0.639,"University of California, Berkeley":1,"Boston Celtics":0.747,"Charlottesville":0.474,"Baltimore":0.899,"Racism":0.95,"Complex":0.335},"_expires":"2017-09-28T20:38:28.0436243Z"},{"XSentiment":0.9999878,"_expires":"2017-09-28T20:38:27.7552452Z"},null,null]},{"_tag":"cmplx$http://www.complex.com/sports/2017/09/life-at-complex-euro-step-king","i":{"constant":1,"id":"cmplx$http://www.complex.com/sports/2017/09/life-at-complex-euro-step-king"},"j":[{"_title":"#LifeAtComplex: Learning How to Do a Proper Euro Step"},{"RVisionTags":{"person":0.997936368,"indoor":0.949007332},"SVisionAdult":{"isAdultContent":false,"isRacyContent":false,"adultScore":0.04012267,"racyScore":0.0322986133},"_expires":"2017-09-28T21:53:22.7104848Z"},{"Emotion0":{"anger":8.338652E-08,"contempt":1.85207156E-08,"disgust":4.11689243E-08,"fear":3.195116E-08,"happiness":0.999993,"neutral":3.68258543E-06,"sadness":2.33167555E-07,"surprise":2.88673687E-06},"Emotion1":{"anger":1.0597676E-05,"contempt":0.000106792926,"disgust":2.92443274E-05,"fear":5.446506E-05,"happiness":0.0018560997,"neutral":0.9653211,"sadness":0.00106734538,"surprise":0.03155431},"Emotion2":{"anger":0.315891534,"contempt":0.03859665,"disgust":0.19966644,"fear":0.000627219,"happiness":0.03433623,"neutral":0.394853681,"sadness":0.0106880162,"surprise":0.00534021},"_expires":"2017-09-28T21:53:22.5349585Z"},{"Tags":{"Complex":0.996,"Twitter Inc.":1,"Nike Air Max":0.014,"Google":0.981,"Michael Jordan":0.52,"Subscription business model":0.007,"YouTube":1,"Instagram":1,"Video Life":0.003},"_expires":"2017-09-28T21:53:21.7997292Z"},{"XSentiment":0.999622643,"_expires":"2017-09-28T21:53:21.7997292Z"},null,null]},{"_tag":"cmplx$http://www.complex.com/life/2017/09/donald-trump-only-supports-free-speech-when-its-white-people-speaking","i":{"constant":1,"id":"cmplx$http://www.complex.com/life/2017/09/donald-trump-only-supports-free-speech-when-its-white-people-speaking"},"j":[{"_title":"Donald Trump Only Supports Free Speech When It's White People Speaking"}]},{"_tag":"cmplx$http://www.complex.com/sneakers/2017/09/life-at-complex-vans-giveaway","i":{"constant":1,"id":"cmplx$http://www.complex.com/sneakers/2017/09/life-at-complex-vans-giveaway"},"j":[{"_title":"#LifeAtComplex: Tony Gives Away 1 of 1 Customized Vans"},{"RVisionTags":{"outdoor":0.9805244,"person":0.952215254},"SVisionAdult":{"isAdultContent":false,"isRacyContent":false,"adultScore":0.137164429,"racyScore":0.194602177},"_expires":"2017-09-28T17:32:23.5544403Z"},{"Emotion0":{"anger":0.0008834338,"contempt":0.002739376,"disgust":0.004593716,"fear":0.00035481088,"happiness":0.000211200721,"neutral":0.932992041,"sadness":0.0538368262,"surprise":0.00438859966},"_expires":"2017-09-28T17:32:23.0075365Z"},{"Tags":{"Vans":0.076,"Complex":0.996,"Twitter Inc.":1,"New York City":0.964,"Big Apple":0.016,"Subscription business model":0.02,"YouTube":1,"Instagram":0.998},"_expires":"2017-09-28T17:32:22.481893Z"},{"XSentiment":1,"_expires":"2017-09-28T17:32:22.6537874Z"},null,null]},{"_tag":"cmplx$http://www.complex.com/pop-culture/2017/09/blueprint-with-angie-nwandu","i":{"constant":1,"id":"cmplx$http://www.complex.com/pop-culture/2017/09/blueprint-with-angie-nwandu"},"j":[{"_title":"How The Shade Room's Angie Nwandu Reinvented Celebrity News and Gossip | Blueprint"}]},{"_tag":"cmplx$http://www.complex.com/music/2017/09/everyday-struggle-ep100-j-cole-nfl-boycott","i":{"constant":1,"id":"cmplx$http://www.complex.com/music/2017/09/everyday-struggle-ep100-j-cole-nfl-boycott"},"j":[{"_title":"Joe Budden and DJ Akademiks Discuss J. Cole's NFL Boycott on 'Everyday Struggle'"},{"RVisionTags":{"silhouette":0.1652744},"SVisionAdult":{"isAdultContent":false,"isRacyContent":false,"adultScore":0.02746914,"racyScore":0.038642168},"_expires":"2017-09-28T15:59:14.8842016Z"},{"Emotion0":{"anger":0.00273246132,"contempt":0.00576696126,"disgust":0.003048269,"fear":0.000822623435,"happiness":0.120170586,"neutral":0.7992291,"sadness":0.06771144,"surprise":0.000518575252},"_expires":"2017-09-28T15:59:13.73704Z"},{"Tags":{"Joe Budden":0.929,"Disc jockey":1,"J. Cole":0.65,"National Football League":1,"Everyday":0.008,"Complex":0.989,"Twitter Inc.":1,"Donald Trump":0.949,"Kylie Jenner":0.044,"Travis Scott":0.211,"Rapsody":0.008,"Kevin Gates":0.016,"Young Thug":0.646},"_expires":"2017-09-28T15:59:13.6433085Z"},{"XSentiment":0.00172495842,"_expires":"2017-09-28T15:59:13.6120362Z"},null,null]}]},"p":[0.816666663,0.0166666675,0.0166666675,0.0166666675,0.0166666675,0.0166666675,0.0166666675,0.0166666675,0.0166666675,0.0166666675,0.0166666675,0.0166666675],"VWState":{"m":"0ba34d278e2946d3addca366446b1f43/df6d05acc2774d599ff4e2f03f95d373"}}

**Comment by JohnLangford** [comment]
An invalid cast is occurring here: https://github.com/JohnLangford/vowpal_wabbit/blob/master/vowpalwabbit/parse_example_json.h#L416 

We should: 
a) Use l.cb rather than a cast 
https://github.com/JohnLangford/vowpal_wabbit/blob/master/vowpalwabbit/example.h#L35
b) The label type should be checked as per this line: https://github.com/JohnLangford/vowpal_wabbit/blob/master/vowpalwabbit/parse_example_json.h#L414

**Comment by JohnLangford** [comment]
I have a fix being checked in now.
