### ISSUE TITLE
Conda does not find boost, even when linked

### ISSUE THREAD

**Issue by franz101** [JohnLangford/vowpal_wabbit#1364]
Tried brew boost,
Macports boost,
conda install boost,

Boost seems to be installed but it can't be found,
even if the makefile is modified.

Any help or a fixed makefile would be appreciated...

**Comment by JohnLangford** [comment]
Unclear what's up here and hard to debug.

**Comment by franz101** [comment]
Found the solution with linux:
Here:
[https://github.com/JohnLangford/vowpal_wabbit/issues/1095#issuecomment-330327771](https://github.com/JohnLangford/vowpal_wabbit/issues/1095#issuecomment-330327771)

and 
Here:
And this fixed the lib error :)
[https://github.com/JohnLangford/vowpal_wabbit/issues/723#issuecomment-121450482](https://github.com/JohnLangford/vowpal_wabbit/issues/723#issuecomment-121450482)

Trying next week with mac

**Comment by JohnLangford** [comment]
This appears fixed in #1426 so closing for now.
