### ISSUE TITLE
Q: String Feature in JSON

### ISSUE THREAD

**Issue by FintanH** [JohnLangford/vowpal_wabbit#1365]
In the JSON input [examples](https://github.com/JohnLangford/vowpal_wabbit/wiki/JSON) there was an example given as:

```json
{
 "ns1":{"location":"New York"},
 "f2":[1,0.2,3]
} 
```
which translates to:
```
|ns1 New_York | :1 :.2 :.3
```
Is there a reason that it isn't:
```
|ns1 location:New_York | :1 :.2 :.3
```

The same goes for the rest of the examples.

**Comment by JohnLangford** [comment]
It does seem inconsistent.  @eisber can you comment?

**Comment by eisber** [comment]
the example is wrong. it's locationNew_York. will fix the wiki

**Comment by FintanH** [comment]
Sorry, I have a question regarding the change:
Why is `locationNew_York` instead of `location:New_York`? The numerical features are of the form `f1:2.5`

**Comment by arielf** [comment]
@FintanH Please see this answer: 
https://stackoverflow.com/questions/28640837/vowpal-wabbit-how-to-represent-categorical-features/28643968#28643968

**Comment by FintanH** [comment]
Awesome, thanks @arielf!
