### ISSUE TITLE
Current stable version?

### ISSUE THREAD

**Issue by ilovezfs** [JohnLangford/vowpal_wabbit#1371]
Based on https://github.com/JohnLangford/vowpal_wabbit/releases and https://github.com/JohnLangford/vowpal_wabbit/releases/latest I cannot tell if 8.4.0 or 8.5.0 is the current stable version.

Which version should be in Homebrew's stable spec? Thanks!

**Comment by JohnLangford** [comment]
8.5.0 is coming out today/yesterday.

-John

**Comment by JohnLangford** [comment]
(updated release notes)

**Comment by ilovezfs** [comment]
Thanks @JohnLangford! Voilà https://github.com/Homebrew/homebrew-core/pull/21299.
