### ISSUE TITLE
Unreasonable hash collisions for --nn and --cubic together [v 8.5]

### ISSUE THREAD

**Issue by ip01** [JohnLangford/vowpal_wabbit#1384]
Frequent, apparently unreasonable hash collisions occur when both --cubic and --nn (any number of nodes >=2) are set.
For example
`seq 1 13|sed 's/^/f/'|xargs|sed 's/^/1 |t /'|vw --cubic ttt --nn 2 --audit --quiet |fgrep 't^'|sed -n 2p|tr '\t' '\n'|fgrep 40637`
produces result
`t^f1*t^f7*t^f9:40637:1:0@0`
`t^f1*t^f12*t^f13:40637:1:0@0`

The effective feature space for cubic interactions of 13 variables, plus weights and biases of 2 neurons is little more than 3000.
Is there any reason for 18 bit hash to collide here?

**Comment by MLWave** [comment]
Check out the cute maths behind hash collisions probability (including the birthday paradox). With an 18 bit hash and 3000 items hashed, the probability of a collision approaches 1. (`0.99999996`).

You can get less chance of a collision by renaming your features to be numerical (then hashing is skipped and the number is directly used instead).

**Comment by JohnLangford** [comment]
MLWave seems right here.  13^3 = 2197 and the birthday paradox implies we
expect a collision if 2197^2 > 2^18, which is correct.

-John

**Comment by ip01** [comment]
You are absolutely right. It was my blackout - for a minute I thought that 2^18 is 268435456, not 262144.
Thanks a lot anyway.
