### ISSUE TITLE
Mac pip install issue

### ISSUE THREAD

**Issue by madhancr** [JohnLangford/vowpal_wabbit#1387]
Hello, I am getting this error on Mac 10.13.2, Python 3.6.4 :: Anaconda, Inc.

$pip install vowpalwabbit
Collecting vowpalwabbit
  Using cached vowpalwabbit-8.4.0.tar.gz
Building wheels for collected packages: vowpalwabbit
  Running setup.py bdist_wheel for vowpalwabbit ... error
  Complete output from command /Users/madhan/anaconda/envs/fastaiV2/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/1y/lhg_qvyx5lvb_6x50gczc6mr0000gn/T/pip-build-rbehjwml/vowpalwabbit/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /var/folders/1y/lhg_qvyx5lvb_6x50gczc6mr0000gn/T/tmp0f2q80iwpip-wheel- --python-tag cp36:
  running bdist_wheel
  running build
.
.
.
  parser.cc:450:26: warning: 'daemon' is deprecated: first deprecated in macOS 10.5 - Use posix_spawn APIs instead. [-Wdeprecated-declarations]
        if (!all.active && daemon(1,1))
                           ^
  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/stdlib.h:293:6: note: 'daemon' has been explicitly marked deprecated here
  int      daemon(int, int) __DARWIN_1050(daemon) __OSX_AVAILABLE_BUT_DEPRECATED_MSG(__MAC_10_0, __MAC_10_5, __IPHONE_2_0, __IPHONE_2_0, "Use posix_spawn APIs instead.") __WATCHOS_PROHIBITED __TVOS_PROHIBITED;
           ^
  /usr/bin/g++ -std=c++0x   -D__extern_always_inline=inline -Wall -pedantic -DNDEBUG -O3 -fomit-frame-pointer -fno-strict-aliasing  -D_FILE_OFFSET_BITS=64 -I /usr/local/include -I ../rapidjson/include -fPIC  -I ../rapidjson/include -c bs.cc -o bs.o
  /usr/bin/g++ -std=c++0x   -D__extern_always_inline=inline -Wall -pedantic -DNDEBUG -O3 -fomit-frame-pointer -fno-strict-aliasing  -D_FILE_OFFSET_BITS=64 -I /usr/local/include -I ../rapidjson/include -fPIC  -I ../rapidjson/include -c cbify.cc -o cbify.o
  /usr/bin/g++ -std=c++0x   -D__extern_always_inline=inline -Wall -pedantic -DNDEBUG -O3 -fomit-frame-pointer -fno-strict-aliasing  -D_FILE_OFFSET_BITS=64 -I /usr/local/include -I ../rapidjson/include -fPIC  -I ../rapidjson/include -c explore_eval.cc -o explore_eval.o
  /usr/bin/g++ -std=c++0x   -D__extern_always_inline=inline -Wall -pedantic -DNDEBUG -O3 -fomit-frame-pointer -fno-strict-aliasing  -D_FILE_OFFSET_BITS=64 -I /usr/local/include -I ../rapidjson/include -fPIC  -I ../rapidjson/include -c topk.cc -o topk.o
  /usr/bin/g++ -std=c++0x   -D__extern_always_inline=inline -Wall -pedantic -DNDEBUG -O3 -fomit-frame-pointer -fno-strict-aliasing  -D_FILE_OFFSET_BITS=64 -I /usr/local/include -I ../rapidjson/include -fPIC  -I ../rapidjson/include -c stagewise_poly.cc -o stagewise_poly.o
  1 warning generated.
  /usr/bin/g++ -std=c++0x   -D__extern_always_inline=inline -Wall -pedantic -DNDEBUG -O3 -fomit-frame-pointer -fno-strict-aliasing  -D_FILE_OFFSET_BITS=64 -I /usr/local/include -I ../rapidjson/include -fPIC  -I ../rapidjson/include -c log_multi.cc -o log_multi.o
  In file included from cbify.cc:6:
  ./../explore/cpp/MWTExplorer.h:1133:13: warning: 'static' function 'Sample_Without_Replacement' declared in header file should be declared 'static inline' [-Wunneeded-internal-declaration]
  static void Sample_Without_Replacement(u32* actions, vector<float>& probs, u32 size, PRG::prg& random_generator, float& top_action_probability)
              ^
  ./../explore/cpp/MWTExplorer.h:1173:13: warning: 'static' function 'Validate_Actions' declared in header file should be declared 'static inline' [-Wunneeded-internal-declaration]
  static void Validate_Actions(u32* actions, u32 num_actions)
              ^
  ./../explore/cpp/MWTExplorer.h:1188:13: warning: 'static' function 'Put_Action_To_List' declared in header file should be declared 'static inline' [-Wunneeded-internal-declaration]
  static void Put_Action_To_List(u32 action, u32* actions, u32 num_actions)
              ^
  In file included from explore_eval.cc:3:
  ./../explore/cpp/MWTExplorer.h:1133:13: warning: 'static' function 'Sample_Without_Replacement' declared in header file should be declared 'static inline' [-Wunneeded-internal-declaration]
  static void Sample_Without_Replacement(u32* actions, vector<float>& probs, u32 size, PRG::prg& random_generator, float& top_action_probability)
              ^
  ./../explore/cpp/MWTExplorer.h:1173:13: warning: 'static' function 'Validate_Actions' declared in header file should be declared 'static inline' [-Wunneeded-internal-declaration]
  static void Validate_Actions(u32* actions, u32 num_actions)
              ^
  ./../explore/cpp/MWTExplorer.h:1188:13: warning: 'static' function 'Put_Action_To_List' declared in header file should be declared 'static inline' [-Wunneeded-internal-declaration]
  static void Put_Action_To_List(u32 action, u32* actions, u32 num_actions)
              ^
  /usr/bin/g++ -std=c++0x   -D__extern_always_inline=inline -Wall -pedantic -DNDEBUG -O3 -fomit-frame-pointer -fno-strict-aliasing  -D_FILE_OFFSET_BITS=64 -I /usr/local/include -I ../rapidjson/include -fPIC  -I ../rapidjson/include -c recall_tree.cc -o recall_tree.o
  /usr/bin/g++ -std=c++0x   -D__extern_always_inline=inline -Wall -pedantic -DNDEBUG -O3 -fomit-frame-pointer -fno-strict-aliasing  -D_FILE_OFFSET_BITS=64 -I /usr/local/include -I ../rapidjson/include -fPIC  -I ../rapidjson/include -c active.cc -o active.o
  3 warnings generated.
  /usr/bin/g++ -std=c++0x   -D__extern_always_inline=inline -Wall -pedantic -DNDEBUG -O3 -fomit-frame-pointer -fno-strict-aliasing  -D_FILE_OFFSET_BITS=64 -I /usr/local/include -I ../rapidjson/include -fPIC  -I ../rapidjson/include -c active_cover.cc -o active_cover.o
  3 warnings generated.
  /usr/bin/g++ -std=c++0x   -D__extern_always_inline=inline -Wall -pedantic -DNDEBUG -O3 -fomit-frame-pointer -fno-strict-aliasing  -D_FILE_OFFSET_BITS=64 -I /usr/local/include -I ../rapidjson/include -fPIC  -I ../rapidjson/include -c kernel_svm.cc -o kernel_svm.o
  /usr/bin/g++ -std=c++0x   -D__extern_always_inline=inline -Wall -pedantic -DNDEBUG -O3 -fomit-frame-pointer -fno-strict-aliasing  -D_FILE_OFFSET_BITS=64 -I /usr/local/include -I ../rapidjson/include -fPIC  -I ../rapidjson/include -c best_constant.cc -o best_constant.o
  /usr/bin/g++ -std=c++0x   -D__extern_always_inline=inline -Wall -pedantic -DNDEBUG -O3 -fomit-frame-pointer -fno-strict-aliasing  -D_FILE_OFFSET_BITS=64 -I /usr/local/include -I ../rapidjson/include -fPIC  -I ../rapidjson/include -c ftrl.cc -o ftrl.o
  /usr/bin/g++ -std=c++0x   -D__extern_always_inline=inline -Wall -pedantic -DNDEBUG -O3 -fomit-frame-pointer -fno-strict-aliasing  -D_FILE_OFFSET_BITS=64 -I /usr/local/include -I ../rapidjson/include -fPIC  -I ../rapidjson/include -c svrg.cc -o svrg.o
  /usr/bin/g++ -std=c++0x   -D__extern_always_inline=inline -Wall -pedantic -DNDEBUG -O3 -fomit-frame-pointer -fno-strict-aliasing  -D_FILE_OFFSET_BITS=64 -I /usr/local/include -I ../rapidjson/include -fPIC  -I ../rapidjson/include -c lrqfa.cc -o lrqfa.o
  /usr/bin/g++ -std=c++0x   -D__extern_always_inline=inline -Wall -pedantic -DNDEBUG -O3 -fomit-frame-pointer -fno-strict-aliasing  -D_FILE_OFFSET_BITS=64 -I /usr/local/include -I ../rapidjson/include -fPIC  -I ../rapidjson/include -c interact.cc -o interact.o
  /usr/bin/g++ -std=c++0x   -D__extern_always_inline=inline -Wall -pedantic -DNDEBUG -O3 -fomit-frame-pointer -fno-strict-aliasing  -D_FILE_OFFSET_BITS=64 -I /usr/local/include -I ../rapidjson/include -fPIC  -I ../rapidjson/include -c comp_io.cc -o comp_io.o
  /usr/bin/g++ -std=c++0x   -D__extern_always_inline=inline -Wall -pedantic -DNDEBUG -O3 -fomit-frame-pointer -fno-strict-aliasing  -D_FILE_OFFSET_BITS=64 -I /usr/local/include -I ../rapidjson/include -fPIC  -I ../rapidjson/include -c interactions.cc -o interactions.o
  /usr/bin/g++ -std=c++0x   -D__extern_always_inline=inline -Wall -pedantic -DNDEBUG -O3 -fomit-frame-pointer -fno-strict-aliasing  -D_FILE_OFFSET_BITS=64 -I /usr/local/include -I ../rapidjson/include -fPIC  -I ../rapidjson/include -c vw_exception.cc -o vw_exception.o
  /usr/bin/g++ -std=c++0x   -D__extern_always_inline=inline -Wall -pedantic -DNDEBUG -O3 -fomit-frame-pointer -fno-strict-aliasing  -D_FILE_OFFSET_BITS=64 -I /usr/local/include -I ../rapidjson/include -fPIC  -I ../rapidjson/include -c vw_validate.cc -o vw_validate.o
  /usr/bin/g++ -std=c++0x   -D__extern_always_inline=inline -Wall -pedantic -DNDEBUG -O3 -fomit-frame-pointer -fno-strict-aliasing  -D_FILE_OFFSET_BITS=64 -I /usr/local/include -I ../rapidjson/include -fPIC  -I ../rapidjson/include -c audit_regressor.cc -o audit_regressor.o
  /usr/bin/g++ -std=c++0x   -D__extern_always_inline=inline -Wall -pedantic -DNDEBUG -O3 -fomit-frame-pointer -fno-strict-aliasing  -D_FILE_OFFSET_BITS=64 -I /usr/local/include -I ../rapidjson/include -fPIC  -I ../rapidjson/include -c gen_cs_example.cc -o gen_cs_example.o
  /usr/bin/g++ -std=c++0x   -D__extern_always_inline=inline -Wall -pedantic -DNDEBUG -O3 -fomit-frame-pointer -fno-strict-aliasing  -D_FILE_OFFSET_BITS=64 -I /usr/local/include -I ../rapidjson/include -fPIC  -I ../rapidjson/include -c cb_explore.cc -o cb_explore.o
  /usr/bin/g++ -std=c++0x   -D__extern_always_inline=inline -Wall -pedantic -DNDEBUG -O3 -fomit-frame-pointer -fno-strict-aliasing  -D_FILE_OFFSET_BITS=64 -I /usr/local/include -I ../rapidjson/include -fPIC  -I ../rapidjson/include -c action_score.cc -o action_score.o
  /usr/bin/g++ -std=c++0x   -D__extern_always_inline=inline -Wall -pedantic -DNDEBUG -O3 -fomit-frame-pointer -fno-strict-aliasing  -D_FILE_OFFSET_BITS=64 -I /usr/local/include -I ../rapidjson/include -fPIC  -I ../rapidjson/include -c cb_explore_adf.cc -o cb_explore_adf.o
  /usr/bin/g++ -std=c++0x   -D__extern_always_inline=inline -Wall -pedantic -DNDEBUG -O3 -fomit-frame-pointer -fno-strict-aliasing  -D_FILE_OFFSET_BITS=64 -I /usr/local/include -I ../rapidjson/include -fPIC  -I ../rapidjson/include -c OjaNewton.cc -o OjaNewton.o
  /usr/bin/g++ -std=c++0x   -D__extern_always_inline=inline -Wall -pedantic -DNDEBUG -O3 -fomit-frame-pointer -fno-strict-aliasing  -D_FILE_OFFSET_BITS=64 -I /usr/local/include -I ../rapidjson/include -fPIC  -I ../rapidjson/include -c parse_example_json.cc -o parse_example_json.o
  /usr/bin/g++ -std=c++0x   -D__extern_always_inline=inline -Wall -pedantic -DNDEBUG -O3 -fomit-frame-pointer -fno-strict-aliasing  -D_FILE_OFFSET_BITS=64 -I /usr/local/include -I ../rapidjson/include -fPIC  -I ../rapidjson/include -c baseline.cc -o baseline.o
  /usr/bin/g++ -std=c++0x   -D__extern_always_inline=inline -Wall -pedantic -DNDEBUG -O3 -fomit-frame-pointer -fno-strict-aliasing  -D_FILE_OFFSET_BITS=64 -I /usr/local/include -I ../rapidjson/include -fPIC  -I ../rapidjson/include -c classweight.cc -o classweight.o
  /usr/bin/g++ -std=c++0x   -D__extern_always_inline=inline -Wall -pedantic -DNDEBUG -O3 -fomit-frame-pointer -fno-strict-aliasing  -D_FILE_OFFSET_BITS=64 -I /usr/local/include -I ../rapidjson/include -fPIC  -I ../rapidjson/include -c allreduce_sockets.cc -o allreduce_sockets.o
  /usr/bin/g++ -std=c++0x   -D__extern_always_inline=inline -Wall -pedantic -DNDEBUG -O3 -fomit-frame-pointer -fno-strict-aliasing  -D_FILE_OFFSET_BITS=64 -I /usr/local/include -I ../rapidjson/include -fPIC  -I ../rapidjson/include -c allreduce_threads.cc -o allreduce_threads.o
  ar rcs liballreduce.a allreduce_sockets.o allreduce_threads.o vw_exception.o
  ar rcs libvw.a hash.o global_data.o io_buf.o parse_regressor.o parse_primitives.o unique_sort.o cache.o rand48.o simple_label.o multiclass.o oaa.o multilabel_oaa.o boosting.o ect.o marginal.o autolink.o binary.o lrq.o cost_sensitive.o multilabel.o label_dictionary.o csoaa.o cb.o cb_adf.o cb_algs.o search.o search_meta.o search_sequencetask.o search_dep_parser.o search_hooktask.o search_multiclasstask.o search_entityrelationtask.o search_graph.o parse_example.o scorer.o network.o parse_args.o accumulate.o gd.o learner.o mwt.o lda_core.o gd_mf.o mf.o bfgs.o noop.o print.o example.o parser.o loss_functions.o sender.o nn.o confidence.o bs.o cbify.o explore_eval.o topk.o stagewise_poly.o log_multi.o recall_tree.o active.o active_cover.o kernel_svm.o best_constant.o ftrl.o svrg.o lrqfa.o interact.o comp_io.o interactions.o vw_exception.o vw_validate.o audit_regressor.o gen_cs_example.o cb_explore.o action_score.o cb_explore_adf.o OjaNewton.o parse_example_json.o baseline.o classweight.o
  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libvw.a(parse_example_json.o) has no symbols
  /usr/bin/g++ -std=c++0x   -D__extern_always_inline=inline -Wall -pedantic -DNDEBUG -O3 -fomit-frame-pointer -fno-strict-aliasing  -D_FILE_OFFSET_BITS=64 -I /usr/local/include -I ../rapidjson/include -fPIC  -I ../rapidjson/include -o vw main.o -L. -l vw -l allreduce -L /usr/local/lib -lboost_program_options-mt -lboost_serialization-mt -l pthread -l z
  cd python; /Applications/Xcode.app/Contents/Developer/usr/bin/make things
  Using Python 3.6
  /usr/bin/g++ -std=c++0x -I/Users/madhan/anaconda/envs/fastaiV2/include/python3.6m -I/Users/madhan/anaconda/envs/fastaiV2/include/python3.6m -I /usr/local/include -I ../rapidjson/include -fPIC -c pylibvw.cc -o pylibvw.o
  /usr/bin/g++ -shared  pylibvw.o -L /usr/local/lib -L/Users/madhan/anaconda/envs/fastaiV2/lib/python3.6/config-3.6m-darwin -lpython3.6m -ldl -framework CoreFoundation -Wl,-stack_size,1000000 -framework CoreFoundation ../vowpalwabbit/libvw.a ../vowpalwabbit/liballreduce.a -L /usr/local/lib -lboost_program_options-mt -lboost_serialization-mt -l pthread -l z -l boost_python3-mt -o pylibvw.so
  ld: -stack_size option can only be used when linking a main executable
  clang: error: linker command failed with exit code 1 (use -v to see invocation)
  make[1]: *** [pylibvw.so] Error 1
  make: *** [python] Error 2
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/1y/lhg_qvyx5lvb_6x50gczc6mr0000gn/T/pip-build-rbehjwml/vowpalwabbit/setup.py", line 211, in <module>
      tests_require=['tox']
    File "/Users/madhan/anaconda/envs/fastaiV2/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/Users/madhan/anaconda/envs/fastaiV2/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/Users/madhan/anaconda/envs/fastaiV2/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/Users/madhan/anaconda/envs/fastaiV2/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 204, in run
      self.run_command('build')
    File "/Users/madhan/anaconda/envs/fastaiV2/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/Users/madhan/anaconda/envs/fastaiV2/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/Users/madhan/anaconda/envs/fastaiV2/lib/python3.6/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/Users/madhan/anaconda/envs/fastaiV2/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/Users/madhan/anaconda/envs/fastaiV2/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/Users/madhan/anaconda/envs/fastaiV2/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 75, in run
      _build_ext.run(self)
    File "/Users/madhan/anaconda/envs/fastaiV2/lib/python3.6/distutils/command/build_ext.py", line 339, in run
      self.build_extensions()
    File "/Users/madhan/anaconda/envs/fastaiV2/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
      self._build_extensions_serial()
    File "/Users/madhan/anaconda/envs/fastaiV2/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
      self.build_extension(ext)
    File "/private/var/folders/1y/lhg_qvyx5lvb_6x50gczc6mr0000gn/T/pip-build-rbehjwml/vowpalwabbit/setup.py", line 122, in build_extension
      subprocess.check_call(['make', 'python'], cwd=path.join(here, 'src'), env=env)
    File "/Users/madhan/anaconda/envs/fastaiV2/lib/python3.6/subprocess.py", line 291, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['make', 'python']' returned non-zero exit status 2.
  
  ----------------------------------------
  Failed building wheel for vowpalwabbit
  Running setup.py clean for vowpalwabbit
Failed to build vowpalwabbit
Installing collected packages: vowpalwabbit
  Running setup.py install for vowpalwabbit ... error
    Complete output from command /Users/madhan/anaconda/envs/fastaiV2/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/1y/lhg_qvyx5lvb_6x50gczc6mr0000gn/T/pip-build-rbehjwml/vowpalwabbit/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/1y/lhg_qvyx5lvb_6x50gczc6mr0000gn/T/pip-ucpuxxs5-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.7-x86_64-3.6
    creating build/lib.macosx-10.7-x86_64-3.6/vowpalwabbit
    copying vowpalwabbit/pyvw.py -> build/lib.macosx-10.7-x86_64-3.6/vowpalwabbit
    copying vowpalwabbit/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/vowpalwabbit
    copying vowpalwabbit/sklearn_vw.py -> build/lib.macosx-10.7-x86_64-3.6/vowpalwabbit
    running egg_info
    creating vowpalwabbit.egg-info
    writing vowpalwabbit.egg-info/PKG-INFO
    writing dependency_links to vowpalwabbit.egg-info/dependency_links.txt
    writing top-level names to vowpalwabbit.egg-info/top_level.txt
    writing manifest file 'vowpalwabbit.egg-info/SOURCES.txt'
    reading manifest file 'vowpalwabbit.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '*' under directory 'src'
    warning: no files found matching '*.dll' under directory 'bin'
    warning: no previously-included files matching '*.o' found anywhere in distribution
    warning: no previously-included files matching '*.exe' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    writing manifest file 'vowpalwabbit.egg-info/SOURCES.txt'
    running build_ext
    make: *** No rule to make target `clean'.  Stop.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/1y/lhg_qvyx5lvb_6x50gczc6mr0000gn/T/pip-build-rbehjwml/vowpalwabbit/setup.py", line 211, in <module>
        tests_require=['tox']
      File "/Users/madhan/anaconda/envs/fastaiV2/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/Users/madhan/anaconda/envs/fastaiV2/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/Users/madhan/anaconda/envs/fastaiV2/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/Users/madhan/anaconda/envs/fastaiV2/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/Users/madhan/anaconda/envs/fastaiV2/lib/python3.6/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/Users/madhan/anaconda/envs/fastaiV2/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Users/madhan/anaconda/envs/fastaiV2/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/Users/madhan/anaconda/envs/fastaiV2/lib/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/Users/madhan/anaconda/envs/fastaiV2/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Users/madhan/anaconda/envs/fastaiV2/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/Users/madhan/anaconda/envs/fastaiV2/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 75, in run
        _build_ext.run(self)
      File "/Users/madhan/anaconda/envs/fastaiV2/lib/python3.6/distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/Users/madhan/anaconda/envs/fastaiV2/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
        self._build_extensions_serial()
      File "/Users/madhan/anaconda/envs/fastaiV2/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
        self.build_extension(ext)
      File "/private/var/folders/1y/lhg_qvyx5lvb_6x50gczc6mr0000gn/T/pip-build-rbehjwml/vowpalwabbit/setup.py", line 105, in build_extension
        prep()
      File "/private/var/folders/1y/lhg_qvyx5lvb_6x50gczc6mr0000gn/T/pip-build-rbehjwml/vowpalwabbit/setup.py", line 65, in prep
        subprocess.check_call(['make', 'clean'], cwd=path.join(here, 'src', 'python'))
      File "/Users/madhan/anaconda/envs/fastaiV2/lib/python3.6/subprocess.py", line 291, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['make', 'clean']' returned non-zero exit status 2.
    
    ----------------------------------------
Command "/Users/madhan/anaconda/envs/fastaiV2/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/1y/lhg_qvyx5lvb_6x50gczc6mr0000gn/T/pip-build-rbehjwml/vowpalwabbit/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/1y/lhg_qvyx5lvb_6x50gczc6mr0000gn/T/pip-ucpuxxs5-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/1y/lhg_qvyx5lvb_6x50gczc6mr0000gn/T/pip-build-rbehjwml/vowpalwabbit/

**Comment by ShushanArakelyan** [comment]
I have the exact same issue, actually.

**Comment by halflearned** [comment]
Same error over here. Using both python 3.5 or python 3.6 in an virtual environment.

**Comment by gramhagen** [comment]
https://github.com/JohnLangford/vowpal_wabbit/issues/1364

Seems to have solved similar problems, do those steps help?

**Comment by JohnLangford** [comment]
I'm assuming this is solved now.  Reopen if not.
