### ISSUE TITLE
Seed VW Model / Shared Models

### ISSUE THREAD

**Issue by apoorvreddy** [JohnLangford/vowpal_wabbit#1393]
Hi @JohnLangford ,

In a previous thread, #1350 , you had suggested that there is a way to share models. I believe that the correct function for this is [seed_vw_model](https://github.com/JohnLangford/vowpal_wabbit/blob/master/vowpalwabbit/parse_args.cc#L1589) defined in parse_args.cc

This function essentially does the following:
``
1. Creates a completely new model from the arguments used to create the original VW model
2. Frees the memory used by the sd struct in the new model
3. Copies the weights from the old model into the new model.
4. Copies the address of the sd struct in the old model into the new model.

I have 2 questions:
1) Does VW_Finish handle the deallocation of shared models properly ?

The [block of code in finish here](https://github.com/JohnLangford/vowpal_wabbit/blob/master/vowpalwabbit/parse_args.cc#L1717-L1726) : 

```
  bool seeded;
  if (all.weights.seeded() > 0)
    seeded = true;
  else
    seeded = false;
  if (!seeded)
  {
    delete(all.sd->ldict);
    free(all.sd);
  }
```

The function `all.weights.seeded` returns the `_seeded` variable (which is a boolean) as a uint64_t. Also, I cannot find the line which sets `_seeded = false` anywhere in the VW code.

2) seed_vw_model is not exposed in vwdll.h.

**Comment by apoorvreddy** [comment]
Hi @JohnLangford ,

To answer my own question 1, _seeded = false will always be true for the 1st / original model. So I think finish handles deallocation for shared models properly. What do you think ?

Can I submit a pull request for exposing seed_vw_model in vwdll.h and vwdll.cpp  ?

**Comment by apoorvreddy** [comment]
Hi,

I added the following method to vwdll.cpp

```
VW_DLL_MEMBER VW_HANDLE VW_CALLING_CONV VW_SeedWithModel(VW_HANDLE handle, const char * extraArgs)
{
  string s(extraArgs);
  vw* origmodel = static_cast<vw*>(handle);
  vw* newmodel = VW::seed_vw_model(origmodel, s);
  return static_cast<VW_HANDLE>(newmodel);
}
```

The method works and when I try to initialize 200 instances of a model, I see about 250MB memory usage as opposed to ~400MB if I use VW_InitializeA for 200 instances.

However, if I try to initialize 400 instances using SeedWithModel, I get the following runtime error:

> libc++abi.dylib: terminating with uncaught exception of type VW::vw_exception: can't open: model_02-10-2017_08-10-2017errno = Too many open files
Abort trap: 6

**Comment by apoorvreddy** [comment]
I just realized that the above seed with model is unncessarily complex and the reason for 

> the too many files open exception

is this line over [here in parse_args.cc](https://github.com/JohnLangford/vowpal_wabbit/blob/master/vowpalwabbit/parse_args.cc#L1449-L1450) : 

```
  if (!skipModelLoad)
    load_input_model(all, model);
```

where `load_input_model` is the only place where [`close_file()` is being called.](https://github.com/JohnLangford/vowpal_wabbit/blob/master/vowpalwabbit/parse_args.cc#L1190)

**Comment by JohnLangford** [comment]
@apoorvreddy thanks for pursuing this---you commented right about when I was dealing with ICML submissions :-)

VW presently uses calloc as the primary heap allocator https://github.com/JohnLangford/vowpal_wabbit/blob/master/vowpalwabbit/memory.h#L8 which guarantees that memory is zero initialized since I was bit by the 'new doesn't initialize primitive types' heisenbugs one to many times.  When initializers need to be called, it is possible to use placement new as here: https://github.com/JohnLangford/vowpal_wabbit/blob/master/vowpalwabbit/memory.h#L31 after calloc. (I've further contemplated overriding the default new to get these semantics...)

It looks like you very effectively worked through things.  Thanks for the pull request.
