### ISSUE TITLE
Python interface for learning to search - Link broken?

### ISSUE THREAD

**Issue by julian-runge** [JohnLangford/vowpal_wabbit#1400]
Could you check the link http://nbviewer.ipython.org/github/hal3/vowpal_wabbit/blob/master/python/Learning_to_Search.ipynb? Doesn't exist for me.

**Comment by JohnLangford** [comment]
I get a 404 as well.  @hal3 do you know what's up?

**Comment by MLWave** [comment]
This can be found here: https://github.com/JohnLangford/vowpal_wabbit/blob/master/python/examples/Learning_to_Search.ipynb

https://github.com/JohnLangford/vowpal_wabbit/wiki/Learning-to-Search-Sub-System was updated with this new link. 

If you find the broken link anywhere else in the documentation/wiki, please let me know (or fix it yourself). Thanks.

**Comment by julian-runge** [comment]
Thank you.
