### ISSUE TITLE
Unable to create vw_jni.so for CentOS

### ISSUE THREAD

**Issue by fernandoabcampos** [JohnLangford/vowpal_wabbit#1405]
I'm really struggling to generate a vw_jni.so for my Linux CentOS (Docker container).
I was following the official doc and as the [documentation](https://github.com/JohnLangford/vowpal_wabbit/tree/master/java) states: "Creating this file is already part of the standard build process of VW".
By standard build process, I'll describe what I've done so far:
```
git clone https://github.com/JohnLangford/vowpal_wabbit.git
cd vowpal_wabbit/
./autogen.sh
./configure
make
make install
```

Apparently, I didn't notice any alarming error that could end up as the reason why vw_jni.so is not generated. Reading (what I consider deprecated doc, once the api has changed), I saw the build.sh under vowpal_wabbit/java/src/bin that was supposed to create the vw_jni.so in the past. However, this thread shows us that this was replaced by a newer solution: https://github.com/JohnLangford/vowpal_wabbit/pull/1193

Given that, I understand that I should execute: 
`make java 
`
And if I do from the root folder, I get:
```
[root@4fa5c1074466 vowpal_wabbit]# make java
make: Nothing to be done for `java'.
```

If I navigate to java directory and do a make

```
[root@4fa5c1074466 vowpal_wabbit]# cd java
[root@4fa5c1074466 java]# make
cd ..; make
make[1]: Entering directory `/vowpal_wabbit'
Making all in vowpalwabbit
make[2]: Entering directory `/vowpal_wabbit/vowpalwabbit'
(CDPATH="${ZSH_VERSION+.}:" && cd .. && /bin/sh /vowpal_wabbit/missing autoheader)
rm -f stamp-h1
touch config.h.in
cd .. && /bin/sh ./config.status vowpalwabbit/config.h
config.status: creating vowpalwabbit/config.h
config.status: vowpalwabbit/config.h is unchanged
make  all-am
make[3]: Entering directory `/vowpal_wabbit/vowpalwabbit'
make[3]: Leaving directory `/vowpal_wabbit/vowpalwabbit'
make[2]: Leaving directory `/vowpal_wabbit/vowpalwabbit'
Making all in cluster
make[2]: Entering directory `/vowpal_wabbit/cluster'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/vowpal_wabbit/cluster'
Making all in library
make[2]: Entering directory `/vowpal_wabbit/library'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/vowpal_wabbit/library'
make[2]: Entering directory `/vowpal_wabbit'
make[2]: Nothing to be done for `all-am'.
make[2]: Leaving directory `/vowpal_wabbit'
make[1]: Leaving directory `/vowpal_wabbit'

```
Am I missing any point here?

P.S: Additional info:

```
[root@4fa5c1074466 /]# lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.4.1708 (Core)
Release:        7.4.1708
Codename:       Core
```

```
[root@4fa5c1074466 /]# lsb_release -i
Distributor ID: CentOS
```

Thanks, 
Regards

**Comment by fernandoabcampos** [comment]
My mistake: when I called `./autogen.sh ` it had overwritten the supplied Makefiles. 

After `git checkout Makefile */Makefile` I was able to:
make
make java

And my **/vowpal_wabbit/java/target/libvw_jni.so** was created.
Thanks

**Comment by matanster** [comment]
@fernandoabcampos just curious, have you been able to actually use it from Java, after the build?
https://github.com/JohnLangford/vowpal_wabbit/issues/1496#issuecomment-396771691

**Comment by fernandoabcampos** [comment]
Hi @matanster. Yes, definitely, I was able to use.
I'm not currently able to test it right now, but I found a chunk of commands that helped me to create a docker container (it's part of a Dockerfile) and for the case you do not have a better path to follow, this somehow might be useful for you:

```
yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-$(rpm -E '%{rhel}').noarch.rpm \
	&& yum -y install gcc* \
	&& yum -y install zlib* \
	&& yum -y install git libtool boost boost-devel \
	&& yum -y --enablerepo=extras install centos-release-scl \
	&& yum-config-manager --enable rhel-server-rhscl-7-rpms \
	&& yum -y install devtoolset-4 \
	&& git clone https://github.com/JohnLangford/vowpal_wabbit.git \
	&& cd vowpal_wabbit/ \
	&& make \
	&& make java \
	#export LD_LIBRARY_PATH = $LD_LIBRARY_PATH:/vowpal_wabbit/java/target/libvw_jni.so
	&& make install 
```

P.S.: I know, I'm installing many unneeded dependencies here and so on.

I hope that helps.

Regards,

**Comment by matanster** [comment]
@fernandoabcampos thanks a lot! I have a similar script latent in my bash history, but your script made me realize what my problem was! 

(My problem was that I didn't `make install`. It seems that although the `.so` file is included in the VW jar and the VW jar is found by my runtime, the runtime/JVM is actually looking for the `.so` file where `make install` places it rather than using the copy included in the jar; and this is not specific in any way to CentOS, my problem reproduced on a fresh setup on Ubuntu 16.04 as well). 

Many thanks, as this likely short-circuited a much longer exploration!

**Comment by fernandoabcampos** [comment]
You're welcome @matanster - I'm glad it helped.
Regards
