### ISSUE TITLE
online boosting performance issue with the base learner

### ISSUE THREAD

**Issue by jf10** [JohnLangford/vowpal_wabbit#1407]
I am currently working with online boosting algorithms and I am now testing the one from Beygelzimer (2015). However, the results I get using boosting are inconsistent.

I have been testing the algorithm using N (weak learners) = 100 and N = 1. I am running a benchmark and the result in most of the cases is that N = 1 outperforms N = 100. I believe that the base learner is too strong for the boosting algorithm.

I wonder what is the weak learner used by default and if we can change it easily using the command line ? 

Have a good day,

jf10

**Comment by JohnLangford** [comment]
The weak learner by default is just linear regression.  This is indeed a rather strong base learner.

**Comment by jf10** [comment]
Thank you. 

So it is rather normal that the boosting does not improve the weak learner in this case. Linear combination of linear regressions is simply a linear regression. Can we use a different base learners?

**Comment by JohnLangford** [comment]
Yes.   You should be able to use a neural network or matrix factorization
easily.

**Comment by beygel** [comment]
You are right that one wouldn't expect any significant improvement from boosting linear learners, but we did find a small consistent improvement.  In the online boosting for regression paper (https://arxiv.org/pdf/1506.04820.pdf), we also used neural networks and regression stumps.  Regression stumps are not in the master branch but I can share our implementation (which may require rolling back to an earlier version of VW for compatibility).  As expected, boosting was much more effective for regression stumps.

**Comment by jf10** [comment]
I would be very interested by your implementation of the online regression stumps as weak learners. 

Thank you very much for your answers.

**Comment by beygel** [comment]
http://hunch.net/~beygel/gradient-boosting.tar.gz
It's packaged with version 7.10.1.  The relevant files are decision_stump.* and gradient_boosting.* .

**Comment by JohnLangford** [comment]
I'm assuming this is closed.   @beygel, if you want to add the decision stump implementation to the master branch that may be worthwhile.
