### ISSUE TITLE
bad tutorial pdf link

### ISSUE THREAD

**Issue by tres-pitt** [JohnLangford/vowpal_wabbit#1408]
would appreciate a fix for https://github.com/JohnLangford/vowpal_wabbit/wiki/v7.0_tutorial.pdf (tested on FF quantum and chrome)

**Comment by JohnLangford** [comment]
wget works.

**Comment by tres-pitt** [comment]
weird, what browser are you using @MLWave ? still not working for me.

anyway, wget works. thanks for following up

**Comment by MLWave** [comment]
@tres-pitt worked on both your tested browsers. Force-download though, not rendering the .pdf in the browser itself. You get a 404?
