### ISSUE TITLE
8.5.0: a variety of tests failures on 32bit

### ISSUE THREAD

**Issue by yarikoptic** [JohnLangford/vowpal_wabbit#1410]
a follow up to #1409 
anything what could be done to make tests more robust across architectures?
```shell
neurodebian@smaug ~/deb/builds/vowpal-wabbit/8.5.0.dfsg1-1 % grep 'RunTests: test .*FAIL' vowpal-wabbit_8.5.0.dfsg1-1~nd+1_i386.build    
RunTests: test 17: FAILED: ref(train-sets/ref/wiki1K.stderr) != stderr(wiki1K.stderr)
RunTests: test 21: FAILED: ref(train-sets/ref/xxor.stderr) != stderr(xxor.stderr)
RunTests: test 24: FAILED: ref(train-sets/ref/active-simulation.t24.stderr) != stderr(active-simulation.t24.stderr)
RunTests: test 25: FAILED: ref(train-sets/ref/bs.reg.predict) != (bs.reg.predict)
RunTests: test 26: FAILED: ref(train-sets/ref/bs.prreg.predict) != (bs.prreg.predict)
RunTests: test 27: FAILED: ref(train-sets/ref/bs.vote.predict) != (bs.vote.predict)
RunTests: test 28: FAILED: ref(train-sets/ref/bs.prvote.predict) != (bs.prvote.predict)
RunTests: test 29: FAILED: ref(train-sets/ref/affix_test.stderr) != stderr(affix_test.stderr)
RunTests: test 30: FAILED: ref(train-sets/ref/mask.stderr) != stderr(mask.stderr)
RunTests: test 31: FAILED: ref(train-sets/ref/remask.stderr) != stderr(remask.stderr)
RunTests: test 32: FAILED: ref(train-sets/ref/remask.final.stderr) != stderr(remask.final.stderr)
RunTests: test 33: FAILED: ref(train-sets/ref/topk-train.stderr) != stderr(topk-train.stderr)
RunTests: test 35: FAILED: ref(train-sets/ref/big-constant.stderr) != stderr(big-constant.stderr)
RunTests: test 36: FAILED: ref(train-sets/ref/progress-10.stderr) != stderr(progress-10.stderr)
RunTests: test 37: FAILED: ref(train-sets/ref/progress-0.5.stderr) != stderr(progress-0.5.stderr)
RunTests: test 38: FAILED: ref(train-sets/ref/nn-1-noquiet.stderr) != stderr(nn-1-noquiet.stderr)
RunTests: test 53: FAILED: ref(train-sets/ref/holdout-loss-not-zero.stderr) != stderr(holdout-loss-not-zero.stderr)
RunTests: test 54: FAILED: ref(train-sets/ref/stage_poly.s025.predict) != (stage_poly.s025.predict)
RunTests: test 56: FAILED: ref(train-sets/ref/stage_poly.s025.doubling.predict) != (stage_poly.s025.doubling.predict)
RunTests: test 57: FAILED: ref(train-sets/ref/stage_poly.s100.doubling.predict) != (stage_poly.s100.doubling.predict)
RunTests: test 71: FAILED: ref(train-sets/ref/0002.autolink.stderr) != stderr(0002.autolink.stderr)
RunTests: test 71: FAILED: ref(train-sets/ref/0002.autolink.predict) != (0002.autolink.predict)
RunTests: test 83: FAILED: ref(train-sets/ref/redefine.stderr) != stderr(redefine.stderr)
RunTests: test 84: FAILED: ref(train-sets/ref/cb_adf.stderr) != stderr(cb_adf.stderr)
RunTests: test 86: FAILED: ref(pred-sets/ref/multilabel_ldf.predict) != (multilabel_ldf.predict)
RunTests: test 87: FAILED: ref(train-sets/ref/cb_adf_rank.stderr) != stderr(cb_adf_rank.stderr)
RunTests: test 87: FAILED: ref(pred-sets/ref/cb_adf_rank.predict) != (cb_adf_rank.predict)
RunTests: test 93: FAILED: ref(train-sets/ref/cb_adf_dr.stderr) != stderr(cb_adf_dr.stderr)
RunTests: test 93: FAILED: ref(pred-sets/ref/cb_adf_dr.predict) != (cb_adf_dr.predict)
RunTests: test 97: FAILED: ref(train-sets/ref/0097.stderr) != stderr(0097.stderr)
RunTests: test 98: FAILED: ref(pred-sets/ref/0098.predict) != (0098.predict)
RunTests: test 99: FAILED: ref(test-sets/ref/0099.stderr) != stderr(0099.stderr)
RunTests: test 99: FAILED: ref(pred-sets/ref/0099.predict) != (0099.predict)
RunTests: test 109: FAILED: ref(pred-sets/ref/oaa_probabilities.predict) != (oaa_probabilities.predict)
RunTests: test 110: FAILED: ref(pred-sets/ref/csoaa_ldf_probabilities.predict) != (csoaa_ldf_probabilities.predict)
RunTests: test 111: FAILED: ref(train-sets/ref/search_dep_parser_one_learner.stderr) != stderr(search_dep_parser_one_learner.stderr)
RunTests: test 113: FAILED: ref(train-sets/ref/confidence.stderr) != stderr(confidence.stderr)
RunTests: test 113: FAILED: ref(pred-sets/ref/confidence.preds) != (confidence.preds)
RunTests: test 122: FAILED: ref(train-sets/ref/confidence_after_training.stderr) != stderr(confidence_after_training.stderr)
RunTests: test 122: FAILED: ref(pred-sets/ref/confidence_after_training.preds) != (confidence_after_training.preds)
RunTests: test 129: FAILED: ref(train-sets/ref/cbe_adf_softmax.stderr) != stderr(cbe_adf_softmax.stderr)
RunTests: test 129: FAILED: ref(pred-sets/ref/cbe_adf_softmax.predict) != (cbe_adf_softmax.predict)
RunTests: test 132: FAILED: ref(pred-sets/ref/poisson.train.predict) != (poisson.train.predict)
RunTests: test 140: FAILED: ref(train-sets/ref/marginal.stderr) != stderr(marginal.stderr)
RunTests: test 145: FAILED: ref(train-sets/ref/labeled-unlabeled-mix.stderr) != stderr(labeled-unlabeled-mix.stderr)
RunTests: test 146: FAILED: ref(train-sets/ref/cbe_adf_cover_dr256.json.stderr) != stderr(cbe_adf_cover_dr256.json.stderr)
RunTests: test 146: FAILED: ref(pred-sets/ref/cbe_adf_cover_dr256.predict) != (cbe_adf_cover_dr256.predict)
RunTests: test 147: FAILED: ref(pred-sets/ref/oaa_scores.predict) != (oaa_scores.predict)
RunTests: test 148: FAILED: ref(train-sets/ref/cb_adf_dm.stderr) != stderr(cb_adf_dm.stderr)
RunTests: test 150: FAILED: ref(train-sets/ref/sparse.stderr) != stderr(sparse.stderr)
RunTests: test 151: FAILED: ref(train-sets/ref/0151.stderr) != stderr(0151.stderr)
RunTests: test 154: FAILED: ref(train-sets/ref/ignore_linear.stderr) != stderr(ignore_linear.stderr)
RunTests: test 155: FAILED: ref(train-sets/ref/0097.audit_regr) != (0097.audit_regr)
RunTests: test 157: FAILED: ref(train-sets/ref/157.stderr) != stderr(157.stderr)
RunTests: test 161: FAILED: ref(train-sets/ref/classweight.stderr) != stderr(classweight.stderr)
```
All the log files including this are available from http://neuro.debian.net/_files/_buildlogs/vowpal-wabbit/8.5.0.dfsg1 if you would like to check on details

**Comment by yarikoptic** [comment]
for tests failures across different platforms, if interested, see https://buildd.debian.org/status/package.php?p=vowpal-wabbit

**Comment by JohnLangford** [comment]
What arguments is RunTests being invoked with?  In particular, it's normal for low-precision differences due to variation in libraries, etc... and there are options to do a fuzzy match before declaring FAILED.

**Comment by JohnLangford** [comment]
Your build testing also looks much more comprehensive than Travis, which is
great.  It would be cool to get that sort of build working on every checkin.

-John

**Comment by yarikoptic** [comment]
Invocation: https://github.com/yarikoptic/vowpal_wabbit/blob/debian/debian/rules#L48
```
cd test && ./RunTests -c -d -f
```
so I guess I just need to add that fuzziness

Environments: I guess it should be feasible to setup a good old x86 environment on Travis one way or another (chroot/bootstrap or a docker image with 32bit user space). Exotic architectures are trickier but eventually I should reincarnate my SPARC box I used as a part of http://nipy.bic.berkeley.edu if you are really interested.

**Comment by JohnLangford** [comment]
The default travis invocation flags are here:
https://github.com/JohnLangford/vowpal_wabbit/blob/master/Makefile#L127
Maybe that "just works".

I think travis gets unhappy if the build takes to long, but I'd be happy to
see at least a 32bit + 64bit working.

-John

**Comment by yarikoptic** [comment]
I guess something like this docker based recipe could do it https://github.com/travis-ci/travis-ci/issues/5770

**Comment by yarikoptic** [comment]
Regarding time - ATM you have only a single run, you could have a material of runs in different environments, iirc up to 4 of them run in parallel in the free tear, and you have time limitation only per each run

**Comment by arielf** [comment]
May be related to incompatible types.

We need to move to explicit types (uint*_t) instead of types that may be different in 32-bit and 64-bit envs, wherever possible.

Also see: (probably unrelated, because that does use explicit types, but wrong ones) [https://github.com/JohnLangford/vowpal_wabbit/issues/1401](https://github.com/JohnLangford/vowpal_wabbit/issues/1401)

**Comment by yarikoptic** [comment]
FTR: thought to recommend using numdiff for cases like this:
```shell
$> diff -u --minimal train-sets/ref/sparse.stderr sparse.stderr
--- train-sets/ref/sparse.stderr	2018-02-08 18:23:15.251625453 +0000
+++ sparse.stderr	2018-02-11 21:24:53.836730166 +0000
@@ -9,7 +9,7 @@
 average  since         example        example  current  current  current
 loss     last          counter         weight    label  predict features
 2.000000 2.000000            1            1.0    known        0:0...       13
-1.000000 0.000000            2            2.0    known        1:-0.0849907...        9
+1.000000 0.000000            2            2.0    known        1:-0.0849606...        9
```
but it didn't "work out" for me, emailed authors and CCed @JohnLangford . 

Still not sure how to proceed -- I would hate to just disable those tests on all (or just 32bt and those exotic) platforms

**Comment by JohnLangford** [comment]
We should try to trace down what the issue is.   Do you have a script which
can make it locally reproducible on my (linux) laptop?

The LDA code has a bunch of SIMD optimizations which are probably the
source of the issue there but the others are more mysterious.

-John

**Comment by yarikoptic** [comment]
you would just need a 32bit userland.  I could give you a debootstrap/schroot recipe if you have a Debian based system (akin to http://neuro.debian.net/blog/2011/2011-12-12_schroot_fslview.html#procedure), or could try to come up with 32bit userland singularity image for you (should be possible according to https://github.com/singularityware/singularity/issues/870 but didn't try yet)

**Comment by yarikoptic** [comment]
woohoo -- they did it! works nice, so if you are willing to install/use singularity (great thing to do anyways), here is a the beginning of the Singularity file to use to generate a 32bit development env
```
$> cat Singularity-vw-32 
BootStrap: debootstrap
OSVersion: stretch
MirrorURL: http://ftp.us.debian.org/debian/
ARCH: i386

# so if image is executed we just enter the environment
%runscript
    echo "Welcome to the VW devel env"
    /bin/bash


%post
    echo "Configuring the environment"
    apt-get update
    apt-get -y install eatmydata
    eatmydata apt-get -y install vim wget strace time ncdu gnupg curl procps
    chmod a+rX -R /etc/apt/sources.list.d
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
    apt-get clean
```
with
```shell
sudo singularity build singularity-vw.img Singularity-vw-32
```
I will now tune it (And adjust above) to the ultimate setup needed to build/test vw

**Comment by yarikoptic** [comment]
ok @JohnLangford - above Singularity file is complete and works -- generated image is about 240M.  I could share it if you like/trust it. Otherwise you could generate yourself one on your own.  I could also make it build automagically on singularity hub so you could pull it, if you like

**Comment by JohnLangford** [comment]
Making it build automagically would be fantastic.    (I've been overloaded
at work, but would really like to see the much broader testing.)

-John

**Comment by yarikoptic** [comment]
Just an update that Singularity image specifications are ready: https://github.com/yarikoptic/vowpal_wabbit/tree/master/singularity  and I am just waiting for an issue with debootstrapping on singularity hub to be resolved: https://github.com/singularityhub/singularityhub.github.io/issues/109 . Otherwise you could grab any of those and build your own image using e.g. `sudo singularity build singularity-vw.img Singularity.debian-unstable-i386`

**Comment by JohnLangford** [comment]
I'm having difficulty getting singularity to work for myself. 

When I login to github, the hook is there, but is says the most recent delivery was a 404 according to:
 Headers

Connection: keep-alive
Content-Length: 54
Content-Type: application/json
Date: Wed, 14 Mar 2018 15:29:43 GMT
Server: nginx/1.13.5
X-Frame-Options: SAMEORIGIN

Body

{"status": "error", "message": "Collection not found"}

When I login to singularity, it appears that I have no Collections.   When I click on 'My Collections->Add Collections' I see a bunch of github repositories next to buttons in grey and a 'Submit Query' button.  I can push the Submit Query button, which appears to do no state change, or I can turn the vowpal_wabbit button blue and then push Submit Query leading to: 
    Errors: Hook already exists on this repository
In all cases, when I click on JohnLangford->MyCollections, I see no collections.  

Any ideas?  I'll add an issue to Singularity as well.

**Comment by yarikoptic** [comment]
Let's ask the singularity-hub god/angel, @vsoch -- could you guide us into the light?

**Comment by vsoch** [comment]
yeah we are currently discussing! I'm going to try a quick test too with a new collection.

**Comment by vsoch** [comment]
hey @yarikoptic and @JohnLangford I reproduced the error, working on this now. Please hold off pushing buttons until further notice!

**Comment by vsoch** [comment]
okay ready for testing!

**Comment by JohnLangford** [comment]
@vsoch nailed it, thanks.

**Comment by vsoch** [comment]
:hammer:

**Comment by JohnLangford** [comment]
Back to the 32bit fails.  If you add:
          cout.precision(10);
          cout << *v << "+" << l.lda_rho << "=" << *v + l.lda_rho << " " << *v + l.lda_rho - 396070 << endl;
After this line:
https://github.com/JohnLangford/vowpal_wabbit/blob/master/vowpalwabbit/lda_core.cc#L779 
I get different results on i386 and x64 builds. 
x64: echo "" | ../vowpalwabbit/vw --lda 1 -b 6 --readable_model x64_readable --quiet | head -n 1
396070.2188+0.1000000015=396070.3125 0.3125
i386: echo "" | ../vowpalwabbit/vw --lda 1 -b 6 --readable_model i386_readable --quiet | head -n 1
396070.2188+0.1000000015=396070.3188 0.3187500015

This is using @yarikoptic singularity i386.  This surprises me---I thought the definition of a float did not change across architectures.  Note that this is a true difference at the bit level as the last subtraction makes clear.

I'm not sure what to do here.  An accumulation of differences could potentially account for the test divergence and varying definitions of float arithmetic make it nigh-impossible to use binary search to find other sources of variation.

**Comment by JohnLangford** [comment]
Following the suggestion here: http://www.linuxtopia.org/online_books/an_introduction_to_gcc/gccintro_70.html at the bottom, I added -msse2 -mfpmath=sse which seems to remove all floating point variation between i386 and x64 as per: https://github.com/JohnLangford/vowpal_wabbit/pull/1427 .

Two daemon tests are failing due to the lack of netcat ('nc') in the virtual environment.

**Comment by yarikoptic** [comment]
Ho ho, nice info, thanks for sharing. Is new release coming or should I just adopt the patch for Debian build?

**Comment by JohnLangford** [comment]
A new release is always coming, but I'd like to work through a number of
issues that have cropped up first.  Given this, adapting is the faster path.

(Also, I'm not sure this is adequate on all the many platforms with failing
tests.   Maybe try it and see if any remaining tests fail?)

-John

**Comment by arielf** [comment]
Good catch on `nc` being a dependency for the tests.

Should we install `nc` into the virtualenv of the test, or require it for `vw` build/test?

It comes from a Debian/Ubuntu package called `nc.openbsd` which provides an executable `/bin/nc.openbsd`.

There are two symlinks:

- `/bin/nc`
- `/bin/netcat`

Both come via the `alternatives` mechanism (pointing to this same executable).

```
$ ls -l /bin/nc*
lrwxrwxrwx 1 root root    20 May  5  2016 /bin/nc -> /etc/alternatives/nc
-rwxr-xr-x 1 root root 31248 Dec  3  2012 /bin/nc.openbsd*

$ dpkg -S /bin/nc.openbsd
netcat-openbsd: /bin/nc.openbsd

$ ls -l /etc/alternatives/nc
lrwxrwxrwx 1 root root 15 May  5  2016 /etc/alternatives/nc -> /bin/nc.openbsd

$ ls -l /bin/netcat
lrwxrwxrwx 1 root root 24 May  5  2016 /bin/netcat -> /etc/alternatives/netcat

$ ls -l /etc/alternatives/netcat
lrwxrwxrwx 1 root root 15 May  5  2016 /etc/alternatives/netcat -> /bin/nc.openbsd
```

Adding `-msse2 -mfpmath=sse` seems safe according to the gcc man page:
```
               For the x86-32 compiler, you must use -march=cpu-type, -msse or
               -msse2 switches to enable SSE extensions and make this option effective.
               For the x86-64 compiler, these extensions are enabled by default.
```
Which is why we had the inconsistency issue between these two envs in the 1st place.

**Comment by JohnLangford** [comment]
It looks like there are still build fails going on here: https://buildd.debian.org/status/package.php?p=vowpal-wabbit  However, these look like automake bugs?

**Comment by JohnLangford** [comment]
Does anyone know what's wrong with this singularity hub build? https://www.singularity-hub.org/containers/2078/log   I'm unfamiliar with the error message.

**Comment by vsoch** [comment]
This might be an issue with using an older version of Singularity, it looks like you are using the release from January! Try going to Settings --> Builder and changing to be 2.5

**Comment by JohnLangford** [comment]
Thanks, done.

However, I'm still not seeing consistent builds.  Why hasn't anything happened with further pushes to the master branch?  When I look at webhooks in github, it claims a successful delivery on 2018-07-04 17:03:40, but I do not see it here: https://www.singularity-hub.org/collections/740 ?

**Comment by vsoch** [comment]
It will only build again if there are changes to the singularity files, so I'm guessing the most recent didn't have commits that changed them directly. I just changed the collection to build manually and triggered a build for the errored one, and if that works you can do the same for the green if needed. Then put the collection to build back on commit and try pushing with changes to these files.

**Comment by JohnLangford** [comment]
Thanks---looks like it worked.
