### ISSUE TITLE
Installing from Pypi doesn't work but source does

### ISSUE THREAD

**Issue by polm** [JohnLangford/vowpal_wabbit#1414]
I'm on Arch Linux and have Boost (package v1.66.0-1) installed. Trying to import the python library causes this error:

```
>>> from vowpalwabbit import pyvw
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../env/lib/python3.6/site-packages/vowpalwabbit/pyvw.py", line 2, in <module>
    import pylibvw
ImportError: /usr/lib/libboost_python.so.1.66.0: undefined symbol: PyString_InternFromString
```
I reinstalled VW using the below command to make sure it was being built on my machine:

    pip install --no-cache-dir --no-binary :all: vowpalwabbit

But unfortunately the error persisted.

Installing from source (`pip install -e path/to/vw/python`) worked fine. 

Maybe the version on Pypi needs to be updated?

**Comment by sevmardi** [comment]
I second this problem! Having the same issue here. Any ideas?

**Comment by polm** [comment]
Not doing anything fancy when installing from source.

    git clone git@github.com:JohnLangford/vowpal_wabbit.git
    cd vowpal_wabbit
    make
    cd python
    make
    virtualenv env
    source env/bin/activate
    pip install -e . # you are in the vw/python directory still
    python examples/test.py # runs without issue

@sevmardi your error refers to a different symbol than mine. Are you sure you have Boost Python installed? On Arch Linux it's in the standard Boost package but on many platforms I suspect it won't be.

For reference, I am *not* using Anaconda.

**Comment by polm** [comment]
@sevmardi Based on [this old Caffe issue](https://groups.google.com/forum/#!topic/caffe-users/jTM5RauJyco) that mentions the same symbol it also seems possible your Python and Boost Python are using different Python versions.

**Comment by sevmardi** [comment]
@polm  I tried it on a fresh ubuntu 16.04. Everything seems to work there. I might indeed have some issues regarding boost and such. Thanks for the help though!

**Comment by JohnLangford** [comment]
Maybe @Scott-Graham-Bose can comment?  This looks like some compiled version incompatibility.

**Comment by Scott-Graham-Bose** [comment]
Curious, I'll try it with arch linux and boost 1.66, we may need to update pypi, i think we improved the boost library searching for python 3 recently which might not be in pypi

**Comment by Scott-Graham-Bose** [comment]
hmm, yeah i ran from a docker file with arch linux and i can confirm it doesn't work with pypi, but it does from a recent checkout of source.

let me update pypi, we're at 8.5.0 anyway so it needs to be bumped

**Comment by Scott-Graham-Bose** [comment]
I just deployed 8.5.0 to pypi, should be good with archlinux and when using python 3, also works with ubuntu 16.04 python 2 and python 3, although you need to change the boost library to point to the python 3 if you are using that.

```
rm /usr/lib/x86_64-linux-gnu/libboost_python.so
ln -s /usr/lib/x86_64-linux-gnu/libboost_python-py35.so /usr/lib/x86_64-linux-gnu/libboost_python.so```

**Comment by JohnLangford** [comment]
This sounds solved:-)  Thanks @Scott-Graham-Bose and @polm

**Comment by polm** [comment]
Just wanted to confirm this works for me, thanks for the fix!

**Comment by robinsonkwame** [comment]
Seeing this issue pop up again, in a python:3.6.7 docker container with 
```
FROM python:3.6.7

RUN apt-get update \
    && apt-get --yes --no-install-recommends install \
        libboost-program-options-dev \
        zlib1g-dev \
        locales tzdata ca-certificates sudo \
        bash-completion iproute2 tar curl vim nano tree \
    && rm -rf /var/lib/apt/lists/*
ENV LANG en_US.UTF-8

# Install Python stack
RUN apt-get update \
    && apt-get --yes --no-install-recommends install \
        python3-dev \
        build-essential \
        git openssh-client \
        libssl-dev libffi-dev \
        libboost-python-dev \
    && rm -rf /var/lib/apt/lists/*

ENTRYPOINT ["bash"]
```
with `pip install vowpalwabbit` and trying to import vowpalwabbit, I get 
```
root@20c31751366c:/# python
Python 3.6.7 (default, Nov 16 2018, 22:33:19) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from vowpalwabbit import pyvw
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/vowpalwabbit/pyvw.py", line 2, in <module>
    import pylibvw
ImportError: /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.62.0: undefined symbol: PyString_Type
```
