### ISSUE TITLE
Compiling Issue with Python 3.6

### ISSUE THREAD

**Issue by eugene-yang** [JohnLangford/vowpal_wabbit#1415]
I am having trouble installing.
Here is my environment info:
 - OS: Mac 10.13.1
 - With Anaconda
 - Python 3.6

And my g++ version info:
```
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.38)
Target: x86_64-apple-darwin17.2.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

My issue is that when running `make python` in the root of the repository, I followed #994 to use python 3. But, I got this error message
```
cd python; /Library/Developer/CommandLineTools/usr/bin/make things
Using Python 3.6
/usr/bin/g++ -std=c++0x -I/Users/eugene.yang/anaconda/envs/vw/include/python3.6m -I/Users/eugene.yang/anaconda/envs/vw/include/python3.6m -I /usr/local/include -I ../rapidjson/include -fPIC -c pylibvw.cc -o pylibvw.o
/usr/bin/g++ -shared  pylibvw.o -L /usr/local/lib -L/Users/eugene.yang/anaconda/envs/vw/lib/python3.6/config-3.6m-darwin -lpython3.6m -ldl -framework CoreFoundation -Wl,-stack_size,1000000 -framework CoreFoundation ../vowpalwabbit/libvw.a ../vowpalwabbit/liballreduce.a -L /usr/local/lib -lboost_program_options-mt -lboost_serialization-mt -l pthread -l z -l boost_python -o pylibvw.so
ld: -stack_size option can only be used when linking a main executable
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [pylibvw.so] Error 1
make: *** [python] Error 2
```
I'm not that familiar with C++ compiling. Can anyone help me with this?

cc @rth

**Comment by eugene-yang** [comment]
Also, I noticed that the name for `boost_python` is different when using anaconda, so I changed the last few lines of `find_boost` function in `python/setup.py`  like this 
```python
    if find_library(boost_lib):
        return boost_lib
    elif find_library('boost_python'):
        return "boost_python"
    else:
        raise Exception('Could not find boost python library')
```
And it helped me to get away with the not finding boost python problem.

This issue would also be raised if using `python setup.py install` since it will also call a subprocess to run `make python` in ./src with proper python version and lib path in the environment variables.

**Comment by rth** [comment]
Looks like it's a similar error to https://github.com/JohnLangford/vowpal_wabbit/issues/1387

**Comment by eugene-yang** [comment]
Looks like this problem haven't been solved...
I'm starting to wonder whether it is the problem of g++ version....

**Comment by eugene-yang** [comment]
A follow up testing. 
I removed `-Wl,-stack_size,1000000 -framework CoreFoundation` from the compiling. It made the compile finished without error messages but ended up with segmentation fault when importing the library.
```
>>> from vowpalwabbit.sklearn_vw import VWClassifier
Segmentation fault: 11
```

**Comment by JohnLangford** [comment]
I'm unfamiliar with the python issues here, but perhaps @Scott-Graham-Bose can comment?

**Comment by Scott-Graham-Bose** [comment]
usually what is happening with segmentation faults under this configuration is that vw is built using different boost dependencies than what is used when running vw under python.
I don't know a ton about the compiler options you are changing (I agree it's worth looking at updating your gcc version or using clang), but I suspect the change to setup.py to find the anaconda library could still be resulting in using a different set of boost libraries.

**Comment by Scott-Graham-Bose** [comment]
looks like we should improve how we're determining flags:
https://github.com/ContinuumIO/anaconda-issues/issues/1761

**Comment by Scott-Graham-Bose** [comment]
@eugene-yang - take a look at this branch, it should support anaconda better, but I need to do more testing
https://github.com/gramhagen/vowpal_wabbit/tree/python_install_improvements

**Comment by clifflyon** [comment]
Further, when I use @Scott-Graham-Bose's `python_install_improvements` branch, it compiles, but the import fails:
```
ImportError: dlopen(/usr/local/lib/python3.6/site-packages/vowpalwabbit-8.5.0-py3.6-macosx-10.13-x86_64.egg/pylibvw.cpython-36m-darwin.so, 2): Symbol not found: _PyClass_Type
  Referenced from: /usr/local/opt/boost-python/lib/libboost_python-mt.dylib
  Expected in: flat namespace
 in /usr/local/opt/boost-python/lib/libboost_python-mt.dylib
```

**Comment by Scott-Graham-Bose** [comment]
@clifflyon how did you install boost?

this tends to happen when you have multiple versions of boost installed and the wrong one is being linked to

can you provide the lines above the error like these:
```
/usr/bin/g++ -std=c++0x -I/Users/eugene.yang/anaconda/envs/vw/include/python3.6m -I/Users/eugene.yang/anaconda/envs/vw/include/python3.6m -I /usr/local/include -I ../rapidjson/include -fPIC -c pylibvw.cc -o pylibvw.o
/usr/bin/g++ -shared  pylibvw.o -L /usr/local/lib -L/Users/eugene.yang/anaconda/envs/vw/lib/python3.6/config-3.6m-darwin -lpython3.6m -ldl -framework CoreFoundation -Wl,-stack_size,1000000 -framework CoreFoundation ../vowpalwabbit/libvw.a ../vowpalwabbit/liballreduce.a -L /usr/local/lib -lboost_program_options-mt -lboost_serialization-mt -l pthread -l z -l boost_python -o pylibvw.so
```

**Comment by clifflyon** [comment]
Hi @Scott-Graham-Bose, I installed boost via brew:

```
In [1]: from ctypes.util import find_library

In [2]: find_library("boost_python-mt")
Out[2]: '/usr/local/lib/libboost_python-mt.dylib'
```

Here are the lines above:

```
/usr/bin/g++ -std=c++0x -I/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/include/python3.6m -I/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/include/python3.6m -I /usr/local/include -I ../rapidjson/include -fPIC -c pylibvw.cc -o pylibvw.o
/usr/bin/g++ -shared  pylibvw.o -L /usr/local/lib -L/usr/local/opt/python/Frameworks/Python.framework/Versions/3.6/lib/python3.6/config-3.6m-darwin -lpython3.6m -ldl -framework CoreFoundation ../vowpalwabbit/libvw.a ../vowpalwabbit/liballreduce.a -L /usr/local/lib -lboost_program_options-mt -lboost_serialization-mt -l pthread -l z -l boost_python-mt -o pylibvw.so
```

**Comment by clifflyon** [comment]
> this tends to happen when you have multiple versions of boost installed and the wrong one is being linked to

you're right - I needed to install `boost-python3`. Works now! 👍

**Comment by JohnLangford** [comment]
Excellent.  Thanks @Scott-Graham-Bose
