### ISSUE TITLE
Online boosting options missing ?

### ISSUE THREAD

**Issue by jf10** [JohnLangford/vowpal_wabbit#1420]
I am currently testing the online boosting version from Beygelzimer et al. In the code I see that there are three options that can be given to the boosting algorithm 'BBM', 'logistic' and 'adaptive' to test the different version of online boosting.

However, I don't quite see how to use the different version via the command line. the --boosting parameter does not take these options into account so what is the proper way ? 

Thank you :).

**Comment by MLWave** [comment]
Hi,

You can set 'BBM', 'logistic', 'adaptive', with the `--alg` parameter

```
vw data.vw --boosting 5 --alg BBM
```

Here more about online boosting related to VW:
https://event.cwi.nl/easydata2015/slides/kale.pdf
http://www2.ims.nus.edu.sg/Programs/015game/files/satyen.pdf
http://www-bcf.usc.edu/~haipengl/papers/OB_poster.pdf

When using `--alg BBM` you can also set `--gamma arg`

**Comment by JohnLangford** [comment]
Thank @MLWave.

vw --help says: 
  --alg arg (=BBM)                      specify the boosting algorithm: BBM 
                                        (default), logistic (AdaBoost.OL.W), 
                                        adaptive (AdaBoost.OL)

Which seems adequate?
