### ISSUE TITLE
Adding cubic and interactions in vw_hyperopt.py

### ISSUE THREAD

**Issue by nirupamkar** [JohnLangford/vowpal_wabbit#1424]
I have been trying to use the cubic feature for vowpal wabbit hyperopt. Did not get any info on that. Then I checked the hyperopt.py and realized that it was not implemented. I have changed the following function to introduce cubic/interaction argument.
Please let me know in case I missed anything.

`    

def _process_vw_argument(self, arg, value, algorithm):

    
        try:
            distr_part = self.distr_pattern.findall(value)[0]
        except IndexError:
            distr_part = ''
        
        range_part = self.range_pattern.findall(value)[0]
            print(range_part)

        is_continuous = '..' in range_part
        
        ocd = self.only_continuous.findall(value)
        if not is_continuous and len(ocd)> 0 and ocd[0] != '':
            raise ValueError(("Need a range instead of a list of discrete values to define "
                              "uniform or log-uniform distribution. "
                              "Please, use [min..max]%s form") % (distr_part))

        if is_continuous and arg == '-q':
            raise ValueError(("You must directly specify namespaces for quadratic features "
                              "as a list of values, not as a parametric distribution"))
        if is_continuous and arg == '-cubic':
            raise ValueError(("You must directly specify namespaces for cubic features "
                              "as a list of values, not as a parametric distribution"))
        if is_continuous and arg == '-interactions':
            raise ValueError(("You must directly specify namespaces for interactions features "
                              "as a list of values, not as a parametric distribution"))

        hp_choice_name = "_".join([algorithm, arg.replace('-', '')])

        try_omit_zero = 'O' in distr_part
        distr_part = distr_part.replace('O', '')

        if is_continuous:
            vmin, vmax = [float(i) for i in range_part.split('..')]

            if distr_part == 'L':
                distrib = hp.loguniform(hp_choice_name, log(vmin), log(vmax))
            elif distr_part == '':
                distrib = hp.uniform(hp_choice_name, vmin, vmax)
            elif distr_part == 'I':
                distrib = hp.quniform(hp_choice_name, vmin, vmax, 1)
            elif distr_part in {'LI', 'IL'}:
                distrib = hp.qloguniform(hp_choice_name, log(vmin), log(vmax), 1)
            else:
                raise ValueError("Cannot recognize distribution: %s" % (distr_part))
        else:
            possible_values = range_part.split(',')
            if arg == '-q':
                possible_values = [v.replace('+', ' -q ') for v in possible_values]
            if arg == '--cubic':
                possible_values = [v.replace('+', ' --cubic ') for v in possible_values]
            if arg == '--interactions':
                possible_values = [v.replace('+', ' --interactions ') for v in possible_values]
                
                
            distrib = hp.choice(hp_choice_name, possible_values)
            print(possible_values)

        if try_omit_zero:
            hp_choice_name_outer = hp_choice_name + '_outer'
            distrib = hp.choice(hp_choice_name_outer, ['omit', distrib])

        return distrib`

**Comment by JohnLangford** [comment]
@arielf can you comment?  Also, @nirupamkar it would be helpful to have this in a pull request.

**Comment by arielf** [comment]
Hi,

This generally looks good to me.  A pull request is the way to go.

I would make the following changes before issuing a PR:

- Is `--cubic` vs `-cubic` (double dash vs dash) potential confusion really necessary, can we allow either in the input (use regex to match the input arg)
- Can we make this even more friendly by allowing more UI flexibility, e.g. allow user to write a range as any of:   low,high low..high  "low high"(quoted pair including a space) etc. Again, this essentially this boils down to using regex in arg detection, and re.split regex instead of rigid string split.  We make the code slightly more complex once, resulting in a big improvement for the long term in User-experience

@nirupamkar can you make this a Pull Request?

**Comment by nirupamkar** [comment]
I can definitely look into it.
On Point 2 and 3, I have not really changed anything what is there already in vw-hyperopt.py. However I will check.
Thanks

**Comment by arielf** [comment]
@nirupamkar sorry if I implied it was you.  There's no diff here, just a full function posted, and I'm not very familiar with this particular code or history (I'm more familiar with the other `vw-hypersearch` perl implementation originally by Paul Mineiro). Anyway, this PR adding broader option support, is a great opportunity to make this code more user-friendly in the way it handles user parameters (ideally, all).  

Thanks for the improvement suggestion!

**Comment by JohnLangford** [comment]
I'm closing this issue, but please send a pull request.
