### ISSUE TITLE
minor Java test quirk

### ISSUE THREAD

**Issue by matanster** [JohnLangford/vowpal_wabbit#1433]
Running the Java API test using `mvn test`, there's one error logged

```
Running vowpalWabbit.learner.VWLearnersTest
Error: unrecognised option '--BAD_FEATURE___ounq24tjnasdf8h'
Error: Model content is corrupted, weight vector index 1347768914 must be less than total vector length 262144
```

It doesn't fail the tests, but might enjoy a small cleanup.

That said many thanks for all the JNI work, and I posted how to use the Java API on [this SO answer](https://stackoverflow.com/a/49412387/1509695), in case you have any comments to make it more accurate I guess please chime in.

**Comment by JohnLangford** [comment]
@jmorra @deaktator your thoughts?

**Comment by deaktator** [comment]
I agree with @jmorra but I did notice that the expected error message is missing in

VWLearnersTest.testBadVWArgs

That could be added if we care but the test is still valid without it.

**Comment by JohnLangford** [comment]
I'm going to close for now.   The minor improvement to the test case is welcome if you have a few minutes.
