### ISSUE TITLE
Multiple predictions on same JNI object

### ISSUE THREAD

**Issue by sergiomazoodigeo** [JohnLangford/vowpal_wabbit#1443]
Hi all,

I have a question regarding JNI API. According to the documentation:

"There is only a small amount of memory used on the Java side including a pointer to the VW model on the C side. Because of this the Java base interface implements Closeable and models MUST BE CLOSED or else you will leak memory. The Java garbage collector will not clean up the C memory."

I don't know if this memory leak would be produced by creating too many VWLearner objects without closing them or by executing several predictions. I'd like to use the same object to evaluate millions of requests in a distributed system without having to create it each time. Would it be possible?

Thanks in advance.
Best regards.

**Comment by deaktator** [comment]
You can use one VWLearner and make millions of predictions with it. If the task is distributed, you can create them on nodes in a cluster to scale horizontally. We’ve done this on Hadoop and Spark without issue when doing hundreds of millions of predictions daily. The leaking is an issue if you have a situation where you’re hot-swapping models and you don’t close the model you’re replacing.  We added the close method when we noticed leaking in this type of situation.

**Comment by sergiomazoodigeo** [comment]
Thanks for your help!
