### ISSUE TITLE
Python wrapper shows wrong infos at the end of the run

### ISSUE THREAD

**Issue by alexisdurieux** [JohnLangford/vowpal_wabbit#1445]
Hello,

Whenever I'm running Vowpal Wabbit models in python everything seems to run smoothly but the display at the end of the run is wrong. For instance if I run the [example notebook](https://github.com/JohnLangford/vowpal_wabbit/blob/master/python/examples/poisson_regression.ipynb) , it runs fine with the same results as in the notebook. 

However the informations displayed at the end of the run in terminal are wrong:
```
finished run
number of examples = 0
weighted example sum = 0.000000
weighted label sum = 0.000000
average loss = n.a.
total feature number = 0
```

Thanks

**Comment by Scott-Graham-Bose** [comment]
When using the python bindings to open a model and learn examples in an interactive fashion the usual data needed to populate this output is not captured, so the results end up being 0 or null. It's better to just turn off the output altogether with a quiet flag.

If you specify a data file as part of the input, then the normal training and validation metrics are captured and printed at the end of the run.

**Comment by alexisdurieux** [comment]
Alright, I see. It works indeed. Not sure what to do with this PR since this is not the desired behavior when feeding examples directly to the model using the wrapper.

**Comment by JohnLangford** [comment]
This is a "patch is welcome" issue.  Please consider sending one in.
