### ISSUE TITLE
Link is Broken

### ISSUE THREAD

**Issue by AdityaSoni19031997** [JohnLangford/vowpal_wabbit#1446]
http://nbviewer.jupyter.org/github/hal3/vowpal_wabbit/blob/master/python/Learning_to_Search.ipynb

The wiki link to Learning_to_Search isn't working

**Comment by MLWave** [comment]
For future reference, this link can be found here: https://github.com/JohnLangford/vowpal_wabbit/blob/master/python/examples/Learning_to_Search.ipynb

I updated the wiki link. Thanks for reporting the issue!

**Comment by JohnLangford** [comment]
Thanks @MLWave
