### ISSUE TITLE
run vw in cluster mode，but the model does not converge like in single machine

### ISSUE THREAD

**Issue by yfhewei** [JohnLangford/vowpal_wabbit#1448]
I trained a model using a dataset with 200,000 features and 20,000,000 examples. 
when I use vw in single machine, everything is right.
but when I try to train the model in cluster, the output model is not converge.
I get the first step model SGD,   the weight is not converge as the single model.  and the second step BFGS model's weights all is -nan. 

anything wrong of me ?
--loss_function=logistic --holdout_off --ect 4 -c -b 22

--bfgs --mem 30 --l2 0.1

in mapperout the average loss is strange:
average since example example current current current
loss last counter weight label predict features
0.000000 0.000000 1 1.0 1 1 661
0.000000 0.000000 2 2.0 1 1 842
0.000000 0.000000 4 4.0 1 1 2940
0.000000 0.000000 8 8.0 1 1 720
0.000000 0.000000 16 16.0 1 1 1267
0.000000 0.000000 32 32.0 1 1 583
0.000000 0.000000 64 64.0 1 1 1690
0.000000 0.000000 128 128.0 1 1 303
0.000000 0.000000 256 256.0 1 1 566
0.000000 0.000000 512 512.0 1 1 1243
0.000000 0.000000 1024 1024.0 1 1 1623
0.000000 0.000000 2048 2048.0 1 1 1185
0.035400 0.070801 4096 4096.0 2 2 1003
0.027710 0.020020 8192 8192.0 2 2 1533
0.034119 0.040527 16384 16384.0 3 3 1405

----------------------
if the input file is gzip， the training is like above,not right. even add --compressed.
if  the input file is txt， the training is OK.

is the input file cause the problem?

-----------
update again
if I gzip file myself， everything is OK.
but if I gz file by hadoop streaming，set -Dmapreduce.output.fileoutputformat.compress.codec=org.apache.hadoop.io.compress.GzipCodec \
 the output file is not right for vw training, even if I unzip the output gz file.

so, the problem is in the gz process. maybe vw has some requirement for gzip.

**Comment by yfhewei** [comment]
in mapperout  the average loss is strange:
average  since         example        example  current  current  current
loss     last          counter         weight    label  predict features
0.000000 0.000000            1            1.0        1        1      661
0.000000 0.000000            2            2.0        1        1      842
0.000000 0.000000            4            4.0        1        1     2940
0.000000 0.000000            8            8.0        1        1      720
0.000000 0.000000           16           16.0        1        1     1267
0.000000 0.000000           32           32.0        1        1      583
0.000000 0.000000           64           64.0        1        1     1690
0.000000 0.000000          128          128.0        1        1      303
0.000000 0.000000          256          256.0        1        1      566
0.000000 0.000000          512          512.0        1        1     1243
0.000000 0.000000         1024         1024.0        1        1     1623
0.000000 0.000000         2048         2048.0        1        1     1185
0.035400 0.070801         4096         4096.0        2        2     1003
0.027710 0.020020         8192         8192.0        2        2     1533
0.034119 0.040527        16384        16384.0        3        3     1405

what is the problem？

**Comment by yfhewei** [comment]
if the input file is gzip， the training is like above。
if the input file is txt， the training is OK.

**Comment by yfhewei** [comment]
you can reproduce the problem easily.
1,compress data by hadoop streaming. use " cat"  and set as this:    Dmapreduce.output.fileoutputformat.compress=true \    -Dmapreduce.output.fileoutputformat.compress.codec=org.apache.hadoop.io.compress.GzipCodec \
2,download the data and the compressed data, train them by vw.  and compare their result.

**Comment by arielf** [comment]
Currently "Automatic" detection of compression is done by the file name (ends with `.gz`)
If you pass the data via useless use of cat (or via stdin) you need to add the `--compressed` option.

**Comment by yfhewei** [comment]
This is not the reason. Even if I download the compressed file from hdfs, unzip it into text, and then training, still can not get the normal model.

**Comment by MLWave** [comment]
Just as an aside: Looks like your training set is not randomly ordered. This can cause problems when online learning.

> Even if I download the compressed file from hdfs, unzip it into text, and then training, still can not get the normal model.

Please reduce this unzipped dataset to just a few rows, so that the problem remains, but is isolated to a small sample, then host it somewhere so we can have a look. Nearly impossible to debug this remotely.

**Comment by JohnLangford** [comment]
In general, parallel training is not guaranteed to replicate sequential training---this is essential to efficiency.  See the terascale learning paper for details: https://arxiv.org/abs/1110.4198
