### ISSUE TITLE
how to use the --bfgs/cg trained model to predict?

### ISSUE THREAD

**Issue by yfhewei** [JohnLangford/vowpal_wabbit#1449]
I trained the model using option --bfgs/--conjugate_gradient,  can get the model successfully. but
If I use the model to predict  like:
`./vw -i model  -d data/test-00000 -p data/pred_model`
It will output like:
  "1 -nan      	-nan      	-nan      	      Maximum number of passes reached. If you want to optimize further, increase the number of passes"
and the output prediction is the same number.

How can I use the batch trained model to predict? 
There must be something wrong with my command.

**Comment by yfhewei** [comment]
thank you for your comment.  even if I add -t, the prediction result is not right. All the predict number is the same.  I viewed the model file, and find that the same sgd model's prediction is normal. But the bfgs model's prediction is always very bad. Accuracy is 0.2.

**Comment by JohnLangford** [comment]
Thanks @MLWave 

@yfhewei This isn't debuggable because you haven't specified your training process.   It's quite possible that you are using bfgs wrong somehow...   Please reopen with more details if you want to pursue further.
