### ISSUE TITLE
Contextual Bandits example wiki page has gone away

### ISSUE THREAD

**Issue by matanster** [JohnLangford/vowpal_wabbit#1450]
It looks like the page for "Contextual Bandits Example", which is still referred from [this other wiki page](https://github.com/JohnLangford/vowpal_wabbit/wiki/Examples), has been removed sometime over the last two weeks or so.

It could be very nice to have it up there again, unless you really think it was worth removing....

**Comment by JohnLangford** [comment]
I believe there was a name change resulting in a dangling pointer.  https://github.com/JohnLangford/vowpal_wabbit/wiki/Logged-Contextual-Bandit-Example
