### ISSUE TITLE
Can't install vw for python on windows10

### ISSUE THREAD

**Issue by macny** [JohnLangford/vowpal_wabbit#1452]
Hi,
I keep failing to install the package, and getting this info no matter from PyPI or local source:

`error: [Error 2] No such file or directory: 'D:\\...\\vowpal_wabbit-8.5.0\\python\\bin\\pyvw36.dll`

I'd really appreciate your help.
Thanks!

**Comment by sharatsc** [comment]
Seems same as https://github.com/JohnLangford/vowpal_wabbit/issues/1374

**Comment by macny** [comment]
thanks
