### ISSUE TITLE
How to transform  VW  datasets into CSV format

### ISSUE THREAD

**Issue by yangxiaokang** [JohnLangford/vowpal_wabbit#1454]

**Comment by matanster** [comment]
Maybe try https://github.com/zygmuntz/phraug

**Comment by yangxiaokang** [comment]
@matanster there is just csv2vw.py，but i want vw2csv

**Comment by MLWave** [comment]
See: https://github.com/JohnLangford/vowpal_wabbit/blob/master/utl/vw2csv

**Comment by JohnLangford** [comment]
Thanks @MLWave
