### ISSUE TITLE
VW Logging to stdout and Java | monitoring

### ISSUE THREAD

**Issue by matanster** [JohnLangford/vowpal_wabbit#1455]
Hi,

Kind of a production question ― 

I have a budding Scala wrapper wrapping around VW models in the framework of Akka, an actor model framework; this setup utilizes the Java API of VW of course. Now, in this kind of environment logging is a major issue ― it may cause disarray if not in some way organized per component, but VW spits out plain unprefixed messages (unless `--quiet` is used).

I'm probably not seeing this in the Java implementation ― are there good ways to redirect VW's stdout output, when used through the provided Java API, or to directly request of it to log to a given file? how do you handle this in the C# API, or do you rather use it over tcp as a daemon, making the solution obvious?

Could you alternatively, suggest how to somehow query a VW model for progress/status/weights, initiated by the Java consumer not by the VW learner itself?

Thanks a lot!
Matan

**Comment by deaktator** [comment]
@matanster, Good question.  Have you tried using a apache commons io TeeOutputStream: 

It might work for you.

```scala
import java.io.{ByteArrayOutputStream, PrintStream}
import org.apache.commons.io.output.TeeOutputStream

val baos = new java.io.ByteArrayOutputStream
val sysout = System.out
val teed = new java.io.PrintStream(new TeeOutputStream(sysout, baos))
// Console.withOut(teed)( /* MAIN FUNCTION HERE */ )
System.setOut(teed)

System.out.println("hello")

baos.toString   // "hello\n"

Console.withOut(teed)(println("world"))

baos.toString   // "hello\nworld\n"
```

**Comment by deaktator** [comment]
I'm not sure this will work. It might, it might not. If it doesn't (because it only works on data emanating from the JVM), you might try PipedInputStream in the Java std lib to read stdout.

**Comment by JohnLangford** [comment]
Most users of VW as a library simply use --quiet and then compute whatever monitoring statistics they want on the side.  

However, it's fairly easy to imagine introducing a stringstream to catch the output and surface it as a string across a library interface.  If you grep for 'quiet' you'll see all the lines which would need to change.  I'm not going to work on this myself, but a patch is welcome if you care.
