### ISSUE TITLE
OSX boost-python3 find library error

### ISSUE THREAD

**Issue by you06** [JohnLangford/vowpal_wabbit#1456]
Platform: OSX

Run `sudo python3 setup.py install` get `Exception: Could not find boost python library`

In the `setup.py`:
```python
def find_boost():
    """Find correct boost-python library information """
    if system == 'Linux':
        # use version suffix if present
        boost_lib = 'boost_python-py{v[0]}{v[1]}'.format(v=sys.version_info)
        if sys.version_info.major == 3:
            for candidate in ['-py36', '-py35', '-py34', '3']:
                boost_lib = 'boost_python{}'.format(candidate)
                if find_library(boost_lib):
                    break
        if not find_library(boost_lib):
            boost_lib = "boost_python"
    elif system == 'Darwin':
        boost_lib = 'boost_python-mt' if sys.version_info[0] == 2 else 'boost_python3-mt'
    elif system == 'Cygwin':
        boost_lib = 'boost_python-mt' if sys.version_info[0] == 2 else 'boost_python3-mt'
    else:
        raise Exception('Building on this system is not currently supported')

    if not find_library(boost_lib):
        raise Exception('Could not find boost python library')

    return boost_lib
```

for `python3`, the value of `boost_lib` will be `boost_python3-mt`. `find_library('boost_python3-mt')` will return `None` which raise Exception and print `Exception: Could not find boost python library`.

I found the library is located in `/usr/local/lib/libboost_python36-mt.dylib`. When I run `find_library('boost_python36-mt')`, I get this library, so I change the value of `boost_lib` to `boost_python36-mt` like this:
```python
elif system == 'Darwin':
    boost_lib = 'boost_python-mt' if sys.version_info[0] == 2 else 'boost_python3-mt'
    boost_lib = 'boost_python36-mt'
```

Than I run `sudo python3 setup.py clean` and `sudo python3 setup.py install`, build success.

For Darwin platform, there may be some boost_lib guessing like Linux platform?

**Comment by arielf** [comment]
@you06 thanks for the report and the fix suggestion.
Just making sure @Scott-Graham-Bose sees this.

**Comment by Scott-Graham-Bose** [comment]
makes sense, this whole approach at guessing for the boost library seems wonky, but I haven't seen a more reliable way to go about it...

I have a few changes here that need to be checked in, I will include this as well, thx!

**Comment by charlescearl** [comment]
FYI, To get this to work on OS X 10.13.4, I had changed Lines 37,38 of `python/setup.py` to
```
    elif system == 'Darwin':
        boost_lib = 'boost_python' if sys.version_info[0] == 2 else 'boost_python3'
```

This compiles but I get a segfault when I attempt to run

```
> python                                                                                                                                                                                         Python 3.5.5 |Anaconda, Inc.| (default, Mar 12 2018, 16:25:05)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from vowpalwabbit import pyvw
>>>
>>> vw = pyvw.vw(quiet=True)
>>> ex = vw.example('1 | a b c')
fish: Job 4, 'python' terminated by signal SIGSEGV (Address boundary error)
```
I am running the anaconda Python, 3.5.

**Comment by you06** [comment]
> FYI, To get this to work on OS X 10.13.4, I had changed Lines 37,38 of python/setup.py to
> 
>     elif system == 'Darwin':
>         boost_lib = 'boost_python' if sys.version_info[0] == 2 else 'boost_python3'
> This compiles but I get a segfault when I attempt to run
> 
> > python                                                                                                                                                                                         Python 3.5.5 |Anaconda, Inc.| (default, Mar 12 2018, 16:25:05)
> [GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
> Type "help", "copyright", "credits" or "license" for more information.
> >>> from vowpalwabbit import pyvw
> >>>
> >>> vw = pyvw.vw(quiet=True)
> >>> ex = vw.example('1 | a b c')
> fish: Job 4, 'python' terminated by signal SIGSEGV (Address boundary error)
> I am running the anaconda Python, 3.5.

@charlescearl `boost_python3 ` and `boost_python3-mt` are different libraries. Does this lead to segfault?
```sh
~ » ls -l /usr/local/lib/ | grep boost_python3                                                                                             
lrwxr-xr-x    1 user  admin        57 Apr 19 23:23 libboost_python36-mt.a -> ../Cellar/boost-python3/1.67.0/lib/libboost_python36-mt.a
lrwxr-xr-x    1 user  admin        61 Apr 19 23:23 libboost_python36-mt.dylib -> ../Cellar/boost-python3/1.67.0/lib/libboost_python36-mt.dylib
lrwxr-xr-x    1 user  admin        54 Apr 19 23:23 libboost_python36.a -> ../Cellar/boost-python3/1.67.0/lib/libboost_python36.a
lrwxr-xr-x    1 user  admin        58 Apr 19 23:23 libboost_python36.dylib -> ../Cellar/boost-python3/1.67.0/lib/libboost_python36.dylib

```

**Comment by charlescearl** [comment]
I changed my Makefile as you suggest to use the libraries in as opposed to the anaconda libraries. I now get the following link error

```
> python setup.py install                                                                                                                                                                        (py_36_vw)
running install
running bdist_egg
...
cd python; /Applications/Xcode.app/Contents/Developer/usr/bin/make things
/usr/bin/g++ -shared  pylibvw.o -L /usr/local/lib -L/Users/charlescearl/anaconda3/envs/py_36_vw/lib/python3.6/config-3.6m-darwin -lpython3.6m -ldl -framework CoreFoundation -Wl,-stack_size,1000000 -framework CoreFoundation ../vowpalwabbit/libvw.a ../vowpalwabbit/liballreduce.a -L /usr/local/lib -lboost_program_options-mt -lboost_serialization-mt -l pthread -l z -l boost_python36-mt -o pylibvw.so
ld: -stack_size option can only be used when linking a main executable
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by JohnLangford** [comment]
I believe(?) this is fixed in the current master with a patch from @Scott-Graham-Bose
