### ISSUE TITLE
Get action order instead of only the best one with contextual bandit

### ISSUE THREAD

**Issue by ssoulier** [JohnLangford/vowpal_wabbit#1464]
I am using vw for contextual bandit. In the context of my architecture, I must predict server side without knowing which action will be eligible client side. So currently, I am doing several vw prediction to get the list of the action in the prefered order, I send them to my client and then the client decide base on eligibility which one it should run.
In order to avoid several predict to obtain this sorted list of action, do you think we can easily add a feature to vowpal that directly output this list and not only the argmin ?
If it seems easy enough, with some help, I can code it. Thanks

**Comment by arielf** [comment]
Hi @ssoulier 

Note that with `vw` you don't have any obligation to be fully synchronous. IOW, you don't have to send (and receive) examples one by one.  The order of responses is guaranteed to be the same as that of the requests.

Given the above, how would sending all actions in one line, be functionally different than sending (a batch of) K requests/lines (K being the number of actions) and reading back a batch of K responses/lines?

**Comment by ssoulier** [comment]
Hi @arielf.
Thanks for your answer. I will try to be more precise with an example.
I have 4 actions (1, 2, 3 and 4) with a 2 features context (a and b).
Imagine that for this example `1 2 3 4 | a b` my vw bandit model predict a cost of 

 - 0.05 for action 1
 - 0.10 for action 2
 - 0.02 for action 3
 - 0.08 for action 4

argmin is reach for action 3, and `-p` will output a`3` for this row.
But then I need to know which is the next _prefered_ one (action 1 in this example).
So for that, I am sending this new row to vw `1 2 4 | a b` and I get `1` predicted.
Then I iterate again this this row `2 4 | a b` and get action 4, ...

My issue is that, today I do not know how to avoid this iteration. What I would like is the raw cost prediction. That way I can order the prefered action myself.

Is it possible, maybe with `csoaa` option ? 

I hope my issue is clearer now :)
Thanks again

**Comment by arielf** [comment]
Hi @ssoulier 

Thanks for the details, and sorry for my misunderstanding.
I believe this is a case where all of the following are true:

- The code could be made more general useful
- Documentation could be improved. There have been many questions on CB lately.
- There may be a work around to achieve what you need.

So looking for a workaround, I would try to:

- add `-a` (audit)
- redirect stderr and stdout to the same place
- capture the audit line (it starts with a tab) as part of the response.  It should contain the list of weights for all the model features which appear in the example, so the answer may be in its values or some transform of them.

Other CB options (there are several, look at `vw --help`) may be also relevant, but I'm not sure which ones, sorry.

**Comment by ssoulier** [comment]
Hi @arielf.

Thank you very much.
I'll try to handle it with the workaround you suggested.

**Comment by ssoulier** [comment]
Unfortunately, --csoaa_rank is unrecognised for a model train with --cb and
I don't believe my use case feet well with adf setup.
Thanks.

**Comment by JohnLangford** [comment]
Interesting.  It seems like there is a case for only _adding_ to a set of
prediction information rather than _replacing_.

-John
