### ISSUE TITLE
the parameter hash_bits, what is maximum? 

### ISSUE THREAD

**Issue by Serene-Guo** [JohnLangford/vowpal_wabbit#1468]
when i use hash_bits=32,  hash_value=0.  could i use hash_bits=63?   that is to say, bigger than 32.

**Comment by sharatsc** [comment]
Its limited to 32 bits. Note that is allocated (1 << hash_bits) * 4 bytes while training. Collisions do not degrade the accuracy of the model. https://alex.smola.org/papers/2009/Weinbergeretal09.pdf

**Comment by JohnLangford** [comment]
The current limiting factor is actually murmurhash3---VW is using the 32bit variant.  Internally, VW supports 64 bits, which you can take advantage of using -q or --ngram, for example: 
echo "|a b |c d " | ./vw -b 60 --sparse_weights --audit -q ac --quiet
0
	a^b:644756112:1:0@0	c^d:1541212946:1:0@0 Constant:11650396:1:0@0a^b*c^d:10817473555501986:1:0@0


Apparently, there is a 128 bit variant: https://github.com/aappleby/smhasher/wiki/MurmurHash3 which is plenty fast, but switching to it is a format-breaking change.  If there is a scenario that actually needs more than 32 bits before generating extra features, please mention it and I'll look into the 128 bit support.
