### ISSUE TITLE
[Python] [sklearn] A few issues (and minor bugs?) in the sklearn_vw.VW.fit() method

### ISSUE THREAD

**Issue by mlisovyi** [JohnLangford/vowpal_wabbit#1475]
Hi,

playing around with the sklearn interface of VW it seems there a few issues (applies to v 8.5.0 and the current master branch):
1. A **very minor bug**: it seems that the code intends to shuffle examples between epochs/passes. This is done [here in the code](https://github.com/JohnLangford/vowpal_wabbit/blob/master/python/vowpalwabbit/sklearn_vw.py#L307). However, `range(n)` starts with `0`, so the `n > 1` condition has to be changed to `n >= 1` otherwise the second pass is done without reshuffling.
2. An **issue/bug** (?): the current implementation of shuffling doesn't work in a general case for pd.DataFrame or pd.Series as an input. It will work if all indices are sequential starting from 0. However, if one attempts to use a KFold splitting from sklearn, then it breaks down. A minimal example to reproduce the problem is given at the end of the post. This feature can be worked around by passing `pd.Series.values` but at the moment it is not clear from the documentation that pandas objects directly have only a limited support. Pandas support also relates to observations in #1472.
3. An **issue**: even if a `np.array` is passed directly, the `VW.fit()` with several passes shuffles examples in the original array. The problem with this is that one wants to evaluate performance on tthe training dataset, thus doing `clf.predict()` and to compare to a vector (=array/pd.Series/etc.) true labels. True labels are usually available separately in a sklearn nomenclature (i.e. 0/1 labels instead of -1/1). However, those have not been shuffled and thus the order of predictions and true labels is broken and performance metric evaluation doesn't make sense. Is it possible to create a local copy of the input data object inside the `.fit()` method and clear it at the end? Otherwise, the documentation has to be very explicit about this behaviour.

Thanks in advance for feedback

**Environmental setup**
Ubuntu 16.04 with conda 4.5.1 and python3.5
vowpalwabbit 8.5.0 (installed from pypi), scikit-learn 0.19.1, numpy 1.14.2

**Example of the issue 2**
```python
import pandas as pd
import numpy as np
from vowpalwabbit.sklearn_vw import VWClassifier
from sklearn.model_selection import KFold

# The dummy example X has already been adjusted to the native VW format, so convert_to_vw=False
X = pd.Series(['1 |Pet cat', '-1 |Pet dog', '1 |Pet cat', '1 |Pet cat'], name='catdog')
# The sklearn-friendly y is needed for the KFold.split() only
y = pd.Series([-1, 1, -1, -1], name='label')

kfold = KFold(n_splits=3, random_state=314, shuffle=False)

# Split the data in folds for cross validation
for train_idx, valid_idx in kfold.split(X, y):
    train_cv, valid_cv = X[train_idx], X[valid_idx]
    # Classifier with a single pass over the data 
    clf = VWClassifier(passes=1, convert_to_vw=False)
    # This will work
    clf.fit(train_cv)
    print('done with a single pass')

    # Classifier with a 3 passes over the data  (i.e. reshuffling should take place)
    clf = VWClassifier(passes=3, convert_to_vw=False)
    # This will still work
    clf.fit(train_cv.values)
    print('done with 3 passes on np.array')
    # This will NOT work
    print('Current indices: ' + str(train_cv.index.values))
    clf.fit(train_cv)
    print('done with 3 passes on pd.Series')
```
The output is:
```python 
done with a single pass
done with 3 passes on np.array
Current indices: [2 3]

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-12-43a4b42f3a13> in <module>()
     26     # This will NOT work
     27     print('Current indices: ' + str(train_cv.index.values))
---> 28     clf.fit(train_cv)
     29     print('done with 3 passes on pd.Series')

~/anaconda2/envs/Titanic/lib/python3.5/site-packages/vowpalwabbit/sklearn_vw.py in fit(self, X, y, sample_weight)
    306         for n in range(self.passes_):
    307             if n > 1:
--> 308                 np.random.shuffle(X)
    309             for idx, x in enumerate(X):
    310                 model.learn(x)

mtrand.pyx in mtrand.RandomState.shuffle()

mtrand.pyx in mtrand.RandomState.shuffle()

~/anaconda2/envs/Titanic/lib/python3.5/site-packages/pandas/core/series.py in __getitem__(self, key)
    621         key = com._apply_if_callable(key, self)
    622         try:
--> 623             result = self.index.get_value(self, key)
    624 
    625             if not is_scalar(result):

~/anaconda2/envs/Titanic/lib/python3.5/site-packages/pandas/core/indexes/base.py in get_value(self, series, key)
   2558         try:
   2559             return self._engine.get_value(s, k,
-> 2560                                           tz=getattr(series.dtype, 'tz', None))
   2561         except KeyError as e1:
   2562             if len(self) > 0 and self.inferred_type in ['integer', 'boolean']:

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_value()

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_value()

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.Int64HashTable.get_item()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.Int64HashTable.get_item()

KeyError: 0

```

**Comment by mlisovyi** [comment]
@JohnLangford is there some developer who would be responsible for the python binding and the sklearn API in particular? It would be interesting to get some insights on this and 2 other issues...

**Comment by JohnLangford** [comment]
Thanks.  @gramhagen is the most expert person here.  I agree we should try to pin this down.

**Comment by Scott-Graham-Bose** [comment]
Hi thanks again for digging into this!

1. yes you're right, should be >=
2/3. I think the best way to handle this is to use sklearn.utils.shuffle instead of np.random.shuffle, this creates a new object (so we don't mess up the original reference), and it handles pandas objects as well as np arrays and lists.

Would you like to make those changes? Adding in unit tests to catch that would be great too since you've already provided a working example.
