### ISSUE TITLE
Java API seems to be asynchronous with no way to sync

### ISSUE THREAD

**Issue by pferrel** [JohnLangford/vowpal_wabbit#1483]
We use `VWLearners.create(initVWConfig)` to create or re-start a leaner. All is fine with this.

The problem comes if you have many models in a multi-threaded system, where they must be created and deleted based on application needs. There is no Java API to `VWLearners.delete(initVWConfig)`. The nearest thing is to `vw.close()` an instance. This however seems to be asynchronous because it will write the model file at some point after `vw.close()` is called. We know this because we delete the model file just after close and it re-appears shortly after.

Avoiding `vw.close()` seems to be the only way to remove the learner from our system but we worry it is not truly gone from VW, which may keep model specific information causing possible memory leaks or ???

Is there a way to cleanly/synchronously remove a model from VW with JNI?

**Comment by pferrel** [comment]
@jon-morra-zefr @deaktator any opinion? Am I on wrong?

**Comment by deaktator** [comment]
The reason I asked was my suspicion that you had "--passes" in your argument string. So the closing code in Java is synchronous but it delegates to native code.  Whether the underlying C code is synchronous, I am not 100% sure. Someone else could better attest to this.

When calling close on the JVM, the 2...N passes are completed. But whether the c code returns before the passes are completed, I can't guarantee.  @JohnLangford, do you know? Maybe we need to add some kind of asynchronous barrier.  @pferrel can you provide an example (<10 lines or so) to validate what you're seeing with models being written after closing?

**Comment by pferrel** [comment]
@deaktator Ok I can work on that simple code. It's part of a bigger system right now. But in the simplest case it is:

```scala
val vw = createVW(params)
// time passes but no input
vw.close()
if (Files.exists(Paths.get(modelPath)) && !Files.isDirectory(Paths.get(modelPath)))
  while (!Files.deleteIfExists(Paths.get(modelPath))) { logger.info("tried to delete model, will try again")}
```

This deletes the model file on the first try but it reappears later, causing problems.

Our work around is to not call `vw.close()` and so the other part of my question is; how does VW coordinate which models are active and cleanup those that are not? Do we need to tell the C code that a model is defunct? Is avoiding the close going to cause VW to accumulate zombie models?

**Comment by deaktator** [comment]
@pferrel can you answer both of the following:

1. Does this issue occur when no training examples are provided?
2. Does this issue occur when at least one training example is provided?

**Comment by pferrel** [comment]
@deaktator 
 1. yes
 2. yes

**Comment by pferrel** [comment]
ok, it will take a bit to pair down a simple app from where we are.

BTW do you know how to tell VW that a model is not used anymore? Is the only way `vw.close()`?

**Comment by ryan-deak-zefr** [comment]
Tried the following which passes.

```java
    @Test
    public void testClosingStuff() throws Exception {
        final File modelFile = File.createTempFile("ClosingTest", "outputmodel.bin.vw");
        modelFile.deleteOnExit();
        final String modelPath = modelFile.getCanonicalPath();
        final String command = "--csoaa 10 -b 24 --l2 0.0 -l 0.1 -c -k --passes 100 -f " + modelPath + " --save_resume";

        // Create a learner and just have it take 1 example, but many passes.
        vowpalWabbit.learner.VWMulticlassLearner vw = VWLearners.create(command);

        Thread.sleep(500);

        vw.close();

        boolean deletedAlready = false;
        long time = System.currentTimeMillis();

        final File mf = new File(modelPath);

        if (mf.exists() && !mf.isDirectory()) {
            do {
                if (mf.exists()) {
                    if (deletedAlready)
                        fail();
                    mf.delete();
                    deletedAlready = true;
                }
            } while(mf.exists() || time + 10000 > System.currentTimeMillis());
        }
    }
```

**Comment by JohnLangford** [comment]
The underlying c code is synchronous.

**Comment by deaktator** [comment]
So I have no idea what's going on if the underlying code is synchronous. I need to be convinced because I have never seen this phenomena.

**Comment by pferrel** [comment]
yeah, got it the burden of proof is on me...

**Comment by pferrel** [comment]
@deaktator @JohnLangford Just to close this. We must have gotten VW, our app, or the models in a bad state. when we rebooted the machine. cleared all model files, and our DBs our automated tests started passing. 

We are able to `vw.close()` then delete the model file. We assume that every close will erase the learner from VW and only resuming it from the model file will re-instate it. Therefore we at all good. 

Thanks for responding, sorry for waisting your time.
