### ISSUE TITLE
Bug constructing label from example in pyvw.py

### ISSUE THREAD

**Issue by aadyotb** [JohnLangford/vowpal_wabbit#1484]
In the `from_example()` method of the classes `cost_sensitive_label` and `cbandits_label` in `pyvw.py`, you have the following for loops on lines 465 and 495, respectively:
```
for i in range(ex.get_costsensitive_num_costs):
...
```
and
```
for i in range(ex.get_cbandits_num_costs):
...
```

This results in a crash because the objects in the `range(...)` are methods, not integers. An easy fix is to just replace these calls with
```
for i in range(ex.get_costsensitive_num_costs()):
...
```
and
```
for i in range(ex.get_cbandits_num_costs()):
...
```
respectively.

**Comment by JohnLangford** [comment]
@Scott-Graham-Bose your thoughts?   A patch is welcome.

**Comment by Scott-Graham-Bose** [comment]
yep, that's an easy fix

**Comment by gramhagen** [comment]
should be all set now, thanks @aadyotb

**Comment by JohnLangford** [comment]
Thanks @gramhagen and @aadyotb .
