### ISSUE TITLE
VWBase.isOpen should be volatile

### ISSUE THREAD

**Issue by ryan-deak-zefr** [JohnLangford/vowpal_wabbit#1486]
[VWBase.isOpen](https://github.com/JohnLangford/vowpal_wabbit/blob/master/java/src/main/java/vowpalWabbit/learner/VWBase.java#L21) should be volatile.

This should help to avoid concurrency issues related to closing models in multithreaded environments.

```java
private volatile boolean isOpen;
```

**Comment by JohnLangford** [comment]
Interesting.   Send a pull request to be precise?

**Comment by deaktator** [comment]
Will so soon.

**Comment by JohnLangford** [comment]
Status on this?  I want to release a new version in the next few days.

**Comment by JohnLangford** [comment]
The URL seems to be specific enough---I'm rolling this into my working fixes patch.
