### ISSUE TITLE
Contextual bandit: in DM, not the same predictions with/without allowed actions specified

### ISSUE THREAD

**Issue by raphaelberly** [JohnLangford/vowpal_wabbit#1504]
I was trying to understand deeper the way VW contextual bandits work and I found something intriguing on a toy example: with direct method, the predictions are not the same if I specify the allowed actions and when I do not.

#### Train data:
```
1:10:0.5 | a
2:-10:0.5 | a
1:-10:0.5 | b
2:10:0.5 | b
```
So, the best action for `a` should be 2 and the best action for `b` should be 1.

Using the `--invert_hash` option, I see in the model that it should work, the weights are exactly as expected:

#### Command
`vw --cb 2 --cb_type dm -f cb.model --noconstant -d data_1.txt --invert_hash inverted.txt `

#### Output model (inverted.txt)
```
[...]
a:185188:0.68253
a[1]:185189:-0.68253
b:64518:-0.68253
b[1]:64519:0.68253
```

However, using basic predict data, the result is not the expected one:

#### Command
`vw -t -d predict.txt -i cb.model -p output.txt`

#### Predict data (predict.txt)
```
 | a
 | b
```

#### Predictions (output.txt)
```
1
1
```

Given the input data and the resulting model, these predictions seem not to be right.

## Specifying the allowed actions...

However, when I specify the actions in the "predict.txt" data, the output changes and is the the expected one:

#### Predict data (predict.txt)
```
1 2 | a
1 2 | b
```

#### Predictions (output.txt)
```
2
1
```
... which is the expected prediction.

## Question

Is there something I misunderstand about this all, or is there something wrong?

**Comment by JohnLangford** [comment]
This seems like a real issue---looking into it.

**Comment by JohnLangford** [comment]
This seems to already be fixed in the current master.
