### ISSUE TITLE
Java jni for a vw 8.5.0 from a repository

### ISSUE THREAD

**Issue by AlphaOlish** [JohnLangford/vowpal_wabbit#1507]
Hello! 

Is there a jni file for the version 8.5.0, ubuntu 16 and 64 bit (vw_jni.Ubuntu.16.amd64.lib or .so) somewhere?
I should have the same version for java and python, but I found only 8.4.1 for java (here: https://mvnrepository.com/artifact/com.github.johnlangford/vw-jni) and 8.4.0 - for python (here: https://github.com/JohnLangford/vowpal_wabbit/tags). 
I've created .so file for java in the Ubuntu 16 container for 8.5.0 version. But this solution does not suit me - it's not possible for now to re-build the library every time. 

Maybe somebody knows answers on my questions: 
1) Could Java8_vw8.4.1 version read without problem models generated in python3_vw8.4.0? 
2) Or where can I find the jni for 8.5.0?

**Comment by JohnLangford** [comment]
For 1), almost surely yes.  For 2), @deaktator @jmorra what is the current java version for VW?

**Comment by jmorra** [comment]
We have not done a Java release for 8.5.0.  Assuming the JNI interface hasn't changed it all should work.  I feel medium confident saying this is the case as we have tests that ensure this interface is broken.  The ramifications of this are that you can use the 8.4.1 public jar backed by the newest version of the shared library and it should work fine.

**Comment by AlphaOlish** [comment]
Thank you!
