### ISSUE TITLE
8.6.0 release still says it is 8.5.0 when asked

### ISSUE THREAD

**Issue by matanster** [JohnLangford/vowpal_wabbit#1537]
## Reproducing steps:

1. Get the compressed source from the releases page
2. Decompress and cd to `vowpalwabbit-8.6.0`
3. `make`
4. `vowpalwabbit/vw --version`

The output:

> 8.5.0

**Comment by JohnLangford** [comment]
Well, that's embarrassing.  Fixed and updated to 8.6.1.  Thanks :-)

**Comment by matanster** [comment]
Not that embarrassing ... unless the entire process is automated it's hard to avoid.

**Comment by JohnLangford** [comment]
I just did 8.6.1 because redoing a release creates ambiguities (which
8.6.0?) that are best avoided.

-John

**Comment by matanster** [comment]
That's typically the right thing to do
