### ISSUE TITLE
Multi-class classification problem

### ISSUE THREAD

**Issue by aboelhamd** [JohnLangford/vowpal_wabbit#1563]
Our problem statement or example is as follows :

We have those ambiguous sentences with their translation rules (42,43&44) :

42. NOUN1 de NOUN2 -> NOUN2 NOUN1

43. NOUN1 de NOUN2 -> NOUN1 of NOUN2

44. NOUN1 de NOUN2 -> the NOUN2 's NOUN

Their Normalised LM score :

millones de euros/42 -> euros millions          0.1

millones de euros/43 -> millions of euros      0.8

millones de euros/44 -> the millions' euros    0.1

umbral de pobreza/42 -> poverty threshold           0.6

umbral de pobreza/43 -> threshold of poverty       0.3

umbral de pobreza/44 -> the poverty's threshold   0.1

fuerzas de seguridad/42 -> security forces           0.8

fuerzas de seguridad/43 -> forces of security       0.15

fuerzas de seguridad/44 -> the security's forces   0.05

papel de aventurero/42 -> adventurer role             0.3

papel de aventurero/43 -> role of adventurer         0.3

papel de aventurero/44 -> the adventurer's role     0.4

Ok, so we need to provide to the learner:

! COUNT !! LABEL  !! PATTERN                !! FEATURES

! 0.1        !! 42         !! NOUN DE NOUN     !! 0:millión 1:de 2:euro

! 0.8        !! 43         !! NOUN DE NOUN     !! 0:millión 1:de 2:euro

! 0.1        !! 44         !! NOUN DE NOUN     !! 0:millión 1:de 2:euro

! 0.6        !! 42         !! NOUN DE NOUN     !! 0:umbral 1:de 2:pobreza

! 0.3        !! 43         !! NOUN DE NOUN     !! 0:umbral 1:de 2:pobreza

! 0.1        !! 44         !! NOUN DE NOUN     !! 0:umbral 1:de 2:pobreza

.............

And we expect an output like this 
a list 
of weights for each feature/label

0:umbral/42 = 1.0054
1:de/42 = 0.0
2:pobreza/42 = 1.014
0:umbral/43 = 1.0044
1:de/43 = 0.0
2:pobreza/43 = 1.004
0:umbral/44 = 1.001
1:de/44 = 0.0
2:pobreza/44 = 1.003
...........

------------------------------------------------------------

I tried using wap_ldf and csoaa_ldf , but it is still bit confusing. The input format for training and predicting is not clear enough for me.

My initial data-set is this :

13:0.5767 12:0.4233 | ұр
13:0.5427 12:0.4573 | тап
13:0.5014 12:0.4986 | жаса
13:0.5308 12:0.4692 | кір
13:0.555 12:0.445 | дамы
13:0.4978 12:0.5022 | тасы
13:0.5018 12:0.4982 | басқар
13:0.4956 12:0.5044 | сайла
13:0.544 12:0.456 | өткіз
13:0.5004 12:0.4996 | орнат
13:0.5014 12:0.4986 | жаса
13:0.5188 12:0.4812 | қос

and I make that format out of that csv data-set

COUNT	LABEL	PATTERN	FEATURE0
0.5767	13	 	v-ger 	 	ұр  
0.4233	12	 	v-ger  		ұр  
0.5427	13	 	v-ger  	 	тап  
0.4573	12	 	v-ger  	 	тап  
0.5014	13	 	v-ger  	 	жаса  
0.4986	12	 	v-ger  	 	жаса  
0.5308	13	 	v-ger  	 	кір  
0.4692	12	 	v-ger  	 	кір  
0.555	13	 	v-ger  	 	дамы  
0.445	12	 	v-ger  	 	дамы  
0.4978	13	 	v-ger  	 	тасы  
0.5022	12	 	v-ger  	 	тасы  
0.5018	13	 	v-ger  	 	басқар  
0.4982	12	 	v-ger  	 	басқар  
0.4956	13	 	v-ger  	 	сайла  
0.5044	12	 	v-ger  	 	сайла  
0.544	13	 	v-ger  	 	өткіз  
0.456	12	 	v-ger  	 	өткіз  
0.5004	13	 	v-ger  	 	орнат  
0.4996	12	 	v-ger  	 	орнат  
0.5014	13	 	v-ger  	 	жаса  
0.4986	12	 	v-ger  	 	жаса  
0.5188	13	 	v-ger  	 	қос  
0.4812	12	 	v-ger  	 	қос  

--------------------------------------------------
Then I trained the data with command "vw --csoaa_ldf m < csldf.txt"
And then predict test data with command "vw test.txt -p csldf.predict"
Where we want to predict the weight of features "жаса" & "тасы" for labels 12 & 13

Where the test data was
13 | жаса
12 | жаса
13 | тасы
12 | тасы

and the prediction was
0
0.688057
0.571441
1.119427
0.931935

But if I reordered the lines of the test data as
12 | жаса
12 | тасы
13 | жаса
13 | тасы

The prediction was
0
0.343257
0.926638
1.130945
0.959539

---------------------------
So are these formats and results are consistent with the problem I stated above, your help will be appreciated and thanks in advance.

**Comment by JohnLangford** [comment]
Is each line supposed to be a different example here?

**Comment by aboelhamd** [comment]
Each line in the dataset ? 
Each two consecutive lines supposed to be for the same original sentence and their weights should aim to one .

I hope that answers your question.

**Comment by JohnLangford** [comment]
Your format is consistent with a non-LDF example, so at a minimum you should use --csoaa or change to the LDF format.

**Comment by aboelhamd** [comment]
I used this command to train with train data mentioned earlier
`vw -d train.txt --csoaa 2 --passes 5 -c -k -f m1.model --l2 0.000001`

 And then used that to predict with the test data mentioned earlier too
` vw -t -d test.txt -i m1.model -r p1.predict`

And It gave me that result :
13:0.530169
12:0.516587
13:0.519988
12:0.519859

But when I tried to change the order of the lines in the train data , I got another results. Is that supposed to be right ?

The  new result :
13:0.600562
12:0.557692
13:0.541575
12:0.518164

And is there an option in wabbit that makes the model learn from the new test set as we use it in prediction ?

**Comment by arielf** [comment]
1) Answer to order of lines:  Yes, `vw` in an online (streaming) learner, not a batch learner.

Order can make a big difference.  The more passes you make, and the more you randomize order of examples inside the batches, the more it should resemble batch learning.

[e.g. see this answer on SO](https://stackoverflow.com/questions/24822288/correctness-of-logistic-regression-in-vowpal-wabbit/24832382#24832382)

2) Answer to option to learn while predicting: if the test-set is labeled, you can keep learning by dropping the `-t` (test only) option.

**Comment by arielf** [comment]
1) How many passes to convergence depends on the data.  You should look at the error column to get a feel for progress.  Also, if you use default options (i.e. don't use `--hodout_off`) , `vw` uses a 1 in 10 examples holdout and early stopping to avoid over-fitting.
2) See this page for multi-class input formats:  [http://users.umiacs.umd.edu/~hal/tmp/multiclassVW.html](http://users.umiacs.umd.edu/~hal/tmp/multiclassVW.html)

**Comment by aboelhamd** [comment]
Thank you very much Ariel.
Thank you very much John.
You were very helpful.
