### ISSUE TITLE
--invert_hash does not work with --oaa

### ISSUE THREAD

**Issue by martinpopel** [JohnLangford/vowpal_wabbit#337]
With older VW (7.4.0), the following code
```
    echo '1 | a b c
    3 | a d e' | vw --oaa 3 --invert_hash model.inv
    cat  model.inv
```
prints a nice inverted-hash model with lines like `^a:108232:0.046370`. With the newest VW, it does not work (no features are printed).

**Comment by KristianHolsheimer** [comment]
It seems that this issue is still present when using `--ftrl`. Could this also be caused by a similar ordering issue?

**Comment by JohnLangford** [comment]
It should work for --ftrl now.
