### ISSUE TITLE
Training Continuation Errors in PV and --Invert Hash

### ISSUE THREAD

**Issue by BrianMiner** [JohnLangford/vowpal_wabbit#401]
Given this training set in housing.vm:

<code>18.60 |  CRIM:0.22876 ZN:10.00</code>
 
<code>19.30 |  CRIM:0.21161 ZN:30.00 </code>

<code>20.10 |  CRIM:0.13960 ZN:50.00</code>

and this command training, saving the model to resume training :
<code>vw -d housing.vm --save_resume -f housing.mod</code>

all seems well. 

![capture](https://cloud.githubusercontent.com/assets/8807554/4314499/a0d92a60-3ee0-11e4-9e57-3903a6066ee0.JPG)

But then upon continuation of training with this data in housing_2.vm:

<code>78.60 |  CRIM:0.5400 ZN:0</code>

via this command

<code>vw -d housing_2.vm  -i housing.mod --invert_hash housing.txt</code>

the progressive loss doesn't make sense I don't think:

![capture](https://cloud.githubusercontent.com/assets/8807554/4314512/c7389fc4-3ee0-11e4-90de-789bbaee6c45.JPG)

Further, the result of housing.txt (from the --invert_hash) doesn't seem to carry through the ZN variable because it was zero in housing_2.vm. Should it not be instead, the same as the initial command?

![capture](https://cloud.githubusercontent.com/assets/8807554/4314528/01961368-3ee1-11e4-8a23-6484d98d9186.JPG)

**Comment by JohnLangford** [comment]
There was a bugfix for this, so I believe this is currently fixed.  Reopen if that's not true.
