### ISSUE TITLE
ngrams + varinfo creates bigrams that don't exist in original data

### ISSUE THREAD

**Issue by barrenWuffet** [JohnLangford/vowpal_wabbit#423]
http://stackoverflow.com/questions/26413990/vowpal-wabbit-varinfo-and-ngrams-non-existent-combinations

**Comment by JohnLangford** [comment]
I'm assuming this is a "won't fix" at the moment.

**Comment by arielf** [comment]
Yes. I have it on my todo, just didn't get a chance yet.  Will fix eventually.
