### ISSUE TITLE
Possible typo in documentation re:learning rate schedule

### ISSUE THREAD

**Issue by jarfa** [JohnLangford/vowpal_wabbit#473]
According to the [documentation](https://github.com/JohnLangford/vowpal_wabbit/wiki/Command-line-arguments), the learning rate is multiplied by (t_0 / (t_0 + w_t))^p . But since t_0 is by default 0, this would imply that the learning rate becomes 0.

Am I misunderstanding the role of this equation, or is there a typo? Thanks.

**Comment by JohnLangford** [comment]
(Not sure what to do, closing for now)
