### ISSUE TITLE
Strange warnings

### ISSUE THREAD

**Issue by leakyMirror** [JohnLangford/vowpal_wabbit#474]
I am running this command:

```bash
  vw \
    --data data/vw/train.vw \
    --loss_function squared \
    -f $model \
    --passes 300 \
    -q nn \
    -k \
    -c \
    --nn 15
```
and get lots of these:
```
You are using a label not -1 or 1 with a loss function expecting that!
```

Response variable is not binary and loss function is ```squared```, so where is the problem? I first thought that ```--nn``` is only for classification, but for this non-linear problem it gives best results.

**Comment by JohnLangford** [comment]
SHould be fixed.

**Comment by arielf** [comment]
Just confirmed that latest HEAD indeed fixes this.
Thanks John.
