### ISSUE TITLE
ftrl: progressive_validation file

### ISSUE THREAD

**Issue by trufanov-nok** [JohnLangford/vowpal_wabbit#480]
It looks like vw creates --progressive_validation file whenever --ftrl mode is used. In case --progressive_validation param isn't specified it uses "ftrl.evl" file by default. That's because
``if (vm.count("progressive_validation"))``
in FTRL::setup() is always true for params with default values.
There should be a way to launch ftrl without creation of this file. Let's remove default value for --progressive_validation in parse_args.cc

**Comment by JohnLangford** [comment]
I rewrote the ftrl code for speed/simplicity, eliminating the "progressive
validation" flag.  To achieve the same behavior, you can use --link
logistic and -p <filename>.

-John

**Comment by JohnLangford** [comment]
Should be deal with.
