### ISSUE TITLE
Proposal: addition of cache_file support to vw-hypersearch

### ISSUE THREAD

**Issue by trufanov-nok** [JohnLangford/vowpal_wabbit#484]
Hi Ariel,

Could you consider addition of cache_file parameter support to vw-hypersearch? I mean that vw can work without dataset file or test file specified if --cache_file is specified in command line. In my case I've modified my dataset file with unix sed utility which made some regexp substitutions for every line and pipe it to stdin of vw. The result was saved to cache file. it was like ``sed -e 's/exp_to_replace/exp/' dataset.vw | vw -b 28 --cache_file dataset.cache``
Now I would like to work with cache only instead of applying sed to dataset every time.
Currently vw-hypersearch can work in test mode with files only and doesn't allow to specify their cache.
I suggest addition of new param -c to vw-hypersearch which will switch vw-hypersearch in test mode like -t param (even if -t param isn't specified) and insert " --cache_file $opt_c " to the test part of command line. For example:
``vw-hypersearch -v -c test.cache -t test.vw 0.005 0.03 vw -l % -f temp.model --cache_file train.cache``
will be resolved as 
``vw -l 0.015 -f temp.model --cache_file train.cache && vw -t test.vw -i temp.model --cache_file test.cache``
and 
``vw-hypersearch -v -c test.cache 0.005 0.03 vw -l % -f temp.model --cache_file train.cache``
will be resolved as 
``vw -l 0.015 -f temp.model --cache_file train.cache && vw -i temp.model --cache_file test.cache``
(no -t specified in last case)

I've done required changes in my copy of script (based on $opt_t usage) and it works as I expected so it's not a critical problem for me. But my knowledge of python doesn't let me to get rid of some warning messages which python prints to the stdout for every  generated command call.

**Comment by JohnLangford** [comment]
This seems reasonable to me.

-John

**Comment by arielf** [comment]
Hi Alex,

Sure.  NP.
Since you already made the change and tested it, would you mind sending a pull request to John?

**Comment by trufanov-nok** [comment]
Ariel,
I've just added ``$opt_c`` wherever I found ``$opt_t`` in script replacing ``if($opt_t)`` with ``if ($opt_t || $opt_c)`` and added ``push(@ARGV, " --cache_file " ,$opt_c);`` after ``push(@ARGV, $opt_t);`` It's just a several lines of code and it works but I'm getting warnings:
```
vw-hypersearch: -L: using log-space search
trying 0.0151319161282584 Use of uninitialized value $c in substitution (s///) at ../vowpal_wabbit/utl/vw-hypersearch line 176.
Use of uninitialized value in join or string at ../vowpal_wabbit/utl/vw-hypersearch line 74.
................................................. 0.390626 (best)
trying 0.00991282258826957 Use of uninitialized value $c in substitution (s///) at ../vowpal_wabbit/utl/vw-hypersearch line 176.
Use of uninitialized value in join or string at ../vowpal_wabbit/utl/vw-hypersearch line 74.
..................^C
```
I'm planning to improve my python in a next 6 month but currently i can't find the reason of these warnings and I don't feel in my own right to push commits into python code.

**Comment by arielf** [comment]
Ah, ok.  Let me try to do it.
BTW: it is perl, not python :)

**Comment by trufanov-nok** [comment]
Hah! indeed :) lol

**Comment by arielf** [comment]
Sent pull request:

https://github.com/JohnLangford/vowpal_wabbit/pull/485

Can you try it and approve?

**Comment by trufanov-nok** [comment]
It seems to work as expected.
