### ISSUE TITLE
vw 7.9.0 output empty raw predictions file with oaa

### ISSUE THREAD

**Issue by brookwc** [JohnLangford/vowpal_wabbit#503]
I tried to the toy oaa.dat example from:
(https://github.com/JohnLangford/vowpal_wabbit/wiki/One-Against-All-%28oaa%29-multi-class-example)
1 ex1| a
2 ex2| a b
3 ex3| c d e
2 ex4| b a
1 ex5| f g

Everything worked fine except when I tried to turn on --raw_predictions. I always got empty raw predictions file back.

// train
vw --oaa 5 -f model -d oaa.dat

// test
vw -t -i model -d oaa.dat -p r1 --raw_predictions r2

This is on mac os x 10.10 (yosemite). Is this a known issue or I have missed some steps?

Thanks in advance,
Kevin

**Comment by JohnLangford** [comment]
Should be fixed now.
