### ISSUE TITLE
Logistic loss function doesn't work with --oaa when using --passes

### ISSUE THREAD

**Issue by yankov** [JohnLangford/vowpal_wabbit#522]
This will work:

vw -d train.vw --oaa 9 --loss_function logistic -f predictor.vw

But this will throw "You are using a label not -1 or 1 with a loss function expecting that!":

vw -d train_bow.vw --oaa 9 -c --passes 10 --loss_function logistic -f predictor.vw

**Comment by arielf** [comment]
Thanks for the report.

To help others reproduce we need a fully reproducible example, so:

I can reproduce this with latest (just pulled John's head).  Using the multiclass trainset in the tree:
```
# works:
$ vowpalwabbit/vw -k --oaa 10 test/train-sets/multiclass --loss_function logistic

# When adding '-c --passes 2` vw doesn't like the non-binary labels
$ vowpalwabbit/vw -k --oaa 10 test/train-sets/multiclass --loss_function logistic -c --passes 2
...
You are using a label not -1 or 1 with a loss function expecting that!
```

I understand the reduction from multiclass to oaa should have made `logistic` possible.

**Comment by JohnLangford** [comment]
Fixed, thanks.

**Comment by dschwertfeger** [comment]
I have the same problem with 7.10.0 on OS X installed with Homebrew. In which version was this supposed to be fixed?

**Comment by JohnLangford** [comment]
This is certainly fixed in the current master.

-John


On Sat, May 9, 2015 at 9:38 AM, David Schwertfeger <notifications@github.com

**Comment by dschwertfeger** [comment]
Thanks for your quick response! 

Looks like the tarball the [homebrew formular](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/vowpal-wabbit.rb) links to was build on February 14. Just a few days before the fix.

Guess I'll build from master then for now.
