### ISSUE TITLE
Zsh is a prerequisite

### ISSUE THREAD

**Issue by shyamsalimkumar** [JohnLangford/vowpal_wabbit#527]
```
shyam@shyam-system:~/Softwares/vowpal_wabbit/demo/mnist$ make mnist.test.confusion
ERROR: you need to install zsh
make: *** [zsh.check] Error 1
```

Uhm... why is this a prequisite?

**Comment by arielf** [comment]
Because the shell scripts in the `demo/mnist` directory are  `#! /bin/zsh`.
This can be changed of course since the differences between zsh and bash aren't big, but someone who cares about this issue will have to volunteer to do the work and test.

**Comment by JohnLangford** [comment]
Closing for now.
