### ISSUE TITLE
Which cross features added by --stage_poly?

### ISSUE THREAD

**Issue by mbowiewilson** [JohnLangford/vowpal_wabbit#529]
I was wondering if anyone could help me figure out which features were being added during the adaptive polynomial expansion. I'm struggling with this particularly because I find that vw-varinfo and --invert_hash do not seem to work when the --stage_poly setting is invoked.  Any help would be welcomed! Thanks!

**Comment by arielf** [comment]
Try `--audit` ?

**Comment by mbowiewi** [comment]
Thanks for the prompt response @arielf. Unfortunately, I have not able to make `--audit` work as I would like with the `--stage_poly` flag. When I do `--audit` (or `--invert_hash`) along with `--stage_poly` I get outputs that look like: `197583:1:-0.134966@0.00174596`

On the other hand,  when I do `--audit` (or `--invert_hash`) without `--stage_poly` I get outputs that look like: `namespace^feature:197583:1:-0.134966@0.00174596`

Assuming the namespace for polynomial features is interpretable then if I could make `--audit` or `--invert_hash` work as desired with `--stage_poly` then I believe it would be simple to figure out which polynomial features are being added by `-stage_poly`.

**Comment by mbowiewi** [comment]
Specifically, in the function `audit_feature` in `gd.cc` the `audit_data` pointer `a` appears to be null when using `--stage_poly` but I do not know why..

**Comment by arielf** [comment]
This may be a bug or a limitation of reductions.  Thanks for digging into it.

**Comment by mbowiewi** [comment]
I believe it may have to do with how the "synthetic example" is created from the "original example" in the `stagewise_poly` struct in `stagewise_poly.cc`. I would love it if anyone more knowledgable about this section of code could help me figure out a hack to make this work. Thanks in advance!

**Comment by JohnLangford** [comment]
The corer issue here is that the stagewise_poly.cc code doesn't have a 
slow path to create audit features.  This could be fixed, and it's 
probably desirable to do so for usability.

-John

**Comment by ekg** [comment]
What would need to happen to resolve this? I can look into it as I'm interested in an application that requires this functionality.

@JohnLangford do you have a line reference to an implementation of the "slow path to create audit features"? I'd like to get a sense of what's required.

**Comment by JohnLangford** [comment]
Look here: https://github.com/JohnLangford/vowpal_wabbit/blob/master/vowpalwabbit/lrq.cc#L111 for an example of creating audit features.

**Comment by JohnLangford** [comment]
I'm closing this for now.  A Pull Request is welcome.  @alekh for reference.
