### ISSUE TITLE
is it possible to pass multiple model to prepare new model 

### ISSUE THREAD

**Issue by maneeshdisodia** [JohnLangford/vowpal_wabbit#536]
i have multiple model created like every 7 day interval. can i combine all the model in one model.
all model is created with market trends as input.

thanks

**Comment by maneeshdisodia** [comment]
after searching i got this: 
vw dataset  --save_resume -f new.model -i old.model

please can u please explain, exactly want happen in this case.

thanks

**Comment by JohnLangford** [comment]
--save_resume just saves the state so that you can resume learning 
exactly where it left off.

For general model combining, there is no support, because the semantics 
of how to combine things is unclear.

-John

**Comment by maneeshdisodia** [comment]
thanks John
