### ISSUE TITLE
test 61 fails

### ISSUE THREAD

**Issue by bremen79** [JohnLangford/vowpal_wabbit#538]
Test 61 from "make test" fails with the following error:
test 61: '/usr/bin/timeout 30 ./daemon-test.sh' failed (exitcode=1)

Anyone has any idea what is this?

**Comment by arielf** [comment]
Yes, this means the daemon test was run and the tester hasn't gotten a response from the deamon after 30 seconds.  It used to happen in the past in envs with firewalls or when running in a VM or where the `netcat` utility was incompatible with expectations.

- Which environment this is running in?
- Are you using latest code?

Your `vw` is probably fine.  This is a test that seem to be relatively dependent on the environment it is running on.

You may debug this by running the daemon test standalone with shell debugging turned-on:

```
bash -x test/daemon-test.sh
```

And post the output here.

**Comment by bremen79** [comment]
Latest version now fails on test 59, this is the output I get:
RunTests: ../library/ezexample_predict: No such file or directory
RunTests: failed to run test line:
        ../library/ezexample_predict models/library_train.w

RunTests: test lines must be one of the following:
        shell command to run
        vw command to run: {VW} ...
        stdout reference:  *.stdout
        stderr reference:  *.stderr
        predict reference: *.predict
RunTests: test 59: command is undefined
make: *** [test] Error 2

Also, the command bash -x test/daemon-test.sh
returns 
+ NAME=vw-daemon-test
+ export PATH=vowpalwabbit:../vowpalwabbit:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/bin:/usr/games:/usr/local/sbin:/usr/sbin:/home/francesco/.local/bin:/home/francesco/bin
+ PATH=vowpalwabbit:../vowpalwabbit:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/bin:/usr/games:/usr/local/sbin:/usr/sbin:/home/francesco/.local/bin:/home/francesco/bin
++ which vw
+ VW=/home/francesco/cProjects/vowpal_wabbit/vowpalwabbit/vw
+ MODEL=vw-daemon-test.model
+ TRAINSET=vw-daemon-test.train
+ PREDREF=vw-daemon-test.predref
+ PREDOUT=vw-daemon-test.predict
+ PORT=54248
+ '[' -x /home/francesco/cProjects/vowpal_wabbit/vowpalwabbit/vw ']'
+ : cool found vw at: /home/francesco/cProjects/vowpal_wabbit/vowpalwabbit/vw
++ which netcat
which: no netcat in (vowpalwabbit:../vowpalwabbit:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/bin:/usr/games:/usr/local/sbin:/usr/sbin:/home/francesco/.local/bin:/home/francesco/bin)
+ NETCAT=
+ '[' -x '' ']'
+ echo 'vw-daemon-test: can not find '\''netcat'\'' in vowpalwabbit:../vowpalwabbit:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/bin:/usr/games:/usr/local/sbin:/usr/sbin:/home/francesco/.local/bin:/home/francesco/bin - sorry'
vw-daemon-test: can not find 'netcat' in vowpalwabbit:../vowpalwabbit:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/bin:/usr/games:/usr/local/sbin:/usr/sbin:/home/francesco/.local/bin:/home/francesco/bin - sorry

So, it seems that my corporate Fedora distribution does not have netcat installed by default.

**Comment by arielf** [comment]
- Test #59 fails: you need to `make library_example` for ` ../library/ezexample_predict` to be there, before running `make test`
- `netcat` missing: ask your sysadmin to install it(?) The package name on Ubuntu is `netcat-openbsd` if this helps.

**Comment by bremen79** [comment]
The following fails at test #59

    make clean
    make
    make test
and

    make library_example
returns
make: *** No rule to make target `library_example'.  Stop.

Am I missing something or I should follow a different procedure?

**Comment by arielf** [comment]
Did run `autogen.sh` py any chance and lost the original `Makefile` ?
autogen is a bit broken at present.
See: https://github.com/JohnLangford/vowpal_wabbit/issues/540

```
$ grep library_example Makefile
all: vw spanning_tree library_example java
library_example: vw
```

As for `nc`: the question is does it behave the same?
Can you provide a patch for `daemon-test.sh`?
Thanks.

**Comment by arielf** [comment]
https://github.com/JohnLangford/vowpal_wabbit/pull/543 should fix two of these issues.

**Comment by arielf** [comment]
I think this can be closed now.

**Comment by bremen79** [comment]
Thanks for the fix.

Re: test 59, autogen was indeed the problem. With the original makefile it works.

Re: test 61, I downloaded the latest version with your patch, but here (on 2 different computers) still it does not work. The problem seems to be that 

    nc localhost

returns
    
    Ncat: Connection refused.

I will try to see if I can find a way to fix it.

**Comment by JohnLangford** [comment]
This sounds like a local access control issue that I don't see a good way around.
