### ISSUE TITLE
Leftover cruft in the VW build system

### ISSUE THREAD

**Issue by bscottm** [JohnLangford/vowpal_wabbit#540]
There's a lot of old cruft leftover in the VW build system. Doesn't look like the library/Makefile has been regenerated in ages -- implying that anyone who runs `autogen.sh` will never be able to `make test` successfully because `Makefile.am` doesn't have those extra targets, like `ezexample_predict`.

Likewise, vowpalwabbit/config.h.in hasn't been regenerated in ages and is likely behind a few things that `configure` would like to probe for. Like largefile support.

I do have a patch, but... the patch will no longer allow users to "build out of the box" with a simple `make`. The user would have to run `configure` followed by `make`:

```
$ ./configure   # with whatever flags they need
$ make
$ make test     # optional.
```

**Comment by JohnLangford** [comment]
VW has 3 build systems---one based on 'make', one based on autogen.sh, 
and one based on visual studio.

Why?

(1) Well, make/autogen.sh does not handle windows build, hence VS.

(2) I found autogen.sh awkward to use effectively.  You can't checking 
the configure script effectively when working on multiple platforms, 
which means you need to regenerate things on every platform, but that 
means a substantial additional dependency. It's much nicer to be able to 
just type 'make'.

There are real downsides---autogen tends to lag the 'make' build, and 
all of these tend to incur additional overhead.  But... what is a better 
solution?

-John

**Comment by bscottm** [comment]
Sounds like the answer is cmake. :-)

Not sure that you want to transition to `cmake` just yet. The advantage is that it will create both `make`-based and VS-based development environments. The disadvantage is that you have an extra dependency, `cmake`, and an extra step when adding new source.

`autogen.sh` is reasonably useful if you actually change `Makefile.am` or `configure.ac` in some way. However, the user shouldn't have to run `autogen.sh` unless they're a developer -- the `configure` script does all of the hard work.

I have a reasonable patch, albeit a large one, that updates the `autotools`-based build system. Major caveat: Python and Java have to be explicitly enabled.

**Comment by bscottm** [comment]
See PR 544

**Comment by JohnLangford** [comment]
Closing this one for now.  A better build system remains desirable, but the tradeoffs seem difficult so far.

**Comment by bscottm** [comment]
I'm working on a cmake-based build system. Nick has been helping to test it, but it's not ready for prime time yet.

**Comment by JohnLangford** [comment]
Sounds interesting.

-John
