### ISSUE TITLE
poor name choice: vowpalwabbit/memory.h

### ISSUE THREAD

**Issue by bscottm** [JohnLangford/vowpal_wabbit#545]
This name conflicts with a standard header file, <memory.h>, present on more than a few Unix platforms. Likely to cause unexpected compile issues that are hard to track down.

**Comment by JohnLangford** [comment]
Is there evidence that this is a problem?  I though <> and "" are distinct enough?  

Anyways, send a pull request if this disturbs you.

**Comment by JohnLangford** [comment]
s/distinct/disambiguating

**Comment by bscottm** [comment]
Not as yet. It's not particularly "disturbing" to me, but for a relative n00bie, it's easy to file bug reports due to an apparent, if erroneous, naming conflict. Preventative maintenance suggestion.

OTOH, it goes away when calloc_or_die<> goes away.
