### ISSUE TITLE
low rank cubic features?

### ISSUE THREAD

**Issue by zachmayer** [JohnLangford/vowpal_wabbit#550]
I've been using the --lrq=ab1 feature a lot lately, and love it.  I was wondering, is something similar possible for cubic interactions?  Or should I break them down into 3 quadratic interactions?

**Comment by JohnLangford** [comment]
Nothing at the moment.

-John

**Comment by pmineiro** [comment]
lrcubic could be implemented using a similar strategy to lrq ("stochastic alternating minimization"), but we haven't done so.  if you want to start with lrq.cc and hack up an lrcubic.cc, we would definitely accept the patch.  feel free to email me (paul.mineiro at gmail.com) if you have questions about how lrq.cc works.

**Comment by zachmayer** [comment]
@pmineiro Unfortunately, I'm just starting to learn C++.  As soon as I feel competent enough, I'll try to hack up lrq.cc into lrcubic.cc.

**Comment by JohnLangford** [comment]
Closing for now, but a pull request is welcome.  Note the new lrqfa code as some expansion on what exists.
