### ISSUE TITLE
"field aware" low rank quadratic features

### ISSUE THREAD

**Issue by zachmayer** [JohnLangford/vowpal_wabbit#551]
A new machine learning library called "LIBFFM: A Library for Field-aware Factorization Machines" [just won](https://www.kaggle.com/c/criteo-display-ad-challenge) two [Kaggle competitions](https://www.kaggle.com/c/avazu-ctr-prediction) for predicting ad click-through-rates.

[Reading through their slides](http://www.csie.ntu.edu.tw/~r01922136/slides/ffm.pdf) and [forum posts](https://www.kaggle.com/c/avazu-ctr-prediction/forums/t/12608/4-idiots-solution-libffm), it seem that what they refer to as [factorization machines](http://www.ismll.uni-hildesheim.de/pub/pdfs/Rendle2010FM.pdf) is the same thing as what VW means by "low rank quadratic features."  

I think the difference "factorization machines" and "field aware factorization machines" is as follows:  let's say you're interacting two namespaces: `--lrq=ab1`.  A factorization machine would build a single weight matrix for all the interactions in those two namespaces, while a field-aware factorization machine would build a separate weight matrix for each pair of features in both namespaces.

Am I correct that VW does the latter, and is therefore "field aware?"

**Comment by JohnLangford** [comment]
I think: no.  VW only learns one low-rank matrix for each interaction.

-John

**Comment by zachmayer** [comment]
Ok, thanks.  Can I put that in as a feature request, if you've got a place to track such things?

**Comment by pmineiro** [comment]
lrq was designed, more or less, to copy libfm.[1]

I'm a bit confused about what a weight matrix would look like "for each pair of features in both namespaces", because for each pair of features there is a single weight.  

note, you can make lrq nonlinear in each feature pair by using a spline encoding.[2]  this ultimately learns multiple weights per (original) feature pair.

[1] https://github.com/JohnLangford/vowpal_wabbit/blob/master/demo/movielens/README.md
[2] http://www.machinedlearnings.com/2010/11/encoding-trick.html

**Comment by JohnLangford** [comment]
I think Paul needs a better description to fully understand the request.

-John

**Comment by zachmayer** [comment]
@pmineiro Gotcha.  Someone recently published a [library based on libFM called libFFM](http://www.csie.ntu.edu.tw/~r01922136/libffm/).  They used this library to win 2 click-through rate prediction competitions on kaggle, both of which had many entries using libFM and VW.

In their [slides discussing libFFM](http://www.csie.ntu.edu.tw/~r01922136/slides/ffm.pdf), the key point seem to be:
![image](https://cloud.githubusercontent.com/assets/581590/6713693/742f1a2e-cd6a-11e4-9f60-a57360a99d8b.png)
![image](https://cloud.githubusercontent.com/assets/581590/6713700/7b68d5f0-cd6a-11e4-83a5-6e61906b329f.png)

Let's say we are predicting movie ratings based on interaction of user and genre:
5 |user a |genre comedy
1 |user a |genre action
1 |user a |genre drama
1 |user b |genre comedy
5 |user b |genre action
5 |user b |genre drama

VW and libFM would learn a single weight matrix for the user-genre interaction, while libFFM would learn 6 weight matrices: user_a / genre_comedy, user_b / genre_comedy, user_a / genre_action, user_b / genre_action, etc. 

I'm not sure why this approach is better, but it seems to yield good results.

I think something similar could be achieved in VW by mapping each feature to it's own namespace, e.g. `|user a` to `|user_a`.

**Comment by pmineiro** [comment]
I'm still confused.  When the user is "a" and the genre is "comedy", there is only 1 value that affects the prediction, so I'm not sure what it means to learn a "weight matrix" here.  

More concretely, for the example you gave above, and ignoring the constant feature: with ordinary -q ab, a total of 6 different values would be learned by VW.  With --lrq ab1, a total of 5 different values would be learned by VW, and the prediction would be computed differently than with -q ab.

Perhaps you can indicate, for the example input you gave above, how many values would be learned, and how they would be combined to compute a prediction?

**Comment by zjf** [comment]
Suppose there are `n` different features residing in `m` fields and the rank parameter is set to be `k`, the number of parameters to be learned are `n*k` and `n*m*k` in FM model and FFM model, respectively.

In FM model, a `k`-dim weight vector would be learned for each feature. In FFM model, a `m*k` weight matrix would be learned for each feature.

If the field id for two feature `j1` and `j2` is `f1` and `f2`, respectively, we extract the `f2`th row in weight matrix of `j1` and the `f1`th row in weight matrix of `j2`. The dot product of the two vector is the scalar weight of the interaction term `j1_j2`, as showed in the slide.

**Comment by pmineiro** [comment]
What is a field (id), and does it naturally correspond to something in the VW input format?

**Comment by zachmayer** [comment]
@zjf Thanks for jumping in with an explanation.  I was struggling.

@pmineiro I think a field naturally corresponds to a namespace in the VW input format, but I'm not 100% sure.

**Comment by pmineiro** [comment]
@zjf it is not clear whether the association between feature f1 and field j1 is fixed, i.e., feature f1 is always associated with field j1, or if feature f1 is associated with multiple fields (in a data-dependent manner?).  also, are the features in your explanation always binary valued?  if not, how is the value associated with the feature used?

**Comment by zjf** [comment]
@pmineiro The association between feature and field is fixed, and just as @zachmayer said, field corresponds to namespace in VW format. The value is not necessary to be binary. I made up the following example:

    1 |a a1:1 a2:0.5  |b b1:1      |c c3:2
    0 |a a3:1         |b b2:0.1    |c c1:1 c2:1

There are three fields (a, b and c) and eight features. For each feature, a weight matrix with dim 3xk is needed to be learned (k is a user defined parameter, as in --lrq mode.). Each row corresponds a field. Supposing the order of field is in a, b and c, if we want to caculate the scalar weight of feature pair a1_b1, we dot product the second row and the first row of the weigth matrix of a1 and b1, respectively.

 I hope the above explanation will help.

**Comment by pmineiro** [comment]
@zjf If there are 3xk weights to be learned, how are they indexed?  In other words, your explanation suggests a weight matrix for each namespace.  How do a1 and a2 in the namespace "a" in the first example get different weights (or do they?).  What would really help is, taking your 2 example lines, actually write down the formula for computing the complete prediction, including how to index any associated weights.  Things that are currently ambiguous in your explanation include: 1) why the second row for a1 and the first row for b1? 2) what portion of the input line indicates using the second row for a1?  3) how could you change the first example line such that the first row of a1 is utilized instead?

**Comment by zjf** [comment]
@pmineiro Yes, a1 and a2 have different weights. If we index the field name as: a->1, b->2, c->3, then the first row in the 3xk matrix corresponds to field a, and the second row corresponds to field b, etc. Which row of a1's weight matrix is utilized is determined by which interaction term we are calculating. For the interaction term a1_b1, the second row of a1's weight is used because the index of b1's field is 2, and the first row of b1's weight is used because the index of a1's field is 1.

So the pseudocode for the complete prediction is like:

    n = feature number of example
    x = feature vector
    w = 3d weight matrix (n*m*k). // The first dim indicates feature, and the second indicates field.
    prediction = 0.0;
    for(j1 = 0; j1 < n; j1++) {
        for(j2 = j1+1; j2 < n; j2++) {
            f1 = x[j1].field_index; // get the field index of feature j1
            f2 = x[j2].field_index; // get the field index of feature j2
            w1 = w[j1][f2]; // weight vector of feature j1 in field f2, with length k
            w2 = w[j2][f1]; // weight vector of feature j2 in field f1, with length k
            prediction += dot_product(w1, w2) * x[j1].feature_value * x[j2].feature_value
        }
    }

**Comment by pmineiro** [comment]
Ah ok.  I think the key is the field index is derived from the _other_ feature in the interaction.  I do not think there is any way to emulate this currently in VW by manipulating namespaces.

**Comment by zjf** [comment]
Could we emulate this by maintaining a map from feature id to its namespace (or field index)?

**Comment by pmineiro** [comment]
@zjf My comment is not "there is no way to implement this".  My comment is that "there is no way to currently achieve this effect merely by manipulating the input to VW, without making code changes to VW itself".

**Comment by zjf** [comment]
@pmineiro Oh, get your point now :)

**Comment by pmineiro** [comment]
@zjf Hey you seem to understand the VW internals pretty well.  You could take a crack at copying lrq.cc to lrqfa.cc and then making the changes, then send me a pull request and we can iterate on this.  I still don't understand (statistically speaking) why this leads to better performance but it looks interesting.

**Comment by zjf** [comment]
@pmineiro I just started diving into the source code of vw recently but I'm glad to give a try.

**Comment by Sandy4321** [comment]
@pmineiro and @zjf 

5 years ago you wanted to do this important change , do you have some progress?

@zjf Hey you seem to understand the VW internals pretty well. You could take a crack at copying lrq.cc to lrqfa.cc and then making the changes, then send me a pull request and we can iterate on this. I still don't understand (statistically speaking) why this leads to better performance but it looks interesting.

**Comment by lokitoth** [comment]
@Sandy4321, per the issue history, it looks like support for it was merged in #573
