### ISSUE TITLE
Multilabel - error assigning to 'char *' from incompatible type 'char'

### ISSUE THREAD

**Issue by amandasposito** [JohnLangford/vowpal_wabbit#557]
I'm getting this error when trying to make vowpal wabbit on yosemite:
multilabel.cc:108:27: error: assigning to 'char *' from incompatible type 'char'
            p->parse_name[i].end = '\0';

It seems to be in this line:
https://github.com/JohnLangford/vowpal_wabbit/blob/master/vowpalwabbit/multilabel.cc#L108

Here's the terminal's error:
![screen shot 2015-03-14 at 4 49 26 pm](https://cloud.githubusercontent.com/assets/840531/6653282/28e89f7a-ca6a-11e4-92f9-7155942951cb.png)

**Comment by arielf** [comment]
Thanks.
Already addressed here:  https://github.com/JohnLangford/vowpal_wabbit/pull/552
Waiting for John to pull.

**Comment by JohnLangford** [comment]
It should be merged in now.

-John

**Comment by JohnLangford** [comment]
Fixed, closing.
