### ISSUE TITLE
Raw predictions option (-r / --raw_predictions) doesn't work with contextual bandit module (--cb)

### ISSUE THREAD

**Issue by langusta** [JohnLangford/vowpal_wabbit#558]
Hi,
First of all, thank you for this nice piece of software (vw)!
I'm looking for a way to get predictions for all the arms for given example. I have found that there is `-r` / `--raw_predictions` option that works for `--csoaa` module. Contextual bandit is implemented as reduction to csoaa, so shouldn't `-r` give raw predictions in case of `--cb`?
In particular, using the  [example](https://github.com/JohnLangford/vowpal_wabbit/wiki/Contextual-Bandit-Example)
and testing with
````Bash
vw -t -d test.dat -i cb.model --quiet -r /dev/stdout
````
Currently it produces empty output :(

**Comment by JohnLangford** [comment]
The generic answer is 'no', because there is nothing about the 
definition of contextual bandits which requires a policy to operate in 
an argmax-of-scores approach. But, this may be possible for the default 
reduction to csoaa.cc which does operate in this fashion.  Do you want 
to make a patch?

-John

**Comment by langusta** [comment]
Yes. I'm working on a problem where multiple arms are chosen at once and I want to be able to chose sub-optimal ones also (and I need a stationary policy trained on offline data).
It would be helpful if you could tell me where (more or less) do I need to make the change.

**Comment by JohnLangford** [comment]
About here:

https://github.com/JohnLangford/vowpal_wabbit/blob/master/vowpalwabbit/csoaa.cc#L35

-John

**Comment by langusta** [comment]
I'm a little confused. Currently, as I see it:
* `--csoaa` module works in argmax-of-scores approach (actually argmin-of-costs, right?), so we can get the raw (cost) predictions by appying `-r` option,
* `--cb` module doesn't work in the above mentioned approach so there are no raw predictions.

1. Isn't it that both modules use csoaa.cc to do predicting? 
2. Will I change the behaviour of only `--cb` module by modifying csoaa.cc ?

**Comment by JohnLangford** [comment]
Yes, --cb uses --csoaa by reduction.

Yes, changing --csoaa would change all applications of --csoaa.

-John

**Comment by OlekZ** [comment]
Hi @JohnLangford  I work with @langusta and we love your library. 
I just created patch that fix this issue. Raw_predications were already in ec.l.cb. cb_class already had 
    uint32_t action;  // the index of this class
    float partial_prediction;//essentially a return value
so We only have to print them.

**Comment by JohnLangford** [comment]
Merged in, thanks.

-John

**Comment by langusta** [comment]
Works perfectly! Thank you all!
