### ISSUE TITLE
different format of raw predictions for csoaa_ldf with or without a shared line

### ISSUE THREAD

**Issue by michnov** [JohnLangford/vowpal_wabbit#562]
Hi,
the following seems like a bug to me:

shared.data

    shared | a 
    1:0 1| x
    2:1 1| y
    
    shared | b
    1:1 2| x
    2:0 2| y

nonshared.data

    1:0 1| x a
    2:1 1| y a
     
    1:1 2| x b
    2:0 2| y b

Training and predicting on the same data with the following commands:

    vw -d shared.data -f shared.model --csoaa_ldf mc
    vw -t -d shared.data -i shared.model -r shared.res
    vw -d nonshared.data -f nonshared.model --csoaa_ldf mc
    vw -t -d nonshared.data -i nonshared.model -r nonshared.res

produces the raw predictions, which one expects to follow the same format. But they don't.

shared.res

    1:-0.0724151 1
    2:0.00984587 1
    
    1:0.00984587 2
    2:0.0921068 2

nonshared.res

    1:-0.0724151 1
    2:0.00984587 1
     1
    1:0.00984587 2
    2:0.0921068 2
     2

Thanks,
Michal Novak

**Comment by JohnLangford** [comment]
Hal, can you look at this one also?

-John

**Comment by JohnLangford** [comment]
yup!

**Comment by JohnLangford** [comment]
This is fixed, just sent a pull request.

**Comment by martinpopel** [comment]
For reference: fixed in #620 (commit 4d736baef8ca4c22e801e6064602885d9810a8c8)
