### ISSUE TITLE
issues with --invert_hash when using csoaa_ldf with shared lines

### ISSUE THREAD

**Issue by michnov** [JohnLangford/vowpal_wabbit#563]
Hi,
I wanted to print out the weights of features for csoaa_ldf method, but using the data format with shared lines causes problems:

shared.data

    shared | a 
    1:0 1| x
    2:1 1| y
    
    shared | b
    1:1 2| x
    2:0 2| y

Running the training with the model to be stored in a readable format with feature names:

    vw -d shared.data --csoaa_ldf mc --invert_hash shared.weights

results in:

    Num weight bits = 18
    learning rate = 0.5
    initial_t = 0
    power_t = 0.5
    using no cache
    Reading datafile = shared.data
    num sources = 1
    average  since         example        example  current  current  current
    loss     last          counter         weight    label  predict features
    Segmentation fault

The same using a binary model instead (`-f shared.model`) works fine.

If I use namespaces:

shared.ns.data

    shared |s a 
    1:0 1|t x
    2:1 1|t y
    
    shared |s b
    1:1 2|t x
    2:0 2|t y

and run the same command for training:

    vw -d shared.ns.data --csoaa_ldf mc --invert_hash shared.ns.weights

the readable model is produced, but with the shared features having no names:

shared.ns.weights

    Version 7.10.1
    Min label:-1.000000
    Max label:1.000000
    bits:18
    0 pairs: 
    0 triples: 
    lda:0
    0 ngram: 
    0 skip: 
    options: --csoaa_ldf mc
    :0
    :11465:0.046053
    :220006:-0.036208
    t^x:246214:-0.036208
    t^y:195504:0.046053

The same using the format without a shared line (with or without namespaces) works ok:

    Version 7.10.1
    Min label:-1.000000
    Max label:1.000000
    bits:18
    0 pairs: 
    0 triples: 
    lda:0
    0 ngram: 
    0 skip: 
    options: --csoaa_ldf mc
    :0
     ^a:92594:-0.036208
     ^b:163331:0.046053
     ^x:170779:-0.036208
     ^y:102934:0.046053

Thanks,
Michal Novak

**Comment by JohnLangford** [comment]
Hmm--there's probably some issue with the features not having a string 
analog.  Hal, can you take a look?

-John

**Comment by JohnLangford** [comment]
Ping for Hal.

-John

**Comment by JohnLangford** [comment]
it's on my queue :)

**Comment by JohnLangford** [comment]
This is fixed, just sent a pull request.

**Comment by martinpopel** [comment]
For reference: fixed in #620 (in commit 1dc9802a4ae01720366730f8984076e6b2c656ec)
