### ISSUE TITLE
Asymmetric Dirichlet Priors to improve LDA

### ISSUE THREAD

**Issue by simoncast** [JohnLangford/vowpal_wabbit#564]
I'm doing some work on using Vowpal Wabbit for topic modelling and I was wondering if there was any plans to introduce Asymmetric Dirichlet Priors to improve the LDA modelling as outlined in this paper http://dirichlet.net/pdf/wallach09rethinking.pdf and this slide deck https://people.cs.umass.edu/~wallach/talks/priors.pdf by Hannah Wallach?

**Comment by JohnLangford** [comment]
No plans at present, but you could do so if you wish.

-John

**Comment by JohnLangford** [comment]
Closing, but open again if something comes up.
