### ISSUE TITLE
The redefine functionality is broken

### ISSUE THREAD

**Issue by trufanov-nok** [JohnLangford/vowpal_wabbit#574]
I have just pulled current VW to compare its performance with mine and found out that my implementation of --redefine is broken by [recent](https://github.com/JohnLangford/vowpal_wabbit/commit/7419f80b245c1df4d02d648252c99c5557998bd3) commit.
``for (size_t i = 0; i < 256; i++)``
was replaced with
``for (unsigned char i = 0; i < 256; i++)``
at line [542](https://github.com/JohnLangford/vowpal_wabbit/blob/master/vowpalwabbit/parse_args.cc#L542).

This cause endless loop whenever you use --redefine as unsigned char can't be > 255.

Could someone fix this asap? Seems I can't create second VW fork, can't delete it yet and it's too different from master branch.

*  I'll add a test for --redefine later to make sure this won't happen again.
* Looks like the line was changed to fix Visual Studio build error - pls let me know what error is, perhaps I could workaround it in a safe manner.

**Comment by arielf** [comment]
Also (please) need some tests added in `test/RunTests` for `--redefine` to make sure this never regresses again.  Thanks.

**Comment by trufanov-nok** [comment]
I would prefer to make tests later by myself just after I'll get my fork up-to-date. Currently only one this line worries me.

**Comment by nicknussbaum** [comment]
I've submitted a pull request to fix this.#577
