### ISSUE TITLE
Average Loss == Logloss with logistic loss function?

### ISSUE THREAD

**Issue by binga** [JohnLangford/vowpal_wabbit#575]
I am dealing with a problem where my target has 2 outcomes. I would like to obtain a prediction with minimum logloss! I am using the command:

vw -c -k -d data.txt -f data.model --loss_function logistic
vw -t -d data2.txt -i data.model --link logistic -p pred.txt

The output shows:
average  since         example        example  current  current  current
loss     last          counter         weight    label  predict features
0.437223 0.437223         3000         3000.0   1.0000  -3.4377      533
0.388972 0.340720         6000         6000.0  -1.0000   2.9327      526
0.367928 0.325839         9000         9000.0   1.0000  -0.8411      504

The average loss that is being shown, is it the logloss? or just the loss (# of misclassified samples/total # of samples)

If it is the logloss, are the predictions capped with an epsilon? Spare my ignorance.

**Comment by binga** [comment]
I figured out that it is the logloss that is being reported. Sorry for the trouble.
However, what is the epsilon with which the predictions are being capped? Thanks!

**Comment by MLWave** [comment]
It's VW's default that logistic regression predictions are not run through a sigmoid function yet. These predictions are capped at [-50,+50]. You could look at "--link logistic" to directly get probabilities in the [0,1]-range or pipe output through the "utl/logistic"-script.

Probability predictions are not being capped. You could cap them yourself by running through a bounded sigmoid function or manually applying the epsilon to your probabilities.

**Comment by binga** [comment]
Yes, I am currently using the --link logistic to obtain probabilities.

Fine. I shall manually apply the epsilon to my use case.

Thank you MLWave (Triskelion I believe). I love your posts. Keep them coming.
