### ISSUE TITLE
Problem building

### ISSUE THREAD

**Issue by zygmuntz** [JohnLangford/vowpal_wabbit#583]
I get the following error when building on Ubuntu 14.04 - both current version and 7.10 release:

Making all in vowpalwabbit
make[1]: Entering directory `/home/aaa/software/vowpal_wabbit-7.10/vowpalwabbit'
(CDPATH="${ZSH_VERSION+.}:" && cd .. && /bin/bash /home/aaa/software/vowpal_wabbit-7.10/missing autoheader)
rm -f stamp-h1
touch config.h.in
cd .. && /bin/bash ./config.status vowpalwabbit/config.h
config.status: creating vowpalwabbit/config.h
config.status: vowpalwabbit/config.h is unchanged
make  all-am
make[2]: Entering directory `/home/aaa/software/vowpal_wabbit-7.10/vowpalwabbit'
/bin/bash ../libtool  --tag=CXX   --mode=compile clang++ -DHAVE_CONFIG_H -I.    -I/usr/include -I/include  -Wall -Wno-unused-local-typedef  -O3 -fomit-frame-pointer -ffast-math -fno-strict-aliasing -D_FILE_OFFSET_BITS=64 -DNDEBUG     -pedantic  -std=gnu++11 -MT allreduce.lo -MD -MP -MF .deps/allreduce.Tpo -c -o allreduce.lo allreduce.cc
libtool: compile:  clang++ -DHAVE_CONFIG_H -I. -I/usr/include -I/include -Wall -Wno-unused-local-typedef -O3 -fomit-frame-pointer -ffast-math -fno-strict-aliasing -D_FILE_OFFSET_BITS=64 -DNDEBUG -pedantic -std=gnu++11 -MT allreduce.lo -MD -MP -MF .deps/allreduce.Tpo -c allreduce.cc  -fPIC -DPIC -o .libs/allreduce.o
warning: unknown warning option '-Wno-unused-local-typedef' [-Wunknown-warning-option]
In file included from allreduce.cc:10:
In file included from /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/iostream:39:
In file included from /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/ostream:38:
In file included from /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/ios:40:
In file included from /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/bits/char_traits.h:39:
In file included from /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/bits/stl_algobase.h:64:
In file included from /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/bits/stl_pair.h:59:
In file included from /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/bits/move.h:57:
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/type_traits:269:39: error: use of
      undeclared identifier '__float128'
    struct __is_floating_point_helper<__float128>
                                      ^
1 warning and 1 error generated.
make[2]: *** [allreduce.lo] Error 1
make[2]: Leaving directory `/home/aaa/software/vowpal_wabbit-7.10/vowpalwabbit'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/home/aaa/software/vowpal_wabbit-7.10/vowpalwabbit'
make: *** [all-recursive] Error 1

**Comment by arielf** [comment]
I can't reproduce with latest `vw` from github.
Ubuntu 14.04, latest updates. g++ version 4.8.2.
libboost-program-options1.54.0:amd64    1.54.0-4ubuntu3.1
libboost1.54-dev        1.54.0-4ubuntu3.1

It may be autogen/automake striking again.

Can you try a simple `make` (no autogen/autoconf/automake) on a pristine tree?

**Comment by zygmuntz** [comment]
Hey Ariel,
Cloned the repo, this time `make` did the trick :)

**Comment by bscottm** [comment]
Zygmunt, Ariel:

Out of curiousity: Your output above uses clang++. When you used the
pristine clone, did the build use g++ instead?

If so, autotools is not broken: you have a mismatch between Boost for g++
and clang++. Your installed Boost is matched to compile with g++, not
clang++. If you want to use clang++, you have to recompile Boost with
clang++.


-scooter

**Comment by zygmuntz** [comment]
I'm not sure, I just ran make. Boost is most probably compiled with gcc.

**Comment by arielf** [comment]
When I start from a pristine tree, both `make CXX=g++` and `make CXX=clang++` are successful.

I always install prebuilt `boost` from Ubuntu repositories. Never build it myself.

But I do use `libboost1.54-dev` which includes various headers in `/usr/include/boost/compatibility/cpp_c_headers/` as opposed to just ``libboost1.54`. Could this make the difference?

**Comment by bscottm** [comment]
@arielf: Very likely. clang++ uses the gcc 4.2 headers as a fallback, so the compatibility headers might be the reason your's works.
