### ISSUE TITLE
Compiling on Windows, fatal error: "ftrl_proximal.cc"

### ISSUE THREAD

**Issue by sergeyf** [JohnLangford/vowpal_wabbit#587]
I have successfully compiled on my Windows machine before (thanks for the amazingly detailed directions, btw). 

Tried to recompile today and it threw this at me:

error C1083: Cannot open source file: 'ftrl_proximal.cc': No such file or directory.

**Comment by sharatsc** [comment]
Fix here: https://github.com/JohnLangford/vowpal_wabbit/pull/586

**Comment by sergeyf** [comment]
Thank you!

**Comment by JohnLangford** [comment]
Merged into master now.
