### ISSUE TITLE
running time error

### ISSUE THREAD

**Issue by poseidon1214** [JohnLangford/vowpal_wabbit#588]
dyld: Symbol not found: __ZNK5boost15program_options22error_with_option_name23substitute_placeholdersERKNSt3__112basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEE
  Referenced from: /Users/poseidon/Downloads/vowpal_wabbit-7.10/vowpalwabbit/.libs/libvw.0.dylib
  Expected in: flat namespace
 in /Users/poseidon/Downloads/vowpal_wabbit-7.10/vowpalwabbit/.libs/libvw.0.dylib
Trace/BPT trap: 5

**Comment by arielf** [comment]
I'm guessing from `dyld` that this is on a Mac.
Try to build with `make` only from a pristine git checkout (do not run `autogen.sh` which overwrites the original `Makefile`).  If this doesn't work, you may need to rebuild your boost library from source. Unfortunately, boost is notoriously picky about exact versions (no backward compatibility).

**Comment by poseidon1214** [comment]
use new Makefile generated by configure, is doesn't work. Maybe it is the issue of boost version. it is 1.57.0. ~~~~

**Comment by arielf** [comment]
Did you try a `make` only?  (Not even configure).
See also:
https://github.com/JohnLangford/vowpal_wabbit/issues/582
https://github.com/JohnLangford/vowpal_wabbit/issues/540

**Comment by poseidon1214** [comment]
yes,as you told me. It makes me crazy~~~

**Comment by arielf** [comment]
See also this:

    https://github.com/JohnLangford/vowpal_wabbit/issues/583

The gist is you need to either 1) have full boost development env (including compatibity headers) or 2) build both boost and vw with the same compiler.  If you have only boost binaries and they were built with a different version of the compiler, you're very likely to hit the boost version incompatibilities.

**Comment by poseidon1214** [comment]
It's the boost problem. I brew uninstall the boost and brew install again. It works, so wierd. Thank you so much~~~~
