### ISSUE TITLE
No --ksvm flag on Ubuntu 14.04

### ISSUE THREAD

**Issue by alexchao56** [JohnLangford/vowpal_wabbit#594]
Hi I tried running vw with the ksvm flag, but it doesn't seem supported on Ubuntu. I'm not sure why because when I installed vw, it said it was the newest version. 

Strangely, on my personal Mac OSX, I'm able to run `vw --ksvm --kernel [kenel type]` with no problems. However I need to run vw on an Ubuntu AWS instance because of the size of my data. 

Any suggestions?

Thanks

**Comment by arielf** [comment]
The ubuntu official repositories happen to have a relatively old version of `vw`.

When `apt-get install` says `"vowpal-wabbit is already the newest version."` it means newest in the ubuntu/debian repositories, not in the absolute "newest" sense.

```
$ /usr/local/bin/vw --version
7.7.0
```
Updating repos is a volunteer work and volunteers may not do it very often. Thank the volunteers.

Mac repos volunteers have different schedules than Ubuntu ones so not surprisingly you have a slightly more recent version on OS-X.

The safest way to ensure you have the latest is to build from github source.

HTH :)

**Comment by alexchao56** [comment]
Thanks for the heads up! Pulling the latest code and recompiling it did it for me. :)

**Comment by alexchao56** [comment]
Quick question. Does the ksvm flag support Support Vector Regression? Or does it only support classification? When I try running it it says that it expects a target variable of -1 or 1.

**Comment by JohnLangford** [comment]
Only classification.

-John

**Comment by JohnLangford** [comment]
Closing for now.
