### ISSUE TITLE
Add coveralls test coverage reporting?

### ISSUE THREAD

**Issue by zachmayer** [JohnLangford/vowpal_wabbit#599]
Coveralls integrates with travis and lets you put a test coverage badge next to your travis build status badge: https://github.com/eddyxu/cpp-coveralls

e.g.: ![Badge](https://camo.githubusercontent.com/bcf81743ae13592e6c36c16a5cfcb23cdb805efc/68747470733a2f2f636f766572616c6c732e696f2f7265706f732f7a6163686d617965722f6361726574456e73656d626c652f62616467652e737667)

It looks like a pretty easy thing to add to the .travis.yml file, you just need to add the repo to [coveralls](https://coveralls.io), build with [gcov support](https://gcc.gnu.org/onlinedocs/gcc/Gcov.html) and then run the coveralls script.

Not really an issue, but might be cool to have along with the travis build status badge.

**Comment by JohnLangford** [comment]
This does seem like a good idea.  Do you want to do it?

-John

**Comment by zachmayer** [comment]
I had the setup pretty much working, but got hung up on the "Build your project with gcov support" requirement.  I'll keep working on it.

**Comment by zachmayer** [comment]
I've got a commit here that gets part of the way there: https://github.com/zachmayer/vowpal_wabbit/commit/5dac87964efda556ea268e0c26e190af950dacc9, but it seems to break C++11 support: https://travis-ci.org/zachmayer/vowpal_wabbit/builds/61669000

I've got a flag wrong somewhere.  As soon as I fix it, this should work.

**Comment by JohnLangford** [comment]
Ping?

**Comment by zachmayer** [comment]
I'm still working on getting the flags in configure.ac correct.  I can open a pull request with what I've got so far, if you want to take a look.

**Comment by JohnLangford** [comment]
If you are stuck, then maybe yes?

Note that the flags in configure.ac don't influence the travis build 
which just uses the plain old Makefile.

-John

**Comment by zachmayer** [comment]
I'm probably doing something wrong then.  Which makefile should I edit?

PR is here: https://github.com/JohnLangford/vowpal_wabbit/pull/690
