### ISSUE TITLE
Test 59 fails to run

### ISSUE THREAD

**Issue by marko-asplund** [JohnLangford/vowpal_wabbit#600]
When using the "autogen" based build test 59 fails to run (on Ubuntu 13.10).
The test succeeds when using the plain "make" build. `ezexample_predict` doesn't get built at all, causing the test to fail.

The source is cloned from a repository where PR #598 has been applied, because otherwise running autogen fails (see issue #597).

```
git clone https://github.com/marko-asplund/vowpal_wabbit.git
cd vowpal_wabbit
./autogen.sh
make
make test
...
RunTests: test 58: stdout OK
RunTests: test 58: stderr OK
RunTests: ../library/ezexample_predict: No such file or directory
RunTests: failed to run test line:
        ../library/ezexample_predict models/library_train.w

RunTests: test lines must be one of the following:
        shell command to run
        vw command to run: {VW} ...
        stdout reference:  *.stdout
        stderr reference:  *.stderr
        predict reference: *.predict
RunTests: test 59: command is undefined
make: *** [test] Error 2
```

**Comment by pmanionc1** [comment]
I am also experiencing this when using the autogen build on OS X Yosemite 10.10.3 (14D131).

**Comment by JohnLangford** [comment]
I believe this is fixed by Ariel in the current master.   Closing, but reopen if not.
