### ISSUE TITLE
--invert_hash should report when it fails to invert a hash

### ISSUE THREAD

**Issue by sam-s** [JohnLangford/vowpal_wabbit#603]
as the output of 
```
vw -i my-model -t --invert_hash readable < /dev/null
```
indicates, `vw` can fail to invert some (or, in the above case, _all_! hashes) and the user will never know.
I suggest two modifications:
1. report the percentage of hashes that have been inverted (so that when it is not 100%, the user will know that there was a problem)
2. when not saving predictions (as in the above code), stop as soon as all the hashes have been inverted.

**Comment by JohnLangford** [comment]
I don't follow (2)---how can the program know when there are no hashes left to invert?

**Comment by JohnLangford** [comment]
I also don't follow (1).  How can the program know how many hashes there are to invert?  Without that, a percentage seems ill-defined.

**Comment by sam-s** [comment]
depending on the `-b N` arg, the model is a vector `M` of length `2^N`
initially:
```
int num_hashes=0;
for i from 0 to 1<<N
    if M[i] != 0:
        num_hashes ++;
```
now `num_hashes` is the number of hashes to be inverted.

**Comment by JohnLangford** [comment]
But what if M[hash[string]] = 0?

-John

**Comment by martinpopel** [comment]
`--invert_hash` reports only the features seen in the input data (`-d`). So it is obvious that if the input is /dev/null then no features are inverted.
Note that `--invert_hash` reports also hash collisions. So the early stopping suggested in (2) would result in inconsistent results (just changing the order of input examples could increase the number of lines of invert_hash.model).
I agree that (1) may be sometimes useful, even if it will be only an approximation because of the cases M[hash[string]] = 0. Can it be implemented without substantial slow down and increased memory requirements? If no then it should be optional. I am not sure if it is worth the work.
A simple workaround is to use `--invert_hash=invert.model --readable_model=readable.model` and then `wc -l {invert,readable}.model`.

**Comment by sam-s** [comment]
such features do not affect the model behavior, right?

On Wed, May 6, 2015 at 2:13 PM, John <notifications@github.com> wrote:

> But what if M[hash[string]] = 0?
>
> -John
>
> On Wed, May 6, 2015 at 1:59 PM, Sam Steingold <notifications@github.com>
> wrote:
>
> > depending on the -b N arg, the model is a vector M of length 2^N
> > initially:
> >
> > int num_hashes=0;
> > for i from 0 to 1<<N
> > if M[i] != 0:
> > num_hashes ++;
> >
> > now num_hashes is the number of hashes to be inverted.
>


-- 
Sam Steingold <http://sds.podval.org> <http://www.childpsy.net/>

**Comment by sam-s** [comment]
On Wed, May 6, 2015 at 3:36 PM, Martin Popel <notifications@github.com>
wrote:

> --invert_hash reports only the features seen in the input data (-d). So
> it is obvious that if the input is /dev/null then no features are inverted.
>

yes, and this should be reported as an error.


> Note that --invert_hash reports also hash collisions. So the early
> stopping suggested in (2) would result in inconsistent results (just
> changing the order of input examples could increase the number of lines of
> invert_hash.model).
>

I am sorry, I afraid I do not understand this.


> A simple workaround is to use --invert_hash=invert.model
> --readable_model=readable.model and then wc -l {invert,readable}.model.
>

Okay, so this should be done automatically in memory ,i.e., take the result
if inverted hash and map it back to the internal model and see which hashes
are missing.


-- 
Sam Steingold <http://sds.podval.org> <http://www.childpsy.net/>

**Comment by martinpopel** [comment]
> such features do not affect the model behavior, right?
No. Such feature (with zero hash) can have non-zero weight, so it influences the behavior.
Of course, the probability of such feature is 1/2^N.

> yes, and this should be reported as an error

There are two use cases for `--invert_hash`:
A) `vw -d full.data  --invert_hash=A.inv_model`
B) `vw -i big.model  -d small.data --invert_hash=B.inv_model`
In case A, the inverted model contains all features.
In case B, the small.data may be just a subset of the full.data which was used to train big.model (possibly  in more passes, where invert_hash would be really slow and take too much memory).

In case A, the "error" never happens. In case B, it happens always. Use case B is quite common and useful (perhaps I am interested *only* in the features that were in small.data), so I don't think it is a good idea to report it as an error.

**Comment by sam-s** [comment]
On Wed, May 6, 2015 at 4:01 PM, Martin Popel <notifications@github.com>
wrote:

> such features do not affect the model behavior, right?
> No. Such feature (with zero hash) can have non-zero weight, so it
> influences the behavior.
> Of course, the probability of such feature is 1/2^N.
>
>
M is the model weight vector.
if a feature has zero hash, i.e., hash(string)==0, this just means that its
weight is in the 1st element of the vector.


> yes, and this should be reported as an error
>
> There are two use cases for --invert_hash:
> A) vw -d full.data --invert_hash=A.inv_model
>

this is too slow and requires that only a single pass is done.
useless.


> B) vw -i big.model -d small.data --invert_hash=B.inv_model
> In case A, the inverted model contains all features.
> In case B, the small.data may be just a subset of the full.data which was
> used to train big.model (possibly in more passes, where invert_hash would
> be really slow and take too much memory).
>
> In case A, the "error" never happens. In case B, it happens always. Use
> case B is quite common and useful (perhaps I am interested *only* in the
> features that were in small.data), so I don't think it is a good idea to
> report it as an error.
>

I am interested in _all_ features of the model because it will be used on
_all_ data.
I use the small.data to invert the hashe because big data is just too huge
and I don't want to score all of it.
I don't understand why the error always happens in that case. sorry.
if every feature does appear in small.data there should be no error.
thanks!

-- 
Sam Steingold <http://sds.podval.org> <http://www.childpsy.net/>

**Comment by martinpopel** [comment]
> M is the model weight vector.
> if a feature has zero hash, i.e., hash(string)==0, this just means that its
> weight is in the 1st element of the vector.

Yes, exactly. It can have non-zero weight, so it affects the model behavior.

> this is too slow and requires that only a single pass is done

Yes. Sometimes full.data may be small (e.g. a toy example for debugging), so this is still a valid use case.

> I am interested in _all_ features of the model

OK, but someone else may interested only in a subset of features.

> if every feature does appear in small.data there should be no error.

Yes, you are correct, I was wrong. I am usually working with millions of sparse features, so in my case if I take only a subset of examples, I can be almost sure that I am missing some features from the full dataset.
As I wrote in my original reply, I agree it may be sometimes useful to know what percentage of features from the full training data (which were assigned non-zero weight) is covered by small.data, but I don't think we should report it as an error if it is < 100%.

**Comment by martinpopel** [comment]
>> Note that --invert_hash reports also hash collisions. So the early stopping suggested in (2) would result in inconsistent results (just changing the order of input examples could increase the number of lines of invert_hash.model).

> I am sorry, I afraid I do not understand this.

Let's say hash(featureA)=hash(featureB)=123, that's an hash collision.
In inverted.model you can detect these cases because you will see
```
featureA : 123 : 0.1
featureB : 123 : 0.1
```
Now imagine you have implemented the early stopping suggested in (2). If small.data contains featureA and featureB before encountering all features in the model, then both features will be printed in invert.model. However, if featureB is encountered after all other features in the model, then it won't be printed because of the early stopping. Is it clear now?

I think inverted.model should not be influenced by the order of examples in small.data.

**Comment by sam-s** [comment]
> * Martin Popel <abgvsvpngvbaf@tvguho.pbz> [2015-05-06 13:40:22 -0700]:
>
> Let's say hash(featureA)=hash(featureB)=123, that's an hash collision.
> In inverted.model you can detect these cases because you will see
> ```
> featureA : 123 : 0.1
> featureB : 123 : 0.1
> ```
> Now imagine you have implemented the early stopping suggested in (2). If
> small.data contains featureA and featureB before encountering all
> features in the model, then both features will be printed in
> invert.model. However, if featureB is encountered after all other
> features in the model, then it won't be printed because of the early
> stopping. Is it clear now?
>
> I think inverted.model should not be influenced by the order of examples
> in small.data.

Thank you very much for the explanation.
You are right, early stopping is not necessarily a good idea, it should
be optional.

-- 
Sam Steingold (http://sds.podval.org/) on darwin Ns 10.3.1347
http://www.childpsy.net/ http://honestreporting.com
http://americancensorship.org http://dhimmi.org http://iris.org.il
Lisp is not dead, it just smells funny.

**Comment by JohnLangford** [comment]
Sam, can you send me a pull request which prints the number of nonzero parameters to the number of entries built up in the hash table at final printing time?  This should be doable right about here:

https://github.com/JohnLangford/vowpal_wabbit/blob/master/vowpalwabbit/gd.cc#L571

**Comment by sam-s** [comment]
John,
I am sorry, I don't understand the code there.


On Sun, Jun 14, 2015 at 6:42 PM, John <notifications@github.com> wrote:

> Sam, can you send me a pull request which prints the number of nonzero
> parameters to the number of entries built up in the hash table at final
> printing time? This should be doable right about here:
>
>
> https://github.com/JohnLangford/vowpal_wabbit/blob/master/vowpalwabbit/gd.cc#L571
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JohnLangford/vowpal_wabbit/issues/603#issuecomment-111880829>
> .
>



-- 
Sam Steingold <http://sds.podval.org> <http://www.childpsy.net/>

**Comment by JohnLangford** [comment]
Closing, I think this is addressed?
