### ISSUE TITLE
squared normalizer computation for categorical/string features is weird.

### ISSUE THREAD

**Issue by sharatsc** [JohnLangford/vowpal_wabbit#605]
Consider two inputs typical for unigrams/categorical data
"1| catA:2 catB" and "1| catA catA catB" 

Intuitively, after hashing both examples should yield the same feature vector hash(catA)=2, hash(catB) = 1, hash(constant) = 1

I would expect that a model learned with this example would be the same. In fact, for --sgd it is identical.
echo "1 | catA:2 catB" | vw --sgd --audit --loss_function=logistic -b 4  --invert_hash hash
echo "1 | catA catA catB" | vw --sgd --audit --loss_function=logistic -b 4  --invert_hash hash.2
tail -3 hash hash.2

==> hash <==
 ^catA:1:7.071068
^catB:3:3.535534
Constant:12:3.535534
==> hash.2 <==
 ^catA:1:7.071068
 ^catB:3:3.535534
Constant:12:3.535534

Instead, if we use the defaults, the models are very different although the first example says the input representation is the same.
==> hash <==
Using:  catA:2 catB
 ^catA:1:0.117653
 ^catB:3:0.235305
Constant:12:0.235305
==> hash.2 <==
Using:   catA catB catA
 ^catA:1:0.284400
 ^catB:3:0.201109
Constant:12:0.201109

This is possible only if the square normalizer is different. Based on my preliminary inspection of parse_example, squared normalizer is computed based on a running sum. What is happening is that for the case "catA:2 catB", normalizer(catA)=sqrt(2x2). However in the second case, normalizer=sqrt(1x1 + 1x1) that explains the larger update on the catA coefficient.

Now, I'm not sure if this is the intended behavior given the representations are the same.

**Comment by JohnLangford** [comment]
VW does not do deduplication of duplicate features in the input example by
default for computational reasons.  Should it?

**Comment by sharatsc** [comment]
In my opinion it should. Unigrams in text will often be repeated. Also,
this might be leading to incorrect behavior for --input_feature_regularizer
and --normalized (scaling factor is off as specified in
http://arxiv.org/pdf/1305.6646v1.pdf)
Also, it might be an implicit expectation that "catA:2 catB" and "catA catA
catB" are the same inputs.

Maybe the correct think to do is to add a --dedup option (off by default)
to support this behavior? I can take this on if you think its the right
thing to do.

regards
Sharat

On Fri, May 1, 2015 at 10:07 AM, John <notifications@github.com> wrote:

> VW does not do deduplication of duplicate features in the input example by
> default for computational reasons. Should it?
>
> On Thu, Apr 30, 2015 at 9:35 PM, Sharat Chikkerur <
> notifications@github.com>
> wrote:
>
> > Consider two inputs typical for unigrams/categorical data
> > "1| catA:2 catB" and "1| catA catA catB"
> > echo "1 | catA:2 catB" | vw --audit --loss_function=logistic -b 4 -f
> > vw.model --invert_hash hash
> >
> > Intuitively, after hashing both examples should yield the same feature
> > vector hash(catA)=2, hash(catB) = 1, hash(constant) = 1
> >
> > I would expect that a model learned with this example would be the same.
> > In fact, for --sgd it is identical.
> > echo "1 | catA:2 catB" | vw --sgd --audit --loss_function=logistic -b 4
> > --invert_hash hash
> > echo "1 | catA catA catB" | vw --sgd --audit --loss_function=logistic -b
> 4
> > --invert_hash hash.2
> > tail -3 hash hash.2
> >
> > ==> hash <==
> > ^catA:1:7.071068
> > ^catB:3:3.535534
> > Constant:12:3.535534
> > ==> hash.2 <==
> > ^catA:1:7.071068
> > ^catB:3:3.535534
> > Constant:12:3.535534
> >
> > Instead, if we use the defaults, the models are very different although
> > the first example says the input representation is the same.
> > ==> hash <==
> > Using: catA:2 catB
> > ^catA:1:0.117653
> > ^catB:3:0.235305
> > Constant:12:0.235305
> > ==> hash.2 <==
> > Using: catA catB catA
> > ^catA:1:0.284400
> > ^catB:3:0.201109
> > Constant:12:0.201109
> >
> > This is possible only if the square normalizer is different. Based on my
> > preliminary inspection of parse_example, squared normalizer is computed
> > based on a running sum. What is happening is that for the case "catA:2
> > catB", normalizer(catA)=sqrt(2*2). However in the second case,
> > normalizer=sqrt(1*1 + 1*1) that explains the larger update on the catA
> > coefficient.
> >
> > Now, I'm not sure if this is the intended behavior given the
> > representations are the same.
> >
> > --
> > Reply to this email directly or view it on GitHub
> > <https://github.com/JohnLangford/vowpal_wabbit/issues/605>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JohnLangford/vowpal_wabbit/issues/605#issuecomment-98140969>
> .
>



-- 
Sharat Chikkerur
"We are the way for the cosmos to know itself." - Carl Sagan

**Comment by arielf** [comment]
Personally, I don't mind another option as long as it doesn't make performance suffer.

I feel in this case the benefit of speed greatly outweights the benefit from being strictly correct on any form of input.

Users who feel this is of critical importance can always preprocess their input and consolidate duplicates.

**Comment by JohnLangford** [comment]
There is a --sort_features option available.  At present, this makes the features unique but does not operate in an additive fashion.  Changing it to work in an additive fashion is reasonable.  

Note that --sort_features is _not_ compatible with ngrams or interaction features.  Hence it is off by default.  I could imagine changing the location where sort happens from here: 
https://github.com/JohnLangford/vowpal_wabbit/blob/master/vowpalwabbit/parser.cc#L744

to here: https://github.com/JohnLangford/vowpal_wabbit/blob/master/vowpalwabbit/parser.cc#L814 
(or even later) to support ngram features.  Properly supporting interactions is quite difficult however, because they are generated on the fly for efficiency reasons.  

Given the above, what do you think the best course of action is?

**Comment by JohnLangford** [comment]
Ping.

**Comment by sharatsc** [comment]
For now, we can just document this. I haven't gotten to adding support yet.

**Comment by JohnLangford** [comment]
Closing for now.
