### ISSUE TITLE
LAST_COMPATIBLE_VERSION is obsolete

### ISSUE THREAD

**Issue by sharatsc** [JohnLangford/vowpal_wabbit#606]
LAST_COMPATIBLE_VERSION is defined at 6.1.3 which means that current code should be able to load models defined after 6.1.3. However, I see that 7.10 code cannot load a model defined by 7.4. Is this tracked in any test?

**Comment by arielf** [comment]
It is not tracked and it is a bug.

**Comment by sharatsc** [comment]
Regressions can be detected adding a test to the RunTests script that stores a model to train-sets/ref in addition to prediction and stderr outputs. Please keep the issue open. I'll try to fix it.

**Comment by JohnLangford** [comment]
A test for compatibility is definitely welcome.

**Comment by trufanov-nok** [comment]
Could you please try this pull request:
https://github.com/JohnLangford/vowpal_wabbit/pull/676
It might fix compatibility for 7.4 too.

**Comment by JohnLangford** [comment]
Ping here.  Alex's code is merged.

**Comment by JohnLangford** [comment]
Closing this---we have a test for compatibility now and LAST_COMPATIBLE_VERSION is set to 7.6.0.
