### ISSUE TITLE
vw-hypersearch problem: command: vw: must start with an executable

### ISSUE THREAD

**Issue by kuo000** [JohnLangford/vowpal_wabbit#616]
I did a little search and realized this issue has been raised here before, but it did not really solve my problem.

My OS is Windows 7 x64. I just followed the guide to compile (using Visual Studio) the source and built VW (7.10.1, i.e., the up-to-date version) on my Windows machine. I added the full paths for the locations of **vw.exe** and **vw-hypersearch** to my environment variable PATH. Now if I enter **vw --help** or **vw-hypersearch**, I can get their help message. In fact, the **vw** is working well; I've just used it to train some model and make predictions.

However, when I entered on a command line prompt **vw-hypersearch -L 1e-10 1e-4 vw ... --l2 % ...**, (where the part **vw ...** was the exact command that worked before, just now with the l2 regularization parameter replaced with **%**), I got **command: vw: must start with an executable**. What could possibly be wrong?

I checked that if I just type **vw-hypersearch**, it does print out the help message, meaning I can call it from the command prompt.

Thanks very much for any help

**Comment by arielf** [comment]
Try to use `vw.exe` instead of `vw` on your command line.

**Comment by kuo000** [comment]
I tried using `vw.exe` before, but it didn't work...

**Comment by arielf** [comment]
Sorry but I'm not familiar with Windows.

What happens if you type `vw` alone ?
`vw.exe` alone?
Where is `vw` (or `vw.exe`) installed?
What is the value of the PATH variable and how do you set it?
Is `vw` (or `vw.exe`) executable in term of file permissions?

The check that `vw-hypersearch` is doing, is simply looking along the components of PATH for a file that exists and is executable.  Before the PR above it was looking only for files named `vw`.
Now, if it is Windows, it also looks for files named `vw.exe`.

Can you pull latest code and see whether it makes any difference?

**Comment by arielf** [comment]
@kuo000 
I really like to solve this issue and it shouldn't be hard, but since I don't use windows, I need help.
Could you try latest, and if it still doesn't work, respond to the questions above?  Thanks!

**Comment by kuo000** [comment]
@arielf 
Thanks a lot for trying to help all along.

I just have been busy these days and never got time to try these things. Can we just leave this issue open? I'll try the latest version (and respond to the questions above if it still doesn't work) and post back here this weekend.

**Comment by arielf** [comment]
@kuo000 
Sure, NP. Thank you!

**Comment by sharatsc** [comment]
Hi Chia, 
Do you mind posting the command line and the error verbatim?

regards
Sharat

**Comment by kuo000** [comment]
@arielf 
I just tried getting the latest code, but the problem persists.

1. If I type `vw` or `vw.exe` at the command prompt, I get

> For more information use: vw --help
Num weight bits = 18
learning rate = 0.5
initial_t = 0
power_t = 0.5
using no cache
Reading datafile = 
num sources = 1
average  since         example        example  current  current  current
loss     last          counter         weight    label  predict features
0.000000 0.000000            1            1.0  unknown   0.0000        1
0.000000 0.000000            2            2.0  unknown   0.0000        1
0.000000 0.000000            4            4.0  unknown   0.0000        1
0.000000 0.000000            8            8.0  unknown   0.0000        1
0.000000 0.000000           16           16.0  unknown   0.0000        1
0.000000 0.000000           32           32.0  unknown   0.0000        1
0.000000 0.000000           64           64.0  unknown   0.0000        1
0.000000 0.000000          128          128.0  unknown   0.0000        1
0.000000 0.000000          256          256.0  unknown   0.0000        1
0.000000 0.000000          512          512.0  unknown   0.0000        1
0.000000 0.000000         1024         1024.0  unknown   0.0000        1
0.000000 0.000000         2048         2048.0  unknown   0.0000        1
0.000000 0.000000         4096         4096.0  unknown   0.0000        1
0.000000 0.000000         8192         8192.0  unknown   0.0000        1
0.000000 0.000000        16384        16384.0  unknown   0.0000        1
0.000000 0.000000        32768        32768.0  unknown   0.0000        1
0.000000 0.000000        65536        65536.0  unknown   0.0000        1

2. My `vw.exe` is installed in `C:\vw\vowpal_wabbit\vowpalwabbit\x64\Release`.

3. There's a variety of ways to set the PATH variable (BTW, variable names are case-insensitive on Windows) on Windows, but I use some simple program called "Rapid Environment Editor" to append values to my PATH variable. I believe this is not where the problem lies.

4. `vw.exe` is executable on my Windows file system.

**Comment by kuo000** [comment]
@sharatsc 
My exact command was `vw-hypersearch -L 1e-10 0.0001 vw -d ../data/d4_train.vw -c --loss_function squared -b 29 --passes 10 --early_terminate 2 --l2 % -q ::`.

The following is the output verbatim:

> C:\vw\vowpal_wabbit\utl\vw-hypersearch.pl: -L: using log-space search
trying 5.10744775086489e-007 '-' is not recognized as an internal or external command,
operable program or batch file.

>	\vw\vowpal_wabbit\vowpalwabbit\x64\Release/vw -d ../data/d4_train.vw -c --loss_function squared -b 29 --passes 10 --early_terminate 2 --l2 5.10744775086489e-007 -q :: failed: (exitcode=1)
Output from \vw\vowpal_wabbit\vowpalwabbit\x64\Release/vw -d ../data/d4_train.vw -c --loss_function squared -b 29 --passes 10 --early_terminate 2 --l2 5.10744775086489e-007 -q :: is:

> You may try to run:
	\vw\vowpal_wabbit\vowpalwabbit\x64\Release/vw -d ../data/d4_train.vw -c --loss_function squared -b 29 --passes 10 --early_terminate 2 --l2 5.10744775086489e-007 -q ::
manually to figure out why.



BTW, the vw command alone (i.e., `vw -d ../data/d4_train.vw -c --loss_function squared -b 29 --passes 10 --early_terminate 2 --l2 1e-5 -q ::`) works.

**Comment by arielf** [comment]
@sharatsc `vw-hypersearch` is a perl script and should be easy to change/update.  Ideally by someone who has access and familiarity with windows.  There are 2 separate (maybe related) errors above: the `'-' is not recognized ...` warning/error, and the `exit code 1`.

What I would suggest at this point is simply to skip the "find the executable" check when on windows (`if ($^O =~ /Win/) ...`) and just try to call the `$ARGV[0]` as it was passed, seems like it is working from the command line.

@kuo000  can you try a little experiment:  You say that, both:

`C:\vw\vowpal_wabbit\utl\vw-hypersearch.pl ...`

    and

`vw ...`

invocations work from the command line.  Does the 1st one without the `C:` prefix work?  If not, this may be the reason for the failure.

**Comment by kuo000** [comment]
@arielf 
I currently do not have access to my own Windows computer. I can try that out later, but my guess is that `C:\vw\vowpal_wabbit\utl\vw-hypersearch.pl ...` would still work even without the `C:` upfront.


> What I would suggest at this point is simply to skip the "find the executable" check when on windows (if ($^O =~ /Win/) ...) and just try to call the $ARGV[0] as it was passed, seems like it is working from the command line.

May I know where in `vw-hypersearch` I should change or comment out? Is it https://github.com/JohnLangford/vowpal_wabbit/blob/master/utl/vw-hypersearch#L512 or somewhere else? Thanks.

**Comment by arielf** [comment]
@kuo000 
I just sent a new pull-request: https://github.com/JohnLangford/vowpal_wabbit/pull/639
I hope this would work better for you. You can look at the diff to the `utl/vw-hypersearch` script in the PR.

**Comment by kuo000** [comment]
@arielf 
Thanks for all your help. I'll check it out when I get to my Windows computer.

**Comment by JohnLangford** [comment]
Closing this on the theory that it is addressed (hope so, reopen if not).
