### ISSUE TITLE
Data loss in daemon mode

### ISSUE THREAD

**Issue by joachimdb** [JohnLangford/vowpal_wabbit#624]
When streaming examples to a vw daemon some examples are silently dropped

See first issue in https://groups.yahoo.com/neo/groups/vowpal_wabbit/conversations/messages/5105

**Comment by joachimdb** [comment]
Update: cannot be reproduced on Ubuntu, see https://github.com/mmroden/vw_daemon_tests/blob/master/features/regularization.feature

**Comment by JohnLangford** [comment]
Closing for now as I can't replicate.  A pull request is definitely welcome.
