### ISSUE TITLE
Regularization doesn't work in daemon mode (logistic regression)

### ISSUE THREAD

**Issue by joachimdb** [JohnLangford/vowpal_wabbit#625]
Streaming examples to a vw daemon with and without regularization produces exactly the same model

See second issue in https://groups.yahoo.com/neo/groups/vowpal_wabbit/conversations/messages/5105

**Comment by joachimdb** [comment]
Update: cannot be reproduced on Ubuntu, see
https://github.com/mmroden/vw_daemon_tests/blob/master/features/regularization.feature

**Comment by JohnLangford** [comment]
On 05/20/2015 08:28 AM, Joachim De Beule wrote:
>
> Update: cannot be reproduced on Ubuntu, see
> https://github.com/mmroden/vw_daemon_tests/blob/master/features/regularization.feature 
>
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/JohnLangford/vowpal_wabbit/issues/625#issuecomment-103863082>.
>

Inability to reproduce is a killer here.   Not sure what's going on.  
I'm going to close this for now, but please reopen if you find something 
reproducible.

-John
