### ISSUE TITLE
Format of the namespaces file for dt2vw

### ISSUE THREAD

**Issue by StuHorsman** [JohnLangford/vowpal_wabbit#646]
What's the expected format of the namespace list for dt2vw?  I can't get even a simple example to work.

**Comment by arielf** [comment]
I assume you mean `R/dt2vw.R`?

The source has a series of comments at the top. It says:
```
#namespaces[list / yaml file]:      name of each namespace and each variable for each namespace
#                                               can be a R list, or a YAML file
```
Perhaps ask the author directly?
`git log R/dt2vw.R` for the email.

HTH.

**Comment by slymore** [comment]
I haven't indeed detailed enough the expected format for namespaces.

I have added a simple example with the iris database as a comment in a pull request for dt2vw.R
The pull request also contains an example of yaml file to define namespaces.


Basically, this is the format expected:
namespaces = list( namespace_1 = list(varName = c("var1, var2", ...), keepSpace = F),
                              namespace_2 = ....)
OR
namespaces = NULL
if you do not want to specify any namespace (all the variables will be grouped in a unique namespace)


keepSpace = TRUE / FALSE allows to keep or remove the spaces in a categorical variable. 
example: "BMW C7" with keepSpace = T ==> "BMW C7" in the vw data format (treated as 2 separate categorical variables)
                                 with keepSpace = F ==> "BMW_C7" in the vw data format (treated as a unique categorical variable)
keeping spaces can be interesting if a categorical variable contains distinct informations that we want to use for discrimination (in this example: the brand of the car BMW, and its model C7 )


I hope it answers your questions

**Comment by StuHorsman** [comment]
Thanks for the feedback.  I'm still struggling to get this working, even with your new code.  I'm just trying this simple example, can you point out what I'm doing wrong:
````
#dt2vw example
library(data.table)
data("iris")
# Load data
data <- data.table(iris)

# Add target
target <- data.table(labels = sample(c("-1", "1"), nrow(data), nrow(data) ))

# Add weights
weight <- data.table(weight = as.character(rnorm(nrow(data), mean=5, sd=2)))

# Add namespaces
#namespaces <- NULL
namespaces = list(sepal = list(varName = c('Sepal.Length', 'Sepal.Width'), keepSpace=F),
                  petal = list(varName = c('Petal.Length', 'Petal.Width'), keepSpace=F))

# Add output file
fileName <- "~/Downloads/training.vw"

# Extract to VW format
dt2vw(data = data, fileName = fileName, namespaces = namespaces, target = target, weight = weight)
````
and this throws an error:
````
 Error in .subset2(x, i, exact = exact) : invalid subscript type 'list' 
````

**Comment by slymore** [comment]
Actually the pull request hasn't been accepted yet (#654), so the updated code isn't available yet on the master branch of the original repo.
Meanwhile, you can try to pull the code from the "R-to-VW-data-conversion" branch of my fork:
https://github.com/slymore/vowpal_wabbit/tree/R-to-VW-data-conversion

There is one major problems in your code:
"weight" and "target" are not data tables or vectors, they are simple strings giving the name of the weight variable and the name of the target. The actual data corresponding to weights and targets must be in the "data object"

Try these changes:
`<data[, "Species":=sapply(data$Species, FUN = function(x){if(x == 'setosa') 1 else -1}), with = F]>
`<target = "Species">`
`<weight = NULL>`
(you could put in weights the name (string) of any variable of your datase i.e weights = "Sepal.Length", but in the iris dataset there is not really any variable that could act as a weight)

**Comment by JohnLangford** [comment]
Merged in now.

-John

**Comment by StuHorsman** [comment]
New code:
````
#dt2vw example
library(data.table)
data("iris")
source("~/workspace/vowpal_wabbit/R/dt2vw.R")

# Load data
data <- data.table(iris)

# Add label and weights
data[, "Label":= sapply(
  data$Species, FUN = function(x) {
    if (x == 'setosa')
      1
    else-1
  }
), with = F]

data[, "Weight":= sample(c(1.0, 1.5, 2.0), nrow(data), replace = TRUE)]

# Define label, weight columns.  Set output file
target <- "Label"
weight <- "Weight"
fileName <- "~/Downloads/training.vw"

# Add namespaces
namespaces <- NULL
# namespaces <- list(default = list(
#   varName = c(
#     'Sepal.Length', 'Sepal.Width', 'Petal.Length', 'Petal.Width', 'Species'), 
#     keepSpace = F
#   )
# )
  
# Extract to VW format
dt2vw(
  data = data, fileName = fileName, namespaces = namespaces, target = target, weight = weight
)
````
I added  a random weight to test.  If you set `namespaces = NULL` then weight gets added as a feature:
````
1.000000 1.000000 |A Sepal.Length:4.600000 Sepal.Width:3.600000 Petal.Length:1.000000 Petal.Width:0.200000 Weight:1.000000 setosa
````
so you do have to define the namespace.  It would be good if it could specify a `tag` too.

**Comment by StuHorsman** [comment]
I've added to PRs: 1) Fixes the bug above and 2) Adds the ability to define a `tag`.  Let me know if you want me to change anything.

**Comment by slymore** [comment]
Nice ! Thanks for contributing.
This script still lacks many possible VW options. If you see anything else important in your workflow that isn't implemented yet let me know.

**Comment by JohnLangford** [comment]
I'm assuming this is done, so closing.
