### ISSUE TITLE
--invert_hash with --oaa reports only the features for the first class

### ISSUE THREAD

**Issue by martinpopel** [JohnLangford/vowpal_wabbit#648]
The famous iris dataset contains 4 features for each example:
```
3 |f s_length:7.9 s_width:3.8 p_length:6.4 p_width:2.0
2 |f s_length:6.8 s_width:2.8 p_length:4.8 p_width:1.4
1 |f s_length:5.7 s_width:4.4 p_length:1.5 p_width:0.4
```
When using `-q ff`, there should be up to 16=4^2 quadratic features (or less with VW after #610) plus 4 simple features plus 1 constant features. With `--oaa=3` there should be three variants of each feature, thus (16+4+1)*3 = 63 features in total.

```
wget http://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data
cat iris.data | perl -nle '@f=split /,/,$_; $class = /setosa/ ? 1 : /versi/ ? 2 : /virgi/ ? 3 : exit for($f[4]); printf "$class |f s_length:%s s_width:%s p_length:%s p_width:%s\n", @f;' > iris.vw
shuf iris.vw > iris.shuf.vw
vw -d iris.shuf.vw -c -k --loss_function=logistic --oaa=3 -q ff --passes=3 -f oaa.model
vw -d iris.shuf.vw -t -i oaa.model --invert_hash=model.invert --readable_model=model.readable
```

When I tried the experiment above with one-month-old VW (7d0ec30), I got 63 features in model.readable as expected. However, model.invert contained only 31 features, because the 16 quadratic features were present only in one version (for class1, because their hashes were divisible by 4).

Now I tried the same experiment with the newest VW from GitHub (003b50b), which contains the new mechanism for interactions ( #610 ), where interactions f1*f2 and f2*f1 are considered the same, so I would expect (4 + 4*3/2 + 4 + 1) * 3 = 45 total features.
model.readable contains 45 features.
model.invert contains 15 features (all divisible by 4, i.e. also the constant feature and simple features are only in one version):

```
Constant:202096:0.784281
f^p_length:106408:-0.163726
f^p_length*f^p_length:248528:-0.038985
f^p_length*f^p_width:158456:-0.126031
f^p_width:16256:-0.706956
f^p_width*f^p_width:248064:-0.285858
f^s_length:140528:0.059708
f^s_length*f^p_length:113272:-0.023495
f^s_length*f^p_width:6736:-0.096329
f^s_length*f^s_length:131360:0.002369
f^s_length*f^s_width:156372:0.026982
f^s_width:149252:0.251030
f^s_width*f^p_length:21732:-0.029810
f^s_width*f^p_width:128204:-0.154771
f^s_width*f^s_width:232520:0.068361
```
This seems like yet another bug.

**Comment by arielf** [comment]
Yes, looks like `--invert_hash` needs to be rewritten/fixed to be compatible with the new interactions code. Also: if we better add some tests/references for `--invert_hash` (both multiclass and not) so these regressions are caught immediately.

**Comment by trufanov-nok** [comment]
It lloks like it was broken before and I carefully reproduced the problem in the new interactions code.
I'm suspecting the problem will disappear if you add `-a` to the command line. If so it would be easy to fix.
I can't reproduce your example as 
```
cat iris.data | perl -nle ...
```
line throws some errors. Output: http://pastebin.com/Crzt2QXN
Could you upload ready iris.shuf.vw somewhere?

**Comment by martinpopel** [comment]
@trufanov-nok:  I am sorry, the perl command was missing double quotes before $class (copy-paste error of mine), now it should be ok. The command just converts iris dataset into VW format. The problem is not specific to the iris data set, I used it because Stephen Hoover had used it in [his original question on the mailing list](https://groups.yahoo.com/neo/groups/vowpal_wabbit/conversations/topics/5117).

I can show the problem also with this tiny two-example dataset:
```
echo -e '3 |f a b c\n2 |f a b c' | vw --oaa 3 -q ff --invert_hash=model.invert --audit
```
In the `--audit` reports you can see 3*7 features with non-zero weight, but `model.invert` contains only 7 features (for the first class).

> It lloks like it was broken before

Yes, but now it is even more broken because not only the quadratic features for non-first class are missing but also the simple features for non-first class.

> if you add -a to the command line

`head -n 1 iris.shuf.vw | vw -t -i oaa.model --audit`
The audit info seems to be ok, there are always 3*15 features reported.

> the problem will disappear
No. Just adding `-a` (`--audit`) did not change the content of `model.invert`.

@trufanov-nok: See also issue #649.

**Comment by trufanov-nok** [comment]
I was wrong. Audit won't affect invert_hash.

The problem is that invert_hash is just printing out a content of name_index_map in gd.cc::save_load_regressor(). And this name_index_map is a map where kay is string and weight is value.  So here you see this key:value pairs:
```
Constant:202096:0.784281
f^p_length:106408:-0.163726
f^p_length*f^p_length:248528:-0.038985
...
```
And you can't hold 2 values with same kay in map - last will overwrite first one.
The problem is all examples which differ by offset have same key. As offset doesn't affect namespace of features titles. I shall debug it but this is most probable reason.

I suggest printing 
`f^p_length:106408:-0.163726` for any example with offset = 0 and
`f^p_length:106408[1]:xxxxxxx` for offset = 1
`f^p_length:106408[2]:yyyyyyy` for offset = 2
ets. Or something like that.
offset shall be incorporated into key or we will be forced to use something else instead of map.

**Comment by martinpopel** [comment]
Yes, printing the offset in audit and in invert_hash will be useful also for the users. For oaa, it would be more natural to report the class number, i.e. offset+1:
`f^p_length:106408:[1]-0.163726` for any example with offset = 0 and
`f^p_length:106408[2]:xxxxxxx` for offset = 1
`f^p_length:106408[3]:yyyyyyy` for offset = 2

> And you can't hold 2 values with same kay in map - last will overwrite first one.

Note that in older VW versions, simple features were reported for all classes:
```
echo -e '3 |f a' | vw --oaa 3 --invert_hash=model.invert
tail -6 model.invert
Constant:202096:-0.253423
Constant:202097:-0.253423
Constant:202098:0.253423
f^a:57420:-0.253423
f^a:57421:-0.253423
f^a:57422:0.253423
```

**Comment by trufanov-nok** [comment]
Could you add following lines:
```
      if (dat.offset != 0)
      {
          ostringstream tempstream;
          tempstream << '[' << dat.offset << ']';
          ns_pre += tempstream.str();
      }
```
right here: line [236](https://github.com/JohnLangford/vowpal_wabbit/blob/master/vowpalwabbit/gd.cc#L236) and recompile vw with `make`

It will generate for your test   
`echo -e '3 |f a b c\n2 |f a b c' | vw --oaa 3 -q ff --invert_hash=model.invert`
following `model.invert``:

```
...
options: --oaa 3
:0
Constant:202096:-0.132257
Constant[4]:202096:-0.132257
Constant[8]:202096:-0.132257
f^a:57420:-0.132257
f^a*f^b:123444:-0.132257
f^a*f^b[4]:123445:0.014981
f^a*f^b[8]:123446:-0.014981
f^a*f^c:157988:-0.132257
f^a*f^c[4]:157989:0.014981
f^a*f^c[8]:157990:-0.014981
f^a[4]:57420:-0.132257
f^a[8]:57420:-0.132257
f^b:62864:-0.132257
f^b*f^c:126768:-0.132257
f^b*f^c[4]:126769:0.014981
f^b*f^c[8]:126770:-0.014981
f^b[4]:62864:-0.132257
f^b[8]:62864:-0.132257
f^c:228992:-0.132257
f^c[4]:228992:-0.132257
f^c[8]:228992:-0.132257
```
4 and 8 bcs offset must be deleted by stride_shift. Forget to do that.

**Comment by trufanov-nok** [comment]
Regarding indexes: it can be easily made [2], [3]  (starting with 1) instead of [1], [2] (starting with 0), but there is a problem with initial indexes: [0] or [1].   
Currently I think that there is no reliable way to find out if VW is working in multiclass mode or as a regular classifier. In case of multiclass 1st class will have offset = 0 and processed before others. In regular case - offset is always 0. 
I'll need either think out a trick to detect multiclass modes, or print [1] suffix everywhere in regular mode, or omit [1] in multiclass output.

**Comment by JohnLangford** [comment]
This is not just about multiclass mode.   There are many reductions to 
base predictors, each of them using offsets.  I'd suggest just eliding 
the [] when offset is zero and otherwise including it, starting from [1].

-John

**Comment by JohnLangford** [comment]
This should be fixed in the current master now thanks to Alex and Martin.

-John

On 05/25/2015 10:36 AM, Martin Popel popel@ufal.mff.cuni.cz 
[vowpal_wabbit] wrote:
>
> Hi Stephen and John,
> I confirm there is something strange going on with --oaa and 
> --invert_hash.
> See https://github.com/JohnLangford/vowpal_wabbit/issues/648
>
> I don't have time now to debug it further, but I hope there are enough 
> clues in my description to find the cause(s) of the problem.
>
> Martin
>
> ----- Original Message -----
> > From: "Stephen Hoover stephen.ld.hoover@gmail.com [vowpal_wabbit]" 
> <vowpal_wabbit@yahoogroups.com>
> > To: "vowpal wabbit" <vowpal_wabbit@yahoogroups.com>
> > Sent: Wednesday, May 13, 2015 9:17:09 PM
> > Subject: Re: [vowpal_wabbit] oaa with quadratic features
>
> > So the class label associated with a coefficient's hash would be ( 
> hash mod
> >
> > 2^[ceil(log_2(k))] + 1), where k is the total number of classes? That's
> > very useful. There's still something else going on here, though. If 
> I use
> > that formula to calculate the class label associated with each of the
> > quadratic coefficients in my inverted hash file, they're all associated
> > with class label 1. If I compare the VW-predicted probabilities to
> > probabilities I calculate using the coefficients in the inverted 
> hash file,
> > the probabilities match for the first class (the one with output 
> quadratic
> > coefficients) but not for the other two (the classes with only linear
> > coefficients).
> >
> >
> > I tried using the readable_model option rather than the invert_hash 
> option,
> > and I discovered the missing coefficients in that file. It looks like
> > invert_hash is not outputting all coefficients for oaa problems. Either
> > that, or there's something else I've missed, which is quite possible. I
> > spent some time reading through the source code, but wasn't able to 
> figure
> > out what was going on. I see functions in gd.cc which appear to be 
> creating
> > the model files, but I haven't worked out how that interacts with oaa.
> >
> >
> > The following instructions reproduce what I'm talking about. My 
> version of
> > vw was up-to-date with the master branch as of two days ago.
> > ---------------------
> > # Put the following three lines in "iris.txt"
> > 1 | sepal_length:5.1 sepal_width:3.5
> > 2 | sepal_length:7.2 sepal_width:3.0
> > 3 | sepal_length:5.5 sepal_width:2.4
> >
> >
> > # This command creates a model file containing the following 
> coefficients
> >
> >
> > vw iris.txt --invert_hash invertedhash.model --oaa 3 -q ::
> > ^sepal_length:117320:-0.011749
> > ^sepal_length:117321:-0.005399
> > ^sepal_length:117322:0.003041
> > ^sepal_length^ ^sepal_length:37744:-0.001509
> > ^sepal_length^ ^sepal_width:226124:-0.003269
> > ^sepal_width:43556:-0.019946
> > ^sepal_width:43557:-0.013824
> > ^sepal_width:43558:0.001966
> > ^sepal_width^ ^sepal_length:188380:-0.003269
> > ^sepal_width^ ^sepal_width:114616:-0.004283
> > Constant:202096:-0.088215
> > Constant:202097:-0.059521
> > Constant:202098:0.023842
> >
> >
> > # A "readable_model" produces the following output, which looks correct:
> >
> >
> > vw iris.txt --readable_model readable.model --oaa 3 -q ::
> > 37744:-0.001509
> > 37745:-0.000414
> > 37746:0.000344
> > 43556:-0.019946
> > 43557:-0.013824
> > 43558:0.001966
> > 114616:-0.004283
> > 114617:-0.003257
> > 114618:-0.001216
> > 117320:-0.011749
> > 117321:-0.005399
> > 117322:0.003041
> > 188380:-0.003269
> > 188381:-0.001316
> > 188382:0.000313
> > 202096:-0.088215
> > 202097:-0.059521
> > 202098:0.023842
> > 226124:-0.003269
> > 226125:-0.001316
> > 226126:0.000313
> >
> >
> >
> >
> >
> >
> > On Wed, May 13, 2015 at 7:07 AM, John Langford jl@hunch.net 
> [vowpal_wabbit]
