### ISSUE TITLE
Some options are missing in vw --help

### ISSUE THREAD

**Issue by martinpopel** [JohnLangford/vowpal_wabbit#665]
According to active.cc, there are parameters `--simulation` and `--mellowness`, but the only way how to discover it is inspecting the source code. 

Problem 1:
`vw -h` prints only `--active`, but no  "simulation" and "mellowness". There is no indication that more info will be shown with `vw --active --help`.

Problem 2:
`vw --active --help` shows no info, it waits for stdin.

Problem 3:
https://github.com/JohnLangford/vowpal_wabbit/wiki/Command-line-arguments#active-learning-options is outdated. (I would fix it now, but I have never used active learning.)

Problem 4:
There is no check that after changing parameter names (refactorization), https://github.com/JohnLangford/vowpal_wabbit/wiki/Command-line-arguments will be updated. Due to problem1 and problem2, the wiki is the only place where we can point users.

**Comment by JohnLangford** [comment]
Fixed #3.

How is it possible to fix #4?

-John

**Comment by martinpopel** [comment]
> Fixed # 3.

OK, I've now substituted the remaining (in the description) `--active_simulation` with `--simulation`.

> How is it possible to fix # 4?

I think it is not worth to make any automation (wiki text automatically generated/validated from the C++ source codes). The wiki should include more details on the parameters (usage hints, links to separate wiki pages and published papers etc.) than `vw -h`. Just keep this wiki page in mind when merging pull requests that change/add the parameters. And/or ask volunteers to check&update the wiki once per several months.

**Comment by trufanov-nok** [comment]
It looks like `use [option] --help for more info` is correct only for reductions that takes no additional arguments. For others you have to specify an argument that let them complete setup() function successfully. Example: `--nn 1 --help`. But some reductions won't work even with that or has additional requirements to complete their setup(). For example: 
```
vw --bfgs --help
enabling BFGS based optimization **without** curvature calculation
vw (bfgs.cc:947): you must make at least 2 passes to use BFGS
```
I think one of the ways to fix this is to move the reduction-specific command line options initialization code from setup() to some new reduction class function (ex, `bool options_init(vw&)`) that could be called from setup(). For example nn setup would be modified from:
```
base_learner* nn_setup(vw& all)
{
  if (missing_option<size_t, true>(all, "nn", "Sigmoidal feedforward network with <k> hidden units"))
    return nullptr;
  new_options(all, "Neural Network options")
  ("inpass", "Train or test sigmoidal feedforward network with input passthrough.")
  ("multitask", "Share hidden layer across all reduced tasks.")
  ("dropout", "Train or test sigmoidal feedforward network using dropout.")
  ("meanfield", "Train or test sigmoidal feedforward network using mean field.");
  add_options(all);

  po::variables_map& vm = all.vm;
  nn& n = calloc_or_die<nn>();
```
to:
```
bool options_init(vw& all)
{
if (  !(missing_option<size_t, true>(all, "nn", "Sigmoidal feedforward network with <k> hidden units")) 
      || all.help == "nn") 
 {
  new_options(all, "Neural Network options")
  ("inpass", "Train or test sigmoidal feedforward network with input passthrough.")
  ("multitask", "Share hidden layer across all reduced tasks.")
  ("dropout", "Train or test sigmoidal feedforward network using dropout.")
  ("meanfield", "Train or test sigmoidal feedforward network using mean field.");
  
   if ( all.help == "nn")
   {
      cout << "\n" << all.new_opts << "\n";
      delete all.new_opts;
      return false;
    }   else add_options(all);
   return true;
 }
return false;  
}

base_learner* nn_setup(vw& all)
{
  if (! options_init(all)) 
    return null_ptr;

  po::variables_map& vm = all.vm;
  nn& n = calloc_or_die<nn>();
```

where all.help is a std::string that holds --help argument.
It would be also great to suppress all standard help output if --help argument isn't empty. In this case by using `--help nn` you will get only 4 lines of Neural Network options instead of whole standard help output + Neural Network options. It's pretty hard to find reduction options in this output and separate from reductions themselves:
```
vw --nn 1 --help
...
  --lrq arg                             use low rank quadratic features

  --autolink arg                        create link function with polynomial d

  --new_mf arg                          rank for reduction-based matrix 
                                        factorization

  --nn arg                              Sigmoidal feedforward network with <k> 
                                        hidden units

Neural Network options:
  --inpass                              Train or test sigmoidal feedforward 
                                        network with input passthrough.
  --multitask                           Share hidden layer across all reduced 
                                        tasks.
  --dropout                             Train or test sigmoidal feedforward 
                                        network using dropout.
  --meanfield                           Train or test sigmoidal feedforward 
                                        network using mean field.

  --confidence                          Get confidence for binary predictions

  --active_cover                        enable active learning with cover

  --active                              enable active learning

  --replay_b arg                        use experience replay at a specified 
                                        level [b=classification/regression, 
...
```

**Comment by martinpopel** [comment]
I like these suggestions. I think there can be a helper function, so we don't need to repeat the `|| all.help == "nn"` in all reductions code (where `nn` is substituted with the respective reduction name). This could allow us also to use `vw --help=all`, which would print help messages for all reductions. This may be helpful e.g. for `vw --help=all | grep keyword` (that is in cases where you don't know which reduction to use, but you want to find all reductions that have something to do with the *keyword*).

**Comment by JohnLangford** [comment]
There are good ideas here that I have not yet had time to implement.  Nevertheless, I'd like to see it happen.

**Comment by JohnLangford** [comment]
This finally happened :-)  vw --help just prints everything now.
