### ISSUE TITLE
Tricky segfaut when using --random_seed and -O3

### ISSUE THREAD

**Issue by trufanov-nok** [JohnLangford/vowpal_wabbit#673]
Thanks to @stephen-hoover and a big luck we've found another memory corruption.
It seems that while working on previous issue something  had damaged --quiet functionality (that behaviour disappeared after `make clean`) which let us realize that `make tests` 18 and 19 are actually cause segfaults.
That wasn't detected because these tests use `--quiet` and compared with empty output files.

After some debugging I was able to reproduce segfault in Linux and found out that:
1. segfaut happens only in presence of `--random_seed`
2. segfaut happens only if `-O3` flag was passed to GCC (another thing that hide this from me as I’m not using such flags in my QtCreator debug setup.)
3. segfaut happens after a call to `po::notify(vm);` in [best_constant.cc](https://github.com/JohnLangford/vowpal_wabbit/blob/master/vowpalwabbit/best_constant.cc#L36)

It seems that `po::notify` must throw exceptions if command line is malformed and don't match options configuration but it didn't. It just corrupts memory.

It looks like i'm reparsing command line at best_constant.cc and this approach was implemented before stack of reductions. Nowadays I can just take a reference to all.vw and use it. This fixes the segfaut (at least for me, currently Stephen checks if this fixes it on Mac too. In his case segfaut happens during learning, so it might not). 

As it was in my code I put some efforts to find out how I made this mistake and found the real cause (imho). The problem happens if only `--random_seed` is passed to command line. It's not depend on other params, `random_seed` param name or its description. But it depends on fact that local variable address is [passed](https://github.com/JohnLangford/vowpal_wabbit/blob/master/vowpalwabbit/parse_args.cc#L864) to its constructor:
```
  size_t random_seed = 0;
  new_options(all, "VW options")
    ("random_seed", po::value<size_t>(&random_seed), "seed random number generator");
```

If you replace it with some member of `all` it won't segfault.

My hypothesis is that in case `--random_seed` value specified it tries to push its value to address in local stack (to local variable). It's fine for `parse_args` but cause memory corruption if `all.opts` is used for parsing in any other function. So either `all.opts` content should be modified before such usage or address from heap should be passed to `random_seed`. And somehow bad things didn't happen if you don't use `-O3`. I suspect memory corruption happens always but don't cause segfault.

This `--random_seed` problem doesn't cause segfault in other paces of code just because `all.new_opts` is used instead of `all.opts` everywhere. And in [only place](https://github.com/JohnLangford/vowpal_wabbit/blob/master/vowpalwabbit/parse_args.cc#L269) `all.opts` is reused the `po::notify()` call was removed after `po::store`. If you return `po::notify()` call in `parse_source()` function bad things might start to happen faster.

So my suggestion is not only reusing existing `all.vm` in best_constant.cc but also fixing the root cause by passing heap address to `--random_seed` param declaration. 

It looks like `random_seed` is only parameter in master branch that takes local variable address. I took a brief look - so don't guarantee that.

**Comment by JohnLangford** [comment]
This is another piece of good detective work.   Thanks.

I suspect that the optimizing compiler notes that only the address of 
the local variable is required, gives that address, but then uses the 
space for something else.  Freaky.

po::notify() is supposed to be called at most once for every argument, 
so it's incorrect to call it again in parse_source(). Note that 
po::notify() _is_ called in add_options() so it is called for every 
argument.  The extra options stuff in parse_source() exists to allow a 
default parameter which can't otherwise be supported with incremental 
options specification.

-John

**Comment by trufanov-nok** [comment]
Feel free to close this one.
