### ISSUE TITLE
unable to run/compile python wrapper on Windows

### ISSUE THREAD

**Issue by AhmedGS** [JohnLangford/vowpal_wabbit#685]
Dear all,

My system is Windows 8.1, when I sucessfully compile vw (debug and release) using Visual studio I'm trying to run the python wrapper but unsuccessful.

I tried what I did on a Linux machine (run the 'make' command inside the python folder). 

I tried to run the 'make' from the python folder under windows using Cygwin64 but I'm getting errors (below) (& warnings):

Any help will be appreciated.

 /cygdrive/d/src/vw/vowpal_wabbit/python
$ make
cd ..; make python
make[1]: Entering directory '/cygdrive/d/src/vw/vowpal_wabbit'
cd vowpalwabbit; make -j 4 things
make[2]: Entering directory '/cygdrive/d/src/vw/vowpal_wabbit/vowpalwabbit'
/usr/bin/g++ -std=c++0x   -D__extern_always_inline=inline -Wall -pedantic -O3 -fomit-frame-pointer -fno-strict-aliasing  -D_FILE_OFFSET_BITS=64 -DNDEBUG -I /usr/include  -fPIC  -c main.cc -o main.o
/usr/bin/g++ -std=c++0x   -D__extern_always_inline=inline -Wall -pedantic -O3 -fomit-frame-pointer -fno-strict-aliasing  -D_FILE_OFFSET_BITS=64 -DNDEBUG -I /usr/include  -fPIC  -c global_data.cc -o global_data.o
/usr/bin/g++ -std=c++0x   -D__extern_always_inline=inline -Wall -pedantic -O3 -fomit-frame-pointer -fno-strict-aliasing  -D_FILE_OFFSET_BITS=64 -DNDEBUG -I /usr/include  -fPIC  -c io_buf.cc -o io_buf.o
/usr/bin/g++ -std=c++0x   -D__extern_always_inline=inline -Wall -pedantic -O3 -fomit-frame-pointer -fno-strict-aliasing  -D_FILE_OFFSET_BITS=64 -DNDEBUG -I /usr/include  -fPIC  -c parse_regressor.cc -o parse_regressor.o
global_data.cc:1:0: warning: -fPIC ignored for target (all code is position independent)
 /*
 ^
main.cc:1:0: warning: -fPIC ignored for target (all code is position independent)
 /*
 ^
parse_regressor.cc:1:0: warning: -fPIC ignored for target (all code is position independent)
 /*
 ^
io_buf.cc:1:0: warning: -fPIC ignored for target (all code is position independent)
 /*
 ^
In file included from io_buf.cc:6:0:
io_buf.h: In member function ‘virtual int io_buf::open_file(const char*, bool, int)’:
io_buf.h:72:25: error: ‘fileno’ was not declared in this scope
       ret = fileno(stdin);
                         ^
Makefile:32: recipe for target 'io_buf.o' failed
make[2]: *** [io_buf.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from comp_io.h:7:0,
                 from global_data.h:20,
                 from parse_args.h:7,
                 from main.cc:13:
io_buf.h: In member function ‘virtual int io_buf::open_file(const char*, bool, int)’:
io_buf.h:72:25: error: ‘fileno’ was not declared in this scope
       ret = fileno(stdin);
                         ^
In file included from comp_io.h:7:0,
                 from global_data.h:20,
                 from global_data.cc:14:
io_buf.h: In member function ‘virtual int io_buf::open_file(const char*, bool, int)’:
io_buf.h:72:25: error: ‘fileno’ was not declared in this scope
       ret = fileno(stdin);
                         ^
global_data.cc: In constructor ‘vw::vw()’:
global_data.cc:318:32: error: ‘fileno’ was not declared in this scope
   stdout_fileno = fileno(stdout);
                                ^
Makefile:35: recipe for target 'main.o' failed
make[2]: *** [main.o] Error 1
Makefile:32: recipe for target 'global_data.o' failed
make[2]: *** [global_data.o] Error 1
In file included from comp_io.h:7:0,
                 from global_data.h:20,
                 from parse_regressor.cc:19:
io_buf.h: In member function ‘virtual int io_buf::open_file(const char*, bool, int)’:
io_buf.h:72:25: error: ‘fileno’ was not declared in this scope
       ret = fileno(stdin);
                         ^
Makefile:32: recipe for target 'parse_regressor.o' failed
make[2]: *** [parse_regressor.o] Error 1
make[2]: Leaving directory '/cygdrive/d/src/vw/vowpal_wabbit/vowpalwabbit'
Makefile:92: recipe for target 'vw' failed
make[1]: *** [vw] Error 2
make[1]: Leaving directory '/cygdrive/d/src/vw/vowpal_wabbit'
Makefile:24: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by JohnLangford** [comment]
The python interface has not been tested with windows, and in particular 
with the VS compile.   I would not be surprised if some work is required 
there.

I'm not sure what to make of:
/io_buf.h:72:25: error: ‘fileno’ was not declared in this scope/

fileno() is supposed to be defined in stdio.h, which is included in 
io_buf.h.

-John

**Comment by AhmedGS** [comment]
Thanks John, I switched to Linux to use it :)

Thanks.
