### ISSUE TITLE
A couple of issues with vowpal_wabbit/python/word_alignment.py

### ISSUE THREAD

**Issue by emjotde** [JohnLangford/vowpal_wabbit#700]
Hi, 
the word alignment example from  vowpal_wabbit/python/word_alignment.py
is not working for me. This iter member call in line 98 seems to be wrong (python croaks), when removed or replaced with iter(my_data) it segfaults. And I just noticed that covington.py segfaults, too. Seems to be same issue. test_search.py and test_search_ldf.py work.
Best,
Marcin

**Comment by JohnLangford** [comment]
Hmm.  Hal, can you take a look?

-John
