### ISSUE TITLE
using --daemon to train a model

### ISSUE THREAD

**Issue by slymore** [JohnLangford/vowpal_wabbit#706]
I'd like to train a model by streaming data to the daemon. In the tutorial "daemon example" of the wiki it is shown how to use the daemon to get predictions from input data (given a pre trained model). 

1. Is it possible to get the daemon to write a model file (to get the weight values) after somehow notifying it that it has received all the training data ?

2. other problem: when in testing mode, I can't get to send multiple examples to the daemon. after I establish a TCP connection and send the examples, it only takes into account the first line received then stops and "waits". I also don;t receive anything back from the daemon (no prediction value). Here is my client code:

```
int len;
char line[256];
TCPConnector* connector = new TCPConnector();
TCPStream* stream = connector->connect(argv[2], atoi(argv[1]));
if (stream) {
string line_f;
ifstream myfile ("train.vw");
if (myfile.is_open())
{
  while ( getline (myfile,line_f) )
  {
        stream->send(line_f.c_str(), line_f.size());
        printf("sent - %s\n", line_f.c_str());
        len = stream->receive(line, sizeof(line));
        cout << line << '\n';
  }
  myfile.close();
}
else cout << "Unable to open file";
delete stream;
}
```

What am I doing wrong ?

**Comment by slymore** [comment]
Found the answer to 2.
line_f is a std::string object so newline is std::endl. vw expects an ASCII 10 newline "\n".
One solution is to do: 
 ``` line_f.replace(line_f.size()-1,1,"\n");```
before sending it to the daemon.
To correctly receive the output, I needed to terminate line:
```line[len] = 0;```
link : http://stackoverflow.com/questions/30882838/how-to-use-vowpal-wabbit-for-online-prediction-streaming-mode

**Comment by JohnLangford** [comment]
You can send an empty example with a tag that says 'save_<file>' to get 
the daemon to save.

-John
