### ISSUE TITLE
Trying to recover probabilities from command line  in daemon mode not working.

### ISSUE THREAD

**Issue by japerez20** [JohnLangford/vowpal_wabbit#724]
My goal is to recover the probabilities from the command line when i am in daemon mode using python.

Based on the response given  below, which  I verified it works (thanks)
http://stackoverflow.com/questions/30764810/how-do-i-get-the-raw-predictions-r-from-vowpal-wabbit-when-running-in-daemon

I do the next:

#I start my process in Daemon
                                    os.system('vw -t -i model.vw --daemon --port 26542 --link=logistic -r /dev/stdout')

Then i start sending examples with the model above in order to get probabilities.
command='echo "2 | landstar system downgraded to sell at zacks lstr |a word_count:8" | nc localhost 26542'

                                      proc = subprocess.Popen(command,shell=True,stdout=subprocess.PIPE)

then I tried to read the output
                                      proc.stdout.read()
but the above instruction returns

'1.000000\n'  

It only returns the prediction :( which is correct. I  can see how the probabilities  were created  properly in the command line but I cannot  extract them . I tried different ways but none of them worked. I only can extract the prediction, which is useless for the task than i want to do.

Could you be so kind to tell me how I can get the probabilities?

I am using mac OS X Yosemite, version 10.10.3.
VW version 7.10.2

Thank you,

ja

**Comment by trufanov-nok** [comment]
Hi,
`-r /dev/stdout` approach proposed on stackoverflow works fine for me on kubuntu. Are you sure the problem is not in your code used to read vw's response?

**Comment by JohnLangford** [comment]
This is part of why -r is a hack---it does not use the standard pipelines because it is totally untyped.  The right thing to do here is to modify VW to have a 'report all probabilities' mode.  @martinpopel is working on that.
