### ISSUE TITLE
perform prediction step on hadoop?

### ISSUE THREAD

**Issue by followyourheart** [JohnLangford/vowpal_wabbit#728]
I know how to perform the training step on hadoop using vw:

see mapscript.sh and runvw-yarn.sh.

After got the model, how can i use the model to prredict new instance on hadoop with vw?

Any help will be highly appreciated.

**Comment by JohnLangford** [comment]
This is just a straight-forward map only job.  You move VW and the 
trained model to the node with -file or -files and then you invoke it on 
a hadoop streaming job.

-John

**Comment by followyourheart** [comment]
Yes, after the question, I got the idea how to do it. Same as you mentioned.
using -files to put vw and libs, 

-mapper "predict.sh MODEL_NAME"

predict.sh
	./vw 
	-t 
	-i ${MODEL_NAME} 
	-d /dev/stdin 
	-p /dev/stdout
