### ISSUE TITLE
expected processing of test examples in case they are mixed in train dataset

### ISSUE THREAD

**Issue by trufanov-nok** [JohnLangford/vowpal_wabbit#729]
Hi,

I'm considering following VW use case:
* VW runs in daemon mode and trains on data it receives via opened port
* sometimes VW receives examples to predict and outputs result.

This allows keep model up-to-date with data flow while getting predictions.

Usually I train vw with some labelled dataset and then get prediction with another dataset by specifying `-t`. Frankly, I always used dummy labels for such test dataset.
This approach won't work as now I need to get prediction in a middle of train step. E.g. both steps are mixed. 

Ok, but VW seems to still be suitable for such use case from the box.   
As I understood VW supposed to treat examples without label as test example. (And assigns FLT_MAX as label automatically).   
So my expectation that `vw -i model -t dummy_labelled_dataset` should work exactly as `vw -i model -d unlabeled_dataset`.   

On practice, this is at least not guaranteed. Or my expectations aren't correct?

For example, at least `vw --oaa 3` calls `base.update` for examples labelled with FLT_MAX too. So they are affecting weights in regressor.
I'm also not happy with the fact that such examples affects progressive loss value. I would want to see average loss that reflects only non-test examples, unless `-t` is explicitly specified or example is marked as tested by holdout rule.

I'm going to adjust this behaviour at least for myself.
But, perhaps I'm just not understanding how VW should work in case test examples are mixed with train examples.
1. Am I right that unlabelled (FLT_MAX) examples **must** be treated as test examples?
2. Is oaa behaviour a bug? Or it has sense to train on such examples for some reductions?
3. How about changing loss reporting to exclude effect of test examples (with exception of -t and holdout)? Won't it be too confusing for end-user?

**Comment by trufanov-nok** [comment]
It looks like I can achieve desired behaviour by setting `ec.test_only` for examples that have default label. Shouldn't it be like that by default?

**Comment by JohnLangford** [comment]
This sounds like a bug to me.  no label should definitely hit the same 
code path as -t.  Can you send a patch please?

-John

**Comment by trufanov-nok** [comment]
Hi,
Sorry for delay, I've just returned from vacation. 
I think I'd fixed in my local fork. Will take a look on this again in a next few day and try to fix it in master.

**Comment by arielf** [comment]
This would be nice to fix in master.

Being able to switch between 'test-only' and 'learn' dynamically during run-time on a per-example granularity is very useful.

However: I don't feel setting the label to FLT_MAX is the cleanest way to go. Why?

We need to also  support _actual_ labels (when known), otherwise estimated loss is meaningless.

So we need to be able to switch modes _regardless_ of what the label is (FLT_MAX is useless for determining real loss).

The way to really do it cleanly is to set the weight of the example to 0 (rather than marking the label as special).

But I'm not sure how cleanly this would work in the current implementation.  Does a weight of 0 really leaves no side effects?

**Comment by trufanov-nok** [comment]
Sounds not easy to do. Can we estimate how many of vw tests will be failed if instead of `vw -t data` we run `sed data -e 'ensure that label (if any) is removed' | vw`? If it's only oaa/ect it would worth to make a simple fix at least as temporary solution.

**Comment by JohnLangford** [comment]
Weight 0 is not precisely equivalent to test only.  The difference comes 
when using --normalized.  If an example with weight 0 has features with 
a new scale, that is taken into account.  However, a test example never 
causes a rescaling.

The basic question here is dispatch.  How do you know whether you should 
call predict or learn?

-John

**Comment by arielf** [comment]
Ideally, `vw` should have a way to say whether to "update weights" or not in whatever field to the left of the first `|`

This runtime per example, user-settable "switch",  should be setting the internal variable.

**Comment by trufanov-nok** [comment]
I've faced with a requirement to switch examples test\train mode at runtime again. Test mark that's not based on labels or weights seems to be a good idea. I've taken a look into parse_example.cc and tried some toy examples. How about these two marks:
1. It can be double `|` that separates label zone from features.  Like `labels tag|| feature:weight` instead of `labels tag| feature:weight`. Looks like this insertion affects nothing in current VW implementation.
2. Looks like VW [ignores](https://github.com/JohnLangford/vowpal_wabbit/blob/master/vowpalwabbit/parse_example.cc#L325) a part of label area that ends with TAB symbol. Like `comment<TAB>label tag| feature`. Was it done for commenting examples? Anyway, required switch could be hidden with this <TAB>.

**Comment by JohnLangford** [comment]
My understanding is that an empty label should give you the desired
behavior with any variation from that a bug that should be fixed.  No?

-John

**Comment by trufanov-nok** [comment]
As it was pointed out by Ariel the estimated loss would be meaningless in this case.

**Comment by JohnLangford** [comment]
Definitely correct.  When/why do you want a test error in a mixed
train/test environment?

-John

On Mon, Apr 4, 2016 at 1:43 PM, Alexander Trufanov <notifications@github.com

**Comment by trufanov-nok** [comment]
I suppose such mix in will spoil the training loss. Ideally I'd need both training and test loss reported separately in a mixed case.

**Comment by JohnLangford** [comment]
Since test loss is a very easy thing, maybe it is easiest to compute it
externally from the predictions?  You can be very _sure_ of any test loss
where VW is completely unaware of the label.

-John


On Mon, Apr 4, 2016 at 2:00 PM, Alexander Trufanov <notifications@github.com

**Comment by JohnLangford** [comment]
Closing this for now.
