### ISSUE TITLE
Vowpal Wabbit installation error 

### ISSUE THREAD

**Issue by ashokharnal** [JohnLangford/vowpal_wabbit#730]
While installing vowpal wabbit on centos 6.5, I get the following error when running '$ make' command:

At global scope:
cc1plus: warning: unrecognized command line option "-Wno-unused-local-typedef" [enabled by default]
make[2]: *** [lda_core.lo] Error 1
make[2]: Leaving directory `/home/test/vowpal_wabbit/vowpalwabbit'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/home/test/vowpal_wabbit/vowpalwabbit'
make: *** [all-recursive] Error 1

I may mention that I have run  '$ ./configure --enable-debug'   but no errors or deficiencies were reported.

Please let me know how to get over it.

Thanks.

**Comment by ashokharnal** [comment]
A detailed error output is as follows that I did not supply in the above post.
++++++++++++++++++++++++++++++++++++++++++++++++++++++++

libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I/usr/include -I/include -Wall -Wno-unused-local-typedef -pedantic -ffast-math -O3 -fomit-frame-pointer -fno-strict-aliasing -DNDEBUG -std=gnu++11 -MT lda_core.lo -MD -MP -MF .deps/lda_core.Tpo -c lda_core.cc  -fPIC -DPIC -o .libs/lda_core.o
lda_core.cc: In function ‘T ldamath::lgamma(T)’:
lda_core.cc:361:96: error: there are no arguments to ‘BOOST_STATIC_ASSERT_MSG’ that depend on a template parameter, so a declaration of ‘BOOST_STATIC_ASSERT_MSG’ must be available [-fpermissive]
     BOOST_STATIC_ASSERT_MSG(true, "ldamath::lgamma is not defined for this type and math mode.");
                                                                                                ^
lda_core.cc:361:96: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
lda_core.cc: In function ‘T ldamath::digamma(T)’:
lda_core.cc:367:97: error: there are no arguments to ‘BOOST_STATIC_ASSERT_MSG’ that depend on a template parameter, so a declaration of ‘BOOST_STATIC_ASSERT_MSG’ must be available [-fpermissive]
     BOOST_STATIC_ASSERT_MSG(true, "ldamath::digamma is not defined for this type and math mode.");
                                                                                                 ^
lda_core.cc: In function ‘T ldamath::exponential(T)’:
lda_core.cc:373:101: error: there are no arguments to ‘BOOST_STATIC_ASSERT_MSG’ that depend on a template parameter, so a declaration of ‘BOOST_STATIC_ASSERT_MSG’ must be available [-fpermissive]
     BOOST_STATIC_ASSERT_MSG(true, "ldamath::exponential is not defined for this type and math mode.");
                                                                                                     ^
lda_core.cc: In function ‘T ldamath::powf(T, T)’:
lda_core.cc:379:94: error: there are no arguments to ‘BOOST_STATIC_ASSERT_MSG’ that depend on a template parameter, so a declaration of ‘BOOST_STATIC_ASSERT_MSG’ must be available [-fpermissive]
     BOOST_STATIC_ASSERT_MSG(true, "ldamath::powf is not defined for this type and math mode.");
                                                                                              ^
At global scope:
cc1plus: warning: unrecognized command line option "-Wno-unused-local-typedef" [enabled by default]
make[2]: *** [lda_core.lo] Error 1
make[2]: Leaving directory `/home/test/vowpal_wabbit/vowpalwabbit'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/home/test/vowpal_wabbit/vowpalwabbit'
make: *** [all-recursive] Error 1

+++++++++++++++++++++++++++++++++++++++++++++++++++++++

Thanks

**Comment by arielf** [comment]
Hi and thanks for the report,

Unfortunately, CentOS is not the friendliest of env for development/building, and boost is notorious for binary compatibility.  If the boost library on your system isn't built with the same compiler you build vw with, all bets are off.  If you have access to a Ubuntu/debian box, you can build statically there and  then copy the resulting executable to your CentOS box. See how to do this under "Ubuntu advanced build options (clang and static)"  here: [https://github.com/JohnLangford/vowpal_wabbit/blob/master/README.md](https://github.com/JohnLangford/vowpal_wabbit/blob/master/README.md)

Another solution is to make sure you have the `-dev` package for `libboost-program-options` before you build vw from scratch.  This way you have full boost _headers_ which are usually located under `/usr/include/boost/program_options/...` and `/usr/include/boost/program_options.hpp` and your build has better chances of succeeding.

Anyway, to try and help, I just did the 1st solution for you and others and uploaded the recently bult, and fully statically-linked (which includes all required version-consistent libs) excutable of vw for your convenience here:

 &nbsp;&nbsp;&nbsp;&nbsp;[http://finance.yendor.com/ML/VW/vw-7.20150623](http://finance.yendor.com/ML/VW/vw-7.20150623)

This binary should run on *any* Intel IA64 hardware (or amd64) running *any* distro of Linux.

 Please verify that the file matches the sums/signatures below after downloading (shared hosting box which I don't adminster, so I can't guarantee full integrity):

```
    $ file vw-7.20150623
    vw-7.20150623: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), statically linked, for GNU/Linux 2.6.24, BuildID[sha1]=0x766351e8af7749a684583a32f9f94dc9ce1de98a, not stripped

    $ sha1sum  vw-7.20150623
    1f4cde5085f18ecb54f3b911ede0995284565f93  vw-7.20150623

    $ sha256sum vw-7.20150623
    dd2769d7ca350ee10ecb6584f8da0d09942ba0fc4defe1d645d3ab14025f927c  vw-7.20150623
```
HTH

**Comment by ashokharnal** [comment]
Many Many thanks for your time and effort. The binary file works.

**Comment by ashokharnal** [comment]
Many Many thanks for your time and effort. The binary file works.

On 18 July 2015 at 11:10, Ariel Faigon <notifications@github.com> wrote:

> Hi and thanks for the report,
>
> Unfortunately, CentOS is not the friendliest of env for
> development/building, and boost is notorious for binary compatibility. If
> the boost library on your system isn't built with the same compiler you
> build vw with, all bets are off. If you have access to a Ubuntu/debian box,
> you can build statically there and then copy the resulting executable to
> your CentOS box. See how to do this under "Ubuntu advanced build options
> (clang and static)" here:
> https://github.com/JohnLangford/vowpal_wabbit/blob/master/README.md
>
> Another solution is to make sure you have the -dev package for
> libboost-program-options before you build vw from scratch. This way you
> have full boost *headers* which are usually located under
> /usr/include/boost/program_options/... and
> /usr/include/boost/program_options.hpp and your build has better chances
> of succeeding.
>
> Anyway, to try and help, I just did the 1st solution for you and others
> and uploaded the recently bult, and fully statically-linked (which includes
> all required version-consistent libs) excutable of vw for your convenience
> here:
>
>     http://finance.yendor.com/ML/VW/vw-7.20150623
>
> This binary should run on *any* Intel IA64 hardware (or amd64) running
> *any* distro of Linux.
>
> Please verify that the file matches the sums/signatures below after
> downloading (shared hosting box which I don't adminster, so I can't
> guarantee full integrity):
>
>     $ file vw-7.20150623
>     vw-7.20150623: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), statically linked, for GNU/Linux 2.6.24, BuildID[sha1]=0x766351e8af7749a684583a32f9f94dc9ce1de98a, not stripped
>
>     $ sha1sum  vw-7.20150623
>     1f4cde5085f18ecb54f3b911ede0995284565f93  vw-7.20150623
>
>     $ sha256sum vw-7.20150623
>     dd2769d7ca350ee10ecb6584f8da0d09942ba0fc4defe1d645d3ab14025f927c  vw-7.20150623
>
> HTH
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JohnLangford/vowpal_wabbit/issues/730#issuecomment-122486481>
> .
>



-- 
Visit my blog at: http://ashokharnal.wordpress.com/

**Comment by uohzoaix** [comment]
hi,what can i do with vw-7.20150623?

**Comment by uohzoaix** [comment]
i encounter the same problem,how can i solve it?

**Comment by ashokharnal** [comment]
vw-7.. is a binary version. It can be executed in CentOS as it is.

**Comment by JohnLangford** [comment]
Closing this---I don't have access to CentOS and so can't fix.  It would be good to fix though.

**Comment by smartkiwi** [comment]
I've got same error when I was building vw 7.10 using boost library (version 1.3 something) available on CentOS 4.7 from EPEL repo.
I've found repo that providers boost package 1.59 here http://vicendominguez.blogspot.com/2014/04/boost-c-library-rpm-packages-for-centos.html
Once I've installed newer boost package I was able to build vw 7.10

**Comment by jennakwon06** [comment]
Which version of Boost package is needed for vw 8.2?

**Comment by bifeng** [comment]
@ashokharnal   how to using vw-7.20150623 on centos?

**Comment by haimnkfans** [comment]
hi, i am getting the same error. I have RHEL 6, gcc 4.8.2 and boost is 1.41. Could someone suggest that vw can be built in this configuration. Is there -dev package available for RHEL 6?

**Comment by arielf** [comment]
You may use a statically linked `vw` executable even on very old RHEL/CentOS versions by simply copying it from a place where you can build statically (when you build with `g++ -static` the single binary executable includes all the required libraries).

If you can't build it yourself, you may use any of these (statically precompiled by me):    [http://finance.yendor.com/ML/VW/Binaries/](http://finance.yendor.com/ML/VW/Binaries/)

**Comment by Spikhalskiy** [comment]
Put this information here just for a reference for anybody who is looking for building under CentOS 6. This is what I do before ```pip install vowpalwabbit``` both to conda or to main python distribution under CentOS 6.8. Contain commented lines for a case of building a docker image. Pretty sure the same should help with just building the vowpal-wabbit library.

```
yum -y install wget make python-devel zlib-devel

# Boost 1.59 required for vowpal wabbit, Boost 1.41 is going with CentOs 6.8 image and repo
wget http://repo.enetres.net/enetres.repo -O /etc/yum.repos.d/enetres.repo
yum -y install boost-devel

# GCC and G++ 4.8.2 for vowpal wabbit build, 4.4.x is going with CentOs 6.8 image
wget http://people.centos.org/tru/devtools-2/devtools-2.repo -O /etc/yum.repos.d/devtools-2.repo
yum -y install devtoolset-2-gcc devtoolset-2-gcc-c++ devtoolset-2-binutils devtoolset-2-runtime devtoolset-2-libstdc++-devel

scl enable devtoolset-2 bash
# Set PATH, because "scl enable" does not have any effects inside "docker build"
#-docker- PATH /opt/rh/devtoolset-2/root/usr/bin:$PATH
# Set CC, CXX, LD variables for make, because "scl enable" does not have any effects inside "docker build"
#-docker- ENV CC /opt/rh/devtoolset-2/root/usr/bin/gcc
#-docker- ENV CXX /opt/rh/devtoolset-2/root/usr/bin/g++
#-docker- ENV LD /opt/rh/devtoolset-2/root/usr/bin/ld

# Python 2.7 for vowpal wabbit, CentOs 6.8 comes with python 2.6
# --enable-shared flag is important for the vowpal wabbit build
cd /opt &&\
  wget --no-check-certificate https://www.python.org/ftp/python/2.7.6/Python-2.7.6.tar.xz &&\
  tar xf Python-2.7.6.tar.xz &&\
  cd Python-2.7.6 &&\
  ./configure --enable-shared --prefix=/usr/local &&\
  make && make altinstall

ln -s /usr/local/bin/python2.7 /usr/bin/python2.7
echo "/usr/local/lib/python2.7" > /etc/ld.so.conf.d/python27.conf
echo "/usr/local/lib" >> /etc/ld.so.conf.d/python27.conf
ldconfig
```

**Comment by matanster** [comment]
@Spikhalskiy is seems that the following is no longer available:
> wget http://repo.enetres.net/enetres.repo -O /etc/yum.repos.d/enetres.repo

At least from my CentOs version 6.9. I am getting the same errors reported at the top of this thread. Any idea how to obtain a suitable version of boost?
