### ISSUE TITLE
vw-hypersearch param boundaries

### ISSUE THREAD

**Issue by trufanov-nok** [JohnLangford/vowpal_wabbit#733]
Hi,
I've just tried following:
```
$ ./utl/vw-hypersearch -t test 2 4 ../vowpalwabbit/vw -q ::  --oaa 3 -d ./data -c -f ./model  -l 0.013 --passes %
trying 3 .................................... 0.379794 (best)
loss(3) == loss(3): 0.379794
3       0.379794
```
It seems script exited without trying 2 and 4. Could someone confirm? I expected it to try 3, then 2, then 4.
P.S. I hadn't work with vw-hypersearch for a long time and may be doing something wrong...

**Comment by arielf** [comment]
Looks like a bug. The golden-section search excludes range end points.  This is not a serious problem with real values as it is with integer options like --oaa.  A quick work-around is to specify a wider range in this case `wv-hypersearch ... 1 5 ...`

**Comment by arielf** [comment]
Also: a obligatory question: wouldn't discrete cases (like `--oaa K`) non-continuous/convex in the loss?  Should they actually require a search of all the range to be safe?

**Comment by trufanov-nok** [comment]
Yes, it's not a big problem.
Note, I'm hypersearching `passes` not `oaa`.

I'd just invoked the script with `1 6` and got optimum at 3 passes. Then I modified a few things and decided to make sure that the optimum is still at 3 passes by checking it and its neighbours.

**Comment by JohnLangford** [comment]
What is the status of this Ariel?

**Comment by arielf** [comment]
still a bug but one that's really easy to work around by giving a wider range to search.

**Comment by JohnLangford** [comment]
I'm going to close this, but if you want to fix, please do so.
