### ISSUE TITLE
ezexample's destructor segfaults when wrapping existing examples. 

### ISSUE THREAD

**Issue by emjotde** [JohnLangford/vowpal_wabbit#737]
Hi,
ezexample's destructor segfaults if ezexample is used to wrap an existing normal example. I think there is a check for we_create_ec missing. The comment actually says there should be a check, doesn't it?

Maybe should be:

    ~ezexample() { // calls finish_example *only* if we created our own example!
       if(we_create_ec) {
            ...
       }
    }

Best,
Marcin

**Comment by JohnLangford** [comment]
Thanks, I added an extra check to the code.

-John
