### ISSUE TITLE
Vowpal Wabbit Truck Factor

### ISSUE THREAD

**Issue by gavelino** [JohnLangford/vowpal_wabbit#741]
As part of my PhD research on code authorship, we calculated the Truck Factor (TF) of some popular GitHub repositories.

As you probably know, the [Truck (or Bus) Factor](https://en.wikipedia.org/wiki/Bus_factor) designates the minimal number of developers that have to be hit by a truck (or quit) before a project is incapacitated. In our work, we consider that a system is in trouble if more than 50% of its files become orphan (i.e., without a main author).

More details on our work in this preprint: https://peerj.com/preprints/1233

We calculated the TF for **Vowpal Wabbit** and obtained a value of **2**.

The developers responsible for this TF are:

John Langford - author of 51% of the files
Hal Daume III - author of 35% of the files

To validate our results, we would like to ask **Vowpal Wabbit** developers the following three brief questions:

(a) Do you agree that the listed developers are the main developers of **Vowpal Wabbit**?

(b) Do you agree that **Vowpal Wabbit** will be in trouble if the listed developers leave the project (e.g., if they win in the lottery, to be less morbid)?

(c) Does **Vowpal Wabbit** have some characteristics that would attenuate the loss of the listed developers (e.g., detailed documentation)?

Thanks in advance for your collaboration,

Guilherme Avelino
PhD Student
Applied Software Engineering Group (ASERG)
UFMG, Brazil
http://aserg.labsoft.dcc.ufmg.br/

**Comment by JohnLangford** [comment]
That's a pretty fun thesis.  Hal and I have written a substantial portion
of the code over time so the numbers seem reasonable.  There are several
others who have understood a substantial part of the code and contributed
very technical things as well, and perhaps one of them could take over.
However, I don't really dispute the truck factor, at least in the past.  A
major caveat is that I don't expect the future to be like the past---we
have been working on making the internals be better hardened, and written
various papers:  http://arxiv.org/pdf/1502.02704
http://arxiv.org/abs/1406.1837 discussing the architecture.

Also, I don't believe winning the lottery would stop me from working on
VW.  It needs to be a truck  :-)

-John

**Comment by gavelino** [comment]
Thank you.
