### ISSUE TITLE
weird behavior on hadoop

### ISSUE THREAD

**Issue by followyourheart** [JohnLangford/vowpal_wabbit#747]
using vw training LR on hadoop, I experienced weird behavior of vw:

1. 10GB input data 
request 150 mappers, run ok with 5min.

2. 40GB input data 
request 2000 mappers, but I don't have enough mappers more 2000 at once. so this time, it run so much time more than 12 hours and I killed it. 

I just wonder that 
when running vw on hadoop, does that mean, only when the requested mappers satisfied, can the training process start?  In my experiment, the training does not require many mappers, only the caching file requests many. When the mappers finished the caching, why all or some of them not return to the pool?

Appreciate your help. 

Waiting!!

**Comment by JohnLangford** [comment]
You definitely need all the mappers to run simultaneously.  The key to 
getting good performance is network IO rather than disk IO.

-John
