### ISSUE TITLE
Unable to run make or make python on Mac OSX

### ISSUE THREAD

**Issue by simonhughes22** [JohnLangford/vowpal_wabbit#750]
I am trying to install from source on Mac OSX. I installed boost and boost python (using the -dev switch) as described in #376 . If I then try to run make within the github folder I get:

``` bash
cd vowpalwabbit; /Applications/Xcode.app/Contents/Developer/usr/bin/make -j 8 things
make[1]: Nothing to be done for `things'.
cd cluster; /Applications/Xcode.app/Contents/Developer/usr/bin/make
make[1]: Nothing to be done for `all'.
cd library; /Applications/Xcode.app/Contents/Developer/usr/bin/make things
make[1]: Nothing to be done for `things'.
```
I get the same error for python. I was able to previously install vw directly using homebrew, but that didn't install the python interface, which is why I tried installing from git. Please advise.

**Comment by sharatsc** [comment]
make should be executed from vowpal_wabbit the root and not vowpal_wabbit/vowpalwabbit?

**Comment by JohnLangford** [comment]
In what sense is this an error?  It says things are already made.

-John

**Comment by simonhughes22** [comment]
@JohnLangford - I still cannot get the python wrapper installed - I get importError when I try

```import pyvw

I have downloaded the source and called make, and make python. I made sure I pre-installed boost and boost python. I am running on OSX. If I call 'make python' from the source root folder, I get 'make: Nothing to be done for `python'.

Please advise. I don't see anything on the wiki

**Comment by simonhughes22** [comment]
Never mind. Found makefile in python subfolder and called make and it worked. Could do with some instructions on this for people like me who know nothing of C++

**Comment by JohnLangford** [comment]
Maybe send a pull request with appropriate instructions?

-John
