### ISSUE TITLE
Python example bug

### ISSUE THREAD

**Issue by zpz** [JohnLangford/vowpal_wabbit#752]
File python/word_alignment.py, line 98, 

task.learn(my_dataset.\_\_iter\_\_)

should be

task.learn(my_dataset)

**Comment by JohnLangford** [comment]
Hal, can you take a look at this?

-John

**Comment by JohnLangford** [comment]
@hal3 Ping

**Comment by JohnLangford** [comment]
@gramhagen What is the status on this?

**Comment by gramhagen** [comment]
this is fixed

**Comment by JohnLangford** [comment]
Thanks, closing.
