### ISSUE TITLE
Parse regressor assumes `uint32_t lda`

### ISSUE THREAD

**Issue by luke-clifton** [JohnLangford/vowpal_wabbit#755]
But [in VW 7.2 `lda` was a `size_t`](https://github.com/JohnLangford/vowpal_wabbit/blob/v7.2/vowpalwabbit/global_data.h#L206). This will cause problems if a model was generated with VW 7.2 (and maybe later) on a machine where `size_t` is 8 bytes, and that model is loaded into a version of VW where [`lda` was changed to `uint32_t`](https://github.com/JohnLangford/vowpal_wabbit/blob/master/vowpalwabbit/global_data.h#L495).

https://github.com/JohnLangford/vowpal_wabbit/blob/v7.2/vowpalwabbit/parse_regressor.cc#L157

https://github.com/JohnLangford/vowpal_wabbit/blob/master/vowpalwabbit/parse_regressor.cc#L250

Both just read/write `sizeof(all.lda)` bytes, in the latter, this is always 4 bytes, in the former it could be something else.

**Comment by luke-clifton** [comment]
Commit 562dba412fea3d7a2b246cbbe4b2694666403601 should probably have introduced a bounds check in the parser, as it can not guarantee that we can parse files from before this commit.

**Comment by JohnLangford** [comment]
Right.  I am bumping LAST_COMPATIBLE_VERSION to 7.6.0.  We've been late 
to the game of backwards compatibility, but we are explicitly worrying 
about it now.

-John
