### ISSUE TITLE
Python module: get_tag() returns empty string

### ISSUE THREAD

**Issue by KristianHolsheimer** [JohnLangford/vowpal_wabbit#758]
Hi there,

I just noticed an issue with the `pyvw.vw.example.get_tag()` method in `python/pyvw.py`. Namely, `get_tag()` fails to parse the example tag and returns an empty string.

The minimal way to reproduce this is to run (in source root):

    $ python python/test.py | grep 'tag ='
    tag = 
    tag = 

which should in fact return

    tag = foo
    tag = foo

I tried to figure out where things go wrong, but without success..

Would this be general issue with example tags or could it be a `pylibvw` issue?

**Comment by JohnLangford** [comment]
I'm assuming pylibvw.

**Comment by JohnLangford** [comment]
Hal, can you look into this one?

-John

**Comment by JohnLangford** [comment]
@hal3 Can you look into this?

**Comment by JohnLangford** [comment]
@gramhagen are tags working in python?

**Comment by gramhagen** [comment]
I'll take a look

**Comment by gramhagen** [comment]
looks like this is still a problem, I'll dig in further

**Comment by JohnLangford** [comment]
Closing.  Thanks @gramhagen !

**Comment by KristianHolsheimer** [comment]
Thanks @gramhagen and @JohnLangford 
I added a test for tags in pyvw in `python/tests/test_pyvw.py`, see https://github.com/JohnLangford/vowpal_wabbit/pull/1076

**Comment by gramhagen** [comment]
looks good! thanks @KristianHolsheimer
