### ISSUE TITLE
Segfault when combining --ftrl and --save_resume

### ISSUE THREAD

**Issue by KristianHolsheimer** [JohnLangford/vowpal_wabbit#763]
When I train a logistic regressor with `--ftrl` updates, VW segfaults when I try the `--save_resume` option.

Minimal way to reproduce this:

    echo '-1 | a b c d' | vw --loss_function logistic --final_regressor mymodel --ftrl --save_resume

I'm guessing that the way the model is finalized doesn't allow for `--save_resume` due to sparsifying the logistic weights (w/ L1 regularization).

Since the sparsified FTRL model does not contain all information that is available at training time (i.e. weights below the L1 threshold), the `--save_resume` option would be very handy to have.

**Comment by JohnLangford** [comment]
This is a 'patches welcome' kind of problem.  --save_resume just isn't
properly supported for --ftrl right now.

-John

**Comment by JohnLangford** [comment]
Closing this for now, although it's certainly a nice-to-have.
