### ISSUE TITLE
Proposal: change redfine operator to '='

### ISSUE THREAD

**Issue by arielf** [JohnLangford/vowpal_wabbit#767]
@trufanov-nok 

Currently the `--redefine` operator is `:=`

This is very confusing because `:` matches any name-space and unspecified-name-space means the default name-space, so we get things like `:=:`, `::=`, `::=:` that are hard to mentally parse.

Why not simply use `=` as the redefine operator?  It is shorter-to-type, simpler-to-understand, and doesn't have the hard to visually parse issue.

**Comment by trufanov-nok** [comment]
Well, historically it supposed to be 'abcdef->n'  where `n` is a new namespace. But one can't freely use `>` in the command line, so it was changed to `:=` and then John suggested to change the order to `n:=abcdef` as `:=` looks like assignment operator. Technically we don't need this separator at all as new namespace is only one char and it's in a fixed position. So it's all about simplicity for end user.  

I was tending to use 2 characters for this separator to highlight it and make sure user won't be confused to use any part of it in the right part of expression. If we consider only one character as separator, let's say `=`, then we'll get valid expressions like `==:` or `a==` where `=` is used as both separator and namespace. Or `a=b=c` is `b,c and =` redefined as `a`.
In case of `:=` I should note that although `::=` and `::=:` are valid they have no sense as you redefine something as namespace `:` which is a wildcard and cant be accessed later as a single namesace. It could be accessed only via wildcard itself.    
In any case I can't assert that current format is better. And I don't see any silver bullet for this problem. And I suspect that I shouldn't make this decision as I barely can look at this problem from regular end user perspective. So I'm fine with any format change whatever John approves. It's easy to implement.

**Comment by JohnLangford** [comment]
= is shorter to parse.

Both = and := have a virtue in that there are other languages (C, Ocaml) 
which use this as assignment.

I do find = like C mentally confusing.  Code like 'if (a = b)' is a 
classical coding error due to mental confusion between equality and 
assignment.  This seems relevant here: What should happen when you do 
a=b c=a ?

-John
