### ISSUE TITLE
Unified source code style

### ISSUE THREAD

**Issue by martinpopel** [JohnLangford/vowpal_wabbit#769]
Currently, the source codes use a mix of 2-space, 4-space and TAB indentation even within one file.
* It is not possible to set up your editor to follow one common style.
* The mixed TAB+space indentation is especially a problem. The files look ugly (the indentation level is wrong, so understanding the code takes longer).
* There are spurious whitespace edits in git history.

I think VW should use [`.editorconfig`](http://EditorConfig.org) file and define also the preferred code style (e.g. [K&R](https://en.wikipedia.org/wiki/Indent_style#K.26R_style)). This issue should serve as a place to discuss what the defaults should be.

**Comment by arielf** [comment]
Martin,

Thanks for opening an issue on this.

`astyle` was suggested by B. Scott Michel in a earlier, [March 30th discussion](https://github.com/JohnLangford/vowpal_wabbit/pull/571), specifically [in this comment](https://github.com/JohnLangford/vowpal_wabbit/pull/571#issuecomment-87775319)

My vote for the "One True Brace Style" (aka `astyle --style=1tbs`) is in that thread. :)
In any case, it is high time we at least agree on a common, consistent style and put the agreed config in.

The only downside I see is that whoever applies this 'patch' will have a huge amount of lines accounted for him/her in `git blame`.

Any other downsides?

John, are you ok with moving this forward?

I also propose John gets to both:
  1. Pick the style
  2. Apply the big commit.

**Comment by martinpopel** [comment]
Ariel, thanks for reminding the older pull request – so obviously, I am not the only one troubled by the inconsistent style. For me the mixed TAB/2space/4space indenting is much more serious problem than the space between ) and { tackled by #571.

In #770, I used `astyle --lineend=linux --indent=spaces=2 *.cc *.h`, i.e. without any `--style` option, so the commit has not changed attached/broken brackets and thus the total number of lines, but (as a side effect from my point of view) it added also the space between ) and {.

> Any other downsides?

Currently, there are several open pull requests that would conflict with #770, so either John merges them first (and applies `astyle` then himself) or their authors would need to sync with upstream and solve the conflicts, e.g. with `git merge -Xignore-all-space` or [manually](https://git-scm.com/book/tr/v2/Git-Tools-Advanced-Merging#_manual_remerge). On the other hand, there will be always some open pull requests.

I agree it should be John who picks the style and applies the big commit.

It may be better to make the big commit even bigger and include also bracketing style, e.g. with `astyle --style=1tbs`. This way `-Xignore-all-space` would not probably solve all the conflicts automatically, but there would be no need of such a big commit in future.

**Comment by martinpopel** [comment]
PR #773 was merged so as for me, we can close this issue (unless someone wants to unify the bracketing style in addition to the indentation).

**Comment by JohnLangford** [comment]
Closing for now.
