### ISSUE TITLE
Eliminate platform dependencies through 3rd party portability library

### ISSUE THREAD

**Issue by marko-asplund** [JohnLangford/vowpal_wabbit#781]
Switch to using a library that provides access to platform specific features instead of implementing a custom portability layer and using pre-processor macros.

Apache APR could be one option:
https://apr.apache.org/
https://en.wikipedia.org/wiki/Apache_Portable_Runtime

**Comment by JohnLangford** [comment]
This seems like a tough judgement call.  I feel like the management cost 
of supporting multiple OSs via our macros is not too great compared to 
the cost of yet-another-dependency.  On the other hand if I was already 
using this library I might want to just keep it and not implement our 
macros.

So to a significant extent the question is: Does someone wants to go 
through the arduous process of switching over?  Thoroughly testing 
multiplatform compatibility is tricky.

-John

**Comment by marko-asplund** [comment]
Disclaimer: I'm not a VW developer and not familiar with how much of an issue cross-platform support has been in the past. So, this is a suggestion coming purely from a user perspective.

One conceivable benefit from utilising a widely used library for abstracting platform specifics is that designing, implementing and testing system-level code is very tricky. Routines that APR and other similar libraries provide (such as network, threading, mutexes etc.) could potentially be useful in VW.

But obviously switching would be a lot of work, and there would likely also be unexpected downsides and quality issues until things stabilise. So, I can appreciate what you said about this being a tough judgement call.

**Comment by JohnLangford** [comment]
Closing this for now.
