### ISSUE TITLE
Build errors in Mac OSX

### ISSUE THREAD

**Issue by simonhughes22** [JohnLangford/vowpal_wabbit#783]
I have all the dependencies installed, but when I do a make in OSX from source, I get:

In file included from ./vw_allreduce.h:10:
./allreduce.h:97:2: error: reference to 'mutex' is ambiguous
        mutex* m_mutex;
        ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__mutex_base:25:24: note: candidate found by name lookup is
      'std::__1::mutex'
class _LIBCPP_TYPE_VIS mutex
                       ^
./allreduce.h:91:8: note: candidate found by name lookup is 'std::mutex'
        class mutex;
              ^
./allreduce.h:98:2: error: reference to 'condition_variable' is ambiguous
        condition_variable* m_cv;
        ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__mutex_base:265:24: note: candidate found by name lookup is
      'std::__1::condition_variable'
class _LIBCPP_TYPE_VIS condition_variable
                       ^
./allreduce.h:89:8: note: candidate found by name lookup is 'std::condition_variable'
        class condition_variable;
              ^
In file included from accumulate.cc:16:
In file included from ./vw_allreduce.h:10:
./allreduce.h:97:2: error: reference to 'mutex' is ambiguous
        mutex* m_mutex;
        ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__mutex_base:25:24: note: candidate found by name lookup is
      'std::__1::mutex'
class _LIBCPP_TYPE_VIS mutex
                       ^
./allreduce.h:91:8: note: candidate found by name lookup is 'std::mutex'
        class mutex;
              ^
./allreduce.h:98:2: error: reference to 'condition_variable' is ambiguous
        condition_variable* m_cv;
        ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__mutex_base:265:24: note: candidate found by name lookup is
      'std::__1::condition_variable'
class _LIBCPP_TYPE_VIS condition_variable
                       ^
./allreduce.h:89:8: note: candidate found by name lookup is 'std::condition_variable'
        class condition_variable;
              ^
2 errors generated.
make[1]: *** [accumulate.o] Error 1
make[1]: *** Waiting for unfinished jobs....
2 errors generated.
make[1]: *** [parse_args.o] Error 1
make: *** [vw] Error 2

**Comment by JohnLangford** [comment]
Is this with the current master? allreduce.h was just refactored to use 
shared memory on a local machine by Markus.

-John

**Comment by simonhughes22** [comment]
Yes with current master.

Simon

**Comment by JohnLangford** [comment]
Try again please---a patch went in that may address this.

**Comment by JohnLangford** [comment]
I believe this is fixed.

**Comment by simonhughes22** [comment]
Sorry for slow reply, had to prep for a conference talk. Make succeeds, but make test fails on test 88:

RunTests: test 88: lenient-diff.tmp: line 1: fuzzy-match missing data on one of the sides. Can't compare
Binary files train-sets/ref/test_named_train.stderr and test_named_train.stderr differ
RunTests: test 88: saving lenient diff in 'test-88.lenient-diff' for later inspection
--- diff -u --minimal train-sets/ref/test_named_train.stderr test_named_train.stderr
Binary files train-sets/ref/test_named_train.stderr and test_named_train.stderr differ
RunTests: test 88: FAILED: ref(train-sets/ref/test_named_train.stderr) != stderr(test_named_train.stderr)
	cmd: ../vowpalwabbit/vw --named_labels det,noun,verb --oaa 3 -d train-sets/test_named  -k -c --passes 10 --holdout_off -f models/test_named.model
make: *** [test] Error 2
(root)~/GitHub/vowpal_wabbit> make python
cd vowpalwabbit; /Applications/Xcode.app/Contents/Developer/usr/bin/make -j 8 things
make[1]: Nothing to be done for `things'.
cd python; /Applications/Xcode.app/Contents/Developer/usr/bin/make things
/usr/bin/g++ -std=c++0x -I/Users/simon.hughes/anaconda/include/python2.7 -I/Users/simon.hughes/anaconda/include/python2.7 -I /opt/local/include -fPIC -c pylibvw.cc -o pylibvw.o
/usr/bin/g++ -shared  pylibvw.o -L /opt/local/lib -lpython2.7 -ldl -framework CoreFoundation -u _PyMac_Error ../vowpalwabbit/libvw.a -L /opt/local/lib -lboost_program_options-mt -lboost_serialization-mt -l pthread -l z -l boost_python -o pylibvw.so
Undefined symbols for architecture x86_64:
  "AllReduceSync::waitForSynchronization()", referenced from:
      void AllReduceThreads::all_reduce<float, &(add_float(float&, float const&))>(float*, unsigned long) in libvw.a(accumulate.o)
      void AllReduceThreads::all_reduce<unsigned long, &(add_size_t(unsigned long&, unsigned long const&))>(unsigned long*, unsigned long) in libvw.a(kernel_svm.o)
      void AllReduceThreads::all_reduce<char, &(copy_char(char&, char const&))>(char*, unsigned long) in libvw.a(kernel_svm.o)
      void AllReduceThreads::all_reduce<unsigned char, &(reduce_min_max(unsigned char&, unsigned char const&))>(unsigned char*, unsigned long) in libvw.a(stagewise_poly.o)
  "AllReduceSockets::all_reduce_init()", referenced from:
      void AllReduceSockets::all_reduce<float, &(add_float(float&, float const&))>(float*, unsigned long) in libvw.a(accumulate.o)
      void AllReduceSockets::all_reduce<unsigned long, &(add_size_t(unsigned long&, unsigned long const&))>(unsigned long*, unsigned long) in libvw.a(kernel_svm.o)
      void AllReduceSockets::all_reduce<char, &(copy_char(char&, char const&))>(char*, unsigned long) in libvw.a(kernel_svm.o)
      void AllReduceSockets::all_reduce<unsigned char, &(reduce_min_max(unsigned char&, unsigned char const&))>(unsigned char*, unsigned long) in libvw.a(stagewise_poly.o)
  "AllReduceSockets::broadcast(char*, unsigned long)", referenced from:
      void AllReduceSockets::all_reduce<float, &(add_float(float&, float const&))>(float*, unsigned long) in libvw.a(accumulate.o)
      void AllReduceSockets::all_reduce<unsigned long, &(add_size_t(unsigned long&, unsigned long const&))>(unsigned long*, unsigned long) in libvw.a(kernel_svm.o)
      void AllReduceSockets::all_reduce<char, &(copy_char(char&, char const&))>(char*, unsigned long) in libvw.a(kernel_svm.o)
      void AllReduceSockets::all_reduce<unsigned char, &(reduce_min_max(unsigned char&, unsigned char const&))>(unsigned char*, unsigned long) in libvw.a(stagewise_poly.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [pylibvw.so] Error 1
make: *** [python] Error 2

Also make python fails as you can see above. That's with latest from GH. I am running OSX 10.10.5 - Yosemite (latest -1 release on the OS version).

**Comment by soloz** [comment]
Hello,
Has anyone solved problem? I'm experiencing same.
Thanks,
