### ISSUE TITLE
can't build vw cluster

### ISSUE THREAD

**Issue by trufanov-nok** [JohnLangford/vowpal_wabbit#784]
Hi,
It seams that now I can't build current master branch from scratch with just make (without calling ./autogen.sh and libtool deps) due to problems with cluster step.  
The log is here http://pastebin.com/0YGe3GfF  
Some bits of it:
```
...
/usr/bin/g++ -std=c++0x   -D__extern_always_inline=inline -Wall -pedantic -O3 -fomit-frame-pointer -fno-strict-aliasing  -D_FILE_OFFSET_BITS=64 -DNDEBUG -I /usr/include  -fPIC  -o vw main.o -L. -l vw -l allreduce -L /usr/lib -L /usr/lib/x86_64-linux-gnu -l boost_program_options -l pthread -l z
make[1]: Leaving directory '/home/truf/ml/vowpal_wabbit_current/vowpalwabbit'
cd cluster; make
make[1]: Entering directory '/home/truf/ml/vowpal_wabbit_current/cluster'
/usr/bin/g++ -std=c++0x   -D__extern_always_inline=inline -Wall -pedantic -O3 -fomit-frame-pointer -fno-strict-aliasing  -D_FILE_OFFSET_BITS=64 -DNDEBUG -I /usr/include  -fPIC  -I ../vowpalwabbit -std=c++0x  -c spanning_tree_main.cc -o spanning_tree_main.o
/usr/bin/g++ -std=c++0x   -D__extern_always_inline=inline -Wall -pedantic -O3 -fomit-frame-pointer -fno-strict-aliasing  -D_FILE_OFFSET_BITS=64 -DNDEBUG -I /usr/include  -fPIC  -I ../vowpalwabbit -std=c++0x  -c ../vowpalwabbit/spanning_tree.cc -o ../vowpalwabbit/spanning_tree.o
/usr/bin/g++ -std=c++0x   -D__extern_always_inline=inline -Wall -pedantic -O3 -fomit-frame-pointer -fno-strict-aliasing  -D_FILE_OFFSET_BITS=64 -DNDEBUG -I /usr/include  -fPIC  -I ../vowpalwabbit -std=c++0x  -o spanning_tree spanning_tree_main.o ../vowpalwabbit/spanning_tree.o ../vowpalwabbit/vw_exception.o 
../vowpalwabbit/spanning_tree.o: In function `VW::SpanningTree::Start()':
spanning_tree.cc:(.text+0x1af1): undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
Makefile:26: recipe for target 'spanning_tree' failed
make[1]: *** [spanning_tree] Error 1
make[1]: Leaving directory '/home/truf/ml/vowpal_wabbit_current/cluster'
Makefile:90: recipe for target 'spanning_tree' failed
make: *** [spanning_tree] Error 2

```
Moreover running ./autogen.sh enforces clang usage as was described in this problem: https://github.com/JohnLangford/vowpal_wabbit/issues/678
Build log after autogen usage: http://pastebin.com/SbZnGNu8
I would stick with gcc by default and no libtool. It was so convenient to use just 'make/make test' before. Could this be adjusted?

**Comment by trufanov-nok** [comment]
And I'm observing a failed test now:
```
RunTests: test 63: ksvm_train.poly.predict OK
RunTests: test 64: FAILED: ref(train-sets/ref/ksvm_train.rbf.stderr) != stderr(ksvm_train.rbf.stderr)
        cmd: /usr/bin/timeout 30 ../vowpalwabbit/vw --ksvm --l2 1 --reprocess 5 -b 18 --kernel rbf -p ksvm_train.rbf.predict -d train-sets/rcv1_smaller.dat
RunTests: test 64: FAILED: ref(train-sets/ref/ksvm_train.rbf.predict) != (ksvm_train.rbf.predict)
        cmd: /usr/bin/timeout 30 ../vowpalwabbit/vw --ksvm --l2 1 --reprocess 5 -b 18 --kernel rbf -p ksvm_train.rbf.predict -d train-sets/rcv1_smaller.dat
RunTests: test 65: stderr OK
```

```
$ diff ksvm_train.rbf.stderr train-sets/ref/ksvm_train.rbf.stderr
28c28
< average loss = 0.888046
---
> average loss = 0.888309
33,34c33,34
< Number of kernel evaluations = 194681 Number of cache queries = 170561
< Total loss = 222.011505
---
> Number of kernel evaluations = 192975 Number of cache queries = 172366
> Total loss = 222.077240
```

**Comment by arielf** [comment]
It needs to link with `-lpthread`.
The original `Makefile` has it:

    `LIBS = -l boost_program_options -l pthread -l z`

Looks like this got lost in the `autogen.sh` process.

**Comment by arielf** [comment]
I just pulled latest from John and I don't get this svm test (# 64) failure.
All tests pass for me with the original `Makefile` build.

**Comment by arielf** [comment]
For reference here is my log (everything builds and no test errors)

  &nbsp;&nbsp;&nbsp;&nbsp; [**http://pastebin.com/twL8qJDu**](http://pastebin.com/twL8qJDu)

**Comment by trufanov-nok** [comment]
well, I've tried to reproduce test problem without clang usage. To do that I've commented line 3 in autogen.sh and rebuild vw. So now I'm using libtool+gcc. The interesting fact that test 64 is fine now. But test 17 failed:
```
RunTests: test 16: stderr OK
RunTests: test 17: FAILED: ref(train-sets/ref/wiki1K.stderr) != stderr(wiki1K.stderr)
        cmd: /usr/bin/timeout 30 ../vowpalwabbit/vw -k --lda 100 --lda_alpha 0.01 --lda_rho 0.01 --lda_D 1000 -l 1 -b 13 --minibatch 128 train-sets/wiki256.dat
RunTests: test 18: stderr OK
```
```
$ diff train-sets/ref/wiki1K.stderr wiki1K.stderr
10,18c10,18
< 10.149310 10.149310            1            1.0  unknown   0.0000      732
< 10.369817 10.590324            2            2.0  unknown   0.0000       27
< 10.325926 10.282035            4            4.0  unknown   0.0000       53
< 10.401768 10.477609            8            8.0  unknown   0.0000       60
< 10.356288 10.310808           16           16.0  unknown   0.0000       26
< 10.472953 10.589619           32           32.0  unknown   0.0000      125
< 10.474859 10.476765           64           64.0  unknown   0.0000      313
< 10.425314 10.375768          128          128.0  unknown   0.0000       50
< 10.005560 9.585807          256          256.0  unknown   0.0000       33
---
> 10.149308 10.149308            1            1.0  unknown   0.0000      732
> 10.369818 10.590328            2            2.0  unknown   0.0000       27
> 10.325930 10.282041            4            4.0  unknown   0.0000       53
> 10.401770 10.477611            8            8.0  unknown   0.0000       60
> 10.356289 10.310807           16           16.0  unknown   0.0000       26
> 10.472942 10.589595           32           32.0  unknown   0.0000      125
> 10.474847 10.476753           64           64.0  unknown   0.0000      313
> 10.425305 10.375763          128          128.0  unknown   0.0000       50
> 9.438502 8.451700          256          256.0  unknown   0.0000       33
24c24
< average loss = 10.005560
---
> average loss = 9.438502
```
I'll check with just gcc now.

**Comment by trufanov-nok** [comment]
Ok, I've made another clone of master then build it with just make (no autogen, so libtool isn't used). Got compilation problem for cluster\ - ignored it as main app was built fine. Then run tests and all tests are passed ok. So I have 4 problems now:  

1. VW's cluster subfolder can't be build with default Makefile and requires launch of autogen.sh
2. Launch of autoget.sh enforces clang usage if it's found in system as described in #678 (i'm bypassing it by commenting out one line is autogen.sh)
3. VW built with libtool+clang fails test 64
4. VW built with just libtool fails test 17

P.s. My setup is:
```
$ clang -v
Ubuntu clang version 3.6.0-2ubuntu1 (tags/RELEASE_360/final) (based on LLVM 3.6.0)
Target: x86_64-pc-linux-gnu

gcc version 4.9.2 (Ubuntu 4.9.2-10ubuntu13) 

      libtoolize:       (GNU libtool) 2.4.2 Debian-2.4.2-1.11
      automake:         automake (GNU automake) 1.14.1
      autoconf:         autoconf (GNU Autoconf) 2.69

```

**Comment by arielf** [comment]
Very interesting.  Build has no issues, and all tests pass for me with clang as well:

    make CXX='clang++ -static' clean all test

Maybe it is the -static?

My `clang++` on Ubuntu 14.04.3 is older too:

    $ clang++ --version
    Ubuntu clang version 3.4-1ubuntu3 (tags/RELEASE_34/final) (based on LLVM 3.4)
    Target: x86_64-pc-linux-gnu
    Thread model: posix

    $ clang -v
    Ubuntu clang version 3.4-1ubuntu3 (tags/RELEASE_34/final) (based on LLVM 3.4)
    Target: x86_64-pc-linux-gnu
    Thread model: posix
    Found candidate GCC installation: /usr/bin/../lib/gcc/i686-linux-gnu/4.8
    Found candidate GCC installation: /usr/bin/../lib/gcc/i686-linux-gnu/4.8.4
    Found candidate GCC installation: /usr/bin/../lib/gcc/i686-linux-gnu/4.9
    Found candidate GCC installation: /usr/bin/../lib/gcc/i686-linux-gnu/4.9.1
    Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/4.7
    Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/4.7.3
    Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8
    Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8.4
    Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9
    Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9.1
    Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.8
    Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.8.4
    Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.9
    Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/4.9.1
    Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7
    Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7.3
    Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
    Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8.4
    Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
    Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9.1
    Selected GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8

    $ gcc -v
    Using built-in specs.
    COLLECT_GCC=gcc
    COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.8/lto-wrapper
    Target: x86_64-linux-gnu
    Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.8.4-2ubuntu1~14.04' --with-bugurl=file:///usr/share/doc/gcc-4.8/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.8 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.8 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libmudflap --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.8-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
    Thread model: posix
    gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04)

**Comment by trufanov-nok** [comment]
I've tried it with `make CXX='clang++ -static'`, `make CXX='clang++ '` and `make CXX='clang' - all passed the tests. Then run ./autogen.sh and got test 64 failed. Guess... the problem in libtool then.

**Comment by arielf** [comment]
Cool.  Thanks for confirming. I think this is libtool's 2nd strike. I'm keeping count ;)

**Comment by trufanov-nok** [comment]
Let's then focus on problem 1.
> VW's cluster subfolder can't be build with default Makefile and requires launch of autogen.sh
It's the the only thing really bothering me. I can't build vw with single `make` bcs libs are not inherited in cluster\Makefile somehow. I don't know make build chain so well to debug.

**Comment by arielf** [comment]
The problem is I don't have problem #1 at all ...

I never use `autogen.sh`.  It is never needed on Ubuntu.

When I build in `cluster`:  `(cd cluster && make)` it works (builds `spanning_tree`) without issues regardless of whether I use clang or gcc.

Could it be `autogen.sh` overwrote (and destroyed) your original `Makefile`(s)?

I think we need to fix `autogen.sh`, not the bad Makefiles it creates.

**Comment by trufanov-nok** [comment]
For problem 1 autogen is a solution (that causes other 3 problems). I'm cloning current master and can't build it by just running `make`

**Comment by trufanov-nok** [comment]
I'm not fully understand how Makefile's recipes work but I've fixed this problem by adding `$(LIBS)` to the end of this [line](https://github.com/JohnLangford/vowpal_wabbit/blob/master/cluster/Makefile#L26).   
Could you check if it breaks something for you or adds duplicate libraries while spanning_tree_main.o compilation in your logs.

**Comment by arielf** [comment]
Thanks Alex.

I added $(LIBS) after $+ in the spanning_tree build line
This macro def, expanded during `make all`  to:
```
     -l boost_program_options -l pthread -l z
```
which are not needed to resolve anything in `spanning_tree` in my case, but are harmless when added.

So it built without problem.

Feel free to leave these in for those who may have `autogen.sh/automake` mess-ups.

**Comment by trufanov-nok** [comment]
Ok, i'll make a PR tomorrow.
