### ISSUE TITLE
In pyvw how do I predict an LDA example without learning it?

### ISSUE THREAD

**Issue by jmizgajski** [JohnLangford/vowpal_wabbit#803]
vw uses an online LDA algorithm. By this virtue learning an example changes the model. In many cases this is undesired at prediction time (learning the same document multiple times can skew the model considerably).

When using pyvw how do I predict the topic distribution without learning the predicted example?

Consider this code as a template:

```
import pyvw
from itertools import imap
import array
import numpy as np


class VwLda(object):

    @classmethod
    def make_line(cls, bow):
        if issubclass(type(bow), dict):
            return "|" + " ".join(imap(lambda (w, c): "%s:%s" % (w, c), bow.iteritems()))
        if issubclass(type(bow), list) or issubclass(type(bow), array) or issubclass(type(bow), set):
            return "|" + " ".join(imap(lambda w: "%s:1" % w, bow))

    def __init__(self, k):
        self.vw = pyvw.vw(lda=k)
        self.k = k

    def learn(self, docs):
        for d in docs:
            ex = self.vw.example(self.make_line(d))
            ex.learn()
            ex.finish()

    def predict(self, doc):
        ex = self.vw.example(self.make_line(doc))

        #FIXME: !!! I don't know how to predict an example without actualy learning it
        ex.learn()
        topic_probabilities = np.array([ex.get_topic_prediction(i) for i in xrange(self.k)])
        return topic_probabilities / sum(topic_probabilities)

```
If I simply remove ex.learn() the notebook kernel crashes. I couldn't find any method inside the pyvw source that would be equivalent to ex.learn() but have no influence on the model.

**Comment by JohnLangford** [comment]
Apparently, you set ec->test_only:

|https://github.com/JohnLangford/vowpal_wabbit/blob/master/python/pylibvw.cc#L107
https://github.com/JohnLangford/vowpal_wabbit/blob/master/python/pylibvw.cc#L488

Hal, it might be better to have a predict() function since that is: (a) 
less modal and (b) more directly guaranteed to do the right thing.
|
-John

**Comment by jmizgajski** [comment]
Thanks!

I'm not 100% sure how what is the right way to ensure that test_only is set from the python interface though.

**Comment by JohnLangford** [comment]
Use the second function I pointed out.

-John

**Comment by jmizgajski** [comment]
Pardon my indolence but it does not seem to have any effect - please refer to the code example in my above post which uses exactly the function you refer to.

**Comment by jmizgajski** [comment]
Hi John,

Did you manage to figure out why the solution you proposed has no effect? Should I provide a synthetic test case to better illustrate the problem?

**Comment by JohnLangford** [comment]
Which VW are you using?

-John

**Comment by jmizgajski** [comment]
1af89d8df136c3fd9992de5bdc0e2797f984d67d

master from a few days ago.

**Comment by jmizgajski** [comment]
@JohnLangford Did you manage to identify the issue? Would you like me to provide a test case illustrating this behaviour?

**Comment by arielf** [comment]
@jmizgajski  yes please.  John is usually very busy.  Plus he wasn't the one who wrote the python interface in the 1st place.  Providing a (preferably minimal) reproducible example increases the chance that someone would look at it.   Having the python interface covered in the test suite (test/RunTests), so it doesn't regress in the future, would be even cooler.  Thanks again.

**Comment by jmizgajski** [comment]
@JohnLangford @arielf There you go:

```
import pyvw
from itertools import imap
import array
import numpy as np


class VwLda(object):

    @classmethod
    def make_line(cls, bow):
        if issubclass(type(bow), dict):
            return "|" + " ".join(imap(lambda (w, c): "%s:%s" % (w, c), bow.iteritems()))
        if issubclass(type(bow), list) or issubclass(type(bow), array) or issubclass(type(bow), set):
            return "|" + " ".join(imap(lambda w: "%s:1" % w, bow))

    def __init__(self, k):
        self.vw = pyvw.vw(lda=k)
        self.k = k

    def learn(self, docs):
        for d in docs:
            ex = self.vw.example(self.make_line(d))
            ex.learn()
            ex.finish()

    def predict(self, doc):
        ex = self.vw.example(self.make_line(doc))

        #FIXME: !!! I don't know how to predict an example without actualy learning it
        # ex.learn()
        ex.set_test_only(True)
        ex.learn()
        topic_probabilities = np.array([ex.get_topic_prediction(i) for i in xrange(self.k)])
        ex.finish()
        return topic_probabilities / sum(topic_probabilities)

    
lda = VwLda(10)
docs = [
    {'cow': 1, 'dog': 1, 'church': 1},
    {'cow': 1, 'dog': 1, 'church': 1},
    {'cow': 1, 'dog': 1, 'pig': 1},
    {'cow': 1, 'dog': 1, 'pig': 1},
    {'cow': 1, 'dog': 1, 'pig': 1},
    {'priest': 1, 'hog': 1, 'church': 1},
    {'copper': 1, 'hog': 1, 'church': 1},
    {'cow': 1, 'hog': 1, 'church': 1},
    {'rumburak': 100, 'hog': 100, 'pig': 100},
]
lda.learn(docs)
doc = docs[-1]
a = lda.predict(doc)
b = lda.predict(doc)
print a
print b
eps = 10 ** -7
assert all(abs((a - b)) < eps )

```

**Comment by JohnLangford** [comment]
Oooh, that's interesting. I had never thought that "having no label" 
would be insufficient for identifying test (that's the general VW 
semantics).

I just pushed a change to my repo. Can you try it?

**Comment by JohnLangford** [comment]
What's the status here?  Fixed?  Reopen if not please.
