### ISSUE TITLE
.travis.yml allows broken java code to pass

### ISSUE THREAD

**Issue by deaktator** [JohnLangford/vowpal_wabbit#804]
Currently, the `.travis.yml` file has the following bug: 

```bash
cd java; mvn test; cd ..
```

This allows the build to pass even when there is a maven failure because the exit code of `cd ..` is always **0** even when the exit code for `mV test` is **non-zero**.  To correct, change the line to:

```bash
cd java && mvn test && cd ..
```

**Comment by arielf** [comment]
This fix looks good. Thanks.

Note that the reason why this is broken is not that "the exit code of cd is always 0" but the fact that the non-zero exit code is being ignored by the cd caller (use of `;` instead of `&&`).

```
# show that cd returns a good code:
$ cd .
$ echo $?
0

$ cd no-such-dir
bash: cd: no-such-dir: No such file or directory
$ echo $?
1
```

**Comment by deaktator** [comment]
Agreed Ariel. I was simplifying.  I almost included an example.  I was just saying

```
cd java && cd ..
echo $?        # = 0
```

So question remains: merge and have the build break?

**Comment by arielf** [comment]
Yes, this is a valid concern.

We need to make sure the build works before we include this (good) fix.

Generally, we try to make sure that pull-requests don't break the build+test
