### ISSUE TITLE
Allow creation of multiple VW instances with Java

### ISSUE THREAD

**Issue by marko-asplund** [JohnLangford/vowpal_wabbit#806]
VW Java interface currently only allows a single VW instance to be created.

Based on discussion on the mailing list, it seems that the interface could allow multiple VW instances to be created:
https://groups.yahoo.com/neo/groups/vowpal_wabbit/conversations/topics/5532

**Comment by marko-asplund** [comment]
here're messages related to this from a discussion that took place on the mailing list:

@JohnLangford 
> It's generally fine to have multiple VW object instances used in 
> different threads. It is _not_ fine to have multiple threads using the 
> same VW instance.
>
> The VW instances generally operate independently so memory usage is 
> additive. There is a trick though---the new CLI interface to VW has 
> modified things so that you can pass a model into an instance as you 
> initialize it, and that model will be shared (in the same sense that 
> models can be shared for daemon mode). It would take a bit of work to 
> enable this for other languages, but it should be doable. Markus (cced) 
> has the right pointers.
>
> -John


@eisber 
> Take a look here: https://github.com/JohnLangford/vowpal_wabbit/blob/master/vw_clr/vw_base.cpp#l36 or here https://github.com/JohnLangford/vowpal_wabbit/blob/8934528f4979b85e1053785a865da97c5dadfb1a/vowpalwabbit/parse_args.cc#l1237
> 
>The C# layer takes care of any synchronization or maintenance of a pool of VW objects.
> 
>Markus

**Comment by JohnLangford** [comment]
This seems like a desirable feature in the long term due to the general shift towards multicore architectures.

**Comment by JohnLangford** [comment]
@jmorra @deaktator have you considered making the java interface support multiple VWs sharing the same model?

**Comment by deaktator** [comment]
@JohnLangford for clarity, are you thinking of something like allowing thread-local copies of the model for prediction to increase prediction throughput (like below) or are you thinking about allowing the model to be mutable across threads?  I think we previously looked at multithreading the underlying models about a year ago and synchronization seemed to limit throughput.  I'll catch up with @jmorra and talk with him about this.  

```java
class ThreadedPredictor {

  private final ThreadLocal<VWFloatLearner> learner;

  public ThreadedPredictor(final String vwInitStr) {
    learner = new ThreadLocal<VWFloatLearner>() {
      @Override protected VWFloatLearner initialValue() {
        return vw.learner.VWLearners.create(vwInitStr);
      }
    };
  }

  public float predict(final String example) {
    return learner.get().predict(example);
  }
}
```

**Comment by marko-asplund** [comment]
Personally, I would be interested in the following uses:
- allow initialization and use of multiple models with different parameters within one process (primarily for prediction) or
- allow multiple copies of a model (within one process) for prediction to increase prediction throughput

**Comment by JohnLangford** [comment]
The first is should be doable now: you just have different VW objects.

The second is also doable now with the caveat that you can't easily share the state.   (And the caveat to the caveat that you _can_ share the state on linux.  See here: https://github.com/JohnLangford/vowpal_wabbit/blob/master/vowpalwabbit/memory.h#L43)

I think a patch on this is welcome but not necessarily needed.  Closing for now.
