### ISSUE TITLE
[vw-jni] more robust OS detection

### ISSUE THREAD

**Issue by petro-rudenko** [JohnLangford/vowpal_wabbit#807]
Hi, i'm using linux mint (ubuntu derivative). Cannot run vw-jni program, because ```lsb-release -r``` shows linux mint version. Maybe distinguish binary files by glibc version, they was compiled, or use /etc/os-release where it actually points to ubuntu:
```
NAME="Ubuntu"
VERSION="14.04.3 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.3 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
```

**Comment by JohnLangford** [comment]
os-release sounds like it might be good.

-John

**Comment by marko-asplund** [comment]
This is related to PR #780.

**Comment by JohnLangford** [comment]
I believe this is fixed.
