### ISSUE TITLE
Suggestion: support of hex \x00 format in command line args for namespaces

### ISSUE THREAD

**Issue by trufanov-nok** [JohnLangford/vowpal_wabbit#808]
VW theoretically supports up to 256 different namespaces. On practice it's a bit more limited. But I'm working with about ~160 namespaces now. (I had to adjust `valid_ns_size` constant for that). And I found out that specification of non-printable characters or characters that are not present in latin charset is a bit painful.  
It seems that it can be done in current bash with `vw --redefine $'a:=\xC0'`, but I also have an app that calls VW directly, and this command line isn't preprocessed in bash in this case. It's written in Qt and encapsulates string data in unicode QString objects, sourcefiles are in UTF-8. I had to play with system codepages to workaround this problem. It may be also a problem for scripts like `vw-hypersearch`.  
My suggestion is to declare and implement in VW an escape sequence for  namespace specification in hex format for `-q`, `--cubic`, `--ngram`, `--interactions`, `--redefine` and perhaps a few more command line parameters. It will be better to have terminal\platform\language independent way to encode such namespaces.
It can be `\x00` in this case from bash it can be called as `vw --redefine a:=abc..\\xFE\\xFF`  
The helper function may be like that:
```
string lookup_for_escape_characters(const string& arg)
{ // make a copy of arg replacing \x00 sequences in it
    string res;
    int pos = 0;
    unsigned char c; char* p;
    while (pos < (int)arg.size()-3)
    {
        if (arg[pos] == '\\' && arg[pos+1] == 'x')
          {            
            c = (unsigned char) strtoul(arg.substr(pos+2,2).c_str(), & p, 16);
            res.push_back(c);
            pos += 4;
          } else
            res.push_back(arg[pos++]);
    }

    while (pos < (int)arg.size())
        res.push_back(arg[pos++]);

    return res;
}
```

and usage:
```
before:
          string arg = *arg_iter;
          size_t arg_len = arg.length();
          // let's find operator ':=' position in N:=S
          for (size_t i = 0; i < arg_len; i++)
after:
          string arg = *arg_iter;
          arg = lookup_for_escape_characters(arg); // the change
          size_t arg_len = arg.length();
          // let's find operator ':=' position in N:=S
          for (size_t i = 0; i < arg_len; i++)
```

If it's fine I'll prepare a PR with function like that for all command line parameters that accept namespaces + case for `make test` and perhaps some notes for wiki.

**Comment by JohnLangford** [comment]
My primary concern is that several of the reductions take advantage of 
the hidden namespaces to squirrel away information.  How should we avoid 
issues related to that?

-John

**Comment by trufanov-nok** [comment]
Well current proposal is not about working\not working with non-latin namespaces. It's about easiness of their specification. One can try to address non-latin namespace with current VW version too. Especially if he has Cyrillic keyboard like me. Of course there are `printable_start = ' ' ` and `printable_end = '~'` constants but they are not used in --redefine parameter and perhaps somewhere else.
As for your concern - I think ideally would be release these (`printable_start` and `printable_end`) limitations and implement a warnings mechanism that will halt VW if someone explicitly working with namespace that known to be used by reduction later. I would suggest adding one more function to base_learner class that could be called during initialization with a list of namespaces. Let's say `bool verify_ns(string ns_list) { return true; }`. The reduction could override it to check namespaces list beforehand and print warning if it's going to use them too. Or something like that.

**Comment by martinpopel** [comment]
Note that [sometimes](https://github.com/JohnLangford/vowpal_wabbit/blob/master/vowpalwabbit/example.h#L20) you want to specify the "private" namespaces, e.g.

    -q a`printf "\x83"`

So please don't halt VW when someone uses this (it is awkward enough, so the people using it probably know what they are doing).

**Comment by JohnLangford** [comment]
Nice hack.

I'd suggest going ahead with enabling this.

-John
