### ISSUE TITLE
Suggestion: confusion matrix

### ISSUE THREAD

**Issue by trufanov-nok** [JohnLangford/vowpal_wabbit#810]
It's logical to display a confusion matrix for classification tasks. But, this may be assumed as functionality that shouldn't be implemented in VW bcs some 3rd party software may be used to build these matrices. Indeed, I was using `confusionMatrix` function from `caret` package in R. It's output is quite informative. Below is sample for 3 randomly generated classes:
```
> confusionMatrix(data = data2, reference = data)
Confusion Matrix and Statistics

          Reference
Prediction      1      2      3
         1 110481 111362 111767
         2 110937 110711 111355
         3 111087 111391 110909

Overall Statistics
                                         
               Accuracy : 0.3321         
                 95% CI : (0.3312, 0.333)
    No Information Rate : 0.334          
    P-Value [Acc > NIR] : 1.0000         
                                         
                  Kappa : NA             
 Mcnemar's Test P-Value : 0.4084         

Statistics by Class:

                     Class: 1 Class: 2 Class: 3
Sensitivity            0.3323   0.3320   0.3320
Specificity            0.6657   0.6665   0.6659
Pos Pred Value         0.3312   0.3325   0.3327
Neg Pred Value         0.6668   0.6660   0.6653
Prevalence             0.3325   0.3335   0.3340
Detection Rate         0.1105   0.1107   0.1109
Detection Prevalence   0.3336   0.3330   0.3334
Balanced Accuracy      0.4990   0.4992   0.4990
```

**\<you may skip these details>**
And now I'm faced with quite exotic situation when usage of 3rd party software for confusion matrix generation is quite difficult. I'm passing examples with custom float labels to VW and change them to -1/1 class inside VW's code based on custom command line parameter. I'm also ignoring some examples those original label values are not good enough.  This allows me to have one dataset and relabel it on fly based on hyperparameter value.  
I would like to use `vw-hypersearch` to optimize this parameter but I must optimize sensitivity/specificity rate bcs parameter can make my dataset highly imbalanced and average loss or `--binary` loss will be easily tweaked to 0.0 by just tuning it that all examples will start to belong to the same class. Thus I had to insert a confusion matrix generation step in `vw-hypersearch` and change its regexp to get model sensitivity/specificity rate instead of average loss. Changing regexp is that I can do easily but reimplementing the label adjustment logic based on hyperparameter plus example ignoring logic (the reference labels for confusion matrix must be defined at runtime too) in Perl or in R is quite annoying. Especially if you change this logic in VW every day. 
**\</you may skip these details>**  
So I implemented a simple confusion matrix in VW itself.  
I've done it for only simple two class SGD and logistic loss. It was quite easy - it took only 4 counter variables (2 for each class correct predictions and 2 for each class total count) and simple specificity/sensitivity reporting near best constant calculation code.  So, I got something like
```
sensitivity 0.930270 [total:421398]
specificity 0.276087 [total:78602]
target_rate = 0.396821 # 1.0 - mean(sensitivity,specificity)
```
at the end of vw output and adjusted vw-hyersearch to minimise `target_rate`.
I believe that confusion matrix reporting is something that could be easily done even for multiclass classification problems in VW code without serious performance hit and with informative output (like the confusion matrix from R provided above. Perhaps without P-values). Reporting confusion matrices can be switched off by default and may be switched on with `--confusion_matrix` parameter.  

If such functionality is desirable I could try to implement it for GD based methods + oaa and ect somewhere in 16'Q1.

**Comment by JohnLangford** [comment]
More thorough outcome printing seems undeniably desirable.  We'd need to 
discuss the interface a bit.

For example, I tend to find expectations more comprehensible than sums, 
so representing the matrix as a box with expectations rather than sums 
seems desirable.  If possible, it would also be good to represent 
precision well by the number of digits.

Another limiting factor may come into play.  For some of the logarithmic 
time prediction stuff, having a KxK matrix in memory is not very 
desirable.  Something which is O(number examples) or less is more palatable.

-John

**Comment by JohnLangford** [comment]
Closing this for now, although I'd welcome a patch with more thorough error reporting.
