### ISSUE TITLE
Using vw as a lib not producing same results as binary

### ISSUE THREAD

**Issue by ashish01** [JohnLangford/vowpal_wabbit#811]
I want to use VW as a library in my application. What is the best way to do this?

I am initializing the lib with following flags and calculate score using learn

```
vw* model_ = VW::initialize("-t -i model.vw");
example* ex = VW::read_example(*model_, "1.0 |n hello:1 world:2 bye:3");
model_->learn(ex);
score = ex->pred.scalar;
VW::finish_example(*model_, ex);
```

I do this multiple times using different data points. The score of library and vw executable matches perfectly for first example but from second data point it diverges significantly.

**Comment by JohnLangford** [comment]
You need to use predict() instead of learn().  learn() is rabid about using
label information when it is available.

-John
