### ISSUE TITLE
Suggestion: avoid fixed buffer usage while storing options in model file

### ISSUE THREAD

**Issue by trufanov-nok** [JohnLangford/vowpal_wabbit#831]
Hi,
< Some unnecesary details>
Today I've trained my model with `--cubic :::`. Then demangled its hashes (I'm going to contribute this module in 16Q1) and got millions of records `<"namespace^feature1 * namespace^feature2 * namespace^feature3", hash, weight>`. Then I summarized absolute values of weights by namespaces and sort them. Thus I've got ~50k namespaces' interactions ordered by their importance in regressor. So I took first 100 of them and spoof `--cubic :::` with explicit calls of necessary cubic  interactions.
I trained the new model and at the test step I've faced with fact that my model file is corrupted because the `all.file_options` contained more than 512 characters (list of 100 --cubic XXX parameters) and it was truncated by buf_size const [here](https://github.com/JohnLangford/vowpal_wabbit/blob/master/vowpalwabbit/parse_regressor.cc#L320).   
</ Some unnecesary details>  

My suggestion is to avoid usage of fixed buffer while storing `file_options`. Let it allocates its own memory chunk big enough to take the whole string.

**Comment by JohnLangford** [comment]
This makes lots of sense.

-John
