### ISSUE TITLE
autogen.sh overwrites CXX environment variable

### ISSUE THREAD

**Issue by hmonteiro** [JohnLangford/vowpal_wabbit#834]
In the system I am currently using (where I don't have root privileges), there are two available versions of gcc, the default one which does not support c++11 or c++0x and a newer one that does. When compiling libraries I set CXX to point to the correct one, but in the case of vowpal wabbit, the autogen.sh script actually overwrites it to point to the default compiler, thus breaking at the point of calling ./configure.

I think the script should check whether the environment variable is set, and, if so, use it, otherwise set it as g++ like it is now.

**Comment by arielf** [comment]
Is your PATH variable set so it find the good/wanted g++ first?
If so, is there really a need to complicate things further by setting an environment variable?

**Comment by hmonteiro** [comment]
Both gcc versions are system installed ones and /usr/bin/g++ is just a link to the default (older) gcc version. If I want to use the new one I have to actually use gcc-x.y as the command.
CXX is a common environment variable to indicate your desired c++ compiler.

**Comment by arielf** [comment]
Thanks for the explanation. It makes sense.

Since this affects a very small portion of `vw` users, and since you already have a good test env for this, would you be so kind to propose a patch to `autogen.sh` that would fix this?

BTW: you can find statically-linked precompiled `vw` binaries for any Linux/IA-64 at:
 http://finance.yendor.com/ML/VW/Binaries/

Thanks again.

**Comment by JohnLangford** [comment]
It looks like this happens at the very top of autogen.sh so this should 
be easy to edit.   If you can test and find something that works well in 
your environment and plausibly works in others I'd welcome it.

-John

**Comment by hmonteiro** [comment]
@arielf Thank you for the binaries, they seem to work. I'm going to use these until I get to the point where I can compile everything on my system.
@JohnLangford I fixed that particular problem, but still stuck on other problems due to some non-standard locations of some libraries. Once I get everything to compile correctly I can submit a patch.

**Comment by trufanov-nok** [comment]
Seems to be related to https://github.com/JohnLangford/vowpal_wabbit/issues/678

**Comment by hmonteiro** [comment]
Yes, definitely related.
I haven't had much time for this, as I found I need to recompile every other dependency with the same c++ standard used here, otherwise I start getting ABI incompatibility problems when linking.

But for this specific problem, I guess adding:
`if [ -z $CXX ]; then`
in line 2
and:
`fi`
in line 5
would solve the GCC selection problem as you can then supply your own CXX environment variable defining the compiler you want.

But I guess, this script will have to be completely restructured if it is to be used with non-standard library paths, as I have had other problems using a locally compiled boost.
