### ISSUE TITLE
Memory and logic error in VW (found by running clang static analysis)

### ISSUE THREAD

**Issue by ashish01** [JohnLangford/vowpal_wabbit#839]
I ran scan-build-3.6 make to do static analysis on VW. It found some errors.

library /search_generate.cc	~IncrementalEditDistance	line:182	
~IncrementalEditDistance() { delete prev_row; delete cur_row; }
Memory allocated by 'new[]' should be deallocated by 'delete[]', not 'delete'

Total 15 errors. Rest are in the ![snapshot](http://i.imgur.com/u07hxF6.png)

**Comment by JohnLangford** [comment]
The line numbers seem to be off so I can't find the problem.   I fixed a
number of these, but I'd appreciate rerunning the test and more detail
about the individual errors.

-John

**Comment by ashish01** [comment]
I will try to setup some kind of CI for this. Its better than doing it adhoc.

**Comment by JohnLangford** [comment]
That would be great.

-John

**Comment by JohnLangford** [comment]
Ping?
