### ISSUE TITLE
early stopping when using --ftrl

### ISSUE THREAD

**Issue by zachmayer** [JohnLangford/vowpal_wabbit#840]
It seems that ftrl always uses all of the passes, regardless of whether or not `--holdout_off` is set.  It'd be nice to be able to use early stopping via the holdout in the same way I do with regular VW.

**Comment by JohnLangford** [comment]
Agreed.  The code for this is here:

https://github.com/JohnLangford/vowpal_wabbit/blob/master/vowpalwabbit/gd.cc#L146

Can you send me a pull request to make it happen in ftrl.cc?

**Comment by zachmayer** [comment]
See #843
