### ISSUE TITLE
Inconsistent handling of examples without labels

### ISSUE THREAD

**Issue by martinpopel** [JohnLangford/vowpal_wabbit#847]
In **simple regression**, an example without label is [detected](https://github.com/JohnLangford/vowpal_wabbit/blob/c116eefe6f11efdeedc45162dbf5990e46a46232/vowpalwabbit/simple_label.cc#L113-L115) and `all.sd->weighted_unlabeled_examples` is increased. It seems that `sd.example_number` is increased as well (but I don't know where). A loss of the example without label is taken to be 0, and **the average loss is decreased**.

```
$ echo -e '1 | a\n| no_label' | vw
average  since         example        example  current  current  current
loss     last          counter         weight    label  predict features
1.000000 1.000000            1            1.0   1.0000   0.0000        2
0.500000 0.000000            2            2.0  unknown   0.2534        2
```

In **multiclass (oaa)**, [there is no test](https://github.com/JohnLangford/vowpal_wabbit/blob/c116eefe6f11efdeedc45162dbf5990e46a46232/vowpalwabbit/multiclass.cc#L104-L105) that `ec.l.multi.label == (uint32_t)-1` (that is test for unknown/missing labels). Thus `all.sd->weighted_unlabeled_examples` is not increased, and loss of the example without label is taken to be 1 (more precisely `ec.l.multi.weight`), and **the average loss is increased**.

```
$ echo -e '1 | a\n| no_label' | vw --oaa 3
average  since         example        example  current  current  current
loss     last          counter         weight    label  predict features
0.000000 0.000000            1            1.0        1        1        2
0.500000 1.000000            2            2.0  unknown        1        2
```

My suggestion is that **the average loss should not be influenced** by the examples without labels.

**Comment by JohnLangford** [comment]
I agree.

-John

**Comment by JohnLangford** [comment]
Reawakening this, the updates to these parameters are centralized here: https://github.com/JohnLangford/vowpal_wabbit/blob/master/vowpalwabbit/global_data.h#L249 

Do you want to try and make things consistent?

**Comment by martinpopel** [comment]
I don't have time for this now (or in the near future), sorry.

**Comment by JohnLangford** [comment]
This is fixed in the master branch.
