### ISSUE TITLE
Build errors on Ubuntu 14.10

### ISSUE THREAD

**Issue by joeporter** [JohnLangford/vowpal_wabbit#849]
I'm trying to build a static version of VW on Ubuntu 14.10 using clang++ and libc++, and I'm getting the same errors that @simonhughes22 was seeing on OSX.  Incidentally, building and running on OSX is working fine for me, so I suspect something to do with OS/configuration detection in the build. This also worked great on Kai-Wei's branches on the same machine, but I'm testing with master now. Here's my procedure:

0. Built a libc++ version of boost 1.55.0 and installed it to its own directory (originally ~/builds/vw/include and ~/builds/vw/lib).
1. vowpal_wabbit$ CXX="clang++ -static" ./autogen.sh --prefix=~/builds/vw2 --enable-shared --enable-libc++ --with-boost=~/builds/vw --with-boost-libdir=~/builds/vw/lib
2. CXX="clang++ -static" make clean 
3. CXX="clang++ -static" make

This fails:
In file included from allreduce_sockets.cc:28:
./allreduce.h:100:3: error: reference to 'mutex' is ambiguous
  mutex* m_mutex;
  ^
/usr/include/c++/v1/__mutex_base:25:24: note: candidate found by name lookup is
      'std::__1::mutex'
class _LIBCPP_TYPE_VIS mutex
                       ^
./allreduce.h:93:7: note: candidate found by name lookup is 'std::mutex'
class mutex;
      ^
./allreduce.h:101:3: error: reference to 'condition_variable' is ambiguous
  condition_variable* m_cv;
  ^
/usr/include/c++/v1/__mutex_base:265:24: note: candidate found by name lookup is
      'std::__1::condition_variable'
class _LIBCPP_TYPE_VIS condition_variable
                       ^
./allreduce.h:91:7: note: candidate found by name lookup is
      'std::condition_variable'
class condition_variable;
      ^
1 warning and 2 errors generated.
Makefile:645: recipe for target 'allreduce_sockets.lo' failed

I'm running on Ubuntu 14.10
uname -a
Linux hostname 3.16.0-44-generic #59-Ubuntu SMP Tue Jul 7 02:07:39 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
clang++ --version
Ubuntu clang version 3.5.0-4ubuntu2 (tags/RELEASE_350/final) (based on LLVM 3.5.0)
Target: x86_64-pc-linux-gnu
Thread model: posix

Any help would be appreciated.  On an unrelated note, a full static build doesn't quite work - we have to do some manual steps at the end to get a fully static vw binary.

Thanks,
-Joe

**Comment by JohnLangford** [comment]
@eisber can you take a look?

-John

**Comment by eisber** [comment]
I fixed this on Apple using ifdefs, but apparently it wasn’t the perfect solution yet.
Can you try


#ifdef _WIN32

namespace std

{

// forward declare promise as C++/CLI doesn't allow usage in header files

template<typename T>

class promise;


class condition_variable;


class mutex;

}

#else

#include<future>

#endif


in allreduce.h? Really I just need to exclude the include on windows. I’ll have a patch for John.

Markus

From: John
Reply-To: JohnLangford/vowpal_wabbit
Date: Friday, October 30, 2015 at 17:55
To: JohnLangford/vowpal_wabbit
Cc: Markus Cozowicz
Subject: Re: [vowpal_wabbit] Build errors on Ubuntu 14.10 (#849)

@eisber can you take a look?

-John

**Comment by arielf** [comment]
If you're ok with not trying to build your own boost, the clean way to build on Ubuntu is to not use `autogen.sh` (at least until someone can fix it)

See:
- How to build on Ubuntu: https://github.com/JohnLangford/vowpal_wabbit/issues/842#issuecomment-151727441
- How to recover original Makefiles: https://github.com/JohnLangford/vowpal_wabbit/issues/842#issuecomment-151935626

**Comment by joeporter** [comment]
Sure I'll give it it a try.

**Comment by joeporter** [comment]
Here's what happened when I tried the _WIN32 flag change -- it built fine on OSX, but on Ubuntu the build gave this error:

clang++ -static -pthreads -DHAVE_CONFIG_H -I. -I../vowpalwabbit    -I/home/joseph.porter/builds/vw/include -I/include  -stdlib=libc++ -I ../vowpalwabbit -std=c++0x -std=gnu++11 -MT ../vowpalwabbit/spanning_tree.o -MD -MP -MF $depbase.Tpo -c -o ../vowpalwabbit/spanning_tree.o ../vowpalwabbit/spanning_tree.cc &&\
mv -f $depbase.Tpo $depbase.Po
clang: warning: argument unused during compilation: '-pthreads'
../vowpalwabbit/spanning_tree.cc:105:3: error: implicit instantiation of
      undefined template 'std::future<void>'
  delete m_future;
  ^
../vowpalwabbit/spanning_tree.h:40:7: note: template is declared here
class future;
      ^
../vowpalwabbit/spanning_tree.cc:111:20: error: unknown type name 'future'
  { m_future = new future<void>;
                   ^
../vowpalwabbit/spanning_tree.cc:114:13: error: no viable overloaded '='
  *m_future = std::async(std::launch::async, &SpanningTree::Run, this);
  ~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../vowpalwabbit/spanning_tree.cc:114:13: note: type 'std::future<void>' is
      incomplete
  *m_future = std::async(std::launch::async, &SpanningTree::Run, this);
  ~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../vowpalwabbit/spanning_tree.cc:123:13: error: implicit instantiation of
      undefined template 'std::future<void>'
  { m_future->get();
            ^
../vowpalwabbit/spanning_tree.h:40:7: note: template is declared here
class future;
      ^
4 errors generated.
Makefile:424: recipe for target '../vowpalwabbit/spanning_tree.o' failed
make[1]: *** [../vowpalwabbit/spanning_tree.o] Error 1
make[1]: Leaving directory '/home/joseph.porter/builds/vowpal_wabbit2/cluster'
Makefile:507: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by joeporter** [comment]
@arielf We built our own boost due to the need to use the Clang libc++ across the board.  The only issues I had with autogen/configure is that the --enable-debug option still strips the symbols from the final installed binary, and building static binaries doesn't really work, either.  We have to delete and manually re-link the final VW binary on both OSX and Linux because libtool messes with the build flags.  I haven't seen any of the problems described in issue #842.

**Comment by joeporter** [comment]
@eisber It was a similar problem in spanning_tree.h
Here are the changed lines:
#ifdef _WIN32
namespace std
{
// forward declare promise as C++/CLI doesn't allow usage in header files
template<typename T>
class future;
}
#else
#include <future>
#endif

**Comment by eisber** [comment]
I actually just did that. Waiting for the pull request to build...

Markus




On Mon, Nov 2, 2015 at 9:16 AM -0800, "Joe Porter" <notifications@github.com<mailto:notifications@github.com>> wrote:


@eisber<https://na01.safelinks.protection.outlook.com/?url=https%3a%2f%2fgithub.com%2feisber&data=01%7c01%7cmarcozo%40064d.mgd.microsoft.com%7c44d15da2bbc64f2d5fb708d2e3a95c29%7c72f988bf86f141af91ab2d7cd011db47%7c1&sdata=zk9jAGhdXqVXJfJ3miW%2f8yrgEyxuZsTxqgLhAhOspso%3d> It was a similar problem in spanning_tree.h
Here are the changed lines:
#ifdef _WIN32
namespace std
{
// forward declare promise as C++/CLI doesn't allow usage in header files
template
class future;
}
#else
#include
#endif

-

**Comment by eisber** [comment]
I issued a pull request #851 which builds locally on ubuntu and Windows, but not in Travis ☹

**Comment by arielf** [comment]
@joeporter I always build statically and with clang on Ubuntu by following the instructions in `README.md` and then deploy the binary.  I have been doing this for years and never had an issue.  I build and test once, and then run the statically-linked file in production on any Linux/Intel (even on many year old, and even on non-Ubuntu distributions, like RHEL and CentOs).

Please make sure you have boost prereqs installed first as detailed in:
  &nbsp;  https://github.com/JohnLangford/vowpal_wabbit#ubuntudebian-specific-info

Then follow the instructions here:
 &nbsp;   https://github.com/JohnLangford/vowpal_wabbit#ubuntu-advanced-build-options-clang-and-static

Following these simple instructions should greatly simplify deployment on multiple and diverse systems and save you time (no need to repeat the build and `make test` for each separate target env).

Would be cool to know what didn't work for you.

Thanks.

**Comment by joeporter** [comment]
@arielf I'll give it a try.

**Comment by joeporter** [comment]
@arielf I used this procedure and I'm getting linking errors (note that it works great without the libc++ switch):

make CXX='clang++ -static -stdlib=libc++' clean vw test

This one failed because it couldn't properly link pthreads.  Just to see what would happen, I added -pthread:

make CXX='clang++ -static -stdlib=libc++ -pthread' clean vw test

This resolved the pthreads linking problems, but can't link libboost_program_options (which I installed via apt-get ...).  The error list is very long, but they all look like this:

(.text+0x2e): undefined reference to `std::__throw_logic_error(char const*)'
/usr/lib/x86_64-linux-gnu/libboost_program_options.a(cmdline.o): In function `void std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<char const*>(char const*, char const*, std::forward_iterator_tag) [clone .isra.104]':
(.text+0x89): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned long&, unsigned long)'
/usr/lib/x86_64-linux-gnu/libboost_program_options.a(cmdline.o): In function `boost::program_options::detail::cmdline::cmdline(int, char const* const*)':
(.text+0x5c5): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned long&, unsigned long)'

So I added the path to my local build of boost 1.55.0 (using libc++):

make CXX='clang++ -static -stdlib=libc++ -pthread -L/home/joseph.porter/builds/vw/lib' clean vw test

That seems to work great. 

My original problem with the autogen approach is that libtool removes all of those extra flags from the CXX='clang++ -static ...', and runs clang++ without the flags.  That yields a dynamic binary, even if autogen or configure was run with --enable-static.

**Comment by joeporter** [comment]
@eisber I am able to build on Ubuntu and OSX with the latest VW from master.   Thanks for your help!
