### ISSUE TITLE
label parsing issue

### ISSUE THREAD

**Issue by tzukuoh** [JohnLangford/vowpal_wabbit#854]
Running 

vw [x.txt](https://github.com/JohnLangford/vowpal_wabbit/files/32438/x.txt)

produces a label parsing error. See [log.txt](https://github.com/JohnLangford/vowpal_wabbit/files/32437/log.txt)

Running an earlier version of vw e08c4e7d6ced6f88621cd39989b36d1472b54ec8 with the same input doesn't produce the error. See [log1.txt](https://github.com/JohnLangford/vowpal_wabbit/files/32436/log1.txt)

**Comment by trufanov-nok** [comment]
That's an interesting case. I believe the commit is unrelated to this problem.
Dataset contains one line with length > 85000. To read it VW needs to call `io_buf::fill()` twice in a raw. First `fill()` is fine. Then io`_buf` can't reach the end of line second time and falls into `if (i.endloaded == i.space.end_array)` condition which sets `i.space.end = i.space.begin;`. After that second `fill()` is called. The memory will be successfully resized in `v_array::resize()`, but it wrongly assumes that `size_t old_len = end-begin;` is 0 and zeroes whole memory with `memset`. Thus data of a first buffer get lost after resize. 
I shall doublecheck that.

**Comment by trufanov-nok** [comment]
Well, to fix this you can just comment out [these 2](https://github.com/JohnLangford/vowpal_wabbit/blob/master/vowpalwabbit/v_array.h#L60) lines in v_array.h
And as these changes were recently introduced by @JohnLangford (https://github.com/JohnLangford/vowpal_wabbit/commit/761ba8884a8cea0a1a1b9ab90fa29c297923e0ac) to prevent some memory leak and I'm not familiar with `bool zero_everything` usage, I'll leave this problem to one who's sure on how it must work.

**Comment by JohnLangford** [comment]
This is fixed in the current master.  The core problem was pretty tricky to
address---in essence the io_buf code was using v_array in a manner which
violated the interface.   Straightening that out took some doing.
@trufanov-nok thanks for your help isolating the problem.

-John

**Comment by JohnLangford** [comment]
Should be fixed now.

**Comment by trufanov-nok** [comment]
It seems that .net interface is a bit broken now. According to AppVeyor:
clr_io.cpp(28): error C2065: 'endloaded' : undeclared identifier [C:\vowpal_wabbit\vw_clr\vw_clr.vcxproj]
  spanning_tree_clr.cpp

**Comment by JohnLangford** [comment]
Thanks, fixed.

-John
