### ISSUE TITLE
Probem with ssize_t under Win32

### ISSUE THREAD

**Issue by trufanov-nok** [JohnLangford/vowpal_wabbit#856]
I'm getting "expression is always true" for this code in [io_buf.h](https://github.com/JohnLangford/vowpal_wabbit/blob/master/vowpalwabbit/io_buf.h#L169):
```
 ssize_t num_read = read_file(f, endloaded, space.end_array - endloaded);
    if (num_read >= 0)
```
while building on Win32. bcs of [this](https://github.com/JohnLangford/vowpal_wabbit/blob/master/vowpalwabbit/io_buf.h#L29):
```
#ifdef _WIN32
#define ssize_t size_t
```

Were there any problems with ssize_t before? I've just commented out this line and (I'm using mingw toolchain) the problem disappeared bcs following definition from _mingw.h come into play:
```
#ifndef _SSIZE_T_DEFINED
#define _SSIZE_T_DEFINED
#undef ssize_t
#ifdef _WIN64
__MINGW_EXTENSION typedef __int64 ssize_t;
#else
typedef int ssize_t;
#endif /* _WIN64 */
#endif /* _SSIZE_T_DEFINED */
```

**Comment by arielf** [comment]
Yes, good catch, broadly forcing a signed size to be unsigned in any env is a bug

**Comment by JohnLangford** [comment]
Oddly, this doesn't seem to trigger a warning in visual studio.

_read() appears to return an int in windows: 
https://msdn.microsoft.com/en-us/library/wyssk1bs.aspx

Using an int64_t instead seems like a reasonable alternative. @eisber 
concur?

-John

**Comment by eisber** [comment]
Flying over http://stackoverflow.com/questions/22265610/why-ssize-t-in-visual-studio-2010-is-defined-as-unsigned it seems there was a bug in a past version of VS.
We’re now on VS2013/2015. If possible I’d vote for the removal of the _WIN32 ifdef.
Can we change the return type of read_file(…) to int64_t (hopefully being a type encompassing all types used across platforms). I think read_file(…) already contains ifdefs anyway, so we can just cast properly there.

Markus

**Comment by JohnLangford** [comment]
Sounds good.   Can you add to your next pull request?

-John

**Comment by JohnLangford** [comment]
@eisber can you handle this?

**Comment by trufanov-nok** [comment]
It looks like this one is fixed but @eisber referred to issue 846 (already solved) in his commit and this issue wasn't closed automatically. So I do this.
