### ISSUE TITLE
Python3 compatibility?

### ISSUE THREAD

**Issue by mikkelam** [JohnLangford/vowpal_wabbit#864]
Is it possible to have python3 compatibility? Python2 is after all legacy nowadays.

I've been fiddling with the 2to3 python utility which seems to translate the .py files just fine. I however can't figure out how to get the makefile to work properly. It seems the building when using python3xx must be done differently. Can anyone help with this?

These are the errors i get when running the makefile:
```
cd python; /Applications/Xcode.app/Contents/Developer/usr/bin/make things
    /usr/bin/g++ -shared  pylibvw.o -L /usr/local/lib -L/Users/mikkel/.pyenv/versions/3.4.3/lib/python3.4/config-3.4m -lpython3.4m -ldl -framework CoreFoundation -Wl,-stack_size,1000000 -framework CoreFoundation ../vowpalwabbit/libvw.a ../vowpalwabbit/liballreduce.a -L /usr/local/lib -lboost_program_options-mt -lboost_serialization-mt -l pthread -l z -l boost_python -o pylibvw.so
    ld: -stack_size option can only be used when linking a main executable
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    make[1]: *** [pylibvw.so] Error 1
```

**Comment by mikkelam** [comment]
update: I managed to get it to work on mac os x with python 3.5. Basically i translated the code to python3 with 2to3, then i modified the makefile to use boost_python3 lib along with linking to python3.5.

Here is my fork:
https://github.com/mikkelam/vowpal_wabbit

**Comment by JohnLangford** [comment]
If you can send a pull request that is backwards compatible (many people
are stuck on old systems), that would be great.

-John
