### ISSUE TITLE
Command line argument initial_t

### ISSUE THREAD

**Issue by swapniel99** [JohnLangford/vowpal_wabbit#869]
Hi,

In the wiki, initial_t is said to have default value 0.
Is this correct? By formula it will lead to learning rate 0:

n_t = L * d^k * (t0/(t0 + w_t))^p

**Comment by trufanov-nok** [comment]
I suppose, initial_t  is 0 for default GD. And by default VW uses  --adaptive, --normalized and --invariant modes for it so the formulas shall be different. If you switch off adaptive and normalized then VW will use 1. as default values as can be seen [here](https://github.com/JohnLangford/vowpal_wabbit/blob/master/vowpalwabbit/gd.cc#L920).

**Comment by JohnLangford** [comment]
--initial_t is also used to set the default sum-of-gradients-squared for
--adaptive with a default value of 0.

echo "|" | ./programs/vowpal_wabbit/vowpalwabbit/vw --audit --initial_t 100
--quiet
0
    Constant:116060:1:0@100

-John
