### ISSUE TITLE
8.1.1: precision issue while running tests on non-amd64 64bit systems

### ISSUE THREAD

**Issue by yarikoptic** [JohnLangford/vowpal_wabbit#878]
Was about to upload the build across all debian/ubuntus for NeuroDebian but all 32bit builds failed due to tests failures.  I see that there were recently addressed relevant issue (#872) so may be it is all gone -- didn't test after release

I did upload to debian nevertheless to see how other platforms are doing -- https://buildd.debian.org/status/package.php?p=vowpal-wabbit&suite=unstable -- so not so good. Other 64bit systems (e.g. ppc64) also have tests fail similarly.

Would it be ok to may be lower testing precision on those platforms? what would be the most efficient/consistent way? or may be you spot some other intricate divergences?

**Comment by arielf** [comment]
Hi Yaroslav,

RunTest has an option `-E` to set the floating-point precision tolerance.  We use `-E 0.001` by default.

I think the cleanest way to address this, would be to make this 0.001 constant (which is hardwired in the Makefile under the target `test`) into a make variable:
```
PRECISION = 0.001
```
So for 32-bit (or whatever) you could use something like:

   make PRECISION=0.01 test

Thanks!

**Comment by yarikoptic** [comment]
gotcha -- thank you @arielf .  I will set it 0.001 only for amd64 and will relax for the other beasts. I will close this issue for now, and if any architecture shows more interesting failure, I will bring up a new issue.

Cheers!
