### ISSUE TITLE
--rank doesn't work with --ftrl

### ISSUE THREAD

**Issue by kirillfish** [JohnLangford/vowpal_wabbit#880]
If I understand that correctly, matrix factorization with `--rank` is not prohibited when `--ftrl` method is used. But on my machine vw refuses to train with this configuration. Here is the toy example (but the result is actually the same regardless of the dataset size):

-1 |O a b c |T a d
-1 |O a f |T
1 |O b d |T e d f
1 |O a c e |T a
-1 |O b |T b c
1 |O b d |T a d
1 |O a b e |T e f
-1 |O e |T a b c

```vw -d ./data/sandbox_vw -q TO --rank 2 --ftrl```

produces
```
creating quadratic features for pairs: TO
Num weight bits = 18
learning rate = 10
initial_t = 1
power_t = 0.5
vw: unrecognised option '--ftrl'
```

Without `--ftrl`, this works fine.

**Comment by JohnLangford** [comment]
There are several matrix factorization available.  --rank is a base 
learner, but --lrq is not, and hence should compose.

-John
