### ISSUE TITLE
Bugs in python boost wrapper

### ISSUE THREAD

**Issue by mdredze** [JohnLangford/vowpal_wabbit#882]
I've been working with the python wrapper (pyvw) and have found some issues. I don't know the correct fix, so I'm not creating a pull request. Instead, I'm opening an issue that documents my changes, which works for me.

1) Incorrect function call
https://github.com/JohnLangford/vowpal_wabbit/blob/master/python/pylibvw.cc#L588
This should point to `my_predict`, NOT `my_predict_string`.

2) `test_only` not being respected
 https://github.com/JohnLangford/vowpal_wabbit/blob/master/python/pylibvw.cc#L127
I am using `--oaa` and have confirmed that the `test_only` flag on the example is being ignored. The model works fine when run with the `-t` flag, but the model is being changed (subsequent predictions change) when calling `my_predict`, even though the code clearly sets `ec->test_only = true;`

The correct fix should be to modify the underlying learner to respect this flag. My fix is to replace the call to `learn` with `predict`. I now get the same results when comparing calls from python to running the tool on the command line.

**Comment by JohnLangford** [comment]
Thanks Mark.  @hal3 can you take a look?

-John

**Comment by hal3** [comment]
this looks good

**Comment by JohnLangford** [comment]
@hal3 Do you have a pull request?

-John

**Comment by JohnLangford** [comment]
@hal3 status on this?

**Comment by JohnLangford** [comment]
I think the first issue has been fixed.  The predict() vs. learn() issue is kind of tricky to deal with.  Essentially, we need code to dispatch to one or the other as is desired.  Something like this: https://github.com/JohnLangford/vowpal_wabbit/blob/master/vowpalwabbit/learner.cc#L5  

However, I'm not sure this is the interface people expect with a library.  When you call learn() do you expect the model to update?  Many people might think "yes" and be confused by it not doing so when a -t is applied on loading.  Overall, it doesn't seem clear enough for me to put the time in, but if you want to go ahead and send a pull request.
