### ISSUE TITLE
Issue with dependencie

### ISSUE THREAD

**Issue by mogthesprog** [JohnLangford/vowpal_wabbit#892]
hi guys,

It seems on centos this library also depends on the boost-devel package, not sure if you wanted to put it in your dependency list.

it can be installed with 

```
yum install -y boost-devel
```

Cheers,

Morgan

**Comment by JohnLangford** [comment]
I'm not sure who maintains the yum package manager?  Anyways, yes, it would
be good to fix the dependency.

-John

**Comment by JohnLangford** [comment]
(closing for now--not sure who to send this to)
