### ISSUE TITLE
Compile errors for Mac OS X 10.10.2

### ISSUE THREAD

**Issue by charlescearl** [JohnLangford/vowpal_wabbit#898]
I run into compile errors on macbook running OS X 10.10.2 on latest master (1ae39c7).
After running

       make

Final output is

      /usr/bin/g++ -std=c++0x   -D__extern_always_inline=inline -Wall -pedantic -O3 -fomit-frame-pointer -fno-strict-aliasing  -D_FILE_OFFSET_BITS=64 -DNDEBUG -I /usr/local/include  -fPIC  -c print.cc -o print.o
     gd_mf.cc:254:8: error: no matching function for call to 'summarize_holdout_set'
     { if(summarize_holdout_set(*all, d.no_win_counter))
       ^~~~~~~~~~~~~~~~~~~~~
     ./simple_label.h:22:6: note: candidate function not viable: no known conversion from 'uint64_t' (aka 'unsigned long long') to 'size_t &' (aka 'unsigned long &') for 2nd argument
      bool summarize_holdout_set(vw& all, size_t& no_win_counter);
     ^
     1 error generated.
     make[1]: *** [gd_mf.o] Error 1

Suggestions?

**Comment by cswhjiang** [comment]
I had the same error.

**Comment by JohnLangford** [comment]
This should be fixed now.

-John

**Comment by JohnLangford** [comment]
(assuming fixed and closing)
