### ISSUE TITLE
Segmentation fault with LDA and single word documents when outputting predictions

### ISSUE THREAD

**Issue by wbt** [JohnLangford/vowpal_wabbit#903]
When including a document which is a single word in input data, using `--lda 30` and including the `-p` option to specify a place to save the predictions (as well as `-d` to specify an input file, but no other options), VW produces a segmentation fault.  The fault appears to occur when reading in documents: the table (average loss / since last / example counter / example weight / current label / current predict / current features) proceeds as normal until the example counter is large enough to cover the single-word document.  Without the `-p` option, the error doesn't happen. 

I've attached an [example VW file with some of today's news headlines](https://github.com/JohnLangford/vowpal_wabbit/files/79365/news.txt) and a one-word example "earthquake." The output is below, with markdown added for easier reading. 

average loss         | since  last       |     example counter       |    example weight  | current label  | current predict   | current features
---------- | ---------- | --------------- | ------------- | ---------- | ------------- | ---------
14.240377 | 14.240377   |         1  |          1.0|  unknown  | 0.0000     |   8
14.674990 |15.109602   |         2    |        2.0 | unknown|   0.0000     |   9
Segmentation fault (core dumped) |

I first observed this in a much larger set with a five-figure count of short documents, but boiled it down for the sake of illustrating the bug.  It doesn't seem to matter what the single word is or what the other documents say.

The expected result is something more graceful than a segmentation fault / core dump.  As to any question regarding why one might have a single-word document, consider that input files might be dynamically generated from some set that wasn't authored for just this use.

**Comment by JohnLangford** [comment]
This is fixed in the current master now.  Also, it wasn't a one-word document but rather a 0-word document.  You need to put a space ' ' between the '|' and the first feature or VW interpret this as part of a namespace.
