### ISSUE TITLE
test 30 failed

### ISSUE THREAD

**Issue by trufanov-nok** [JohnLangford/vowpal_wabbit#908]
I've downloaded up-to-date sources and tried to make test it. The following problem was found:
```
RunTests: test 27: bs.vote.predict OK
RunTests: test 28: stderr OK
RunTests: test 28: bs.prvote.predict OK
RunTests: test 29: stderr OK
*** Error in `../vowpalwabbit/vw': double free or corruption (out): 0x00007fa2c40009b0 ***
Aborted
RunTests: test 30: '/usr/bin/timeout 30 ../vowpalwabbit/vw -d train-sets/0001.dat -f models/mask.model --invert_hash mask.predict --l1 0.01' failed (exitcode=134)
using l1 regularization = 0.01
final_regressor = models/mask.model
Num weight bits = 18
learning rate = 0.5
initial_t = 0
power_t = 0.5
using no cache
Reading datafile = train-sets/0001.dat
num sources = 1
average  since         example        example  current  current  current
loss     last          counter         weight    label  predict features
1.000000 1.000000            1            1.0   1.0000   0.0000       51
/usr/bin/timeout: the monitored command dumped core
RunTests: exiting with status=134
Makefile:125: recipe for target 'test' failed
make: *** [test] Error 134
```
while Travic-CI reports that all tests are fine.

My configuration is: Linux 4.2.0-23-generic, gcc version 5.2.1 20151010 (Ubuntu 5.2.1-22ubuntu2)
Will try to debug.

**Comment by trufanov-nok** [comment]
valgrind results: http://pastebin.com/631WNQhM
it barks on accessing values (string::operator==()) of audit_strings elements in audit_interaction() and then on destruction of audit_strings in features::free_space_names()

**Comment by trufanov-nok** [comment]
Well, it seems my std::string implementation has local buffer for very short strings 

```      void   _M_dispose()
      {
	if (!_M_is_local())
	  _M_destroy(_M_allocated_capacity);
      }```
```     bool
      _M_is_local() const
      { return _M_data() == _M_local_data(); } 
```
`enum { _S_local_capacity = 15 / sizeof(_CharT) };`

`_CharT           _M_local_buf[_S_local_capacity + 1];`
And it's often used in our case.

In this case the pair<string,string> stored in v_array contains both pointers to string and string data. This is how `pair<string("features"), string("24")>` looks like in v_array: http://i75.fastpic.ru/big/2016/0114/7a/fdc9b68d391b678f818b3bc2ad04727a.png

And if resize() moves v_array memory the pair's members still point to local string buffers in old v_array chunk. And it would crash if this old chunk was filled by zeros but it's only marked as free'd. Still this cause exception when pair destructor is called.

Looks like that. Will think on a fix this evening.

**Comment by trufanov-nok** [comment]
>  it seems my std::string implementation has local buffer for very short strings 
It has a name: [SSO](http://stackoverflow.com/questions/10315041/meaning-of-acronym-sso-in-the-context-of-stdstring).

**Comment by JohnLangford** [comment]
I can't reproduce locally.  Can you fix?

-John

**Comment by trufanov-nok** [comment]
As there is no simple way to [disable](http://stackoverflow.com/questions/34788789/disable-stdstrings-sso?noredirect=1#comment57321148_34788789) SSO in string (proposed solution won't be easy shot as v_array stores copy constructed objects and reserve() workaround seems to need to be applied to them again) we have no options except avoiding storing string objects in v_array.  
 I would suggest either using some string alternative (char*+len or v_array\<char\>) or storing audit_stings in v_array as std::shared_pointer\<audit_strings\>. I don't know what is better from performance and code style perspective. I'll submit a fix based on shared_pointer's.  Let me know if another fix is preferable.
