### ISSUE TITLE
Are FTRL tests correct?

### ISSUE THREAD

**Issue by trufanov-nok** [JohnLangford/vowpal_wabbit#910]
Hi,
I know nothing about FRTL or Pistol. Just noticed that both doesn't save their params in model file via `all.file_options`. And if you check corresponding tests in RunTest (73,82,106,108) there are no ftrl-related command line parameters specified on a test step. For example:
```
# Test 73: test FTRL-Proximal
{VW} -k -t -d train-sets/0001.dat -i models/0001_ftrl.model -p 0001_ftrl.predict
```
So it relies on model and as was mentioned there are no ftrl params in model file. So `ftrl_setup` returns asap doing nothing while testing ftrl. Thus its regressor is tested with default SGD.

Perhaps FTRL/PiSTOL do work as SGD on a test step? But FTRL has own implementation of predict() function which is never called on test step. It's suspicious. Could someone who knows how it should work confirm that tests run correctly?

**Comment by JohnLangford** [comment]
FTRL stores parameters in the same representation as GD so w.r.t. testing
precisely the same code works as in gd.cc.  This is by design.

-John
