### ISSUE TITLE
The "--quiet" option does not work properly with "--named_labels" options

### ISSUE THREAD

**Issue by usptact** [JohnLangford/vowpal_wabbit#911]
I am building a multi-class classifier where the data is labeled using strings. VW can use string labels as long as the "--named_labels" option is used with an exhaustive list of possible labels.

The training is performed like this:
```
shuf train.vw | vw --passes 10 -c -k -f model.vw -b 28 --named_labels A,B,C,D --oaa 4 --l2 1e-10 --l1 1e-10 -l 1.0 --loss_function squared
```

During prediction time, I am willing to print out only the raw predictions, no diagnostic information. For this, I believe, the "--quiet" option is for.

The prediction on some test data is done with this call:

```
vw -t -d test.vw -i model.vw -r /dev/stdout --quiet
```

The problem is that I still get some diagnostic information about named labels being parsed. The output for a single data point is:

```
parsed 4 named labels
1:-1 2:-1 3:-1 4:1
in namedlabels delete
```

I don't wish to see in output the first and last lines. Is this possible with the current options?

I am using VW 8.1.1

**Comment by JohnLangford** [comment]
This should be fixed in the current master now.

-John

**Comment by JohnLangford** [comment]
(Thanks)
