### ISSUE TITLE
Old C# example in wiki

### ISSUE THREAD

**Issue by d-khokhlov** [JohnLangford/vowpal_wabbit#913]
Consider Wiki page "C# Binding", section "Generic data structures", C# example. As far as I understand for the latest version of  Vowpal Wabbit NuGet package (8.0.0.29):
  1. ```exampleBuilder.Label = "1";``` should be changed to ```exampleBuilder.ParseLabel("1");```
  2. ```example.Learn();``` should be changed to ```vw.Learn(example);```

**Comment by JohnLangford** [comment]
There are two C# interfaces now, so ... some confusion.   Please update the wiki.  @lhoang29 @eisber any comment?

**Comment by eisber** [comment]
I've updated the wiki to reflect the latest nuget. @JohnLangford I don't think there is a confusion between the old and the new API, the documentation for the new API was simply out-of-date.
