### ISSUE TITLE
Can't create features in "Generic data structures" style in C#

### ISSUE THREAD

**Issue by d-khokhlov** [JohnLangford/vowpal_wabbit#914]
I'm trying to use generic data structures in C# binding and often (not every time) I get this error:
```
An unhandled exception of type 'System.AccessViolationException' occurred in VowpalWabbitCore.dll
Additional information: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
```
I was able to reproduce this error with this versions of Vowpal Wabbit NuGet package: 8.0.0.29, 8.0.0.28, 8.0.0.27, 8.0.0.17. And was not able with this versions: 8.0.0.11, 8.0.0.6. I was going to bisect interval between 8.0.0.11 and 8.0.0.17 to find out the exact version where the issue started happen. But at that time I noticed that in versions 8.0.0.29, 8.0.0.28, 8.0.0.27 and 8.0.0.17 the number of features in VW diagnostic output was always 1 (only the constant feature). And in versions 8.0.0.11, 8.0.0.6 this number is far more correct (28-30, I have 30 potential features some of which is absent sometimes).

So I assumed that this two problems is related. I decided to check much simpler case to eliminate that I'm doing something wrong with features etc. I tried to use the example from Wiki page "C# Binding", section "Generic data structures" with version 8.0.0.29 (I have corrected the example code according to my issue #913, hope this isn't wrong). And it fails with the same exception (not every time) and shows that there was only 1 feature instead of 4 (every time).

Here is the exact code:
```c#
namespace TestApp
{
    internal class Program
    {
        private static void Main( string[] args )
        {
            using ( var vw = new VW.VowpalWabbit( "-f rcv1.model" ) )
            {
                VW.VowpalWabbitExample example = null;
                try
                {
                    // 1 |f 13:3.9656971e-02 24:3.4781646e-02 69:4.6296168e-02
                    using ( var exampleBuilder = new VW.VowpalWabbitExampleBuilder( vw ) )
                    {
                        var ns = exampleBuilder.AddNamespace( 'f' );
                        var namespaceHash = vw.HashSpace( "f" );

                        var featureHash = vw.HashFeature( "13", namespaceHash );
                        ns.AddFeature( featureHash, 8.5609287e-02f );

                        featureHash = vw.HashFeature( "24", namespaceHash );
                        ns.AddFeature( featureHash, 3.4781646e-02f );

                        featureHash = vw.HashFeature( "69", namespaceHash );
                        ns.AddFeature( featureHash, 4.6296168e-02f );

                        exampleBuilder.ParseLabel( "1" );

                        // hand over of memory management
                        example = exampleBuilder.CreateExample();
                    }

                    vw.Learn( example );
                }
                finally
                {
                    if ( example != null )
                    {
                        example.Dispose();
                    }
                }
            }
        }
    }
}
```
And here is the exact output when running without debugging (Ctrl+F5) and exception occured:
```
final_regressor = rcv1.model
Num weight bits = 18
learning rate = 0.5
initial_t = 0
power_t = 0.5
using no cache
Reading datafile =
num sources = 0
1.000000 1.000000            1            1.0   1.0000   0.0000        1

finished run
number of examples = 1
weighted example sum = 1.000000
weighted label sum = 1.000000
average loss = 1.000000
best constant = 1.000000
best constant's loss = 0.000000
total feature number = 1

Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at VW.VowpalWabbitNamespaceBuilder.!VowpalWabbitNamespaceBuilder()
   at VW.VowpalWabbitNamespaceBuilder.Dispose(Boolean A_0)
Press any key to continue . . .
```

I run this on Windows 10 x64 with Visual Studio 2015 in Debug x64 configuration (with standard build settings) targeting .NET Framework 4.6.

**Comment by d-khokhlov** [comment]
I have additionaly tested Vowpal Wabbit NuGet package versions from 8.0.0.14 to 8.0.0.16 and find out that the issue appeared in the version 8.0.0.16 (8.0.0.14 and 8.0.0.15 are OK).

Yesterday's new version 8.0.0.30 also suffer from this issue.

**Comment by JohnLangford** [comment]
Not sure what's up.  @lhoang29 @eisber any ideas?

**Comment by eisber** [comment]
the namespace builder is disposable. check the updated wiki page, but in essence you need to do using(var ns = exampleBuilder.AddNamespace( 'f' )) { /* add features here */ }

The AccessViolationException comes from the fact that CLR disposes the object at one time by itself and the referenced memory is not valid anymore.
