### ISSUE TITLE
vw_hyperopt error when tag and importance are in an example string

### ISSUE THREAD

**Issue by cheklov** [JohnLangford/vowpal_wabbit#916]
I've pushed next example:
-1 1 'C6C792693E620CF0A316C46FA39A5684 |a feature feature...
and I've got the error:
 y_pred_holdout.append(float(line.strip()))
ValueError: invalid literal for float(): -8.938600 C6C792693E620CF0A316C46FA39A5684

**Comment by kirillfish** [comment]
Please, provide some minimal reproducible example for me to get at the same error. 

By the way, I've tried to guess what the source of the error is. Here is a small bugfix in my fork repo:
https://github.com/kirillfish/vowpal_wabbit/blob/master/utl/vw-hyperopt.py

Try this out and see if it helps. If not, please, provide a reproducible example.

**Comment by cheklov** [comment]
I see that problem has been fixed. Thank you.

**Comment by kirillfish** [comment]
@cheklov: thanks for the detected bug.
