### ISSUE TITLE
Make multiclass prediction score available in Python

### ISSUE THREAD

**Issue by mdredze** [JohnLangford/vowpal_wabbit#918]
A prediction can be one of several types:
https://github.com/JohnLangford/vowpal_wabbit/blob/master/vowpalwabbit/example.h#L37

When we have a multi-class prediction, it populates the field `multiclass`. If `--probabilities` is provided, it populates `probs` of `prob`.

It is often helpful, even without using probabilities, to have access to the score associated with a multiclass prediction. For example, if you want to set a prediction threshold you need the score.

Since multi-class predictions only store the label, we don't have access to the score.

I have a proposed change. Replace `uint32_t multiclass` with `MULTICLASS::label_t multiclass`.  `MULTICLASS::label_t` has two fields: a label (the prediction) and a weight, which we can use to store the score.

While this requires changing a dozen lines of code, its impact is minimal. Everywhere that currently accessed `multiclass` will instead access `multiclass.label`. The prediction method in `oaa` is modified to store the score. Finally, the Python interface is modified to make the prediction score available.

If this sounds good, I can generate a PR.

**Comment by jconwell** [comment]
Exposing all scores for all labels in multiclass prediction would be really useful as well.  Essentially exposing the same output as --raw_predictions in the python API

**Comment by mdredze** [comment]
I considered doing that. A few options.
1) A list of `float`s, with the `i`th float being the `i`th labels score. This would require every method that accessed this list to find the max.
2) An ordered list of `MULTICLASS::label_t`. If you wanted the prediction, you'd access the `0`th entry. Otherwise, you can iterate through the list to find the value you want.
3) Store both the ordered list as in #1 AND the predicted label. Makes it efficient to get the max prediction, and any score.

Thoughts?

**Comment by eisber** [comment]
I like (3), but can we parameterize to avoid additional overhead if one doesn’t need one or the other? I’m using a factory pattern in C# for the predicitons to trigger what I need…

**Comment by mdredze** [comment]
There is currently a flag --probabilities that stores probability scores.
We could add a similar flag that stores the raw scores.

**Comment by jconwell** [comment]
I like (3) as well.  And would love the raw scores

**Comment by JohnLangford** [comment]
We discussed these variants when --probabilities was being made.   I'd 
suggest just tweaking things so that '--scores' provides arbitrary 
scores: use the same datastructure as --probabilities, but no logistic 
link function.

There is little _computational_ value in providing the scores and the 
max (option (3)), because the computation of the scores deeply amortizes 
a max operation.  So, if we wanted to provide a max (or min), I'd think 
that should be done by function rather than by RAM.

-John

**Comment by jconwell** [comment]
I'm down with a '--scores' flag that populates *probs.  It would then be easy to add an accessor function to pylibvw.cc to return the scores or probs, depending on the flag.

**Comment by JohnLangford** [comment]
There have been several changes to the code to support more advanced prediction types of one sort or another so this is relatively easy to do now.  This: https://github.com/JohnLangford/vowpal_wabbit/blob/master/vowpalwabbit/example.h#L42 is probably the right/best datastructure to store raw scores in for the purpose of reading out from the library interface.

**Comment by danqing** [comment]
Wondering if there's any progress/plan on this :) I think having the raw scores is going to be immensely helpful

**Comment by JohnLangford** [comment]
I've modified oaa.cc to allow you to pass --scores which stores all the scores.  Hence, the underlying plumbing is now setup, and this may just work in some interfaces.

**Comment by JohnLangford** [comment]
I've modified oaa.cc to allow you to pass --scores which stores all the scores. Hence, the underlying plumbing is now setup, and this may just work. I'm not positive about the python interface.  @gramhagen does the python interface multiplex on the prediction type stored here: https://github.com/JohnLangford/vowpal_wabbit/blob/master/vowpalwabbit/learner.h#L114 ? (This is relatively recent, but it makes interfaces much cleaner/safer.)

**Comment by gramhagen** [comment]
the python interface multiplexes on a provided label type, which can be accessed from the label parser. It shouldn't be too hard to switch this to the learner's prediction type and provide access to raw scores through the python interface. #1139 already starts to provide multiple class probabilities.

**Comment by gramhagen** [comment]
This is now supported through the python wrapper with #1139, using scores will give you a list of probabilities.
