### ISSUE TITLE
bfgs can't use sgd final regressor as initial regressor in pyvw.py

### ISSUE THREAD

**Issue by jconwell** [JohnLangford/vowpal_wabbit#924]
Using pyvw python API I can't use a sgd regressor as an initial regressor to bfgs.

I've got a full example below that demonstrates this issue (below).  In STEP 1, it creates a regressor with a couple demo examples.  At the end of the step, it calls vw.finish() to persist the final regressor.

STEP 2 creates a new vw instance that takes as initial regressor the regressor saved from STEP 1.  This works great and gives me predictions.

STEP 3 tries to create a new vw instance that uses bfgs, and takes as initial regressor the regressor saved from STEP 1.  At this point the python process does with an exit code of 139.

If I try to run step 3 from the command line, using the same initial regressor:

```
vw --data <full_path_to_data_file>/tfidf.training.vw --bfgs --hash all --mem 18 --learning_rate 1.0 --power_t 1.0 --l2 0.005 --loss_function squared --l1 0.01 --initial_regressor <full_path_to_model_file>/vw.sgd.model --final_regressor <full_path_to_model_file>/vw.bfgs.model --bit_precision 18 --passes 5 --cache
```

VW outputs: "vw (./io_buf.h:231): file is not a model file"

If I run both the SGD step and the BFGS step from the command line, everything works great.

```
vw --data <full_path_to_data_file>/tfidf.training.vw --hash all --learning_rate 0.5 --quiet --power_t 1.0 --loss_function squared --final_regressor <full_path_to_model_file>/vw.sgd.model --bit_precision 18

vw --data <full_path_to_data_file>/tfidf.training.vw --bfgs --hash all --mem 18 --learning_rate 1.0 --power_t 1.0 --l2 0.005 --loss_function squared --l1 0.01 --initial_regressor <full_path_to_model_file>/vw.sgd.model --final_regressor <full_path_to_model_file>/vw.bfgs.model --bit_precision 18 --passes 5 --cache -p predictions.txt
```

This works great, as expected. 

Here is the python code that reproduces the issue I'm seeing

```
import pyvw

# STEP 1
# create vw instance
vw = pyvw.vw("--hash all --learning_rate 0.5 --quiet --power_t 1.0 --loss_function squared --final_regressor <full_path_to_model_file>/vw.sgd.model --bit_precision 18")

# learn a couple examples
ex = vw.example('1 |a two features |b more features here')
ex.set_label_string('1.0')
vw.learn(ex)
ex.finish()
ex2 = vw.example({ 'a': ['features'], 'b': ['more', 'features', 'there'] })
ex2.set_label_string('-1.0')
vw.learn(ex2)
ex2.finish()

# close the vw instance, persisting off the final regressor
vw.finish()

# STEP 2
# create a new vw instance that takes prior finall regressor as the initial regressor
# (THIS WORKS)
vw = pyvw.vw("--hash all --learning_rate 0.5 --quiet --power_t 1.0 --loss_function squared --initial_regressor <full_path_to_model_file>/vw.sgd.model --bit_precision 18")

ex = vw.example('1 |a two features |b more features here')
ex.set_test_only(True)
ex.learn()
pred = ex.get_simplelabel_prediction()
print pred

ex2 = vw.example({ 'a': ['features'], 'b': ['more', 'features', 'there'] })
ex2.set_test_only(True)
ex2.learn()
pred2 = ex2.get_simplelabel_prediction()
print pred2

vw.finish()

# STEP 3
# create a vw instance that'll use bfgs and the prior final regressor as the initial regressor
# (THIS DOESNT WORK)
vw = pyvw.vw("--bfgs --hash all --mem 18 --learning_rate 1.0 --power_t 1.0 --l2 0.005 --loss_function squared --l1 0.01 --initial_regressor <full_path_to_model_file>/vw.sgd.model --final_regressor <full_path_to_model_file>/vw.bfgs.model --bit_precision 18")

# Code goes boom and never gets here, process exist with code 139
ex = vw.example('1 |a two features |b more features here')
ex.set_label_string('1.0')
vw.learn(ex) ; vw.learn(ex) ; vw.learn(ex) ; vw.learn(ex) ; vw.learn(ex)
ex.finish()

ex2 = vw.example({ 'a': ['features'], 'b': ['more', 'features', 'there'] })
ex2.set_label_string('-1.0')
vw.learn(ex2) ; vw.learn(ex2) ; vw.learn(ex2) ; vw.learn(ex2) ; vw.learn(ex2)
ex2.finish()

vw.finish()
```

**Comment by jconwell** [comment]
I did a bit more experimentation, trying different combinations of running vw via command line and with pyvw, all combos creating a SDG model and using it as an initial regressor for BFGS models in both .

If I make the SGD model via pyvw and pass it in as initial regressor to BFGS in pyvw, I get the error:
`Process finished with exit code 139`
also, the bfgs model file is created and has the name: vw.bfgs.model.writing

If I make SGD model via command line using vw, then pass it in as initial regressor to BFGS in pyvw, I get the error:
`RuntimeError: bad model format!`
the bfgs model file is not created

if I make SGD model via pyvw, and then pass it in as initial regressor to BFGS via command line using vw, I get the error:
`vw (./io_buf.h:231): file is not a model file`
the bfgs model file is not created

If I make SGD model via command line using vw, and then pass it in as initial regressor to BFGS via command line using vw, it works just fine.

**Comment by JohnLangford** [comment]
ml_geek@yahoo.com has apparently fixed this.  Hopefully we'll see a pull 
request.

-John

**Comment by jconwell** [comment]
Actually I'm ml_geek@yahoo.com, but these are two separate issues.  I discovered this regressor compatibility issue after getting sklearn pipelining working.  I can pipeline two SGD estimators, where the output estimator for first guy is input estimator for second guy, just fine.  But if I put BFGS into the mix, where it uses the SGD output model, it gives the errors above.  

I'll make sure the get a pull request going for the sklearn python changes.  But I'm at a loss for what's going on here.  It's something inside vw vs the python wrapper

**Comment by JohnLangford** [comment]
Oh, good, that resolves the coincidence.

What happens when you try to do things from the commandline?

-John

**Comment by jconwell** [comment]
If I manually run things from the commandline, it works just fine.  

For example, if I run SGD from commandline, and use its final regressor as initial regressor for BFGS, like so:

`vw --data <full_path_to_data_file>/tfidf.training.vw --hash all --learning_rate 0.5 --quiet --power_t 1.0 --loss_function squared --final_regressor <full_path_to_model_file>/vw.sgd.model --bit_precision 18`

`vw --data <full_path_to_data_file>/tfidf.training.vw --bfgs --hash all --mem 18 --learning_rate 1.0 --power_t 1.0 --l2 0.005 --loss_function squared --l1 0.01 --initial_regressor <full_path_to_model_file>/vw.sgd.model --final_regressor <full_path_to_model_file>/vw.bfgs.model --bit_precision 18 --passes 5 --cache -p predictions.txt`

BFGS runs just fine and gives me prediction output.  

It seems to be something about models generated by pyvw.  Maybe there is some model finalizer or persistence code somewhere that isn't getting called when pylibvw.vw.finish() is called

**Comment by JohnLangford** [comment]
@gramhagen have you seen this one?  Do you know what's up?

**Comment by dlihhats** [comment]
BFGS option simply doesn't work with VW in Python sklearn. When you try, it says that the minimum number of passes should be 2 even though I have set it up to even larger number.

For example, just adding "bfgs=True" produces the following:

`model = VW(oaa=550, passes=30, b=26, convert_to_vw=False, random_seed=7, \
           decay_learning_rate=0.8097261737051064, initial_t=4.617634843743026e-05, \
           l=0.9037695975303308, power_t=0.5, l2=3.022731250666471e-11, \
           loss_function='squared', l1=1.2144958188964683e-11, cubic="sbc", sort_features=True, q="sd", bfgs=True)
model.fit(train_part_file)`

`---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-360-7d0c40441795> in <module>()
----> 1 get_ipython().run_cell_magic(u'time', u'', u'model = VW(oaa=550, passes=30, b=26, convert_to_vw=False, random_seed=7, \\\n           decay_learning_rate=0.8097261737051064, initial_t=4.617634843743026e-05, \\\n           l=0.9037695975303308, power_t=0.5, l2=3.022731250666471e-11, \\\n           loss_function=\'squared\', l1=1.2144958188964683e-11, cubic="sbc", sort_features=True, q="sd", bfgs=True)\n\n#c_scores = cross_val_score(model, X=train_part_file, y=y_train, cv=skf, scoring=make_scorer(accuracy_score), n_jobs=3)\n#print c_scores, np.mean(c_scores)\nmodel.fit(train_part_file)')

/home/dlihhats/anaconda2/lib/python2.7/site-packages/IPython/core/interactiveshell.pyc in run_cell_magic(self, magic_name, line, cell)
   2118             magic_arg_s = self.var_expand(line, stack_depth)
   2119             with self.builtin_trap:
-> 2120                 result = fn(magic_arg_s, cell)
   2121             return result
   2122 

<decorator-gen-60> in time(self, line, cell, local_ns)

/home/dlihhats/anaconda2/lib/python2.7/site-packages/IPython/core/magic.pyc in <lambda>(f, *a, **k)
    191     # but it's overkill for just that one bit of state.
    192     def magic_deco(arg):
--> 193         call = lambda f, *a, **k: f(*a, **k)
    194 
    195         if callable(arg):

/home/dlihhats/anaconda2/lib/python2.7/site-packages/IPython/core/magics/execution.pyc in time(self, line, cell, local_ns)
   1175         else:
   1176             st = clock2()
-> 1177             exec(code, glob, local_ns)
   1178             end = clock2()
   1179             out = None

<timed exec> in <module>()

/home/dlihhats/anaconda2/lib/python2.7/site-packages/vowpalwabbit/sklearn_vw.pyc in fit(self, X, y, sample_weight)
    270             X = tovw(x=X, y=y, sample_weight=sample_weight)
    271 
--> 272         model = self.get_vw()
    273 
    274         # add examples to model

/home/dlihhats/anaconda2/lib/python2.7/site-packages/vowpalwabbit/sklearn_vw.pyc in get_vw(self)
    242         """
    243         if self.vw_ is None:
--> 244             self.vw_ = pyvw.vw(**self.params)
    245 
    246         return self.vw_

/home/dlihhats/anaconda2/lib/python2.7/site-packages/vowpalwabbit/pyvw.pyc in __init__(self, argString, **kw)
     65         if argString is not None: l = [argString] + l
     66         #print ' '.join(l)
---> 67         pylibvw.vw.__init__(self,' '.join(l))
     68         self.finished = False
     69 

RuntimeError: you must make at least 2 passes to use BFGS`

**Comment by gramhagen** [comment]
The situation with passes for the python wrapper isn't great. right now the
model is configured to learn by processing one example at a time and the
wrapper controls looping over the input data based on the number of passes.
Let me see what can be done to work around this.

**Comment by gramhagen** [comment]
The simplest thing to do is to pass a training data file directly during construction of the VW object which will use the native training (with a cache file and multiple passes). This would be in lieu of using the sklearn fit() method.

something like this:
`model = VW(convert_to_vw=False, oaa=3, passes=30, bfgs=True, data=data_file, cache=True)`

this should take care of the sklearn passes issue. I will look into the initial regressor issue with the python wrapper.

**Comment by gramhagen** [comment]
this use case is a little awkward with python. the python wrapper and subsequent sklearn wrapper create the vw model in memory and interact with it (to learn new examples and make predictions). It does have some capabilities of saving and loading models, but they are not stored in the normal vw format (as you would use for an initial regressor).

The model can be finished, but at that point you can no longer interact with it (or you get the exit code 139 seg fault).

@JohnLangford do you know how the jni handles this case? It seems like we would need to be able to stream in the training data, let vw loop through the passes, save the model and then re-open that file for prediction only. Figuring out how to save a proper vw model from the python interface will probably be necessary to solve most of the issues here.

**Comment by gramhagen** [comment]
Ok, I think I've addressed the concerns with the new PR.  You can load in initial regressor models, and specify external data files to use for training (using data='filepath') when constructing the model. This will let you do something like VW(data='filepath', passes=30, oaa=3, bfgs=True), check out the new tests in test_sklearn_vw, and test_pyvw.

To save the output you should use model.save('filename'), note this is in pyvw, not in sklearn. The sklearn wrapper has it's own save/load methods, but they don't use the vw format. If you want to access the new pyvw save method, you can try model.get_vw().save('filepath')

let me know if this doesn't cover all the cases you're bumping into

**Comment by JohnLangford** [comment]
Thanks @gramhagen
