### ISSUE TITLE
Parser::parser_done() inconsistency

### ISSUE THREAD

**Issue by trufanov-nok** [JohnLangford/vowpal_wabbit#926]
While testing #923 I found out that resulting small audit files randomly appears empty. That happens bcs I call close() for output file in `end_examples()` and it wasn't called. We already had this problem in #726 (III) when it was never called after parser::set_done(). It seems it wasn't fixed for 100% and now it's randomly not invoked.

The problem is that `parser_done()` check may return `false` [here](https://github.com/JohnLangford/vowpal_wabbit/blob/master/vowpalwabbit/learner.cc#L58) after [set_done()](https://github.com/JohnLangford/vowpal_wabbit/blob/master/vowpalwabbit/parser.cc#L598) was called.
That's because it has additional check `p->used_index != p->begin_parsed_examples`.
It looks like it was designed to not return true until all loaded examples are processed. But this function is only used twice [here](https://github.com/JohnLangford/vowpal_wabbit/blob/master/vowpalwabbit/learner.cc#L45) in loop over `all.early_terminate` and in `if` clause with `early_terminate`. It seems it's not used anywhere else at current point of time. Also `set_done()` sets both `early_terminate` and `p->done()` to true.

I believe that  `p->used_index != p->begin_parsed_examples` shouldn't be checked at least when `all.early_terminate` is true. Is it's not possible to access `all` from this function I'd suggest replacing line 49
` else if (parser_done(all.p))` with
`  else if (all.early_terminate || parser_done(all.p))`
and line 58
`if (parser_done(all.p))`
with just
`if (all.p->done)`
in learner.cc

Perhaps parser_done() is never invoked in situation when p->done is true and all.early_terminate is false. In this case this function may be just thrown out and replaced with all.p->done. Perhaps I just misunderstand something but the soft fix proposed above seems to be safe.

**Comment by arielf** [comment]
Thanks Alex.

Atomicity and placement of 'parsing is done' and 'all is done' vs the two `vw` concurrent threads may have been related to a long series of race conditions which would cause intermittent failures (small differences in the diff) in some tests in the past.

You may do a stress test to any test number (integer argument to the bash script below is test no).
It runs the same test many times to try and reproduce the race condition.

```
#!/bin/bash
# heisen-bug-test:  run this inside the 'test' subdirectory
OutLog=/tmp/vw.heisen.bug
MaxCount=500
Timeout=10s

case "$@" in
    [1-9]*) TestNo=$1 ;;
    *) TestNo=5 ;;
esac

case `pwd` in
    */test) : ;;
    *) cd test ;;
esac

rm -f RunTests.last.times

counter=1
while [ $counter -lt $MaxCount ]; do

    timeout $Timeout ./RunTests -d -fe -E 0.001 $TestNo ../vowpalwabbit/vw ../vowpalwabbit/vw >$OutLog 2>&1

    case $? in
        0)  : -- no heisenbug, keep trying
            printf '\r%d' $counter > /dev/tty
            ;;
        124) printf '\r' > /dev/tty
             echo "=== timed-out after Timeout=$Timeout (no heisenbug)"
             ;;
        *)  printf '\r' > /dev/tty
            echo "=== +++ Test $TestNo: heisen-bug HIT ($counter attempts)"
            # Need to auto-find the relevant stderr
            diff_files=`grep FAILED $OutLog | perl -ne '
                /\(([^)]+)\)[^(]+\(([^)]+)/ && print "$1 $2\n"'`
            diff -u $diff_files
            exit 1
            ;;
    esac
    counter=$(($counter + 1))
done
printf '\r' > /dev/tty
echo "=== --- Test $TestNo: no heisen-bug ($counter attempts)"
exit 0
```


Here's an additional script trying to stress test the few tests that used to exhibit the issue more than others:

```
#!/bin/sh
# heisen-bug-runall
for TestNo in `seq 20 40 `; do
# for TestNo in 1 3 5 14 60; do
# -- known to hit the bug:
# for TestNo in 5 24 60; do
    echo "### --- Test $TestNo"

    for try in `seq 1 10`; do
        heisen-bug-test $TestNo 2>&1 >ztemp
        grep '^=== ' ztemp
    done
done
```

**Comment by trufanov-nok** [comment]
Well, currently I can't reproduce this problem at all. `p->used_index != p->begin_parsed_examples` is always false. Will check again this evening.

**Comment by JohnLangford** [comment]
I believe this is fixed.
