### ISSUE TITLE
Thread-safe prediction for string based examples

### ISSUE THREAD

**Issue by d-khokhlov** [JohnLangford/vowpal_wabbit#928]
From the "C# Binding" wiki page it is unclear how to make thread-safe predictions using string based examples (e.g. "1 |f 13:3.9656971e-02 24:3.4781646e-02 69:4.6296168e-02"). In the "Multi-threading" section there is a code for user defined data types only. I can think of three cases here:
- The VW.VowpalWabbit class (non-generic) is actually thread-safe. So there is no need to pool VW instances for string based (and generic data structures also) predictions. Then we need to clarify this in "Multi-threading" section.
- All VW.VowpalWabbit classes (both generic and non-generic) are not thread-safe. But only the pool for generic VW.VowpalWabbit classes is implemented now (or I haven't find one for non-generic). Then I need to implement it myself. For example (is it correct?):
```c#
private class VowpalWabbitStringBasedThreadedPrediction : VowpalWabbitThreadedPredictionBase<VowpalWabbit>
{
    public VowpalWabbitPool(VowpalWabbitModel model)
        : base(model)
    {
    }

    protected override VowpalWabbit InternalCreate(VowpalWabbit vw)
    {
        return vw;
    }
}
```
So, how should I make thread-safe string based predictions?

**Comment by eisber** [comment]
None of the VW.VowpalWabbit classes are thread safe, only the pool is.
The below is almost correct (modulo some naming). I included it in https://github.com/JohnLangford/vowpal_wabbit/pull/917/files#diff-a61e35491c76a976dd0aa13d366ac5c0

Markus
