### ISSUE TITLE
vw-varinfo and --loss_function logistic

### ISSUE THREAD

**Issue by trufanov-nok** [JohnLangford/vowpal_wabbit#930]
There is a small bug. Using `--loss_function logistic` in vw-varinfo command line may trigger
`ignoring trainset: logistic in vw-args: train-set must be last arg`
because there is a file named logistic in utl folder. Perhaps `--loss_function` arguent should be escaped at line 139 too.

**Comment by trufanov-nok** [comment]
Btw, I'm using almost all characters as a namespaces in my dataset. Including some special. Looks like vw-varinfo has some problems with at least `[`. I think I'm getting:
`Unmatched [ in regex; marked by <-- HERE in m/^[ <-- HERE \S*\s*/ at ./vw-varinfo line 325, <$ts> line 1.`
bcs I have namespace `|[` in my data. Is there an easy way to escape the `$ns`content in perl script to prevent its processing as a part of regexp?

**Comment by eisber** [comment]
Are you looking for…


Use \Q...\E to escape special symbols directly in perl string after variable value interpolation:

if( grep {$_ =~ m/^\Q$word\E$/i} @arr)

http://stackoverflow.com/questions/2001176/how-can-i-escape-meta-characters-when-i-interpolate-a-variable-in-perls-match-o

**Comment by trufanov-nok** [comment]
@eisber Thanks, that helps.

**Comment by JohnLangford** [comment]
Fixed so closing.
