### ISSUE TITLE
sequence tagging memory usage too high

### ISSUE THREAD

**Issue by vjeranc** [JohnLangford/vowpal_wabbit#937]
I've ran an example provided in [this tutorial](https://github.com/JohnLangford/vowpal_wabbit/wiki/2015_tutorial.pdf).

Example snippet:
```
wget http://bilbo.cs.illinois.edu/~kchang10/tmp/wsj.vw.zip
unzip wsj.vw.zip
vw -b 24 -d wsj.train.vw -c --search_task sequence --search 45 --search_neighbor_features -1:w,1:w --affix -1w,+1w -f wsj.weights
```

bug is present in current HEAD 7eebf3a
Memory usage explodes (more than 10GB) and training is significantly slow, gets killed before training finishes.

training finished successfully (not the first commit where this happens): c78f026
memory usage is constant here, around 260MB (I think 256MB is allocated once for the longest possible sequence or weight array). Although, training took 10 minutes, not 10 seconds as reported in the tutorial.

Built it from source on osx i5 and ubuntu i7 - on both the memory explodes.

**Comment by vjeranc** [comment]
I've checked some of the previous commits [listed here](https://github.com/JohnLangford/vowpal_wabbit/commits/master/vowpalwabbit/search.cc) and memory does grow, although slowly.

The commit where memory starts growing insanely fast is 94541ec5. (will check what exactly happened there since the commit seems fairly simple)

The furthest I've checked is 97b5e4d2. Here the memory also grows but more slowly. Other commits I've tried I couldn't build.

As reported growth was not present at c78f026.

**Comment by eisber** [comment]
Hmmm. I looked throught the commits and can’t spot anything right now. Did you check using valgrind?

Markus

**Comment by vjeranc** [comment]
Tried it but there wasn't any info during the training process (memory grows but there are no memory leaks visible).

Will try again with a smaller example and report here.

**Comment by vjeranc** [comment]
Valgrind says that v_array resize (realloc call leaks). It happens at [this line](https://github.com/JohnLangford/vowpal_wabbit/blob/master/vowpalwabbit/search.cc#L2390). Call to action_repr constructor uses copy_array and the memory allocated there leaks.

copy_array calls in [this function](https://github.com/JohnLangford/vowpal_wabbit/blob/master/vowpalwabbit/feature_group.h#L325) leak too.

I've been looking at search.cc calls and it seems that these arrays in features inside action_repr get deallocated [here](https://github.com/JohnLangford/vowpal_wabbit/blob/master/vowpalwabbit/search.cc#L549-L554).

[search_finish](https://github.com/JohnLangford/vowpal_wabbit/blob/master/vowpalwabbit/search.cc#L1935) calls `delete_v()` on arrays storing `action_repr`, after adding loops for [`condition_on_actions`](https://github.com/JohnLangford/vowpal_wabbit/blob/master/vowpalwabbit/search.cc#L1956) and [`learn_condition_on_act`](https://github.com/JohnLangford/vowpal_wabbit/blob/master/vowpalwabbit/search.cc#L1987) there seem to be fewer leak errors but as far as I know, `search_finish` is called in the end and this leak isn't causing the memory growth.

Maybe the action_repr v_arrays inside search.cc are the cause. I'm not really sure.

**Comment by vjeranc** [comment]
My `git bisect` journey. What I did was start with c78f026 as a good commit, 7eebf3a as bad.

I mentioned memory growth being different throughout, luckily during my `git bisect` journey I stumbled upon only constant memory branches (there was no increase - always around 260MB), I was prepared to mark the slowly rising ones as good.

There's also a slowdown at some point, although 17s training time for 50k tokens seems a bit long too. I used `wsj.test.vw` as a testing example.

This is the journey, columns - commit - status (rising memory) - time in seconds - memory usage. I've skipped the ones I couldn't build (`git bisect skip`).

3c2651238ab4a17917eaa23bd059edada4f65f25 good  17   constant
65cc59ffdd8a690fdc81a89657896dbb7712474f good  17   constant
806ca7fdf65b732d2a6af22c17c588c67a71d19e good  17   constant
c9f93cdf429d8a40633b74ef91d6a0db42f53bbb good  26   constant
17df3cfcb99abc0fc39847839e91db38cf76126c good  26   constant
dd0e068788137df3a965fe0a2d0a6c2cd22d76ea skip
ff377b21a1219d81cd1fe8719509604f60599eca bad
283c5540bdd343d58db910611363ba047dea6cde good  26   constant
901c8032152cf87475cf4c8ad2de50190e9a0b7c skip
4ae1ac47c1de7cd1a94c54f54db7347466bdbbcb good  27   constant
0a591fc6c61d6c14285dc64da2219a13ab5b11f8 skip
63cbd101cec9d2848417d9581116dd01bf2c9ebe skip
c4490d35d0c12d5492e0823d12b521ebc8c7f956 skip
4424dbd8f02507fea8f96e78ab2f663df0bbdf65 bad


`git bisect` report

The first bad commit could be any of:
63cbd101cec9d2848417d9581116dd01bf2c9ebe
0a591fc6c61d6c14285dc64da2219a13ab5b11f8
dd0e068788137df3a965fe0a2d0a6c2cd22d76ea
901c8032152cf87475cf4c8ad2de50190e9a0b7c
c4490d35d0c12d5492e0823d12b521ebc8c7f956
4424dbd8f02507fea8f96e78ab2f663df0bbdf65

I'll see if there's anything interesting above.

**Comment by vjeranc** [comment]
Found [the bug](https://github.com/JohnLangford/vowpal_wabbit/blob/master/vowpalwabbit/feature_group.h#L325-L333). The function did look suspicious when I mentioned it previously.

Deleted this operator and the code doesn't leak at all. (memory around 260MB).

Will see the minimum amount of changes necessary to fix the bug - I'm not sure if this deletion breaks something else.

**Comment by vjeranc** [comment]
Found the bug.

**Comment by eisber** [comment]
The underlying issue is that there is a mix of shallow vs. deep copy.

**Comment by eisber** [comment]
The deletion actually breaks deep copy in other places. I replaced some calls to copy_array() with assignments. Will discuss with John on how to model shallow vs. deep copy.

**Comment by vjeranc** [comment]
Yes, noticed the breakage.

`push_at` in `search.cc` uses the `features& operator=(const features& rhs)` when otherwise it used a shallow copy.

**Comment by vjeranc** [comment]
I've added a pull request https://github.com/JohnLangford/vowpal_wabbit/pull/939 which seems to resolve the leak (also added proper `delete_v()` calls that resolve couple of not-a-problem leaks in `search_finish`).

**Comment by JohnLangford** [comment]
This is some good detective work---thank you.

Another question is: how do we prevent this sort of thing in the 
future?  Valgrind would have nailed this, but can valgrind be used 
effectively on travis?

-John

**Comment by vjeranc** [comment]
Should be possible. valgrind allows defining the error exit code which can then trigger a fail.

I can add play with it in my fork to see if travis will catch it with valgrind.

I think with cmake it would be a trivial addition.

I'm assuming that travis doesn't need to provide debugging information - avoiding the need to build the test in debug mode?

**Comment by JohnLangford** [comment]
The RunTests code supports -V which runs valgrind.   The primary concern 
I have is that it will take too much computation for Travis.

-John

**Comment by vjeranc** [comment]
Is it necessary to run all of the tests for leak checks?

This leak fails for one sentence, assuming only 2 possible labels - test is done in less than 5s.

**Comment by eisber** [comment]
created a PR #946 

Thanks for all the archaeology

**Comment by vjeranc** [comment]
no problem, I'll close my PR.

**Comment by JohnLangford** [comment]
This is fixed now.   Thanks (again) for finding the bug.
