### ISSUE TITLE
sequence tagging performance regression

### ISSUE THREAD

**Issue by vjeranc** [JohnLangford/vowpal_wabbit#940]
[This tutorial](https://github.com/JohnLangford/vowpal_wabbit/wiki/2015_tutorial.pdf) mentions 10s training time for POS tagging over almost 1M tokens.

Currently on i7 4770 I get 4m22s on `wsj.train.vw` (with the [leak fix](https://github.com/JohnLangford/vowpal_wabbit/pull/939) - 7m50s with the [proper leak fix](https://github.com/JohnLangford/vowpal_wabbit/pull/946)). 16s on `wsj.test.vw`.
Testing time seems to be similar (0.125s) to the reported one so I guess learning is affected.

Training time reported [here](http://arxiv.org/abs/1406.1837v4) (from the graphs) is less than a minute. In the paper it is mentioned there's a couple of minutes worth of training for vw. So I guess results for 7.10 seem to be correct, although this 10s per 1M tokens sounds amazing and I can't reproduce it.

I've been playing around and [here's a trivial change](https://github.com/vjeranc/vowpal_wabbit/commit/99b8acd6ce33267668bced93675c31488216d832). Replacing [sequence task run function](https://github.com/JohnLangford/vowpal_wabbit/blob/94541ec5dd8ec8a722d9dd4396d3332f603a72c3/vowpalwabbit/search_sequencetask.cc#L24-L33) with snippet given below results in a ~3 times faster training - 1m32s.

```c++
void run(Search::search& sch, vector<example*>& ec)
{ auto predictor = Search::predictor(sch, (ptag)0);
  for (size_t i=0; i<ec.size(); i++)
  { action oracle     = ec[i]->l.multi.label;
    size_t prediction = predictor.set_tag((ptag)i+1).set_input(*ec[i]).set_oracle(oracle).set_condition_range((ptag)i, sch.get_history_length(), 'p').predict();

    if (sch.output().good())
      sch.output() << sch.pretty_label((uint32_t)prediction) << ' ';
    predictor.reset(); // looks exactly the same as ~predictor - all calls to delete_v replaced with erase.
  }
}
}
```

I'm wondering is this implementation desired? Did regression happen?
I've tried 72994d3f1c5cdb33d842bac7bea146679c84ad98 (7.10 referenced in the arxiv paper) and training time on `wsj.train.vw` was 3m50s. So, I'm not exactly sure if there's anything different (parameters which I'm not aware of)

**Comment by JohnLangford** [comment]
@KaiWeiChang @hal3 Can you take a look at this?

**Comment by KaiWeiChang** [comment]
Thanks for reporting this.  The following command should be able to reproduce the experiments:
time ./vowpalwabbit/vw  -b 24 -d wsj.train.vw -k  --search_task sequence --search 45 --passes 1  --search_alpha 1e-8 --search_neighbor_features -1:w,1:w --holdout_off --search_rollout none --affix -1w,+1w -f wsj.weights

Thanks,
Kai-Wei

**Comment by vjeranc** [comment]
Without `--search_rollout none` it's back to ~4 minutes. With it it's definitely 10s or less :smile: 

I assumed there were no rollouts if Hamming loss was declared, but I guess, given the fact that one can define possible actions for each time step it is better to leave that option to the user. Should have checked the code more carefully :)

Thanks for the fix.

**Comment by vjeranc** [comment]
Without `--search_rollout none` it's back to ~4 minutes. With it it's definitely 10s or less :smile: 

I assumed there were no rollouts if Hamming loss was declared, but I guess, given the fact that one can define possible actions for each time step it is better to leave that option to the user. Should have checked the code more carefully :)

Thanks for the fix.

**Comment by KaiWeiChang** [comment]
Yes, when Hamming loss is used, rollout=none is the same as rollout=ref, and the experiments shown in the tutorial were done with rollout=none. Rollout=ref is useful when the loss is not decomposable over the search space. There was a recent change slowed down the speed of prediction. We now make sure the training time matches v7.10.

I'm now looking at your suggestion -- reusing the predictors. This is a good idea, but I want to make sure it also works for other applications. 

Thanks,
Kai-Wei

**Comment by vjeranc** [comment]
Yep. My suggestion is ugly, and could be made prettier and non-explicit. It does speed up things significantly because that `predict()` hot loop doesn't make any new allocations while looping over the example.

Again, thanks! I'm loving the code :)

**Comment by KaiWeiChang** [comment]
The pull request #979 should address this now. 
I made changes on both sequential taggers and dependency parsers. 

Thanks for your suggestion. Please let me know if you have any comments.

@hal3: Do the changes look good to you?
