### ISSUE TITLE
Unclear loop semantics in vowpalwabbit/cb_adf.cc  get_observed_cost(), unused iterator

### ISSUE THREAD

**Issue by arielf** [JohnLangford/vowpal_wabbit#945]
file `cb_adf.cc` function `get_observed_cost` has this loop:
```
  for (CB::cb_class& cl : ld.costs)
  { mydata.known_cost = ld.costs[0];
    mydata.known_cost.action = index;

    // take care of shared example
    if(shared)
      mydata.known_cost.action--;
  }
```

So `cl` iterates over the label costs, but `cl` isn't used inside the loop.

Also, the loop has two assignments that look invariant with respect to the iterator.
Only the `mydata.known_cost.action--` decrement looks like it is relevant to the loop.

All in all it is not clear what is the intention here.
Can/should this loop be simplified?

**Comment by eisber** [comment]
Before my change the loop existed, but the variable wasn’t there. C++ 11 doesn’t allow range loops with an iterator variable.
I was about to simplify the loop, but then wasn’t 100% clear on the effect. Maybe Alekh/John can shed some light on this.

**Comment by JohnLangford** [comment]
This code is headscratcher.  It's equivalent to having no loop.  I verified that it has the same semantics as before, so I just removed the loop.
