### ISSUE TITLE
Python library/module not loading when installing through brew on Mac OS X 10.11.3

### ISSUE THREAD

**Issue by kamal94** [JohnLangford/vowpal_wabbit#963]
After installing with brew, 
     ```brew install vowpal-wabbit```
the following code does not work, either when using python 2 or python 3
     ```import pyvw```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named pyvw

**Comment by amrsharaf** [comment]
The python library is not in the make target by default. You have to download vw from github and compile the python library separately. You may run into some issues on Mac, so have a look at this thread as well before compiling the library: https://github.com/JohnLangford/vowpal_wabbit/issues/415#issuecomment-188615631

**Comment by kamal94** [comment]
Thank you. Indeed this was the solution, though a hectic one on Mac. The whole anaconda environment problem though seems to be a prevalent one. Perhaps a fix is needed.
