### ISSUE TITLE
Long line issue in 8.1.1

### ISSUE THREAD

**Issue by bpovlich** [JohnLangford/vowpal_wabbit#966]
I am able to reproduce an issue where after a certain length, VW thinks a new line has started:

```
vw -k -b 24 -d as_error.txt -f model
final_regressor = model
Num weight bits = 24
learning rate = 0.5
initial_t = 0
power_t = 0.5
using no cache
Reading datafile = as_error.vw
num sources = 1
average  since         example        example  current  current  current
loss     last          counter         weight    label  predict features
Error: 6 is too many tokens for a simple label: bbbba1a2
0.000000 0.000000            1            1.0  unknown   0.0000        1

finished run
```

I have attached the as_error.txt file.  If I take a few of the "b" characters (at the end of the file) away, I get this warning:

```
warning:  is not a good float, replacing with 0
warning: a2 is not a good float, replacing with 0
```

I believe VW thinks it's a new line because the error is coming from simple_label, line 81.
https://github.com/JohnLangford/vowpal_wabbit/blob/master/vowpalwabbit/simple_label.cc

This error does not occur in version 8.0.0, but it is uncertain if it is just silently failing.

[as_error.txt](https://github.com/JohnLangford/vowpal_wabbit/files/184992/as_error.txt)

**Comment by JohnLangford** [comment]
This appears to be fixed in the current master.

-John
