### ISSUE TITLE
autoconf encounters possibly undefined macros

### ISSUE THREAD

**Issue by kamal94** [JohnLangford/vowpal_wabbit#969]
**problem** 
When running autoconf on a clean clone of the project, the errors below are returned.

```
configure.ac:3: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:15: error: possibly undefined macro: AM_PROG_LIBTOOL
configure.ac:20: error: possibly undefined macro: AC_MSG_ERROR
configure.ac:41: error: possibly undefined macro: AM_CONDITIONAL
```

**solution**
From some [error searching](http://stackoverflow.com/questions/29136216/am-prog-libtool-not-found-in-library), I found that it could be due to automake or libtool not being installed (though they were installed on my machine). The only fix was to run ```autoreconf -fvi``` which gave an error fixed by #968 .

*edit*: my system is Mac OS X 10.11.4

**Comment by abhijithea37** [comment]
please initialize m4 enviornment by using aclocal
