### ISSUE TITLE
Does sklearn interface allow multiclass classification?

### ISSUE THREAD

**Issue by erogol** [JohnLangford/vowpal_wabbit#973]
I tried oaa=N for enabling multiclass case it did not work. I guess I am missing something or sklearn interface does not provide multi-class case.

**Comment by mikkelam** [comment]
I hacked it to work for ECT multiclass classification https://gist.github.com/mikkelam/0c333310ee47c14dad4b8bd51589a8a5

check out the example in the bottom

**Comment by JohnLangford** [comment]
Something should work in the current interface for specific multiclass 
algorithms (like oaa).  I'm not sure what's going wrong in your case?

-John

**Comment by mikkelam** [comment]
> Something should work in the current interface for specific multiclass algorithms (like oaa). I'm not sure what's going wrong in your case?

I believe the classifier is hardcoded  to only work in the binary case
https://github.com/JohnLangford/vowpal_wabbit/blob/master/python/sklearn_vw.py#L452

**Comment by gramhagen** [comment]
yeah, that's the way to do it for now.  Just use the VW base estimator.  I looked at supporting something from sklearn.multiclass, but it's not trivial.  One thing to note is your class ids need to be in range [1, k], i.e. vw doesn't support class id = 0.

**Comment by JohnLangford** [comment]
Closing for now.
