### ISSUE TITLE
RFE: Avoiding Hash Collisions

### ISSUE THREAD

**Issue by sam-s** [JohnLangford/vowpal_wabbit#982]
I am aware that some people consider hash collisions to be a _feature_, not a _bug_. However, in our experience hash collisions reduce model performance because different features are effectively interpreted as if they were identical.

I am also aware that the standing recommendation for avoiding hash collisions is to increase `bit_precision`. Alas, this is not a solution because, first, it does not guarantee that there will be no collisions, and, second, this increases the memory footprint which is not acceptable in production.

# Proposal

Use [gperf](https://www.gnu.org/software/gperf/) to generate perfect hashing functions.

Initially, create the feature weight hash table the way it is done now (with the current function). Additionally, create the second table - feature name table. 

When a feature string is mapped to the weight, we first look it up in the feature name table; if the value is `NULL`, we record the feature name (say, `foo`) there the use the feature weight table as we do now. If the feature name table has `foo` there already, there is no collision and we proceed as usual. 

If the feature name table has `bar`, we have a hash collision (i.e., the hash value for `foo` and `bar` is the same). Now we take all the feature names seen so far (from the values of the feature name table plus the new name which causes the collision) and generate a perfect hash function using `gperf`, and re-map both feature weight and feature name tables.

Presumably previously unseen features will appear less and less frequently, so this hash table rebuilds will not be too frequent.

# Drawbacks

1. Hash rebuild requires a `C` compiler (to compile the `C` code generated by `gperf`).
1. Hash rebuild is more expensive than ignoring hash collisions

# Advantages

1. Much smaller model size
1. All features are used individually, there is no random merging of unrelated features due to hash collisions.

# Variant

To avoid calling gperf at training time, use a real hash table (with hash collision resolution at run time) to train the model, and then use gperf for model deployment only.

**Comment by trufanov-nok** [comment]
Basically you can create a dictionary of feature names and use feature ID from that dictionary as its hash. It'll be unique. It could have sense to implement this as a script and preprocess incoming data. VW supports `--hash` parameter that allows to just spoof features in dataset with their hash. I wouldn't mind from such script in VW's `utl\` folder or even as optional VW's logic. 
But I would be definitely against that switched on by default. It could decrease performance a lot and more important - blow up RAM usage. User can face a dataset with unlimited number of different features in it (like words in text for spam detection) especially If VW is used as daemon for realtime prediction. And more important -  I often use interactions of feature namespaces (`-q`, `--cubic` etc) and that blows up feature space.
I made such dictionary making tool for myself in Qt years ago and experimented with one of Kaggle datasets by preprocessing it to avoid hash collisions in VW. In my case it didn't affect my model accuracy at all.

**Comment by JohnLangford** [comment]
@aartibagul is working on supporting sparse models which (I think) addresses this in a different way.  Instead of building a perfect hash, it allows a hash function with a large number of bits.

**Comment by JohnLangford** [comment]
Closing this for now, but reopen to discuss further.
