### ISSUE TITLE
search learning model performance regression

### ISSUE THREAD

**Issue by vjeranc** [JohnLangford/vowpal_wabbit#983]
It seems that the learner (at least the one used for `--search`) has regressed (not a speed related issue).
The [7.10](https://github.com/JohnLangford/vowpal_wabbit/tree/c1184888abc799433d4071ca1e74dbbf8894aec9) seems to be significantly outperforming latest HEAD b879ee2222b9bb647b4646b608fdde9592294be4.

It might also be that for my particular case the behaviour changed significantly. I couldn't get similar performance on the same data no matter how hard I tried :smile: At first I thought Croatian is difficult, or that the dataset isn't sufficient but it isn't true.

I've attached a small Croatian corpus ([data.zip](https://github.com/JohnLangford/vowpal_wabbit/files/238461/data.zip)) for part-of-speech and MSD tagging. (MSD includes part-of-speech and various other attributes, which implies that accuracy will be lower than POS)

I use the following settings on both 7.10 and current head.
```sh
$VW --cache \
    --bit_precision 28 \
    --data $TRAIN \
    --kill_cache \
    --search_task sequence \
    --search $poscount \
    --passes 3 \
    --search_neighbor_features -2:w,-1:w,1:w,2:w \
    --affix -5w,-4w,-3w,-2w,-1w,1w,+2w,+3w,+4w,+5w \
    --search_alpha 1e-8 \
    --holdout_off \
    --search_rollout=none \
    --final_regressor $MODEL \
    --ring_size 256
```
Accuracy and vw reported loss on test set by commit:

| Commit                                   | POS    | MSD    | Avg. loss |
|------------------------------------------|--------|--------|-----------|
| c1184888abc799433d4071ca1e74dbbf8894aec9 | 0.9738 | 0.8830 | 1.4323    |
| b879ee2222b9bb647b4646b608fdde9592294be4 | 0.9464 | 0.8088 | 2.19382   |

The performance with the current HEAD can be better if `--affix` features are removed and `--search_neighbor_features -1:w,1:w` used instead but still not near the 7.10 numbers. I'm not sure why that is the case. (this might not work on the current permutation of the dataset but works in general)

I also couldn't get satisfying results on dependency parsing for Croatian and other languages (couldn't reproduce http://arxiv.org/abs/1503.05615), I assumed I just didn't play long enough but it seems that every search task might be affected.

It's also not the case that only the current head has the problem. Similar bad performance happens few commits before.

I'll do a `git bisect` to see where the regression point is for the POS task.

`--search 13` for POS
`--search 686` for MSD

I use bash below for measuring accuracy where files do not have empty lines:
```sh
a1=`diff .outputtrue .output | grep "^>" | wc -l`
a2=`wc -l < .outputtrue`
echo "Acc:" `calc "1-$a1/$a2"`
```

This is the testing call:
```sh
$VW -t -d $TEST -i $MODEL --ring_size=256 -p .outputtest # --quiet
```

**Comment by KaiWeiChang** [comment]
Thanks! 

Once you point me out where the regression point is, I can check what possible changes may cause this regression. 

Best, 
Kai-Wei

**Comment by JohnLangford** [comment]
What is an automated test to find the regression point?

-John

**Comment by vjeranc** [comment]
`git bisect` result:

> There are only 'skip'ped commits left to test.
> The first bad commit could be any of:
> badeedb2c11dfb56f5c2314088de2d8e3eb88e4f
> dba18da6195f101151efe61a792b7375e17af587
> eb84b13ca73005c02fe5bfa9df60b5bcf53d79b1
> We cannot bisect more!


This could have been automated by a script running the pos task, parsing the accuracy measure and announcing `good` or `bad` to `git bisect` if it differed significantly, announcing `skip` if it couldn't build the vw.

It takes logarithmic time anyway so it took me about 15 minutes of testing and reporting.

I guess the biggest issue with automating this would be the build time.

Manual `git bisect` journey:

| Commit                                   | act  | test-acc                |
|------------------------------------------|------|-------------------------|
| e9a673a8e8de0ef1e8259738c8cca44e1a153db9 | skip |                         |
| 7c1fc5584f590837af26c231aa123c3831ec7b05 | good | ~0.97377446035908815816 |
| ae05c637fb4b7761add9f5ff55d11c4bbc11de0d | good | ~0.97377446035908815816 |
| 0f3c11c20d3f68bb9674ae5945c2f4b07818a4a9 | bad  | ~0.94638894492636675409 |
| 65cc59ffdd8a690fdc81a89657896dbb7712474f | skip |                         |
| 12e309347444cce46d922b7a65afe29df61eb82e | skip |                         |
| 307e71a0176ff0e1578e6940f85ecd428bb97bf5 | skip |                         |
| 9eac70e42a99dcfe56f1d5cfa1508eeef08a2fa5 | skip |                         |
| 8806cd4382cbf3957bf700a29e24ff42d3f07abf | skip |                         |
| 1ae39c78299b3f54c3d6a3c15be0ff7a8907cf1c | good | ~0.97639701432317934234 |
| 9c59f2044cb68aa5c055e933c3706a5abf6516fe | bad  | ~0.94638894492636675409 |
| d3078704c73bd0da9164bc01d8ab0be8fd8e1247 | good | ~0.97639701432317934234 |
| 09b53cab4364d7eddc9363b384f7a9a07c78d471 | bad  | ~0.94638894492636675409 |
| 1e0e5d137f1dbc0c18dda76e9416c94d0cfb37a7 | bad  | ~0.94654024611660278394 |
| dba18da6195f101151efe61a792b7375e17af587 | skip |                         |
| badeedb2c11dfb56f5c2314088de2d8e3eb88e4f | skip |                         |
| eb84b13ca73005c02fe5bfa9df60b5bcf53d79b1 | bad  | ~0.94654024611660278394 |
| 0069eb50af49ef65aaa696e6af3535590b0727d6 | good | ~0.97639701432317934234 |

**Comment by vjeranc** [comment]
`affix_features` change from `char` to `uint64_t` brings back the accuracy to ~0.97639701432317934234.

Is it really the case that only 8 per namespace work? Meaning that `-5w,-4w,-3w,-2w,-1w,1w,+2w,+3w,+4w,+5w` used above has 2 which won't be used?

**Comment by KaiWeiChang** [comment]
I don't know about the affix_features implementation.

 @JohnLangford  or @hal3, do you know why we need to restrict only 8 affix features per namespace?

**Comment by vjeranc** [comment]
I've looked at the code. It assumes there are at most 256 namespaces. For each namespace there was a 64-bit integer and it could hold 4 bits per affix, meaning there could be at most 16 affixes. [Some time](https://github.com/JohnLangford/vowpal_wabbit/blob/a3d796c2592f665236057e29421bdc9004b29adc/vowpalwabbit/global_data.h#L471) in the past `uint32_t` was used so it could hold 8.

https://github.com/JohnLangford/vowpal_wabbit/blob/master/vowpalwabbit/parse_args.cc#L277-L279

I can make a pull request with the fix and change of comment.
