### ISSUE TITLE
Want to locate feature in readable_model

### ISSUE THREAD

**Issue by swapniel99** [JohnLangford/vowpal_wabbit#985]
Hi,

I was trying to replicate murmurhash to find the hash of feature used in readable model (not invert_hash).

When I don't use namespace, I am able to find the exact hash externally. Using murmurhash and then taking reminder with 2^b

But with namespace I am not able to do it. Can you tell what string is used to find hash of a feature within namespace. Also how to find the hash of constant in readable_model?

**Comment by trufanov-nok** [comment]
Are you sure you want to lookup features by their hash? Perhaps you may try `--audit_regressor` to get both hashes and feature names in namespaces.Check out its description [here](https://github.com/JohnLangford/vowpal_wabbit/wiki/Command-line-arguments)

**Comment by swapniel99** [comment]
Ok I found the answer:
hash(feature, hash(namespace)) % 2^b

I went through audit_regressor. It can also serve my purpose.

Thanks.
