### ISSUE TITLE
No update to version number

### ISSUE THREAD

**Issue by swapniel99** [JohnLangford/vowpal_wabbit#993]
Hi,

I would like to know why the version number is not being updated. It has been 8.1.1 since quite a long time now.

The model files created with current commit are no longer readable in older commits I get the following error if I create a model file with current commit and read it on a older commit I get the following error:
vw (io_buf.h:231): file is not a model file

Apparently the checksum doesn't match in readable_model

I request please follow version system as I had a hard time rolling back, not knowing where to roll back.

**Comment by usptact** [comment]
The version has been recently bumped to 8.2.0. Your voice in the desert has been heard after all. I would close the issue.

**Comment by swapniel99** [comment]
Thank you.
It would be great if significant and/or non-reverse compatible changes be versioned. :)

**Comment by JohnLangford** [comment]
I agree in general---not sure where this one slipped in.

-John
