### ISSUE TITLE
Learning to Search example in Graph?

### ISSUE THREAD

**Issue by usptact** [JohnLangford/vowpal_wabbit#995]
Is there an example how to run the learning to search algorithm for an arbitrary graph? I could find few examples for entity relation, dependency parsing and sequence tagging.

In VW it appears something to do with the options "--search" and "--search_task" but I am not certain.

My learning task is to build a statistical model which jointly performs two tasks:

- sequence tagging
- classification of the sequence

I see the graph in my case as triangular:
```
     o
/    |    \
o -- o -- o
```

Here my sequence has 3 elements and one global label. The length of sequence can vary from 3 to 10, the global label is always one.

During prediction stage, the algorithm should predict the labels for all elements in the sequence as well as the global label.

As for features, I have a bunch of features for each sequence element as well as for the global label element. I can also construct the features for edges.

Does the learning to search approach using the graph fits to such data? Any hints on where I can get started are greatly appreciated.

**Comment by vjeranc** [comment]
You can easily write your own run function in C++ or use the [python interface](https://github.com/JohnLangford/vowpal_wabbit/tree/master/python).

```cpp
void run(Search::search& sch, vector<example*>& ec)
{ Search::predictor P(sch, (ptag)0);
  action oracle = ec[0]->l.multi.label;
  size_t global_prediction = P.set_tag(1).set_input(*ec[0]).set_oracle(oracle).predict();
  if (sch.output().good())
      sch.output() << sch.pretty_label((uint32_t)global_prediction) << ' ';
  for (size_t i=1; i<ec.size(); i++)
  { oracle     = ec[i]->l.multi.label;
    size_t prediction = P.set_tag((ptag)i+1)
                         .set_input(*ec[i])
                         .set_oracle(oracle)
                         .set_condition_range((ptag)i, sch.get_history_length(), 'p')
                         .add_condition(1, 'a') // adds the global as condition on each sequence element
                         .predict();

    if (sch.output().good())
      sch.output() << sch.pretty_label((uint32_t)prediction) << ' ';
  }
}
```

Code above is just a slight variation on the POS tagging, it assumes that features for the global decision are positioned in the first row.
```
5 |w features for the global decision
1 |k little_word1
2 |k little_word2
...
```
`add_condition` propagates the decision to each sequence element.

If you're interested in how to add your problem to vowpal wabbit checkout [diff](https://github.com/JohnLangford/vowpal_wabbit/compare/master...vjeranc:ref_msd#diff-b9d82cb30817f827b27af1e948bc1a56) on my branch (I added a variant of pos tagging where POS tags have some additional attributes).

I can then, given [this](https://github.com/JohnLangford/vowpal_wabbit/compare/master...vjeranc:ref_msd#diff-b9d82cb30817f827b27af1e948bc1a56R12), call vowpal wabbit with `--search_task sequence_msd` or `--sequence_msd_layered` (in my particular problem I had to use cost sensitive label parser but it seems to me you could just adjust the [POS tagging](https://github.com/JohnLangford/vowpal_wabbit/blob/master/vowpalwabbit/search_sequencetask.cc#L15-L34) for your problem, like I did above).

I believe vowpal wabbit can do learning and inference on arbitrary graphs (something in the vowpalwabbit/search_graph.cc) but it's overkill for your particular problem.

You could also change the code and influence the global decision on each particular decision of the local features.

```cpp
void run(Search::search& sch, vector<example*>& ec)
{ Search::predictor P(sch, (ptag)0);
  for (size_t i=0; i<ec.size()-1; i++)
  { action oracle     = ec[i]->l.multi.label;
    size_t prediction = P.set_tag((ptag)i+1)
                         .set_input(*ec[i])
                         .set_oracle(oracle)
                         .set_condition_range((ptag)i, sch.get_history_length(), 'p')
                         .add_condition(1, 'a') // adds the global as condition on each sequence element
                         .predict();

    if (sch.output().good())
      sch.output() << sch.pretty_label((uint32_t)prediction) << ' ';
  }
  action oracle = ec.back()->l.multi.label;
  size_t global_prediction = P.set_tag(ec.size())
                              .set_input(*ec.back())
                              .set_oracle(oracle)
                              .set_condition_range(ec.size()-1, ec.size()-1, 'a').predict();// conditioning on all previous sequence decisions
  if (sch.output().good())
      sch.output() << sch.pretty_label((uint32_t)prediction) << ' ';
}
```

This code assumes that the features for the global decision are positioned in the last row.

**Comment by usptact** [comment]
Thanks a lot for your input @vjeranc ! I will take a much closer look at the source code bit later, unfortunately I am not very comfortable with more than simple C++ code (shame on me).

I was looking at the source code for the "search_graph.cc", especially the comments section. It mentions that the graph can be defined very easily if the following format is respected:

For nodes:
label:weight |n node_features

For edges:
n1 n2 n3 ... |e edge_features 

I can definitely construct such file and run the training. I am still curious whether this fits my problem.

Some context:
My data has sequence nature, I am currently using CRF for labeling every element. The sequence needs also to be globally classified into a predefined number of classes, a Logistic Regression model is built here. There are some cases/signs when the joint model could help to tag the sequence AND globally classify it. Doing first sequence tagging, then classification or vice versa is error prone and seems not to use all the information.

I would gladly provide the data examples but unfortunately I don't have this liberty.

**Comment by vjeranc** [comment]
This picture is taken from McDonald et al. 2007 (Fine to Coarse Sentiment Analysis)

<img width="536" alt="screen shot 2016-05-20 at 21 17 37" src="https://cloud.githubusercontent.com/assets/4954310/15439295/8ad8b1e6-1ed0-11e6-844f-8bea8b6cf0bb.png">

To me it seems that you have this exact problem. You have to predict labels for the constituent elements, and then a global label conditioned on each sequence decision.

The snippets in my previous reply solve this problem (it's really just that amount of code), and you'd only have to put the features for the global decision in the first row (or last, depending on which snippet you choose).

first row ex.:

```
label_for_global_decision |w this is a large document containing stuff .
19 |w this
12 |w is
33 |w a
1 |w large
2 |w document
9 |w containing
5 |w stuff
99 |w .
```
The code is simple c++, it's just function calls to vw functionality :) But, you could do the same thing in python, so check the ipython notebook tutorials, they are nice :)

**Comment by usptact** [comment]
Yes, it indeed looks very close, if not exact match, to my problem. I looked also at your diff, there shouldn't be any difficulties integrating it into my copy (or checking out your branch?).

I will close the issue and open a new one if I encounter some specific issue.

Thanks again @vjeranc , you've been very helpful.!

**Comment by vjeranc** [comment]
For example, if the global label can only have values {1, 2, 3}, and sequence elements only labels {4,5,6,7,8}, you can use `set_allowed(allowed_labels)` function to restrict that so you don't get labels for examples which shouldn't have them (I use something similar for msd tagging in my branch).

My branch has too much copy and paste, it's just an example of how to add new tasks and still use the vw executable.

you could just remove the `run` in sequence task and put one of my snippets and rebuild.

no problem, enjoy the success.

**Comment by usptact** [comment]
The labels I use to tag the sequence and the global label are completely distinct in my application. Thanks for pointing out this detail.
