### ISSUE TITLE
NoClassDefFoundError when using the JNI interface

### ISSUE THREAD

**Issue by stangirala** [JohnLangford/vowpal_wabbit#999]
I see the following class def error in the java lib and I'm trying to identify the cause of this.

`java.lang.NoClassDefFoundError: Could not initialize class vw.VW`

Looking at my packaged java jar, I see the vw_jni.lib file at the top level dir and, the respective class files under vw at the top level.

Any ideas on where the packaging might have gone wrong?

**Comment by JohnLangford** [comment]
There is a platform autodetector in the java library.  Maybe you have a 
weirdo platform?

-John

**Comment by stangirala** [comment]
@JohnLangford You're talking about the NativeUtils right?

**Comment by JohnLangford** [comment]
@jmorra @deaktator any ideas?

**Comment by deaktator** [comment]
@JohnLangford You're right.  Every time I've had this issue, it's been an issue loading the C code via JNI.  @stangirala, could you please give some platform information.  `name -a` and also, if you're on linux, maybe cat the redhat release file if you have one.  Also, are you running inside any containers?  Thanks.

**Comment by JohnLangford** [comment]
Ping on this @stangirala

**Comment by JohnLangford** [comment]
I'm going to assume this was fixed, so closing for now.  Please reopen if not so.

**Comment by abissell** [comment]
We encountered this issue when the output of `uname -a` on our servers was:

`Linux <hostname> 3.2.0-39-virtual #62-Ubuntu SMP Thu Feb 28 00:48:27 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux`

We didn't notice it with any other version of Ubuntu running. It may have been due to an unrelated difference in our config on servers where we had deployed that particular version.

**Comment by jmorra** [comment]
Is this on the latest code?  The JNI layer has been refactored quite a bit.

**Comment by abissell** [comment]
No, this is on 8.0.0 as well.

**Comment by jmorra** [comment]
Does it still occur on the latest code?

**Comment by abissell** [comment]
Don't know, we've already re-provisioned all the instances that were running this version unfortunately.
